### ISSUE TITLE
Варианты обрезки при загрузке изображений

### ISSUE THREAD

**Issue by Troollios** [instantsoft/icms2#1001]
**Используемая версия InstantCMS**: 2.11.0

**Версия PHP**:  7.2

**Как воспроизвести проблему**: Панель управления > Компоненты > Загрузка изображений > Пресеты

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

**Вариант №1**

При активной опции "Обрезать строго по размеру" добавить варианты обрезки.

Вертикальные изображения:
- Сверху
- Посередине
- Снизу

Горизонтальные изображения
- Сверху
- Посередине
- Снизу

Для чего это нужно?
Сайты бывают разной направленности, соответственно требования к обрезке изображений тоже разные.

Если на сайте загружаются вертикальные фотографии с изображением людей, то их необходимо обрезать сверху. Вертикальные с автомобилями - к примеру снизу. Горизонтальные часто нужно обрезать посередине.

**Вариант №2, более правильный.**

При загрузке можно кадрировать изображение.

В таком случае не требуется никаких настроек, пользователь сам выбирает нужную ему часть обрезки.

Пример приложил.

<img width="510" alt="2019-02-15 14 32 36" src="https://user-images.githubusercontent.com/25584057/52854226-e0b92f00-312e-11e9-80d5-9ced74aad353.png">

**Comment by narochnyi** [comment]
Поддерживаю!

**Comment by geminisf** [comment]
Было бы не плохо. Поддерживаю.

**Comment by vitaliyremi** [comment]
Поддерживаю!

**Comment by GiulioAntonioSantorio** [comment]
Вещь очень нужная
