### ISSUE TITLE
SEO по умолчанию - Тайтл страницы(ошибка)

### ISSUE THREAD

**Issue by iton1** [instantsoft/icms2#1008]
**Используемая версия InstantCMS**: InstantCMS 2.11.0

**Версия PHP**:  5.6

В типе контента в "SEO по умолчанию" в поле "Тайтл страницы" добавляем значения

![default](https://user-images.githubusercontent.com/17750649/53296793-93227d80-3824-11e9-93e4-f6c11f513236.png)

На сайте не появились:

![default](https://user-images.githubusercontent.com/17750649/53296817-104df280-3825-11e9-935f-b5c65823a985.png)

В коде тоже нет:

![default](https://user-images.githubusercontent.com/17750649/53296836-28be0d00-3825-11e9-8c17-2a12ed397526.png)

keywords и description появились, а title нет.

Как это исправить?

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
SEO по умолчанию означают значения по умолчанию, т.е. когда в записи они не заданы. title в записи задан.

**Comment by iton1** [comment]
Так галочка не стоит чтобы title прописывать руками, title сейчас берется из заголовка.

Если я ставлю галочку "Разрешить ввод тайтлов для страниц категорий" и поле в категории оставляю пустое - то  title берется из заголовка, а таком случае не понятно когда title берется из "SEO по умолчанию" ?
