### ISSUE TITLE
Не понятно формирование  названия классов внутри контроллера

### ISSUE THREAD

**Issue by maxicms** [instantsoft/icms2#101]
Например у нас есть контроллер rss_rambler, и получается что класс frontEnd будет иметь название class rss_rambler extends cmsFrontend  при этом класс action index index будет иметь 
class actionRssRamblerIndex extends cmsAction

Получается легкая путаница в правилах формирования имен классов в контролере.

**Comment by fuzegit** [comment]
Все описано в документации.
http://docs.instantcms.ru/dev/controllers

Классы фронта - rss_rambler, класс бэка backendRss_rambler
Классы экшенов actionRssRamblerIndex

Подчеркивание в названиях контроллеров (в бэке) будет работать корректно начиная с 2.4.1

**Comment by maxicms** [comment]
Логично было бы как раз убрать подчеркивание и сделать camelCase как сейчас сделано в action

**Comment by maxicms** [comment]
И на это еще не все даже шаблоны и те не корректно работают 
Не найден шаблон для отображения: /Users/admin/Sites/dev240/templates/default/controllers/rssyandex/backend/index.tpl.php

подчеркивание полностью выкидывается из названия папки контроллера.

**Comment by fuzegit** [comment]
> подчеркивание полностью выкидывается из названия папки контроллера.

я же написал выше: с 2.4.1 все должно работать. текущая версия из гита также обрабатывает корректно по схеме, описанной мной выше.

**Comment by lokanaft** [comment]
Просто лучше не использовать подчерки в названиях контроллеров
