### ISSUE TITLE
SEO по умолчанию - Тайтл страницы

### ISSUE THREAD

**Issue by iton1** [instantsoft/icms2#1010]
**Используемая версия InstantCMS**: InstantCMS 2.11.0

**Версия PHP**:  5.6

**Как воспроизвести проблему**:

В продолжение темы https://github.com/instantsoft/icms2/issues/1008 

В типе контента в "SEO по умолчанию" в поле "Тайтл страницы" добавляем значения И ставим галочку "Разрешить ввод тайтлов для страниц категорий"

![default](https://user-images.githubusercontent.com/17750649/53484785-ac7e3080-3a95-11e9-8e23-0c5061435d7d.png)

Захожу в категорию и оставляю поле "Тайтл страницы" Пустым
![default](https://user-images.githubusercontent.com/17750649/53484865-db94a200-3a95-11e9-8d43-49014e3f14e0.png)

В категории используется Не тот title что прописан в "SEO по умолчанию" !
![default](https://user-images.githubusercontent.com/17750649/53484929-08e15000-3a96-11e9-8955-0daf637de17e.png)

![default](https://user-images.githubusercontent.com/17750649/53484973-1d254d00-3a96-11e9-8a06-e6202dc52e81.png)

Как тогда должно работать "SEO по умолчанию" если в этой теме поле title не заполнено в категории - но при этом не появляется что прописано в "SEO по умолчанию" ?

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
Да что же такое.
https://docs.instantcms.ru/manual/ctypes/add#seo-по-умолчанию

В категории title это её название. По умолчанию. Это умолчание перекрывает умолчание от типа контента.

**Comment by iton1** [comment]
И как тогда использовать поле "Тайтл страницы" в "SEO по умолчанию" ? пример можно зачем это

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/blob/master/system/controllers/content/actions/category_view.php#L250

Тут все условия.
