### ISSUE TITLE
Вернуться на сайт в новой вкладке

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#1012]
Мелочь, а приятно.

templates/default/admin.tpl.php
`<a href="<?php echo href_to_home(); ?>"><?php echo LANG_CP_BACK_TO_SITE; ?></a>`
заменить на 
`<a href="<?php echo href_to_home(); ?>" target="_blank"><?php echo LANG_CP_BACK_TO_SITE; ?></a>`

**Comment by Risgit** [comment]
Схватите ссылку "Вернуться на сайт" мышкой и киньте в сторону - откроется в новой вкладке.

**Comment by fuzegit** [comment]
По мне, так сомнительно. И лишаете возможности тех, кто хочет открывать в текущей вкладке. При этом в текущем варианте открыть в новой вкладке тысяча вариантов. Я лично открываю средней кнопкой мыши.
