### ISSUE TITLE
Не работает пагинация в контенте по умолчанию

### ISSUE THREAD

**Issue by SergeyRN** [instantsoft/icms2#1013]
Используемая версия InstantCMS 2.11.0

Если на сайте установлен контент по умолчанию, на некоторых сайтах перестает работать пагинация ( при нажатии на любую страницу пагинации перебрасывает на главную страницу категории )

Об этой проблеме уже писали на форуме есть тема:
https://instantcms.ru/forum/thread31124-1.html

Как воспроизвести проблему:
Как выяснилось:
https://instantcms.ru/forum/thread31124-2.html#306004

Проблема возникает если в настройках стоит типом контента по умолчанию выбранный контент.
Если поставить в этой настройке "Тип контента по умолчанию" - "Нет".

Проблема пропадает:
https://instantcms.ru/forum/thread31124-2.html#306008

НО: при этом изменяются текущие URL, а значит для тех сайтов что давно проиндексированы будет происходить переиндексация страниц.

Поэтому простая смена настроек не вариант.

К тому же если правильно понимаю (может ошибаюсь) при настройке "Нет" в URL НЕ должно быть типа контента по умолчанию, а он есть. то есть сейчас при этой настройке адрес страниц такой:

site.ru/board/illyuzii-pokazalos-sravnenie

а должен быть такой
site.ru/illyuzii-pokazalos-sravnenie

PS: Однако здесь бы не ошибиться. Иначе могут изменится URL на всех действующих сайтах....

**Comment by fuzegit** [comment]
> К тому же если правильно понимаю (может ошибаюсь) при настройке "Нет" в URL НЕ должно быть типа контента по умолчанию, а он есть.

Вы ошибаетесь, стоит сначала всё же прочитать документацию https://docs.instantcms.ru/manual/settings/global

Проблема с пагинацией в версии здесь на Github давно решена.
