### ISSUE TITLE
Разделить $is_voted и $is_enabled в рейтинге.

### ISSUE THREAD

**Issue by Risgit** [instantsoft/icms2#1018]
**Используемая версия InstantCMS**: 2.11.1

**Версия PHP**:  Любая версия

Раз уж появилась возможность манипулирования рейтингом:
https://github.com/instantsoft/icms2/commit/7d94d7a3e608e3399c5d5ab6561885d85a01cb5b#diff-7e70a53f3e1da9f05692c8d66bad4d5e
просьба разделить в /system/controllers/rating/fronted.php $is_voted и $is_enaled.
То есть заменить 
`'is_enabled'        => ($is_voted ? false : $is_enabled),`
на 
`'is_enabled'        => $is_enabled,`
с целью возможности переголосования пользователям.

**Comment by elipss** [comment]
Переголосования без обновления страницы.
