### ISSUE TITLE
Поле список в типах контента невозможно сделать обязательным

### ISSUE THREAD

**Issue by Maratakziaplus** [instantsoft/icms2#102]
В поле список первое значение можно ли сделать пустым, как это реализовано в фильтре? Создаю список в типах контента и хочу сделать это поле обязательным, но не получается. Пробовал ставить пробел первым в списке, чтобы было пусто, но это не помогает.

**Comment by fuzegit** [comment]
Уважаемый Maratakziaplus, убедительно прошу для вопросов использовать форум, где спрашивать то, что вам непонятно, вместо того, чтобы на каждое ваше недопонимание писать здесь. 
Здесь пишут об ошибках и адекватных пожеланиях, которые будут полезны всем.

Все прекрасно реализуется, например в статьях можно сделать так:

0 | 
1 | Авторская
2 | Рецензия
3 | Перевод
