### ISSUE TITLE
"Установить обложкой альбома" в списке фотографий.

### ISSUE THREAD

**Issue by Loadir** [instantsoft/icms2#1027]
https://github.com/instantsoft/icms2/blob/30c3d0fb4fe8898c46aa61fcae38075f65234e34/system/controllers/photos/actions/set_cover.php#L24
При установке обложки альбома по ссылке из списка изображений редирект идёт на страницу изображения. Желательно возвращать обратно в список $this->redirectBack();

**Comment by fuzegit** [comment]
У нас есть функционал установки обложки из списка?

**Comment by Loadir** [comment]
Нет, но мне это не помешало сделать его в своем шаблоне.
