### ISSUE TITLE
Хук engine_before_start

### ISSUE THREAD

**Issue by dxdxd1** [instantsoft/icms2#1029]
Предлагаю добавить в главный исполняемый файл хук engine_before_start. Всего одна строчка, но пользы много. Простейший пример - возможность создания ЧПУ без редиректов, на сегодняшний момент все известные мне компоненты из этой области используют редиректы, что не совсем хорошо.

`require_once 'bootstrap.php';

if ($config->emulate_lag) { usleep(350000); }

cmsEventsManager::hook('engine_before_start');

//Запускаем роутинг
$core->route($_SERVER['REQUEST_URI']);`

**Comment by fuzegit** [comment]
Я не знаю о каких редиректах вы ведёте речь, полагаю, что я не очень вас понял.
Хук есть
https://github.com/instantsoft/icms2/blob/master/bootstrap.php#L95
Ну и в хуке engine_start вы прекрасно можете поменять всё, что сделал route или вовсе вызвать его заново.

Если ответ вас не удовлетворил, опишите реальный пример того, что хотите сделать, но упираетесь в архитектуру.

**Comment by dxdxd1** [comment]
Слона то я и не приметил ... Спасибо, вопрос снят, хук core_start полностью решает все необходимые задачи.
