### ISSUE TITLE
Просмотр записи > выключен = ошибка ссылки поле "Изображение"

### ISSUE THREAD

**Issue by iton1** [instantsoft/icms2#1030]
**Используемая версия InstantCMS**: InstantCMS 2.11.0

**Версия PHP**:  5,6

**Как воспроизвести проблему**:

В типе контента убираем галочку "Просмотр записи включен "

![изображение](https://user-images.githubusercontent.com/17750649/54864733-75d1c800-4d6c-11e9-9ed3-5a30a46ea440.png)

если в типе контента есть поле "Изображение" и оно показывается в списках, то ссылки работают и ведут на отключенные страницы и получается 404 ошибка.

![изображение](https://user-images.githubusercontent.com/17750649/54864767-e547b780-4d6c-11e9-8538-612dacf3eb2f.png)

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
Решено в новом шаблоне
