### ISSUE TITLE
Невозможно создать новый пресет изображения

### ISSUE THREAD

**Issue by dobriydaniil1982** [instantsoft/icms2#1033]
Версия движка 2.12.0 

Версия php 5.4

После последнего обновления движка невозможно создать новый пресет изображения или отредактировать существующий, поле "Качество" выдает ошибку "Введите только цифры", хотя ввожу все как надо

Воспроизводится ли проблема на демо http://demo.instantcms.ru/: ДА воспроизводится

**Comment by fuzegit** [comment]
Уже в версии здесь исправлено.
Можете заменить файл
https://github.com/instantsoft/icms2/blob/master/system/fields/number.php
