### ISSUE TITLE
Регистрация новых пользователей

### ISSUE THREAD

**Issue by dobriydaniil1982** [instantsoft/icms2#1035]
**Используемая версия InstantCMS**: 2.12.1

**Версия PHP**:  5.4.45

**Как воспроизвести проблему**: Регистрация нового пользователя

После обновления движка не возможно зарегистрироваться на сайте, после заполнения всех полей в форме регистрации и нажатия кнопки "Продолжить", в режиме отладки - белый экран и ошибка: Fatal error: Call to undefined function password_hash() in /home/host1701262/ufadvorik.ru/htdocs/www/system/controllers/users/model.php on line 272

Так же непонятная ситуация при настройке прав на изменение обязательных полей профиля для разных групп пользователей. Раньше, в форме регистрации, при выборе группы пользователей в которую пользователь хочет зарегистрироваться, появлялись или исчезали поля относительно настроек прав доступа на изменение выбранной группы, сейчас же этого не происходит, отображаются только поля, доступ на изменение к которым настроен для всех

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА/НЕТ

Этот текст можно стереть, если вы сообщаете не о баге, а пишите пожелание/предложение.

**Comment by fuzegit** [comment]
![Выделение_062](https://user-images.githubusercontent.com/13233234/55275556-fc505180-52f8-11e9-99e8-921f8655cdfc.png)
