### ISSUE TITLE
Подружить кеш с мультиязычными сайтами

### ISSUE THREAD

**Issue by WebRio** [instantsoft/icms2#1038]
Вроде как движок поддерживает мультиязычность, но кеширование совсем не дружит. Если на подобном сайте включит кеширование то мультиязычность теряет свой смысл так как при переключение языка не работает, язык остается тот что по умолчанию.

**Comment by fuzegit** [comment]
Напишите более развернуто.

**Comment by WebRio** [comment]
> 
> 
> Напишите более развернуто.

Есть прекрасный компонент [языки](https://addons.instantcms.ru/addons/reviews/627) от разработчика DWD я ему задавал вопрос на эту тему, но получил такой ответ

**Выдержка из ответа DWD**

Да, Кэширование не поддерживается. Но не компонентом, а системой. Это у разработчиков надо спрашивать почему при их "стремлении к развитию многоязычности системы" страницы site.ru/page.html и site.ru/en/page.html считаются одной страницей и кэшируются как одна страница. Почему при составлении масок в виджетах приставка языка тоже ни на что влияет. И т.д. и т.п. С этим я к сожалению ничего не могу поделать.

**Comment by fuzegit** [comment]
Ну Dwd в своём духе, что тут сказать.
Отвечаю по существу.

1. По виджетам. В масках НЕ нужно указывать префикс языка. Для этого у каждого виджета есть соответствующая опция, кроме этого сам виджет может быть мультиязычным.

2. 
> страницы site.ru/page.html и site.ru/en/page.html считаются одной страницей и кэшируются как одна страница. 

Это не так. Скриншоты ниже

![Выделение_066](https://user-images.githubusercontent.com/13233234/55392794-a96ada00-5544-11e9-9ea6-c8717cc054d0.png)
![Выделение_067](https://user-images.githubusercontent.com/13233234/55392796-a96ada00-5544-11e9-8365-817de4e703ac.png)
![Выделение_068](https://user-images.githubusercontent.com/13233234/55392797-a96ada00-5544-11e9-9556-325341499b90.png)
![Выделение_069](https://user-images.githubusercontent.com/13233234/55392798-a96ada00-5544-11e9-8500-3ae363fb8394.png)

Поэтому повторяю свой вопрос. Опишите конкретно, что не так. Полагаю, что описать суть проблемы лучше всего самому Dwd, вместо подобных высказываний не по существу.

**Comment by BorisRBJ** [comment]
> так как при переключение языка не работает, язык остается тот что по умолчанию

Введите вручную префикс языка в адресную строку и увидите, что все работает.
У вас кешируется виджет переключателя языков.
Отключите кеширование виджета /site.com/system/controllers/languages/widgets/switch/, например [так](https://instantcms.ru/forum/thread28460-1.html)
