### ISSUE TITLE
Не работает SEO для записей с паттернами

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#1039]
**Используемая версия InstantCMS**: 2.12.0

**Версия PHP**:  5.6.37

**Как воспроизвести проблему**: Добавить новость при таких настройках seo для записей
http://joxi.ru/GrqQZkc4GVaQrz

![02-04-2019 17-45-13](https://user-images.githubusercontent.com/9349934/55412163-94f00700-556f-11e9-8011-a3ecb23b0a0e.png)

* первый шаг - добавляем новость

meta name="keywords" content="Тест проверка"
meta name="description" content="&lt;p&gt;Тест проверка&lt;/p&gt;, Гламур"
- на сайте в код добавляются, а в базу нет.
В description, дописывает шляпу в виде &lt;p&gt; &lt;/p&gt;

* второй шаг - проверяем, 
![02-04-2019 17-47-23](https://user-images.githubusercontent.com/9349934/55412308-dda7c000-556f-11e9-8ee5-c0a71cc156fc.png)
* третий шаг - проверяем базу - столбцы seo_keys, seo_desk - NULL -  с паттернами в базу не пишет.

* четвертый шаг - если убрать паттерны - то автоматически все генерируется.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: на сайте ДА, там вообще при таких настройках не было ни meta name="keywords", ни  meta name="description", в базе не видел.

На 2.11.0 всё работало

**Comment by fuzegit** [comment]
Вам нужно обновить свой шаблон в части компонента контент.
То, что добавляются HTML теги, вероятно да, ошибка.

> с паттернами в базу не пишет.

И не должен теперь.

**Comment by nomad48** [comment]
Иногда эти настройки http://joxi.ru/GrqQZkc4GVaQrz системой игнорируются вообще, вот добавил новость при таких настройках, система сгенерировала meta name="keywords" и meta name="description" автоматически без учета паттернов.
![02-04-2019 18-14-43](https://user-images.githubusercontent.com/9349934/55414385-ad622080-5573-11e9-88ab-bf0ce9586543.png)

в базе 
![02-04-2019 18-15-54](https://user-images.githubusercontent.com/9349934/55414460-d1bdfd00-5573-11e9-8b24-da36cd9e3aeb.png)

**Comment by nomad48** [comment]
> Вам нужно обновить свой шаблон в части компонента контент.

Я обновил, или надо 2.12.1 ставить

**Comment by fuzegit** [comment]
В базу пишется теперь только, если вы эти параметры задали вручную в записи. В остальных случаях в базу ничего НЕ пишется, всё генерируется на лету.

**Comment by nomad48** [comment]
Я понял, раньше при изменении настроек в типе контента, и при пересохранении контента, пересохранялись и seo_keys, seo_desk, а сейчас нет

**Comment by fuzegit** [comment]
С HTML тегами решу, в остальном я не очень понимаю что не так.

**Comment by nomad48** [comment]
> я не очень понимаю что не так.
на 2.11.0 при пересохранении новости, если изменял настройки в типе контента seo для записей, пересохранялись seo_keys, seo_desk

**Comment by fuzegit** [comment]
Так я вам объяснил же. Сейчас это не так. Мета информация генерируется на лету и после изменений паттернов теперь не надо пересохранять ничего. В эти ячейки теперь пишутся данные только если вы их указали вручную в записи.
Если данные указаны у вас в таблицах, то они оттуда и берутся. Если вы хотите чтобы было все на основе паттернов, то в базе везде нужно этим ячейкам проставить null. Это можно сделать одним sql запросом.

**Comment by nomad48** [comment]
У меня на 2.11.0 и так всё работало, а сейчас нет, шаблон обновлён. Я на 2.11.0 хотел на основе паттернов всё, так всё и было. Сейчас я не пойму откуда что берется, в двух одинаковых случаях.

**Comment by fuzegit** [comment]
Вы меня как будто не слышите.
Как формируются сео для записей.

**Comment by fuzegit** [comment]
Вы меня как будто не слышите.
Как формируются сео для записей:
Есть заполненные ячейки seo_keys, seo_desc в базе, выводятся ОНИ. 
Если нет заполненных ячеек, работает паттерн.

После пересохранения записи движок больше НЕ пишет в эти ячейки ничего. Ячейки эти можно заполнить, если выключена автоматическа генерация.

Если вам нужно чтобы работали паттерны, обнулите в базе все ячейки сео

```SQL
UPDATE `cms_con_news` SET `seo_keys`=NULL,`seo_desc`=NULL,`seo_title`=NULL
```
Название таблицы ставите своё.

**Comment by nomad48** [comment]
а как старые записи, влияют на новые, я вот этого не пойму, в старых записях всё ок, в столбцах всё по паттернам.

**Comment by fuzegit** [comment]
Вы можете вникнуть что я вам пишу уже которое сообщение?
В базе в столбцах НЕ должно быть ничего, если в них в форме не указывали ВРУЧНУЮ. Для работы паттернов в базе НЕ должно быть ничего. Как это сделать, я написал выше запрос.

**Comment by nomad48** [comment]
> Если вам нужно чтобы работали паттерны, обнулите в базе все ячейки сео

я правильно понимаю, должна быть команда на обновление таблицы `cms_con_news` после 

`UPDATE `cms_con_news` SET `seo_keys`=NULL,`seo_desc`=NULL,`seo_title`=NULL`

ведь все новости сами по себе не обновят своё seo или этой команды достаточно.

**Comment by fuzegit** [comment]
Просто выполните этот запрос и всё. Если вы вручную сео не заполняли никогда.

**Comment by nomad48** [comment]
Я понял, спасибо.
