### ISSUE TITLE
Доработка подтверждения е-майл при регистрации

### ISSUE THREAD

**Issue by zau4man** [instantsoft/icms2#1041]
**Используемая версия InstantCMS**: 2.12.0
В опциях регистрации стоит "подтверждать е-майл"

В текущей версии, получается, если случайно опечатался при указании е-майл и нажал регистрация, заново зарегистрироваться нельзя, так как при незавершенной регистрации идет редирект на /auth/verify где система ждет код с почты.

Кода у нас нет, так как в е-майл опечатка.

Предложение: на страницу /auth/verify надо добавить кнопочку "Ошибочно указан е-майл". И при клике сбрасывать cookie reg_email и отправлять пользователя на страницу регистрации.

**Comment by nomad48** [comment]
Поддерживаю

**Comment by vitaliyremi** [comment]
Поддерживаю
