### ISSUE TITLE
Слайдер в записях

### ISSUE THREAD

**Issue by vitaliyremi** [instantsoft/icms2#1042]
Можно ли доработать функционал редактора "redactor"? 
Сделать кнопочку "слайдер" возле "изображения", при нажатии всплывает окно точно такое же, как и в "изображения", но уже можно загружать несколько фото, как загрузятся можно подписать.
+ Таких слайдеров можно делать на странице сколько угодно и вставлять где угодно(в материале). Таким образом можно делать статью с фотообзорами

**Comment by vlad7090** [comment]
Актуально

**Comment by fuzegit** [comment]
> Можно ли доработать функционал редактора "redactor"?

Боюсь, что нет. Это сторонний редактор. Воспользуйтесь опцией "Обрабатывать специальные шаблоны" поля HTML и вставьте в текст {images_field}, где images_field название поля с набором изображений.
