### ISSUE TITLE
Ошибка в настройках редакторов.

### ISSUE THREAD

**Issue by maxisoft-git** [instantsoft/icms2#1044]
При объединении дефолтных параметром с переданными в класс редактора нужно исправить функции array_merge на array_merge_recursive По причине того что через хук нельзя будет дополнить например массив плагинов редактора.

**Comment by fuzegit** [comment]
array_merge_recursive тут не годится. array_replace_recursive
https://github.com/instantsoft/icms2/commit/da5c9db788ae1271802d9d8b83c70368a3347107
