### ISSUE TITLE
Доработка шаблонов записей

### ISSUE THREAD

**Issue by zau4man** [instantsoft/icms2#1045]
С версии 2.11.0 для каждой записи типа контента теперь можно задавать свой шаблон вывода, как это выглядит можно посмотреть в комментарии [тут](https://instantcms.ru/novosti/release2110.html#c110494)

Предлагаю дать возможность авторам шаблонов указывать название шаблона записи типа контента в самом файле, например, добавив его в самом начале в комментарии после специального слова
Примерно так
`<?php
/*
Template Name: Видеоблог
*/
?>`
и выводить в форме добавления записи не **albums_item_1.tpl**, а **Видеоблог**
icms может брать имя, открыв файл и найдя регуляркой "Template Name:"

Также предлагаю дать доступ к этим шаблонам и пользователям, добавив права группам.
В версии 2.12.1 выбор шаблона доступен только админам.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/1bf125494f07d911bc1f1933a11e3f8fb1dcb665
