### ISSUE TITLE
По мультиязычности

### ISSUE THREAD

**Issue by BorisRBJ** [instantsoft/icms2#1050]
1. При редактировании записи типа контента на дополнительных языках заголовок показывается только на основном языке, потому что https://github.com/instantsoft/icms2/blob/8abb3e84da08f3af90322d42da61a753b0b60232/system/controllers/content/actions/item_edit.php#L16
2. Все $ctype['labels'] на неосновном языке отдаются в шаблон YAMLом
$relation['child_labels'] то же

**Comment by fuzegit** [comment]
1. Так и должно быть
2. Где и как это проверить?
