### ISSUE TITLE
Скрытая категория попадает в sitemap.xml

### ISSUE THREAD

**Issue by montysoft** [instantsoft/icms2#1052]
Если допустим пустая категория и хочешь, чтобы она не отображалась на сайте и не попадала в поисковики, берем ставим у этой категории галочку "Скрытая категория", то она на сайте не отображается, но в sitemap.xml ссылка на нее генерируется, считаю, что это является багом

**Используемая версия InstantCMS**: 2.12.1

Воспроизводится ли проблема на демо http://demo.instantcms.ru/: ДА

Этот текст можно стереть, если вы сообщаете не о баге, а пишите пожелание/предложение.

**Comment by fuzegit** [comment]
Не является багом. Скрытая категория = скрытая на сайте. Индексироваться она должна.
