### ISSUE TITLE
Виджеты в группах

### ISSUE THREAD

**Issue by kizaika** [instantsoft/icms2#1064]
Было бы очень хорошо, если бы в разделе "Виджеты и страницы" появилась возможность расставлять виджеты на страницах групп - в списке групп, на странице группы и т.д., как это реализовано у типов контента, у фотоальбомов и у профилей пользователей.

**Comment by fuzegit** [comment]
Вы это можете делать и  сейчас
https://docs.instantcms.ru/manual/widgets/pages
