### ISSUE TITLE
не вставляется изображение в комментарий

### ISSUE THREAD

**Issue by kikoroute** [instantsoft/icms2#1066]
**Используемая версия InstantCMS**: 2.12.2

**Версия PHP**: 7.1

**Как воспроизвести проблему**:

При использования редактора Redactor не вставляются(грузятся?) изображения
1)Нажимаем написать комментарий
2) Выбираем иконку изображения
3) Нажимаем "Выберите файл", указываем файл с компьютера либо просто перетаскиваем его
4)Сверху на короткое время появляется полоса загрузки, но дальше  ничего не происходит, изображение не добавляется к комментарию
**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: НЕТ

**Comment by yuri25** [comment]
Аналогичная проблема с текущей версией с гита:(

**Comment by fuzegit** [comment]
Да, проблема есть, решим на днях, без паники :)

**Comment by fuzegit** [comment]
Так, я погорячился. С редактором Redactor проблемы не вижу. Была проблема с другим, когда я проверял.

Кто-нибудь может описать в подробностях последовательность действий, чтобы я поймал ошибку у себя? Желательно максимально подробно и еще лучше, если будет скрин консоли бразузера, скрин ответа аякс загрузки оттуда же.

**Comment by Toxu-ru** [comment]
@fuzegit  аналогично не мог повторить. Лайки вот наставил. ) А вот предложение по надписи в кнопке "Выбрать",  ИМХО, стоит.

**Comment by fuzegit** [comment]
Кажется я понял где проблема. Но прошу уточнить, при добавлении комментария к чему, такая ошибка?

> А вот предложение по надписи в кнопке "Выбрать", ИМХО, стоит, относится к вкладке - фото. На форуме в Предложениях написал. 3 человека уже сказали это. Воспринимают, как ошибку

Редактор не мы писали. Фразу "У вас нет изображений" наверное добавлю.
