### ISSUE TITLE
Не создаются наборы в фотоальбомы

### ISSUE THREAD

**Issue by elipss** [instantsoft/icms2#1067]
2,12,2 , PHP 7.1 
Не создаются наборы в фотоальбомы
Воспроизводится ли проблема на демо : ДА

**Comment by nomad48** [comment]
> Воспроизводится ли проблема на демо : ДА

Создайте два и более набора, просто один набор не показывается 

![04-06-2019 10-26-45](https://user-images.githubusercontent.com/9349934/58859935-9b0b7c80-86b3-11e9-9699-ea006e377ce9.png)
![04-06-2019 10-29-21](https://user-images.githubusercontent.com/9349934/58859971-b5ddf100-86b3-11e9-98b1-096971e2f4ec.png)
![04-06-2019 10-29-10](https://user-images.githubusercontent.com/9349934/58859975-b7a7b480-86b3-11e9-97da-7a3dafa1b4ec.png)

**Comment by elipss** [comment]
Если стоит Интерфейс - Тема оформления для панели управления не дефолтная не создаются наборы и Компоненты - Комментарии - Редакторы HTML для групп - Добавить , возможно не работают остальные функции.

**Comment by nomad48** [comment]
@elipss так сделайте дефолтную тему панели управления и удалите из своего шаблона всё что касается панели управления

**Comment by elipss** [comment]
На время настроек можно ставить панель дефолт, в панели не дефолт есть плюшки которых нет в дефолте.
