### ISSUE TITLE
Мелкий недочет в генераторе robots.txt

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#1068]
**Используемая версия InstantCMS**: 2.12.2

Если после правил вставить пустую строку (нажатие Enter после последнего правила), сохраняется вот в таком виде:

![52](https://user-images.githubusercontent.com/16401582/58947669-0bd49680-8791-11e9-8c74-fb62bb484ef1.jpg)

Вертикальная черта, пробелы в начале строк.

**Comment by iton1** [comment]
Я такое тоже встречал но не в файле robots.txt, а в редакторе:
в виджетах на страницу добавил "HTML блок" и в нем набрал текст и сохранил, зашел еще раз и еще добавил текст и сохранился, получилось:

в редакторе
![изображение](http://dl4.joxi.net/drive/2019/07/10/0013/2721/871073/73/d8368a3b58.png)

на сайте 
![изображение](http://dl3.joxi.net/drive/2019/07/10/0013/2721/871073/73/34b782e70f.png)
