### ISSUE TITLE
Типы полей: "Изображение" и "Набор изображений" (Не используемые изображения)

### ISSUE THREAD

**Issue by ArtSolist** [instantsoft/icms2#1071]
**Используемая версия InstantCMS:** 2.12.2

**Версия PHP**:  7.1

**Как воспроизвести проблему**:

1. Если пользователь выбрал изображения при добавлении/редактировании материала, а потом передумал (закрыл страницу/перешел на другую) - то изображения остаются на сервере.
2. Если пользователь при добавлении/редактировании материала выбрал изображение, а потом передумал (нажал кнопку "Удалить" рядом с изображение, потом выбрал другое изображение и сохранил материал) - то предыдущие тоже остаются на сервере.

**Comment by elipss** [comment]
При удалении изображений в редакторах (в комментариях тоже) удаляется ссылка, изображение остается на сервере, что не есть хорошо. Есть компонент Чистильщик, но в нем можно удалить нужные файлы, не мешала бы чистка в определенных типах контента и компонентах, на 2.12.2 не работает.
