### ISSUE TITLE
Изменить валидацию email.

### ISSUE THREAD

**Issue by Risgit** [instantsoft/icms2#1072]
Большая просьба изменить валидацию email при авторизации.
Да, я понимаю, что авторизация по почте - это правильно, безопасно и современно, как смузи с мюслями в барбершопе. Но очень у многих пользователей есть потребность организовать авторизацию на сайте не по емейлу, а по нику, логину, телефону, скайпу и т.д.
Казалось бы, вопрос решается одним хуком 'user_auth_error', но валидация емейла на входе в экшен не дает возможности ни для каких дальнейших действий и сразу редиректит назад.
Приходится при каждом обновлении удалять эту валидацию.
Просьба изменить 
```
if (!$password || !$email || $this->validate_email($email) !== true){
 cmsUser::addSessionMessage(LANG_LOGIN_ERROR, 'error');
$this->redirectBack();
}
```
на что-нибудь типа 
```
if (!$password || !$email || $this->validate_email($email) !== true){
$is_auth_valid = cmsEventsManager::hook('auth_validate', $email);
if (!$is_auth_valid){
cmsUser::addSessionMessage(LANG_LOGIN_ERROR, 'error');
$this->redirectBack();
}
}
```
И тогда уже в этом хуке можно будет валидировать что угодно, телефон, никнейм, логин и т.д.

С уважением и надеюсь на понимание.

**Comment by fuzegit** [comment]
Дело всё в том, что логически здесь всё правильно.
А менять нужно саму форму авторизации и сделать её как и остальные формы. После чего хук на эту форму все подобные вопросы закроет.

**Comment by Risgit** [comment]
Не понял, как например мне сейчас менять форму авторизации? Которая выполнена в виде login.tpl.php.
Даже если изменить форму, из неё не прилетит емейл. И тогда 
`if (!$password || !$email){$this->redirectBack();}`
Как обойти валидацию емейла? Нельзя ли чуть-чуть попрдробнее?

**Comment by fuzegit** [comment]
Сейчас никак, поскольку форма формируется обычным HTML в шаблоне.

**Comment by Risgit** [comment]
Так может всё-таки двухступенчатая валидация?

**Comment by fuzegit** [comment]
Вы не поняли. Нужно форму логина переделать (не вам, а мне в движке) на стандартную форму через класс. И тогда хуком на эту форму можно будет её изменить.
Т.е. объявить форму как подобные тут https://github.com/instantsoft/icms2/blob/master/system/controllers/auth/forms/form_restore.php

Сейчас вы конечно же никак не сделаете то, что задумали.

**Comment by Risgit** [comment]
Я уже пытался какую-то конструкцию на чистом яваскрипте (почему-то из хука жиквери не работает) сделать, которая дописывает собаку с неким плацебо для валидации при нажатии сабмита. Например из admin делает admin@fake.fake
Получилось очень громоздко и страшно, но так и не заработало...

**Comment by fuzegit** [comment]
Да нет же, это всё не то.

Я хочу описать форму логина тут /system/controllers/auth/forms/
Соответственно из экшена, о котором вы пишите, принудительная валидация email уйдёт автоматически.
И далее уже можно будет применять хуки на эту форму, убирая поля и добавляя нужные.
В общем я понял что вы хотите, сделаем в лучшем виде.

**Comment by Risgit** [comment]
Вас понял! Спасибо!
