### ISSUE TITLE
Изменение структуры папок в upload с целью облегчения поиска лишних картинок.

### ISSUE THREAD

**Issue by Risgit** [instantsoft/icms2#1077]
Есть рационализаторское предложение обозначить в папках с файлами принадлежность изображений и файлов к типам контента и компонентам.
То есть, чтобы при добавлении картинки в статьях она добавлялась в папку например 
/upload/ u1/articles/d/e/ , при добавлении картинки в комментариях, добавлялась бы в папку 
/upload/ u1/comments/f/3/ и т.д.
Это позволит создать нормальную утилиту для поиска неиспользуемых изображений, которая будет эффективно и быстро (ведь не понадобится делать выборку из всех таблиц для поиска ссылок на изображения и перелопачивать весь upload в поисках картинок) искать и удалять файловый мусор.

В случае одобрения разработчиком обязуюсь изготовить утилиту для массового переименования ссылок в базе и папок в upload.

**Comment by Risgit** [comment]
Или хотя бы обозначать папки в соответствии хоть с какой-нибудь логикой.
Например, картинка относится к типу контента "новости" - должна лежать в папке 
/upload/u1/c2/t10/d/a/
Где u1 - пользователь с id = 1, c2 - id контроллера content в таблице cms_controllers, а t10 - id типа контента news в таблице cms_content_types, а d и a - как принять в Instantcms какие-то произвольные папки для уменьшения размера папки..
То что есть сейчас - логике не поддается. Картинки новостей лежат в папке /upload/u1/003/
Что такое 003 - непонятно.

**Comment by zau4man** [comment]
Fuze где-то на форуме писал, что текущая структура оптимальна в плане скорости работы движка. И что все папки будут заполняться плюс-минус равномерно. И не будет падать ftp клиент, при попытке открыть такую папку.

А  за лишними фотографиями и т.п. должен следить компонент, который создает папки и фото в них. Если какой-то мусор остается, надо править причину его появления.

**Comment by Risgit** [comment]
> Если какой-то мусор остается, надо править причину его появления.
Причина появления картинок, которые нигде не используются - пользователь.
Его не исправить...

**Comment by zau4man** [comment]
Повторюсь, править надо причину.
Если пользователь загрузил фото, но не опубликовал запись, значит надо удалить такое фото.
Как? Это и надо обсуждать. А не бороться со следствием.

**Comment by Risgit** [comment]
И как удалить такое фото? Посадить с каждым юзером по модератору? Проверять при каждой загрузке файла, записалась ли ссылка на него в базу?
Это абсолютно невозможно.

**Comment by narochnyi** [comment]
Согласен на счет удаления фото, при отказе публикации записи. Так можно очень много фото загрузить, а запись не добавлять, а потом иди ищи какие файлы левые, а какие нужные!

**Comment by narochnyi** [comment]
> И как удалить такое фото? Посадить с каждым юзером по модератору? Проверять при каждой загрузке файла, записалась ли ссылка на него в базу?
> Это абсолютно невозможно.

Можно с помощью glob сравнить названия всех файлов с теми, что записаны к БД, и которых нет, удалить!)

**Comment by fuzegit** [comment]
#1398
