### ISSUE TITLE
Адаптивная верстка для админки

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#108]
Система дминистрирования смотрится очень криво на смартфонах и вообще нка узких мониторах, т.к не имеет ни резиновой, ни адаптивной верстки, что приходит к искажению админки, в связи с чем ее управление фактически невозможно.

**Comment by Val-Git** [comment]
**Потому что не надо управлять сайтом с телефона!**
p.s. резиновая и адаптивная - это одно и тоже

**Comment by lokanaft** [comment]
> p.s. резиновая и адаптивная - это одно и тоже
Резиновая - это когда расширяется вслед за размером экрана, а адаптивная - это когда наоборот сжимается, пропадает функционал, дизайн становится убогим и тд
Шаб одновременно может быть адаптивным и не резиновым, то есть фиксированная ширина 960 для пк и далее сжимается до меньших экранов.
Сейчас админка резиновая и неадаптивная, а фронт фиксированный и адаптивный.

**Comment by vlad7090** [comment]
а с планшета тоже не надо управлять? вообще это онрмально урпавлять сайтом с мобильных устройств, т.к проникновение таких устройств более 30-40% в зависимости от сегмента. 

Вот так выглядит на планшете http://prntscr.com/9yw43u

**Comment by Val-Git** [comment]
> Резиновая - это когда расширяется вслед за размером экрана, а адаптивная - это когда наоборот сжимается, пропадает функционал, дизайн становится убогим и тд
> Шаб одновременно может быть адаптивным и не резиновым, то есть фиксированная ширина 960 для пк и далее сжимается до меньших экранов.

Есть Adaptive Web Design и Responsive Web Design (ну и изначальный фиксированный). Так называемая резиновая верстка это уже выдуманный частный вариант адаптивного.
Глобально **Adaptive** - грузится с сервера **вся** html-страница и подстраивается под экран устройства на котором ее просматривают (как это реализовано - через перемещение блоков, "резиновую" ширину элементов - не важно.) **Responsive** - на сервере определяется что за устройство запрашивает html-страницу и рендерятся данные конкретно под устройство. В частности для смартфонов - это может быть облегченная страница (отсутствует ряд блоков, размер картинок и т.д.).

**Comment by lokanaft** [comment]
Резиновая была уже тогда, когда ещё слова такого "адаптивная" не было. Вы сейчас вообще не о том пишите.

**Comment by Val-Git** [comment]
> а с планшета тоже не надо управлять? вообще это нормально управлять сайтом с мобильных устройств, т.к проникновение таких устройств более 30-40% в зависимости от сегмента.

У меня на планшете прекрасно все отображается в текущей конфигурации. Если у вас серьезный сайт то управлять им с телефона - это не нормально, имхо. 
В целом я не против адаптации админки под телефоны, но считаю это **не первоочередной** задачей! Времени для адаптации потребуется достаточно, а выхлопа полезности практически ноль.

Если вы желаете - сделайте и выложите здесь Pull request, вам все скажут спасибо ))

**Comment by Val-Git** [comment]
В моем понимании резиновая - это **div width: 100%;**  т.е. элемент растягивается вместе с шириной окна. 
Согласен, понятие адаптивная верстка пришло позже и вобрало в себя набор техник которые позволяют добиться требуемого результата (вывод страницы без горизонтального скролла). И резиновые стили это часть адаптивной верстки.

**Comment by pin-git** [comment]
Ушёл разговор в сторону.
Шаблон default, что FrontEnd, что BackEnd, на мой взгляд, не обязан отвечать всем потребностям, его задача обозначить заложенный в движок функционал. А за разнообразием и частным потребностям обращаться к сторонним или делать самому.

**Comment by vlad7090** [comment]
шаблон должен работать корректно на всех устройствах. я бы с удовольствием помог в верстке, если понадобится моя помощь

**Comment by pin-git** [comment]
Вы в нужном месте, готовьте предложение и отправляйте в пулл. Разработчики рассмотрят.

**Comment by vlad7090** [comment]
> Вы в нужном месте, готовьте предложение и отправляйте в пулл. Разработчики рассмотрят.

у вас на сайте вроде как видел сию наработку:)

**Comment by iWeb1** [comment]
Очень актуальная на сегодняшний день тема, так как админу особенно крупного портала постоянно и в любом месте с любого устройства необходима постоянная работа на сайте ! Поддерживаю предложение !
