### ISSUE TITLE
Добавить возможность скрытия ленты активности от гостей.

### ISSUE THREAD

**Issue by Big-coder** [instantsoft/icms2#1081]
**Используемая версия InstantCMS**: 2.12.2

**Версия PHP**:  7,2

**Как воспроизвести проблему**:

* В пункте меню "Лента активности" запрещаю доступ гостям
* Пункт меню не показывается для гостей, но при вводе напрямую в строке браузера адрес: https://ваш_домен/activity лента все равно отображается гостям
* В настройках самой компоненты "Лента активности" тоже нет настроек доступа
О проблеме также написал на форуме:
https://instantcms.ru/forum/thread32021-1.html

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/activity: ДА

Этот текст можно стереть, если вы сообщаете не о баге, а пишите пожелание/предложение.
Заранее спасибо.

**Comment by fuzegit** [comment]
Доступ для показа пункта меню относится к самим пунктам меню, а не их урлам.
Как решить вашу задачу вам подсказали на форуме.
