### ISSUE TITLE
Смена порядка выполнения задач в планировщике

### ISSUE THREAD

**Issue by zau4man** [instantsoft/icms2#1090]
**Используемая версия InstantCMS**: 2.12.2

В версиях 2.12.2 задачи в планировщике выполняются по порядку. Иногда возникает ситуация, когда одна из задач "сбоит" и мешает выполняться всем последующим. Такое бывает с тяжеловесными задачами парсинга, постера, или из-за скрытых лимитов хостинга. И не всегда обнаруживается оперативно.

Предлагаю добавить возможность смены порядка выполнения задач в планировщике. Тогда можно будет важные (системные, например) задачи поднять повыше, и точно быть уверенными, что они выполнятся.

**Comment by my-instantcms** [comment]
Я решаю проблемы тяжелых задач так:
Вставляю галочку на "Строгое следование периоду" и укажу последний запуск в 2 часа ночи
