### ISSUE TITLE
Добавить smartcrop (умную обрезку) в опциях пресетов изображений

### ISSUE THREAD

**Issue by webtotma** [instantsoft/icms2#1091]
В версии 2.12.2 добавлены следующие изменения:

- Переработан конвертер изображений, в пресетах добавлены новые опции: гамма коррекция, режим строгой обрезки, увеличение маленьких 

Реально ли  добавить функцию-опцию - умная обрезка (smartcrop)?

**Comment by fuzegit** [comment]
Что это?

**Comment by webtotma** [comment]
Т.е. кропит с учетом значимых деталей на фото
Вот один из примеров реализации: 
https://github.com/xymak/php-smartcrop-extension

**Comment by fuzegit** [comment]
> Т.е. кропит с учетом значимых деталей на фото

Это как раз понятно.

Реализовывать на PHP нечем. Пример реализации  - это php модуль, который нужно компилировать, подключать. 99.9% пользователей InstantCMS это делать не будут. А кто будет, сделает это и сейчас.

> Первоначальная реализация на js:

Это серверный js, Nodejs. Пакет с кучей зависимостей. Писать самостоятельно - не самая лучшая идея. Есть множество более важных задач для развития InstantCMS.
