### ISSUE TITLE
Массовая загрузка фото в фотоальбом

### ISSUE THREAD

**Issue by bilarius** [instantsoft/icms2#1092]
InstantCMS 2.12.2

Версия PHP 5.6.40

Фото в компоненте Фотоальбомы больше трех не грузит за один раз

Воспроизводится ли проблема на демо - нет нет возможности загружать фото в фотоальбомы 

![1 (2)](https://user-images.githubusercontent.com/6613897/63128899-d3d2a680-bfbe-11e9-85cc-b5e5128f878d.jpg)

**Comment by fuzegit** [comment]
Не могу повторить проблему. Всё работает на чистой установке. Откройте консоль браузера и смотрите ошибки.

**Comment by bilarius** [comment]
Создал тему https://instantcms.ru/forum/thread32138-1.html#315081
Ок сейчас буду смотреть в консоли

**Comment by bilarius** [comment]
![ууу](https://user-images.githubusercontent.com/6613897/63129175-915d9980-bfbf-11e9-9eff-6d67d3113716.jpg)

**Comment by bilarius** [comment]
Все понял - Проблема только в конструкторе тем
Тему закрывать надо

**Comment by fuzegit** [comment]
Обновите js файлы вашего шаблона. Вы опускаете информацию, что всё это происходит не на дефолтном шаблоне, а на шаблоне конструктора тем.
