### ISSUE TITLE
Сделайте уже наконецто шаблон сайа как новую Админку!

### ISSUE THREAD

**Issue by andrewua85** [instantsoft/icms2#1098]
Лучше в место новой Админки, сделали новый шаблон самой instantCMS 2.12.3
Я конечно рад таким изменениям, но блин не в админке менять весь шаблон а лучше в клиентской части обновить древний шаблон.

**Comment by fuzegit** [comment]
Не зная, не стоит писать.
https://instantcms.ru/forum/thread32086-1.html

**Comment by andrewua85** [comment]
Там собственно речь идет за Админку. По поводу нового Шаблона сайта толком не понятно, будет или нет, когда и  какие планы по поводу нового Шаблона =\
Там только предложения и идеи и больше ничего...

**Comment by fuzegit** [comment]
Мы прекрасно понимаем, что новый шаблон нужен. Ссылку вам дали для того, чтобы 
> Лучше в место новой Админки, сделали новый шаблон

вам стало понятно, почему приоритетной стала админка.
