### ISSUE TITLE
Более подробная статистика на домашней странице админки

### ISSUE THREAD

**Issue by Maratakziaplus** [instantsoft/icms2#110]
Было бы отлично, если бы на на домашней странице админки выводилась более подробная статистика, такие как, количество контента на сайте по типам контента, количество пользователей и т.д.

**Comment by fuzegit** [comment]
Maratakziaplus, влезать в вашу голову и разбираться что она имела в виду и как себе представляет никто не будет.

**Comment by pin-git** [comment]
Предлагаю рассмотреть возможность добавлять в Dashboard виджеты сторонних разработчиков.

**Comment by fuzegit** [comment]
> Предлагаю рассмотреть возможность добавлять в Dashboard виджеты сторонних разработчиков.

так уже сейчас можете это делать. все хуки есть для этого. admin_dashboard_chart, admin_dashboard_block

**Comment by pin-git** [comment]
оказался не внимателен, спасибо!

**Comment by iAndroS** [comment]
Было бы неплохо в дашборде видеть последние опубликованные материалы на МОДЕРАЦИИ
