### ISSUE TITLE
Счетчик позиции записи в наборе и общее количество материалов

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#1101]
Есть тип контента "Организации".
Есть наборы, один из которых Рейтинг. 
Хотелось бы выводить на странице и/или в метатегах организации ее место в наборе из общего количества организаций.

>  "Компания **{title}** находится на **XX** месте среди **XXX** компаний города".

 Это можно было бы выводить только при условии, если бы были поля-счетчики, показывающие реальную позицию записи по рейтингу.
В идеале, если бы данный счетчик еще бы и по категориям работал... 

> "Компания **{title}** находится на **XX** месте в категории **{category}** среди **XXX** компаний города и на **XX** месте в общем рейтинге компаний!". 

Готов профинансировать данную доработку для включения в ближайший релиз.

**Comment by Risgit** [comment]
Функционал очень специфический и нишевый.
Делается одним хуком.
Стоит ли это включать в релиз?

**Comment by iAndroS** [comment]
> Функционал очень специфический и нишевый.
> Делается одним хуком.
> Стоит ли это включать в релиз?

Вы уверены? Если решается хуком, цена вопроса? Напишите мне в ЛС на сайте, пожалуйста
