### ISSUE TITLE
Не отправляется почта с настройками SMPT Yandex

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#1102]
**Используемая версия InstantCMS**: 2.12.2

**Версия PHP**:  5.6.37

**Как воспроизвести проблему**: сделать настройки SMPT Yandex и протестировать почту

* первый шаг: прописываем настройки Яндекс почты с SMPT
* второй шаг: тестируем, письма не уходят. Ошибка "SMTP Error: Could not connect to SMTP host. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting"
* третий шаг: прописываем настройки другой почты - допустим mail.ru и всё работает без ошибок. 

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: Не могу проверить не даёт сохранить файл конфигурации

Переписывался с хостером и с Яндексом.

Ответ хостера:

Здравствуйте, класс /var/www/u0006953/data/www/ваш_домен/mail/SendMailSmtpClass.php в принципе не работает ни по 25 порту без шифрования ни по 465 с шифрованием.

Попробовали также и оригинальный класс https://raw.githubusercontent.com/Ipatov/SendMailSmtpClass/master/SendMailSmtpClass.php

Те же ошибки. Проблема не в хостинге.

Обратитесь к разработчику.

Домен делегирован Яндексу - Яндекс ответил что с почтой проблем нет, проверил через себя и через свой компьютер по их подсказкам, письма ходят туда-сюда нормально.

Рекомендовали обратиться к разработчику почтовой программы.

![21-10-2019 11-12-44](https://user-images.githubusercontent.com/9349934/67373516-75124600-f588-11e9-969c-2234015fb4ad.png)
![23-10-2019 11-31-26](https://user-images.githubusercontent.com/9349934/67373655-ae4ab600-f588-11e9-9fa6-35fbfc1850d3.png)
С настройками mail.ru
![23-10-2019 10-59-12](https://user-images.githubusercontent.com/9349934/67373814-ebaf4380-f588-11e9-890f-af19db579d40.png)
![23-10-2019 11-34-21](https://user-images.githubusercontent.com/9349934/67373923-1ac5b500-f589-11e9-9ba8-9a4931c91a87.png)

**Comment by fuzegit** [comment]
Очевидно, Яндекс что-то поменял у себя, всё прекрасно работало.

**Comment by fuzegit** [comment]
![Выделение_065](https://user-images.githubusercontent.com/13233234/67378306-bbb76e80-f58f-11e9-9bd0-ca85bd570be2.png)

И работает дальше без проблем. Вот с такими настройками тестовое письмо ушло. Проверил только что.

**Comment by nomad48** [comment]
Что делать то?

**Comment by fuzegit** [comment]
Не ко мне вопрос

**Comment by nomad48** [comment]
@fuzegit поддержка хостера пишет что - Отправка почты не работает только через используемый сайтом php класс. Подскажите пожалуйста какие файлы сравнить с дистрибутивом ICMS 2
![23-10-2019 12-48-58](https://user-images.githubusercontent.com/9349934/67380826-9593cd80-f593-11e9-8f50-8aa151998413.png)

**Comment by fuzegit** [comment]
Я еще раз вам пишу. Я проверил. Тестовое письмо отправлено. Настройки на скриншоте выше. Отправляется всё через https://github.com/instantsoft/icms2/tree/master/system/libs/phpmailer

**Comment by nomad48** [comment]
@fuzegit да ничего я не превышал. Сейчас попробую обновить указанные файлы.

**Comment by nomad48** [comment]
@fuzegit подскажите пожалуйста, поддержка хостинга спрашивает:

> "Как включить отладку smtp сессии в cms при проверке. Чтобы можно было посмотреть на ответ сервера и узнать причину."
> Дело осложняется тем, что яндекс принимает только шифрованное подключение и через telnet достаточно сложно реализовать проверку.

![23-10-2019 16-38-30](https://user-images.githubusercontent.com/9349934/67398581-9177a800-f5b3-11e9-8572-cf055c28bd59.jpg)

**Comment by fuzegit** [comment]
Ответ отдаётся при отправке письма. Показывается в админке.
В cms я уже писал какая используется библиотека. https://github.com/PHPMailer/PHPMailer
Мы не писали ничего своего для отправки email.
У меня всё работает по прежнему. Очевидно, что проблема не в библиотеке, не, тем более, в cms.
