### ISSUE TITLE
Публикация текущей записи во время модерации

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#1103]
**Используемая версия InstantCMS**: 2.12.2
**Версия PHP**:  7.1.14

**Как воспроизвести проблему**:

* Создаем запись обычным юзером, отправляем на модерацию
* Модер принимает запись на публикацию, поисковики получают пинг и кушают статью
* Юзер вносит правки в текущую статью (в настройках стоит логичное "редактировать свои с премодерацией"), материал снова уходит на модерацию
* В этот момент по скушанному ранее поисковиками url 403 ошибка.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

Данная проблема обсуждалась уже давно, а воз и ныне там. Предлагаю на время модерации заблокировать возможность редактирования кем-либо записи с указанием причины аля "в данный момент статья находится на редактировании и/или ожидает модерации. Вы можете посетить эту страницу позже и/или подписаться на ее обновление." 

Для настроек модерации в настройках типов контента можно сделать одноименный блок настроек, в котором задавать различные параметры модерации, в том числе и вышеупомянутый комментарий задавать можно там же. 

Самое главное, суть этой заметки: нельзя снимать с публикации уже размещенный материал! Пусть остается текущая версия до принятия новой редакции! Вопрос уже как минимум 2 года актуален https://instantcms.ru/forum/thread28334-1.html#272993

**Comment by fuzegit** [comment]
Я готов выслушать пожелания, обсудить и принять решение.
