### ISSUE TITLE
Модерация "Страница появится на сайте после проверки"

### ISSUE THREAD

**Issue by SergeyRN** [instantsoft/icms2#1106]
Пожелание.

Предупреждение о том что страница появится на сайте после модерации перед отправкой есть, но как то ИМХО процесс (отправки материала при включенной модерации) выглядит логически не завершенным, а кому то и не понятным (заметил на своих сайтах)... 

Кто то не читает предупреждение о модерации перед отправкой,  отправляет, его перекидывает на сайт, он не понимает, отправлен материал или нет, отправляет повторно и т.д.

Хотелось бы после отправки материала на модерацию, что бы юзер попадал на страницу уведомления "Страница появится на сайте после проверки" со ссылкой для перехода на Главную (Или например кнопкой "Хорошо" и переходом на Главную), а не просто (как сейчас) перекидывало на Главную.

**Comment by fuzegit** [comment]
Уведомления **после** добавления записи есть. Вплоть до того, какому модератору отправлено. И перекидывать должно не на главную.
