### ISSUE TITLE
Страницы и виджеты: список виджетов с картинками

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#1107]
Предлагаю добавить возможность к виджетам прикреплять картинку, а не только название. Как-то так:

![3в3в3](https://user-images.githubusercontent.com/16401582/67855623-d2c40680-fb23-11e9-9297-e3fb1d20cb7e.jpg)

Для этого надо в таблицу виджетов добавить поле image, где прописывается имя картинки. Картинку поставлять в корне дистрибутива и при установке грузить в какую-то конкретную папку. И дальше условие в шаблоне админки, если картинка указана, то ее выводить, а если нет, то не выводить. Работы на несколько минут, если знать, где копать.

Неверное будет отклонено с пометкой "не требует решения". На всякий случай попробую объяснить, для чего это может понадобиться. Когда-нибудь, возможно, в этой жизни, планирую запилить шаблон (мини-конструктор лендингов), там будет много виджетов разных со странными названиями. А если бы визуально было видно, что за виджет, было бы гораздо удобнее конечному пользователю. Как в списке доступных виджетов, так и в схеме позиций.

Спасибо.

**Comment by fuzegit** [comment]
Такой виджет с картинкой показывать только в блоке всех виджетов? На схеме обычно?

**Comment by asnenne** [comment]
Можно было бы и на схеме)))

Например, лендинг состоит из 12 разных блоков - отдельных виджетов. Визуально ведь понятнее, что идет за чем, и что куда перетащить.

Спасибо.

**Comment by fuzegit** [comment]
![Выделение_110](https://user-images.githubusercontent.com/13233234/68387793-34aded00-0170-11ea-9ad4-5b508d076c7e.png)

Как то так устроит?

**Comment by asnenne** [comment]
В зависимости от картинки, она может сливаться с текстом. Тут можно было бы как-то так сделать:
Шапка - в ней название и иконка перетаскивания
Картинка под шапкой, если она есть для виджета. Ширина картинки 100%, а высота auto.
![2019-11-07_151015](https://user-images.githubusercontent.com/16401582/68388123-febd3880-0170-11ea-83fb-c12fc4e7bca7.jpg)

**Comment by fuzegit** [comment]
![Выделение_111](https://user-images.githubusercontent.com/13233234/68388775-6de75c80-0172-11ea-8a21-1c797c2b4aae.png)

**Comment by asnenne** [comment]
Вот, то что надо)))

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/19ef497a40fad4a08c1e670876b0062e790fc2a0
https://docs.instantcms.ru/dev/packages#блок-info

**Comment by asnenne** [comment]
Всё хорошо, кроме одного момента. Если картинка большая, то она в списке виджетов растягивается на всю ширину экрана. Ломается верстка вся. Предлагаю сделать так:

`#cp-widgets-list li > img{
    max-width:250px;
}`
Вместо 250px можно другое значение, подходящее для шаблона.

Спасибо.

**Comment by asnenne** [comment]
> Всё хорошо, кроме одного момента. Если картинка большая, то она в списке виджетов растягивается на всю ширину экрана. Ломается верстка вся. Предлагаю сделать так:
> 
> `#cp-widgets-list li > img{max-width:250px;}`
> Вместо 250px можно другое значение, подходящее для шаблона.
> 
> Спасибо.

В 2.14 проблема исправлена в одном месте, но добавлена в другом)))
![0](https://user-images.githubusercontent.com/16401582/102885804-08812880-4465-11eb-812f-9f3e27c381e8.jpg)

```#cp-widgets-list li > img{max-width:200px;}``` надо было только для `#cp-widgets-list li > img` делать, а не для всех.

Спасибо.

**Comment by asnenne** [comment]
Вот так предполагалось
![0](https://user-images.githubusercontent.com/16401582/102886146-a37a0280-4465-11eb-9ec5-9a2c1e3dacb3.jpg)

**Comment by fuzegit** [comment]
исправил
https://github.com/instantsoft/icms2/commit/b9fed817a726c7ac68b8853d8517e7c8cef4fed4#diff-d33ff82509d184b61001b188570adef7599bc8eca225276822b4a4d7fbeda52aR769
