### ISSUE TITLE
Мертвые души в профиле админа

### ISSUE THREAD

**Issue by ToxicSisters** [instantsoft/icms2#1108]
В профиле админа считаются пользователи которых нет на сайте. И устанавливается демо контент которого там не должно быть. См.  скриншоты ниже.

**Используемая версия InstantCMS**: 2.12.2 и та что с гита

**Версия PHP**:  7.1

**Как воспроизвести проблему**:

* Установить движок с АНГЛИЙСКОЙ версией БЕЗ демо данных (то бишь голый)
* зайти в профиль админа и наблюдать вкладки Friends и Subscribers. Поклацать по ним и убедиться что считаются пользователи которых нет.
* Наблюдать заполненный профиль, который по идее в версии без демо данных должен быть голым.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: невозможно проверить.

**Вкладки профиля без людей**

![friends](https://user-images.githubusercontent.com/43343657/67966949-74735280-fc0d-11e9-978c-92401c95de40.png)

**Демо контент**

![demoadmin](https://user-images.githubusercontent.com/43343657/67967121-aedcef80-fc0d-11e9-822d-a95c9e103652.png)

И еще при установке движка похоже путь к файлу config указан с лишним слешем.  Должно быть так /var/www/html/site1/system/config но указывается /var/www/html/site1//system/config
То есть один слеш перед system лишний.

**Скриншот установки**

![2sl](https://user-images.githubusercontent.com/43343657/67967707-c072c700-fc0e-11e9-83da-e7d1ef5c4e9a.png)
**Скриншот с реальными путями к файлу**

![puti](https://user-images.githubusercontent.com/43343657/67968465-1dbb4800-fc10-11e9-92c1-4ee8151d087c.png)

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/19ef497a40fad4a08c1e670876b0062e790fc2a0
