### ISSUE TITLE
Не переопределяется H1 в наборах

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#1111]
**Используемая версия InstantCMS**: 2.12.2

**Версия PHP**:  7.1.14

**Как воспроизвести проблему**:

* Создаем набор
* Редактируем "Шаблон генерации тега h1"
* Обновляем страницу, изменений никаких - H1 берется из названия набора

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
![Выделение_114](https://user-images.githubusercontent.com/13233234/68599171-2c77e980-04b1-11ea-871f-d1dea787e24a.png)

Перейдите в категорию и всё будет как положено.

**Comment by fuzegit** [comment]
Ну так задайте шаблон в общих настройках типа контента
