### ISSUE TITLE
Проблема со скриптом templates/default/js/fileuploader.js

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#1112]
**Используемая версия InstantCMS**: 2.12.2

Cкрипт - templates/default/js/fileuploader.js

Проблема заключается в том, что при добавлении в модальную форму полей типа Изображение посредством ajax-запроса все уже существующие в форме поля типа Изображение перестают работать

(Error: Passed obj in not a File (in qq.UploadHandlerXhr))

Решение:
строка 371
`if (this._handler instanceof qq.UploadHandlerXhr){`
заменить на
`if (this._handler.hasOwnProperty("_xhrs")){`

Описание ситуации - https://yiiframework.ru/forum/viewtopic.php?t=2470&start=80#p118082

Спасибо.

**Comment by fuzegit** [comment]
В остальных местах проверяли, всё работает?

**Comment by asnenne** [comment]
На самом деле специально не проверяли. Столкнулись в процессе.
