### ISSUE TITLE
Методы класса cmsForm - addHtmlBlock, addHtmlBlockToBeginning, addHtmlBlockAfter не работают

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#1113]
**Используемая версия InstantCMS**: 2.12

Методы класса cmsForm - addHtmlBlock, addHtmlBlockToBeginning, addHtmlBlockAfter не работают.

Не удалось добавить блок HTML-кода в форму ни одним из указанных методов, например:

```
<?php class formMyWidgetOptions extends cmsForm {

    public function init() {
        
        $this->addHtmlBlockToBeginning('xxx', '<p>Я HTML-блок в начале формы!</p>');
```

**Comment by fuzegit** [comment]
В приведённом вами примере подход неверный.
Если вы хотите в описании формы добавить, то нужно делать:
```
public function init() {

    return array(
        array(
            'type' => 'html',
            'content' => '<p>Я HTML-блок</p>'
        )
    );

}
```

**Comment by asnenne** [comment]
Ок, понял, спасибо.
