### ISSUE TITLE
Карма для групп

### ISSUE THREAD

**Issue by vitasport22** [instantsoft/icms2#1123]
Репутация в группы для защиты от спама. Новички не могли создавать группы.
Функция нужная и полезная.

**Comment by Toxu-ru** [comment]
Мы имеем возможность запретить "Новичкам" создавать группы.
Компоненты: Группы  -> Доступ->Создание групп->Новички (Нет)
А вот интересно, а **количество** групп, которое можно создать, есть ограничение?
