### ISSUE TITLE
Убрать из формы авторизации предупреждение о несохраненных данных.

### ISSUE THREAD

**Issue by Risgit** [instantsoft/icms2#1124]
**Используемая версия InstantCMS**: 2.12.3

**Версия PHP**:  7.2.20

**Как воспроизвести проблему**:

* первый шаг  Нажать кнопку "Выйти"
* второй шаг   Попробовать перейти на другую страницу сайта.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**:  НЕТ, там другая версия движка.

В неавторизованном состоянии, если на странице присутствует виджет авторизации и в нем что-нибудь написано, каждый переход сопровождается всплывающим предупреждением о несохраненных данных, которое приходится закрывать. Это очень неудобно.
Можно ли как-нибудь отключить это предупреждение именно для формы авторизации (в остальных пусть будет) ?
У себя на тестовом сайте сделал так: обернул вывод предупреждения о несохраненных данных в \templates\default\assets\ui\form.tpl.php в условие.
```
<?php if ($attributes['action'] != '/auth/login'){ ?>
 icms.forms.initUnsaveNotice();
<?php } ?>
```
Работает нормально, алармы не всплывают.

**Comment by Toxu-ru** [comment]
Файл form.tpl.php используется в другом месте. Зайдите скажем в админку / поля и там должны быть ошибки, ИМХО.

**Comment by kalisto74** [comment]
админку / поля
а можно полный путь? 

 

С ув., дизайнер, программист Татьяна Ануфриева
 <https://kali100.ru/> https://kali100.ru/
тел. 8 908 571 4864

**Comment by Toxu-ru** [comment]
@Risgit  очень интересно. Видимо это мой персонально случай. Хм... 
`—`
использование этого символа в одной языковой переменно, выдает ошибку.  
https://www.artlebedev.ru/kovodstvo/sections/97/

Установил движок по умолчанию. Ошибки нет. Давайте я изучу это, и если что, постараюсь выйти на вас.

**Comment by kalisto74** [comment]
System/fields – в папке много файлов и где смотреть и что править?

 

С ув., дизайнер, программист Татьяна Ануфриева
 <https://kali100.ru/> https://kali100.ru/
тел. 8 908 571 4864
