### ISSUE TITLE
Проблема с отображением вкладок профиля

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#1128]
**Используемая версия InstantCMS**: 2.12.2
**Задача**
Выводить вкладку профиля ее владельцу и администраторам/модераторам проекта
**Как воспроизвести проблему**:

* Ставим соответствующие настройки 
![Screenshot_1](https://user-images.githubusercontent.com/17408903/70323061-c8a1d000-1866-11ea-88e3-41f8acc23d0e.png)

Вкладку не видит никто. Получается какой-то конфликт между условием "только юзеру" и при выборе, каким группам еще можно показывать.

* Убираем галочку "Показывать вкладку только владельцу профиля" - тогда ее видят только админы, юзер не видит у себя в профиле...
* При таких настройках 
![Screenshot_2](https://user-images.githubusercontent.com/17408903/70322877-46191080-1866-11ea-8e40-f8f6610bb992.png)
пользователь свой профиль видит без настраиваемой вкладки, все остальные профили отдают 404 ошибку. 

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

Вроде некритичная настройка и багом не назовешь, но заложенные функции не отрабатывают возложенные надежды )

**Comment by fuzegit** [comment]
> Вкладку не видит никто.

Вскладку видят все, согласно условиям.

> пользователь свой профиль видит без настраиваемой вкладки, все остальные профили отдают 404 ошибку.

вкладка на скриншоте отключена.

Проблема то в чем?
