### ISSUE TITLE
Клонирование записи типа контента одним кликом

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#113]
При организации каталога на сайте очень не хватает возможности клонирвоания записи, т.к бывает, что позиции отличаются всего 1-2 свойствами, которые легче после клонирования исправить, нежели добавить полностью новую запись вручную.
Также сам тип конента было бы хорошо мочь клонировать одним кликом.

**Comment by Val-Git** [comment]
> Также сам тип конента было бы хорошо мочь клонировать одним кликом.

Где-то на сайте, если не ошибаюсь, проскакивало дополнение которое позволяет копировать и сохранять типы контента

**Comment by vlad7090** [comment]
> а записи в типах контента?

**Comment by Val-Git** [comment]
@vlad7090, нет копирование/клонирование записей не видел ;)

**Comment by fuzegit** [comment]
#545
