### ISSUE TITLE
Добавление 2 полей в 2 таблицы (rating)...

### ISSUE THREAD

**Issue by Toxu-ru** [instantsoft/icms2#1131]
Возможно это частный случай. 
Для внутренней статистике (графиков, например) данное решение, ИМХО. может быть полезно.  "Голосование" является важной социальной функцией, и ее можно использовать далее, чтобы расширить, например. 

`ALTER TABLE `N_rating_log` ADD `date_add` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `ip`;
ALTER TABLE `N_comments_rating` ADD `date_add` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `score`;`

**Comment by fuzegit** [comment]
> Для внутренней статистике (графиков, например) данное решение, ИМХО. может быть полезно.

Само собой полезно. Когда делается дополнение, нужные поля и добавляются. Добавлять столбцы "просто так на будущее" не вижу никакого смысла. Как только мы решим задействовать указанные поля в движке, они сразу будут добавлены.
