### ISSUE TITLE
Добавление виджетов с фронта.

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#1135]
Было бы очень удобно, чтобы можно было в страницу вставлять виджеты с фронта, а не только через админку. Сильно облегчало бы задачу по расстановке виджетов.

Т.е если на страницу записи типа контента или в раздел типа контента добавляется виджет с фронта, то такая страница автоматически в админке попадает в Пользовательские страницы в разделе "Виджеты".

**Comment by robotanks-llc** [comment]
Идея интересная, но думаю это создаст лишнее нагромождение функционала.

**Comment by vlad7090** [comment]
по сути появится две кнопки в панели админа во фронте - показать виджеты. После этого показываются виджеты справа или слева также колонкой, как и в админке.

И далее видна сетка для расстановки этих виджетов - т.е дублируем функционал админки, только получается удобнее сразу визуально видеть что и куда встает.
