### ISSUE TITLE
Цель ссылок в подменю, генерируемых специальными ссылками

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#1142]
**Используемая версия InstantCMS**: 2

При создании пункта меню мы можем указать цель ссылок, например, открывать в новом окне. Но было бы логично эту цель применять и к генерируемым пунктам меню в этом подменю. 

Например, специальный пункт меню **{admin:menu}**, устанавливаем цель "В новом окне"  (**target="_blank"**), отлично, панель управления открывается в новой вкладке. Но сгенерированный пункт меню **/admin/content** открывается в текущей вкладке. Почему, если нужно все разделы админки открывать в новой вкладке?

Предлагаю добавить опцию "Применить ко всем пунктам меню нижнего уровня для специальных ссылок".

Спасибо.

**Comment by fuzegit** [comment]
> Предлагаю добавить опцию "Применить ко всем пунктам меню нижнего уровня для специальных ссылок".

Тогда уж просто сразу применять, к чему опция

**Comment by asnenne** [comment]
Можно и сразу. Насчет опции на всякий случай предложил.

**Comment by yuri25** [comment]
Я извиняюсь если не по теме... А для чего нужно все разделы админки открывать в новой вкладке? Может чего то не понимаю, но зачем плодить открытые вкладки в браузере?

**Comment by fuzegit** [comment]
> но зачем плодить открытые вкладки в браузере?

Разговор не о об этом. Абстрагируясь, разговор о том, что опция работает не так, как от неё ожидают. Это надо исправить.
А опцию как открывать ссылку, т.е. атрибут тега <a target="" вы можете не задавать. Всё на ваше усмотрение.
