### ISSUE TITLE
Выбор иконки, для шапки виджетов.

### ISSUE THREAD

**Issue by lakomet** [instantsoft/icms2#1143]
Предлагаю добавить выбор иконки, для шапки виджетов. 
![vybor](https://user-images.githubusercontent.com/20047445/71982854-733f5100-3260-11ea-8ade-b9eb506bb0eb.png)
.

Выводить перед заголовком виджета 
.
![vybor2](https://user-images.githubusercontent.com/20047445/71982893-8a7e3e80-3260-11ea-8a5e-2d6246951650.png)
.
Первое - это будет эстетичней смотреться, а второе, когда в сайтбар помещаем объеденённые виджеты, порой названия виджетов не всегда помещаются, у них можно будет отключить вывод названий виджетов, оставив только иконки.

**Comment by fuzegit** [comment]
Будет реализовано для шаблона modern.
