### ISSUE TITLE
Настройка отключения виджетов в админке не сохраняется

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#1144]
**Используемая версия InstantCMS**: 2.13.0

**Версия PHP**:  7.1.14

**Как воспроизвести проблему**:

* Заходим в админку /admin
* В правом верхнем углу нажимаем "Настроить эту страницу" /admin/index_page_settings
* Снимаем галочки с виджетов, которые не хотим видеть
* Сохраняем и видим, что ничего не изменилось - виджеты остались на месте, при входе в настройки страницы также все виджеты включены.

**Comment by fuzegit** [comment]
Напишите, пожалуйста, подробности.
