### ISSUE TITLE
Url категории untitled

### ISSUE THREAD

**Issue by 2murkin** [instantsoft/icms2#1147]
**Используемая версия InstantCMS**:  2.13.0

Не правильно заполняется url категории

**Как воспроизвести проблему**:

* Изменить язык системы на EN
* В настройках типа контента выбрать "Генерировать URL из названия категории"
* Создать категорию на русском языке

**Comment by fuzegit** [comment]
Это ожидаемо. Если сайт англоязычный, то и генератор url не знает о наличии других языков, не только русских. Можете попробовать создать при выбранном русском языке категорию, скажем на польском.
