### ISSUE TITLE
Авторизация по номеру телефона

### ISSUE THREAD

**Issue by VunderkindMedia** [instantsoft/icms2#1148]
Практически все существующие ресурсы используют авторизацию/регистрация/ремембер по номеру телефона. Почему же такой мощный конструктор ICMS2 не имеет до сих пор этой функции. Реализация сводится к 15 мин. рефакторинга существующей системы для хорошего программиста. 
Думаю большинство поддержат эту хотелку.

**Comment by fuzegit** [comment]
> Реализация сводится к 15 мин. рефакторинга существующей системы для хорошего программиста.

Никогда не пишите так, если хотите, чтобы кто-то, кроме вас, это сделал.

**Comment by fuzegit** [comment]
#1145

**Comment by VunderkindMedia** [comment]
> > Реализация сводится к 15 мин. рефакторинга существующей системы для хорошего программиста.
> 
> Никогда не пишите так, если хотите, чтобы кто-то, кроме вас, это сделал. Сделайте этот новый функционал за 15 минут и пришлите пулреквест. Учтите только, что нужно оставить совместимость с текущим функционалом, должен быть выбор по каким полям авторизоваться, все SMS сервисы платные и в коробку их включать нельзя.

Понял. Приношу свои извинения.
Я не php программист и очень слаб в этом, но раз уж такое дело - то очень постараюсь. Очень жаль, что нельзя в коробку. SMS сервисы платные, несомненно, но если будет выбор, по каким полям авторизоваться - почему в \том случае нельзя поместить в коробку?
Или тут дело в модели распространения движка, лицензия и т. д.?

**Comment by fuzegit** [comment]
> SMS сервисы платные, несомненно, но если будет выбор, по каким полям авторизоваться - почему в \том случае нельзя поместить в коробку?

Что поместить в коробку? Авторизацию по любым полям сделаем в перспективе. Интеграцию коммерческих SMS сервисов нет.
Программно, уже сейчас можно сделать авторизацию хоть по чему.

**Comment by VunderkindMedia** [comment]
> > SMS сервисы платные, несомненно, но если будет выбор, по каким полям авторизоваться - почему в \том случае нельзя поместить в коробку?
> 
> Что поместить в коробку? Авторизацию по любым полям сделаем в перспективе. Интеграцию коммерческих SMS сервисов нет.
> Программно, уже сейчас можно сделать авторизацию хоть по чему.

Ведь для этого необходимо корректировать ядро: 

`public static function login($email, $password, $remember = false, $complete_login = true) {

        if (!$email || !$password){
            return 0;
        }

        $model = cmsCore::getModel('users');

        $user = $model->getUserByAuth(**$email**, $password);`

Аналогично в модели. Хотя Вы и сами лучше меня знаете.
Я могу ошибаться, ввиду отсутствия достаточных знаний, надеюсь что это так
