### ISSUE TITLE
Личные сообщения некорректно работают / не работают

### ISSUE THREAD

**Issue by yuri25** [instantsoft/icms2#1149]
**Используемая версия InstantCMS**:  последняя с GitHub

**Версия PHP**:  7.3.11

**Как воспроизвести проблему**:
Выбрать какого нибудь пользователя и нажать пункт "Написать сообщение"
После набора сообщения и нажатия кнопки отправить - сообщение продолжает оставаться в поле набора текста. Если несколько раз нажать кнопку отправить то при обновлении страницы и последующем заходе в сообщения наблюдаю множество отправленных сообщений (сколько раз нажал кнопку отправить). Далее выделяю любое из этих сообщений - сверху не появляются кнопки - удалить сообщение и удалить контакт.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: НЕТ На демо сайте проверил - работает все корректно. На своем тестовом ничего не менял - чистая установка и регистрация одного пользователя - и не работает отправка ЛС как я описал.

**Comment by fuzegit** [comment]
Кэш браузера конечно же чистили?
Какой редактор личных сообщений выбран?

**Comment by yuri25** [comment]
Кеш чистил, редактор не выбирал - то что было по умолчанию

**Comment by yuri25** [comment]
В настройках компонента выбрал - Redaktor:  Редактор для личных сообщений - заработало:)

**Comment by fuzegit** [comment]
Был какой редактор?

**Comment by yuri25** [comment]
Сейчас попробовал выбирать другие редакторы в настройках этого компонента - они некорректно работают. У большинства модальное окно снизу обрезано - не видно кнопки отправить, у textarea - аналогично не уходит отправляемый текст, висит окно с текстом.  Просто зачем в настройках компонента столько редакторов... Может есть смысл оставить только вот это - Redaktor: Редактор для личных сообщений?

**Comment by fuzegit** [comment]
> У большинства модальное окно снизу обрезано

для этого нужно задать нужную высоту в настройках редактора

> Просто зачем в настройках компонента столько редакторов

Чтобы был выбор очевидно

**Comment by yuri25** [comment]
Попробовал, создал пресет для Tinymce, в настройках указал минимальная высота 50, максимальная высота 100.  Кнопка снизу появилась, все работает... Только слишком узкое поле для ввода текста по высоте... 
![tinymce](https://user-images.githubusercontent.com/253228/72746684-c94ab780-3bc3-11ea-9d36-0696cb3b557d.jpg)

Это наверное надо в файлы лезть... В markitup и ace в настройках не нашел параметров высоты.

**Comment by fuzegit** [comment]
Вы когда меняете редактор в админке, страницу полностью обновляйте.
Проблемы нет.

Вид редактора в окне личных сообщений зависит от выбранного редактора и его пресета - т.е. высоты поля и выбранных кнопок.
Например, весьма странно выбирать ace редактор для личных сообщений.
