### ISSUE TITLE
Ошибка отправки почты после обновления phpmailer

### ISSUE THREAD

**Issue by mafru** [instantsoft/icms2#115]
Если в настройках сайта используется отправка почты через smtp, то она не работает и вызывает 500 ошибку.
В логах ошибка: 
PHP Fatal error:  Class 'SMTP' not found in /var/www/.../system/libs/phpmailer/class.phpmailer.php on line 1443 
Вот данная строка: $this->smtp = new SMTP;
Думаю вызвана тем, что нигде не подгружается файл - class.smtp.php из папки с phpmailer и система не может найти класс SMTP.
Посмотрите пожалуйста.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/d7798f1a9cbb2b9a519dd215416eef9bcd464828
Проверьте пожалуйста

**Comment by mafru** [comment]
Не знаю, сервер напрочь перестает отвечать на запросы (504 Gateway Time-out).
В логе:
upstream timed out (110: Connection timed out) while reading response header from upstream
До обновления phpmailer почта отправлялась нормально (это к тому, что не думаю что виноваты настройки nginx или apache).

**Comment by fuzegit** [comment]
Проверил сам. У меня отправилось без проблем.

![настройки почты]
(http://storage8.static.itmages.com/i/16/0210/h_1455126061_2549544_0f22e2e9aa.png)

**Comment by mafru** [comment]
Подтверждаю, с вашими настройками рабоатет.
Просто у меня раньше в поле smtp сервер было
tls://smtp.yandex.com и без шифрования.
До обновления mailer - работало.

**Comment by mafru** [comment]
Проблема решена.
