### ISSUE TITLE
Поведение виджета Фильтр контента

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#1161]
**Используемая версия InstantCMS**: 2.13.1

**Версия PHP**:  7.1.14

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

Хотелось бы, чтоб и в виджете отображалось количество найденных записей при отметки какого-либо значения в фильтре, как это сделано, если использовать системный фильтр контента, выводимый над записями (новая фича с прошлого релиза).

![image](https://user-images.githubusercontent.com/17408903/74431175-733dfc80-4e6f-11ea-8c35-e1307d23017c.png)

**Comment by fuzegit** [comment]
#1150
