### ISSUE TITLE
Предложение - заглушка для поля Изображение

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#1163]
**Используемая версия InstantCMS**: 2.13.1

**Версия PHP**:  7.1.14

При создании поля Изображение нет возможности указать файл изображения по умолчанию.
Но есть системное поле в настройках поля (сорри за тавтологию) "Предустановленные значения".

Предлагаю использовать его для указания ссылки на изображение по умолчанию, которое бы использовалось по принципу добавление изображения по ссылке. Указал один раз в настройках поля внешнюю или внутреннюю ссылку на изображение, а оно при сохранении настроек поля выкачивается на сервер и в дальнейшем используется в качестве заглушки для нашего поля.

**Comment by fuzegit** [comment]
Именно в этом поле сейчас и можно указать изображения по умолчанию. В формате YAML.

**Comment by iAndroS** [comment]
> Именно в этом поле сейчас и можно указать изображения по умолчанию. В формате YAML.

Можно конкретный пример? Погуглил, ничего толкового внятного по теме не нашел

**Comment by fuzegit** [comment]
На форуме был подобный вопрос, например как то так https://instantcms.ru/forum/thread27194-1.html
Поиск по сайту - предустановленные значения

**Comment by iAndroS** [comment]
ТС лишь процитировал вашу документацию. Я ее тоже читал после вашего первого ответа.
Я не первый год в сети и на инстанте, считаю себя вполне понимающим в теме, но документацию по этой части не могу однозначно читать и понимать. 

Возникает целый ряд вопросов: 

- мне указывать ссылку на каждый пресет изображения? 
- То есть, мне сначала загрузить изображение нужно и потом каким-то мистическим способом вычислить url изображения каждого пресета?
- А может, я могу указать единожды url изображения по умолчанию, какое я бы загружал в поле записи?
- Мне прописывать путь от /var/www/site/ или можно все-таки от корня сайта???

Не проще ли мной предложенный вариант использовать? Указал ссылку на изображение один раз, а движок там уже сам сформирует формат хранения данных, как ему нужно. Или прямо поле загрузки изображения по умолчанию в настройках поля сделать.

PS: да, я могу попробовать реализовать каждое из моих предположений при заполнении данного поля, после чистить кэш в браузере, на сайте, в клаудфлейр и т.д. При этом не факт, что увижу свои изменения. 
PPS: попробовал указывать и от корня и от var/www/site/... путь к одному изображению - просто заполняю поле как ссылка /var/www/site.info/upload/000/u1/3/9/photo-normal.png
Не работает такая схема. А вот на странице вывода записи, в которой не указано изображение, выводится Notice: Undefined offset: 1 in /var/www/impo/data/www/site.info/system/fields/image.php on line 166

ЧЯДНТ???
