### ISSUE TITLE
Предложение - добавить в настройки типа поля Изображение возможность загрузки файла-заглушки

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#1164]
**Используемая версия InstantCMS**: 2.13.1

**Версия PHP**:  7.1.14

**Как воспроизвести проблему**:

* Создаем поле Изображение
* Указываем в поле Предустановленные значения ссылку на имеющееся на сайте изображение
* Создаем запись в настраиваемом выше типе контента, при открытии страницы создания записи видим наше изображение
* Сохраняем запись - изображение не сохранилось
* Открываем любую запись на сайте в данном типе контента (с отсутствующим изображением) на редактирование - изображение по умолчанию не подгружается

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

Это в продолжении [этой темы](https://github.com/instantsoft/icms2/issues/1163), а также [этой](https://instantcms.ru/forum/thread32931-1.html). В любом случае, даже если исправить текущую логику работы данного типа поля, использовать его неудобно, ибо перед использованием сначала нужно где-то загрузить изображение на сайт (создать специально для этого закрытый тип контента???), затем получить ссылку на это изображение, и вставить ее в поле, убрав часть ссылки до папки аплоада.
Гораздо логичнее было бы, если б движок проверял "Если поле изображения NULL, то выводим загруженный в настройках типа поля файл изображения".

**Comment by numinaki** [comment]
как вариант, загружаете в любом типе контента фотографию, правой кнопкой мыши кликаете по картинке, жмете"копировать url картинки", вставляете url по умолчанию, удаляете только часть с доменом, а путь будет от корня.

**Comment by geminisf** [comment]
Проверил. Действительно изображение не сохраняется, хотя на этапе создания записи картинка показывается.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/801733d76cc77e7ef1db7fb9093d5d169dc017ee
