### ISSUE TITLE
Проблема со счетчиком контента

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#1165]
**Используемая версия InstantCMS**: 2.13.1

**Версия PHP**:  5.6.40

**Как воспроизвести проблему**: В новой админке напротив контента постоянно виден счетчик контента, при добавлении записей, счетчик возрастает.
При переходе по новым записям, счетчик не сбрасывается.

* первый шаг - добавить любой контент
* второй шаг - проверить счетчик
* третий шаг - перейти к новой записи
* четвертый шаг - счетчик не сбрасывается.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: Да

![25-02-2020 14-33-44](https://user-images.githubusercontent.com/9349934/75244013-049c5f80-57dc-11ea-8f52-1b01ccb7f5d7.jpg)
![25-02-2020 14-37-09](https://user-images.githubusercontent.com/9349934/75244185-6a88e700-57dc-11ea-9041-20676f032be6.jpg)

**Comment by fuzegit** [comment]
Это суммарное количество новых записей за последние сутки
