### ISSUE TITLE
Часовой пояс

### ISSUE THREAD

**Issue by chiefpromo** [instantsoft/icms2#1166]
Когда в админке выбираешь часовой пояс во вкладке "Дата", добавить чек-бокс: "Давать возможность пользователям выбирать свой часовой пояс в настройках профиля"?

**Comment by fuzegit** [comment]
Выбор часового пояса есть

![Выделение_010](https://user-images.githubusercontent.com/13233234/75246865-b12d1000-57e1-11ea-8b59-e963cfc215dc.png)

**Comment by chiefpromo** [comment]
А если отключить тот самый чек-бокс, о котором идёт речь, то этого выбора у пользователя не будет. Это удобно для региональных сайтов, где все пользователи находятся и должны видеть информацию по единому времени. В таком случае, поле становится лишним в настройках профиля.
