### ISSUE TITLE
Некорректная работа рандомизатора SEO-паттернов

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#1172]
**Используемая версия InstantCMS**: 2.13.1

**Версия PHP**:  7.1.14
**Как воспроизвести проблему**:

* Создаем в типе контента в настройказ SEO для записей шаблон вида "Это объявление {в категории {category}|- категория {category}"
* При переходе в запись получаем заголовок вида "Это объявление |- категория Вакансии}"

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

На демо-сайте также пробовал с объявлениями самые разные конструкции с разным количеством скобок - неправильный вывод в итоге всегда. Например, "Это объявление {{{в категории {category}}|{категория {category}}}" выведет "Это объявление }|}}"

**Comment by Loadir** [comment]
В фигурные скобки надо вставлять только "переменные" - системные названия полей и т. п. Всё, что не совпадет с доступными данными сотрется.

**Comment by iAndroS** [comment]
{category: в %s категории}|{position: категория %s} тоже не работает

**Comment by Loadir** [comment]
Всё верно. Работать будет только так 
{category}: в %s категории|{category}: категория %s

**Comment by Loadir** [comment]
при этом %s так и останутся %s

**Comment by iAndroS** [comment]
> Всё верно. Работать будет только так
> {category}: в %s категории|{category}: категория %s

да не будет так работать, даже согласно документации... 
` <title>Вакансии: в %s категории|Вакансии: категория %s &mdash; InstantCMS 2 демо сайт</title>`

**Comment by Loadir** [comment]
А вместо {category}, если использовать поле например {title}, тоже не работает?

**Comment by Loadir** [comment]
{title: в %s категории}|{title: категория %s}

**Comment by iAndroS** [comment]
> {title: в %s категории}|{title: категория %s}

проверять не стал, но полагаю, что выдаст тоже самое, только вместо слова Вакансия выдаст заголовок объявления )))

Думаю, нужно просто внедрять в паттерны еще квадратные скобки, чтоб движок мог вложенные конструкции обрабатывать )
А если еще внедрить условия if/else то вообще огонь будет
