### ISSUE TITLE
Админка - контент, не работает переключатель "Показывать по"

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#1174]
**Используемая версия InstantCMS**: 2.13.1
**Версия PHP**:  разные

**Как воспроизвести проблему**:

* Заходим в админку
* Пункт меню Контент
* Пытаемся переключить отображение списка записей на по любое значение, ничего не происходит

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: Недостаточно демо-данных для проверки.

У себя пробовал на 3-х сайтах, проблема актуальна на всех.

**Comment by fuzegit** [comment]
Всё работает.
Переключает количество записей на странице.
