### ISSUE TITLE
Не отображается статистика в админке

### ISSUE THREAD

**Issue by geminisf** [instantsoft/icms2#1177]
**Используемая версия InstantCMS**: 2.13.1 

**Версия PHP**:  7.2.21

**Как воспроизвести проблему**:

1. Перейти в админку.
2. Если не включена тема админки "default", включить её.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: На демо сайте нет возможности переключать темы.

Если включить новую тему для админки, то статистика начинает работать.

**Comment by fuzegit** [comment]
Всё работает

![Выделение_067](https://user-images.githubusercontent.com/13233234/76620493-53692980-653e-11ea-86c5-73085154143b.png)
![Выделение_068](https://user-images.githubusercontent.com/13233234/76620495-5401c000-653e-11ea-80e4-2faa463fd572.png)

**Comment by geminisf** [comment]
Сейчас сделал копию рабочего сайта. На локалке у меня тоже работает. А на что можно обратить внимание. Из-за чего такое может быть?

**Comment by fuzegit** [comment]
Я не могу знать, лучше попробовать спросить на форуме

**Comment by geminisf** [comment]
В любом случае - спасибо.

**Comment by geminisf** [comment]
Появились новые данные: виджет не показывает информацию только если тема админики "default" и включено объединение JS файлов. Такое поведение наблюдается при обновлении на версию 2.13.0 и далее. На локальном сайте работало потому, что не включено было объединение JS файлов.

**Comment by dmitriybarinov** [comment]
> Появились новые данные: виджет не показывает информацию только если тема админики "default" и включено объединение JS файлов. Такое поведение наблюдается при обновлении на версию 2.13.0 и далее. На локальном сайте работало потому, что не включено было объединение JS файлов.

Такая проблема бывает из за комментария внутри JS! Замените ВСЕ комментарии с // на /* */

**Comment by geminisf** [comment]
> 
> 
> > Появились новые данные: виджет не показывает информацию только если тема админики "default" и включено объединение JS файлов. Такое поведение наблюдается при обновлении на версию 2.13.0 и далее. На локальном сайте работало потому, что не включено было объединение JS файлов.
> 
> Такая проблема бывает из за комментария внутри JS! Замените ВСЕ комментарии с // на /* */
> 
> было(например)
> `var latLngList = []; //var latWngList = [];`
> стало
> `var latLngList = []; /*var latWngList = [];*/`

Это я знаю. Об этом подумал в первую очередь. Но что-то собственными силами не могу найти проблемный участок. Если вообще проблема в этом.
