### ISSUE TITLE
Предложение - Копировать поле с настройками

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#1179]
**Используемая версия InstantCMS**: 2.13.1

Предлагаю реализовать возможность копирования определенного готового поля для использования как в текущем типа контента, так и в другом типе контента.
Довольно часто возникает такая необходимость, особенно в связанных типах контента. Например, делаешь привязку типа контента отзывов ко многим типам контента. В моем случае используется стороннее поле, выводящее поле из родительского типа контента. Их реально много и приходится по несколько минут настраивать каждое, и чаще всего некоторые важные момента могут быть упущены при настройке.

Было бы очень удобно в меню действий относительно поля видеть кнопочку копирования, при нажатии на которую в модальном окне задаешь тип контента, в который копируешь данное поле и его новое системное имя. После сохранения попадешь в настройки скопированного поля, вносишь мелкие правки и радуешься результату за несколько секунд. Минимум ошибок в настройке!

Постоянно ощущаю острую необходимость в данном функционале!

**Comment by iAndroS** [comment]
Еще один из способов применения данной функции.
Если например, в списке у меня последовательность полей одна, а в записи хочу выводить эти поля иначе. Создаю поле, настраиваю его на показ в списке записей вторым, потом ДЕЛАЮ его КОПИЮ и размещаю в самой записи последним.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/32f7cd7dfe4d092d9df271a5f468bc1760f3c5c3
