### ISSUE TITLE
Предложение по фильтрам в типах контента

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#1181]
**Используемая версия InstantCMS**: 2.13.1

Это всего лишь предложение для удобства использования компонента - можно тоже самое реализовать и ручками, но зачем делать ручками то, что можно автоматизирова?

В-общем предлагаю улучшить раздел с фильтрами, сделав возможность их группировки и дальнейшего вывода на сайте в виде виджета списка подборок. К примеру, для списка автомобилей можно сделать несколько подборок-виджетов. По типу кузова, куда выводились бы страницы фильтра Седан, Универсал, Минивен и т.д., а также по типу топлива, например "Бензиновые, Дизельные, Гибридные"

**Comment by fuzegit** [comment]
https://instantcms.ru/forum/125

**Comment by iAndroS** [comment]
Про виджет понятно - можно сделать фрилансерами, а вот группировку фильтров для последующего вывода виджетов - это уже правка ядра будет. 
Как вы отнесетесь, если эти правки внесут в ядро здесь?

**Comment by fuzegit** [comment]
> а вот группировку фильтров для последующего вывода виджетов - это уже правка ядра будет.

Как вы это определили?

Вы бы прекращали каждую свою мысль по **своему** проекту писать сюда, как в блокнот.
