### ISSUE TITLE
Не работает проверка на целые числа 'options' => array('is_ceil' => true) в опциях виджетов

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#1185]
**Используемая версия InstantCMS**: 2.13.1

Проблема в заголовке. Сохраняет отрицательные значения как ни в чем не бывало. Ни ошибок, ни предупреждений. Это облом))

![fs](https://user-images.githubusercontent.com/16401582/77529851-78945b00-6ea1-11ea-8b20-c6aefa7b4888.jpg)
![fd](https://user-images.githubusercontent.com/16401582/77529859-7b8f4b80-6ea1-11ea-94c7-cb117bc0bdcf.jpg)

**Comment by fuzegit** [comment]
Не та опция. Вбейте в переводчик ceil.
'is_abs'=> true

**Comment by asnenne** [comment]
> Вообще форум такие вопросы решает
Так это да, подумал, что может ошибка.

> Не та опция. Вбейте в переводчик ceil.
![wd](https://user-images.githubusercontent.com/16401582/77538459-daa88c80-6eb0-11ea-8e60-8fd159a57452.jpg)
Судя по выделенному варианту перевода, есть предположение, что это про целые числа.

Признаю, затупил.

Спасибо.

**Comment by fuzegit** [comment]
> Судя по выделенному варианту перевода, есть предположение, что это про целые числа.

Гугл переводчик тот еще)

Вообще в вашем случае всё бы решили правила

```
'rules' => array(
    array('min', 0)
    array('max', 100)
),
```
