### ISSUE TITLE
Получение опций шаблона

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#1186]
**Используемая версия InstantCMS**: 2.13

https://github.com/instantsoft/icms2/blob/master/system/core/template.php

Предлагаю protected $options; заменить на public $options;

Я конечно не разбираюсь совсем, но не могу понять, что такого можно написать в опциях шаблона, что нужно прятать.

Зачем public? Ну вот я, например, пилю сейчас шаблон, в котором опции оформления. И к этому шаблону несколько виджетов. Элементарный вопрос: как получить в опциях виджета значения опций из шалона, например, цвет ссылок, чтобы сделать его значением по-умолчанию в опциях виджета? Ответ - никак, потому что всё защищено не понятно от какой угрозы.

Дальше. Все любят, чтобы стили были прописаны не внутри кода, а в отдельных css файлах. Хорошо, есть уже решение. Но блин эта защита не дает получить опции шаблона, чтобы сохранить всё в файл css.

Пожалуйста, уберите эту защиту!

Спасибо.

**Comment by fuzegit** [comment]
> Я конечно не разбираюсь совсем

Но предлагаю) 

> Ответ - никак

Вообще-то никаких проблем нет
https://github.com/instantsoft/icms2/blob/master/system/core/template.php#L2877

> Пожалуйста, уберите эту защиту
> ... потому что всё защищено не понятно от какой угрозы.

Вы с чего решили, что это вообще какая-то защита?)

Я знаю откуда ветер дует и чьими мыслями вы пишите) Почему он сам это не пишет, неведомо. Наверное потому, что на все вопросы будут ответы. 

Так же, если по существу, геттер и сеттер уже загруженных в объект опций, я добавлю. И это вопрос исключительно удобства.

**Comment by asnenne** [comment]
> Я знаю откуда ветер дует и чьими мыслями вы пишите

Не знаю, что Вы там придумали, но просьба эта исключительно от меня.

> Вы с чего решили, что это вообще какая-то защита?)

По Вашей рекомендации, воспользовался переводчиком
![003](https://user-images.githubusercontent.com/16401582/77825484-b0f29e00-711a-11ea-99fc-4e88d0021a56.jpg)
