### ISSUE TITLE
Статичный метод для очистки кэша

### ISSUE THREAD

**Issue by my-instantcms** [instantsoft/icms2#1190]
Здравствуйте.
Очень не хватает какого нибудь статичного метода для очистки кэша, увеличение абстрактного счетчика, очистка кэша объединенных js и css файлов.
Что бы при установке или обновлении дополнений, разработчик просто прописал в install.php код типа:
`cmsCore::ClearCache();`
Можно добавить параметры, что бы по частям очищать определенный кэш
`cmsCore::ClearCache(true. false, true);`

**Comment by fuzegit** [comment]
Не очень понятно зачем

https://github.com/instantsoft/icms2/blob/master/system/controllers/admin/actions/clear_cache.php
https://github.com/instantsoft/icms2/blob/master/system/controllers/admin/actions/settings.php#L106
https://github.com/instantsoft/icms2/blob/master/system/controllers/admin/actions/settings.php#L150

> cmsCore::ClearCache(true. false, true);

А когда надо будет еще что-то очистить, подкинем параметров?)

**Comment by my-instantcms** [comment]
> Не очень понятно зачем
Просто когда делаешь обновления какого то дополнения, получаешь куча сообщений, что не работает или криво отображается, приходиться всем писать что надо очистить кэш. Можно в тексте об обновлении написать, но 99% не читают их.
Поэтому было бы удобно, что бы сам установщик очищал кэш после установки

**Comment by fuzegit** [comment]
Добавил автоматическую очистку. Проверьте пожалуйста.

**Comment by iAndroS** [comment]
Я бы добавил сюда еще и чтоб события обновлялись сами (ну или какая-то уведомлялка хотя бы для админка выскакивала о необходимости проверить события компонентов). 
Несколько раз сталкивался с таким, даже с программистом толковым (!!!) долго (в пределах получаса-часа) искали баг в компоненте, а потом выяснилось, что события не обновлены были. 
Человеческий фактор никто не отменял...
