### ISSUE TITLE
Не сохраняется фильтр при наличии поля СПИСОК с множественным выбором, неактивным в данном фильтре

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#1196]
**Используемая версия InstantCMS**: 2.13.1

**Версия PHP**:  любая

**Как воспроизвести проблему**:

* Создаем в типе контента любое поле типа "Список"
* Выбираем у этого поля настройку "Множественный выбор"
* Создаем фильтр, выбирая нужные значения фильтрации любых полей, КРОМЕ нашего списка
* Фильтр не сохраняется. Пишет надпись "Найдены ошибки в форме", а у самого поля надпись "Указано недопустимое значение"

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

![image](https://user-images.githubusercontent.com/17408903/79631067-23293200-815f-11ea-9a83-38f0139b513c.png)

При этом с другими типами полей данную ошибку не наблюдал. Тот же мультисписок работает корректно.

**Comment by mafru** [comment]
А при создании поля вы указали предустановленные значения?

**Comment by iAndroS** [comment]
> А при создании поля вы указали предустановленные значения?
> В мультисписке тоже самое, если вы попытаетесь выбрать несуществующее значение.
> ![image](https://user-images.githubusercontent.com/6131327/79634808-9473df80-8175-11ea-88a2-661968177a52.png)
> Мне кажется так и должно быть.

Указывал, конечно... Нет, так быть не должно. Я фильтрую контент по другим типам полей в своих фильтрах.

**Comment by iAndroS** [comment]
В-общем, данная ошибка очень критичная - фильтрами пользоваться просто невозможно при наличии полей списков в типе контента. Даже если выбрать все имеющиеся значения, проблемы это не решает, ибо если поле необязательное к заполнению, то оно не заполнено, соответственно, часть записей в фильтр просто не попадут из-за сторонних полей, которые по идее в фильтрации участвовать не должны.

**Comment by fuzegit** [comment]
На версии с гита проблема есть?

**Comment by iAndroS** [comment]
> На версии с гита проблема есть?

Потестирую и отпишусь. Просто виже issue открытый, думал, что не учли этот нюанс.

**Comment by iAndroS** [comment]
> На версии с гита проблема есть?

Да, актуально. Протестировал на копии своего типа контента и на демо-контенте объявлений.

![image](https://user-images.githubusercontent.com/17408903/82560172-8285c200-9ba3-11ea-8c69-921a4ba0a5cf.png)

Причем в объявлениях не подсвечивает проблемное поле. Возможно, потому что я выбирал для фильтрации категорию автомобилей, а там не поля, а свойства. Это уже вторая трабла получается с фильтрами.

А вот на примере типа контента статей

![image](https://user-images.githubusercontent.com/17408903/82560338-d2fd1f80-9ba3-11ea-8323-5014d7d6d9c6.png)

**Comment by mafru** [comment]
Действительно, ошибка есть и проявляется только в случае, если для поля список в типе контента установлен переключатель "Множественный выбор в фильтре".
При отключенном переключателе фильтр создается.

**Comment by iAndroS** [comment]
Демо-сайт обновлен? Потыкался сейчас - уже все работает, хотя релиз пишется 2.13.1

**Comment by fuzegit** [comment]
Прошу проверить на текущей версии.
