### ISSUE TITLE
SEO-паттерны для категорий

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#1197]
**Используемая версия InstantCMS**: 2.13.1

**Версия PHP**:  не важно

**Как воспроизвести проблему**:

* Создаем тип контента
* Добавляем в нем списком кучу многоуровневых категорий (пусть будет список материков со странами на них)
* Переходим в настройки типа контента с желанием автоматизировать метатеги для категорий и видим, что возможности задать название категории нет (((
* Также было бы замечательно вывести в доступные выражения минимальные и максимальные значения числовых полей. Пример применения ниже.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

По умолчанию движок подставляет просто название категории в тайтл, а хотелось бы генерировать более расширенные мета-теги. На примере демо-сайта в объявлениях можно было бы генерить "Купить недвижимость (категория) по ценам от XXX (минимальное значение всех записей из поля цены) руб!".

Вообще кажется, что текущие доступные выражения в настройках SEO для категорий адекватного применения не найдут в принципе
![image](https://user-images.githubusercontent.com/17408903/79681869-7c0fcd80-8226-11ea-864b-fe1b456fac51.png)

Прописывать вручную мета-теги для сотен категорий - та еще боль...

**Comment by fuzegit** [comment]
> что возможности задать название категории нет

Уверены?
![U9GnmPbc_3](https://user-images.githubusercontent.com/13233234/79682133-977bd800-8228-11ea-8961-5d7648bfe55d.png)

Может быть стоит сначала хотя бы на форуме спросить, а не считать всё ошибкой по умолчанию.

**Comment by iAndroS** [comment]
> Уверены?

Ой-йо... Глаз замылился, в заблуждение ввели подписи к следующим паттернам, что относятся к типу контента! С этим вопросом упс, а по второй части что скажете?
По поводу min и max от числовых полей...
