### ISSUE TITLE
Изменить хук "content_list_filter"

### ISSUE THREAD

**Issue by geminisf** [instantsoft/icms2#1199]
Доброго всем дня
Предлагаю в файле frontend.php контроллера "content" в хуках "content_list_filter" и "content_{$ctype['name']}_list_filter" передавать помимо "$ctype" и "$this->model" еще и переменную "$category_id".
Это решило бы проблему высказанную [тут](https://github.com/instantsoft/icms2/issues/1028)

**Comment by Risgit** [comment]
**geminisf**
А откуда при выборке контента можно взять $category_id ?
Просто используйте хуки content_before_category и content_{$ctype['name']}_before_category

**Comment by geminisf** [comment]
**Risgit**
В файле frontend.php контроллера "content" есть функция "renderItemsList".
