### ISSUE TITLE
Добавить функцию выбора выводить или нет информацию о удаленном комментарии

### ISSUE THREAD

**Issue by uzunhair** [instantsoft/icms2#120]
После удаления сообщения, остается информационный блок, о том что комментарий был удален. Предлагаю либо добавить в админку кнопку отключения вывода информации об удаленных комментариях, или же при удалении самого комментария, дать возможность  выбирать показывать ли после удаления информацию об удалении или же нет.

На одном из сайтов клиента, несколько человек заспамили пару статей. Теперь после статьи 10-15 уведомлений о том что сообщение удалено.
![2016-02-11 23-19-45](https://cloud.githubusercontent.com/assets/3851365/12989318/05e1473a-d116-11e5-9c8a-00cd10d9c790.png)

**Comment by Val-Git** [comment]
@uzunhair, если не ошибаюсь через админку можно полностью удалить такие комментарии как приведенные у вас на картинке.
Но при добавлении какого либо функционала, не стоит забывать зачем вообще сделано так чтобы удаленные комментарии выводили сообщение о своем удалении)) А именно при просмотре дерева комментариев и ответов на них бывают случаи когда пользователь удалит свой комментарий, а ответы на него остаются (наглядный пример сайт хабра).

**Comment by iAndroS** [comment]
@Val-Git в таком случае, наверное, нужно прописать в скрипте проверку, есть ли вложенные каменты к удаляемому комментарию, если их нет, то удалять недоветку...

**Comment by pin-git** [comment]
полу-решение, лучше вообще не удалять

**Comment by fuzegit** [comment]
![права доступа](http://storage1.static.itmages.com/i/16/0818/h_1471544649_5690008_fd25eb21eb.png)

Разрешите правами доступа удалять комментарии полностью нужной вам группе. При этом если комментарий имеет потомков, то он не удалится и вся ветка ниже останется. Если нет потомков, то комментарий удалится полностью.

Если нужно удалять ветками (родителя и все вложенные в него), то это делается из админке, но с версии InstantCMS 2.5.2.

![права доступа](http://pix.toile-libre.org/upload/original/1471544986.png)
