### ISSUE TITLE
При запрете добавления фотоальбомов исчезают права для добавления фото.

### ISSUE THREAD

**Issue by Risgit** [instantsoft/icms2#1200]
**Используемая версия InstantCMS**: 2.13.1

**Версия PHP**: любая

**Как воспроизвести проблему**: Отобрать у группы пользователей права на добавление фотоальбомов и попробовать от юзера из этой группы добавить фото в фотоальбом. Хоть в чужой, хоть в свой, созданный до отбирания прав на создание фотоальбомов.

* первый шаг Отбираем у группы "Пользователи" права на создание записей в типе контента "Фотоальбомы".
* второй шаг  Пытаемся добавить фото в фотоальбом от этого юзера.
* третий шаг.... Недоумеваем...

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
Опция создания фотоальбомов равносильна опции добавления фото. Единственное что можно исправить, так это добавление в свои, ранее созданные альбомы.
Либо вводить отдельно правило доступа "добавлять фото в общие альбомы".

**Comment by Risgit** [comment]
Да! "добавлять фото в общие альбомы"!

**Comment by Risgit** [comment]
Спасибо!
