### ISSUE TITLE
Предложение - Добавление своих TITLE к пунктам меню

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#1207]
**Используемая версия InstantCMS**: 2.13.1

Не хватает движку возможности задавать собственные title к пунктам меню. По опыту работы с вордпресс скажу, что фишка хорошая для SEO.

**Comment by fuzegit** [comment]
Что такое alt теги?

**Comment by iAndroS** [comment]
> Что такое alt теги?

Перепутал, извиняюсь. Title, конечно же )))

**Comment by fuzegit** [comment]
> Перепутал, извиняюсь. Title, конечно же )))

На это всё SEO и стоит)

Тайтлы у пунктов меню есть с первого релиза.

**Comment by noszone** [comment]
Fuze, очень нужная вещь для SEO. Прошу посмотрите пожалуйста тему:
https://instantcms.ru/forum/thread33623-1.htm

Например, у меня в главном меню есть пункт "Чат", у него title тоже "Чат". А я хочу сделать ему другой title. Т.к. это влияет на seo. Пример:

<a title='Казахстан чат, общение, знакомства. Чат онлайн Казахстан. Комнаты по городам Казахстана - Алматы, Астана, Шымкент, Тараз и другие города.' href='https://host/chat' target='_blank'>Зайти в чат</a>

На своём опыте знаю, что существенно поднимает позиции сайта в поисковиках.
