### ISSUE TITLE
В InstantMaps 2 при щелчке по тегу на карте выводится не то, что должно.

### ISSUE THREAD

**Issue by sercherton** [instantsoft/icms2#121]
Есть один момент в ИнстМапс2 который смущает.
Сделайте пожалуйста, чтобы при щелчке на теге (Объекты на карте)
высвечивались на карте объекты именно с этим тегом.
А то как-то нелогично, при выборе тега.. показываются ВООБЩЕ ВСЕ объекты.

Огромная просьба сделать это в официальном обновлении.
И где это обновление можно скачать?
Или скажите где это можно сделать самому? В каком файле?

Для меня это очень критично.
Огромная просьба сделать это.

Большое спасибо вам!

**Comment by fuzegit** [comment]
sercherton, вы не ошиблись адресом?
