### ISSUE TITLE
Права на счетчик просмотров

### ISSUE THREAD

**Issue by goldman-sax** [instantsoft/icms2#1210]
Сделайте, пожалуйста, разделение прав на просмотр статистики по просмотру страниц. Например, чтобы администратор видел сколько раз просматривалась страница, а гость - нет. А то с одной стороны нужна статистика, с другой - нечего её показывать конкурентам.

**Comment by elipss** [comment]
Через виджет html и права доступа

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/f6983f08c339b1eaf2d49f26d959e7e5f8df8309
