### ISSUE TITLE
Отправка пинга на неопубликованные материалы

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#1211]
**Используемая версия InstantCMS**: 2.13.1
**Версия PHP**:  7.1.14

**Как воспроизвести проблему**:

* Ставим в настройках типа контента "Включить пинг сервисов обновления"
* Создаем новую запись с настройкой публикации "НЕТ"
* При сохранении записи получаем уведомление об успешно отправленном пинге.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
https://addons.instantcms.ru/addons/se-ping.html
