### ISSUE TITLE
Не хватает события для формы добавления редактирования поля в типе контента

### ISSUE THREAD

**Issue by softsolution** [instantsoft/icms2#1212]
Добавьте, пожалуйста, событие для обрабоки поля при сохранении поля в типе контента.
Перед выводом есть событие, а перед сохранением нет.

не хватает события после сохранения поля в админке
файл: 
system\controllers\admin\actions\ctypes_fields_edit.php
$_field = cmsEventsManager::hook("ctype_field_before_update", $_field);

и 
system\controllers\admin\actions\ctypes_fields_add.php
$field = cmsEventsManager::hook("ctype_field_before_update", $field);

Спасибо.

**Comment by fuzegit** [comment]
> не хватает события после сохранения поля в админке

Есть же события после сохранения:
https://github.com/instantsoft/icms2/blob/master/system/controllers/content/model.php#L515
https://github.com/instantsoft/icms2/blob/master/system/controllers/content/model.php#L837

Это решит ваш вопрос?

**Comment by fuzegit** [comment]
@softsolution очень хотелось бы прояснить ваш issue.
