### ISSUE TITLE
Републикация записи в ленте активности при редактировании записи

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#1213]
**Используемая версия InstantCMS**: 2.13.1

**Как воспроизвести проблему**:

* Редактируем старую запись многолетней давности на сайте
* Переходим в ленту активности
* Видим нашу запись как только что опубликованную

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

Багом данное недоразумение, конечно, не назвать, а вот серьезнной недоработкой вполне можно как минимум по двум причинам:

1. Введение пользователей сайта в заблуждение о публикации новой записи. Как вариант тогда уж сделать "{user} **обновил** запись {title}" текущей "{user} **добавляет** запись {title}"
2. В случае UGC-сайта (а движок позиционируется именно таковым) такие обновления ленты активности могут использоваться в качестве бесплатного АПа недобросовестными пользователями, раскусившими данную недоработку сайта. Такой своеобразный спам, получается...

**Comment by fuzegit** [comment]
Вы бы обсуждали сначала свои проблемы на форуме.

**Comment by iAndroS** [comment]
Как не подтерждается, когда на демо-сайте в том числе именно такая же проблема? )
