### ISSUE TITLE
не верный метод обработки фильтра store вместо storeFilter

### ISSUE THREAD

**Issue by softsolution** [instantsoft/icms2#1214]
При работе с фильтром по идее должен вызываться метод 
storeFilter класса cmsFormField.

Но в system\controllers\content\frontend.php:
в методе renderItemsList стр. 256 вызывается
$value = $field['handler']->store($value, false);
стр. 289
$value = $field['handler']->store($value, false);

Во всех других местах вызывается правильно:
system\controllers\groups\frontend.php
$value = $field['handler']->storeFilter($value);
и т.д.

У меня, например, в методе store в полях используются дополнительные запросы к базе, которые не нужно вызывать при фильтрации.

**Comment by fuzegit** [comment]
У вас какая версия InstantCMS?

https://github.com/instantsoft/icms2/blob/master/system/controllers/content/frontend.php#L256

**Comment by softsolution** [comment]
Да, действительно. видимо кто-то поменял, отбой
