### ISSUE TITLE
Редактирование новости только после её одобрения

### ISSUE THREAD

**Issue by goldman-sax** [instantsoft/icms2#1219]
Присылают новость на модерацию.
Если я её отредактирую от лица админа, поправлю, то как вариант завершения модерации мне даётся только "Отменить". Нажимаешь, и вся правка сбрасывается.
Возможен только один вариант модерации - одобрить новость как есть, а уж потом лезть и править её.
Это неудобно. Лучше сначала поправить новость и на этой же странице чтобы была кнопка "Опубликовать".

**Comment by fuzegit** [comment]
Версия CMS какая?
При создании Issues шаблон текста не просто так :)

**Comment by goldman-sax** [comment]
Версия 2.13.1
