### ISSUE TITLE
Предложение - показывать количество введенных символов в системном поле Title

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#1224]
**Используемая версия InstantCMS**: 2.13.1

**Как воспроизвести проблему**:

* Пишем новый пост, любой другой материал, с длинным заголовком
* Нажимаем сохранить запись
* Получаем уведомление, что поле TITLE ограничено 100 символами.

При этом счетчика количества вводимых символов возле поля не отображается и настроек у поля соответствующих нет, как если бы это было нами созданное строковое поле.
Это маленькое, но очень важное улучшение юзабилити движка.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

**Comment by WebXRs** [comment]
Нужно увеличить количество символом как минимум до 200
