### ISSUE TITLE
Ошибка генерации URL записи при включенном только {title} в нем (Если TITLE имеет числовое значение)

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#1225]
**Используемая версия InstantCMS**: 2.13.1

**Как воспроизвести проблему**:

* В типе контента указываем генерация url записи не id-title, как по умолчанию, а только title 
![image](https://user-images.githubusercontent.com/17408903/88528131-ccba7200-d030-11ea-8524-57cbea00eafd.png)

* Создаем запись с заголовком 911
* URL полученной записи приобрел странный вид https://demo.instantcms.ru/board/911july.html вместо ожидаемого https://demo.instantcms.ru/board/911.html
То есть, к концу дописывает текущий месяц... 

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

Если мне не изменяет память - это очень старая бага. И как показала практика, довольна важная для некоторых проектов (например, где в качестве заголовков указываются номера накладных, артикулы и тд и тп)

**Comment by fuzegit** [comment]
Это не баг. Урл, содержащий только цифры, без других символов, запрещён.

**Comment by progerwtf** [comment]
А почему?

**Comment by iAndroS** [comment]
> Это не баг. Урл, содержащий только цифры, без других символов, запрещён.

Какое-то логическое объяснение этому есть?

**Comment by ToxicSisters** [comment]
Поддерживаю. Тоже столкнулась с такой проблемой. Видела несколько раз на форуме народ тоже недоумевал по этому поводу. Если это фича, то лучше бы она была опциональной. Ведь если ул состоит только из цифр, то это явно не просто так, иначе люди бы дописывали месяц сами.
