### ISSUE TITLE
Предложение: Виджет "Список контента" - Список записей из фильтра

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#1227]
**Используемая версия InstantCMS**: 2.13.1

Предлагаю реализовать в виджете Список контента вывод записей из определенного фильтра определенного типа контента, возможно с сортировкой по рейтингу, дате или случайный вывод... 
Очень удобный инструмент для перелинковки получится

**Comment by fuzegit** [comment]
#1201

вы перед очередным добавлением своих хотелок проверяли, не добавляли ли вы раньше.
