### ISSUE TITLE
Админка: при добавлении пользователя возможность загрузить аватр

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#123]
Было бы отлично иметь функцию заполнения профиля сразу из админки, а не только указывать почту, логин и пароль.

**Comment by fuzegit** [comment]
Зачем? Если весь необходимый функционал есть на самом сайте.

**Comment by vlad7090** [comment]
для удобства управления профилем, т.к основное это мыло, ник, пароль и аватарка.
а так приходится создавать в админке, потом идти на сайт, чтобы отредактировать профиль - добавить фотку, что не очень удобно, т.к занимает больше времени.
В идеале было бы, возможность добавлять пользователей списком, как категории типа объеекта. что позволит добавить одним кликом сразу сотни пользователей.

**Comment by rdimrs** [comment]
Я считаю тоже очень нужной функцией. Многие пользователи не добавляют картинку, почему бы им не предложить добавить при регистрации.
