### ISSUE TITLE
Лимит на размещение записей для одного пользователя 

### ISSUE THREAD

**Issue by GoodMade** [instantsoft/icms2#1230]
Было бы неплохо иметь возможность задавать лимит на размещение записей для одного пользователя.
Например: 1:1 - один раз в сутки

**Comment by iAndroS** [comment]
> Было бы неплохо иметь возможность задавать лимит на размещение записей для одного пользователя.
> Например: 1:1 - один раз в сутки

![image](https://user-images.githubusercontent.com/17408903/90590908-4f8bb280-e214-11ea-9c35-738335fd9c2d.png)

Это разве не то, о чем вы просите? В настройках доступа в типе контента для каждой из групп пользователя есть такая настройка.

**Comment by fuzegit** [comment]
@GoodMade прокомментируйте пожалуйста ответ iAndroS. Это не то, что нужно?

**Comment by GoodMade** [comment]
> @GoodMade прокомментируйте пожалуйста ответ iAndroS. Это не то, что нужно?
Да, то что нужно. Упустил. Спасибо.
