### ISSUE TITLE
Предложение - реализовать опцию "Тип заголовка" в настройках виджета

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#1233]
Предлагаю реализовать опцию "Тип заголовка" или "Теги заголовка" в настройках виджетов на сайте. 

Варианты:

- H2
- H3
- div

Немного поясню. Один и тот же виджет на разных страницах сайта несет разную информационную функцию. Иногда виджет не имеет конкретного значения к текущей странице, в другом случае этот виджет являются частью тела страницы.

Например, есть структура страницы:

**H1** - Название
**H2** - Описание
**H3** - Фото и видео
**H3** - Преимущества и недостатки
**H2** - Выводы

И есть виджеты "Список контента" (отзывы, похожие записи и т.д.), заголовки которых логично было бы обернуть в H2 на страницах записей текущего типа контента, дабы соблюсти структуру страницы и расширить ее семантику. А есть еще виджет фильтра или другие виджеты, к которым не нужно применять тег <H> и логичнее было бы в див его обернуть.
При этом эти же самые виджеты на страницах списков или в дочерних типах контента уже не нуждаются в выделении тегом <H>.

**Comment by fuzegit** [comment]
Делаете свой wraper (шаблон обёртки виджета) с нужными тегами и проблемы нет.
