### ISSUE TITLE
Мню категорий для типов контента

### ISSUE THREAD

**Issue by WebXRs** [instantsoft/icms2#1237]
Хорошо было бы иметь возможность создавать меню из дерева категорий для одного типа контента. При создании такого меню можно было бы указать просто тип контента и корневые пункты меню стали бы категории после корневой с выпадающим списком на подкатегории. 
Иначе очень сложно строить сайт, когда он состоит из одного типа контента и меню каждый раз приходится менять вручную.

**Comment by fuzegit** [comment]
https://docs.instantcms.ru/manual/menu/special

**Comment by WebXRs** [comment]
В доках этого нет и в движке не работает. 
Хорошо, пишу категорию, созданную в коробке {content:nedvizhimost} и никак это не работает.

**Comment by fuzegit** [comment]
> В доках этого нет и в движке не работает.

Есть. 
{content:name} | Категории контента

> и никак это не работает.

Работает. Демо сайт тому подтверждение.

**Comment by WebXRs** [comment]
На демо этого нет. Вы не понимаете о чем я говорю. 
Не тип контента на один пункт меню, а весь тип контента на все меню. 
На демо это работало бы как отдельное меню к примеру статей с пунктами меню: "Астрономия Геология, Литература, Маркетинг " и в них уже выпадающее меню. 
Как я раньше говорил, если строит сайт на одном типе контента, то это было бы удобнее, чем просто виджет категорий.
