### ISSUE TITLE
Неактивные записи

### ISSUE THREAD

**Issue by WebXRs** [instantsoft/icms2#1239]
Можно было бы сделать еще один вид активности записи. Запись не активная и не отображается в списке контента, но отображается в профиле автора. Очень применимо в некоторых типов сайтов и такое лучше делать из коробки.

**Comment by fuzegit** [comment]
Вы точно использовали движок?
Запись, скрытая с публикации, отображается в профиле автора под авторизацией автора.
В остальном подобное регулируется созданием полей и фильтрами в наборах.

**Comment by WebXRs** [comment]
Может вы не поняли, что иногда надо всем другим пользователям видеть неактивные записи. С приватными папками это у меня не вышло, может  не так сделал.
 Я на форуме про это спрашивал. Мне сказали надо дорабатывать. Хорошо, я могу заказать доработку, но такое на мой взгляд   логичнее по-умолчанию предусмотреть.

**Comment by fuzegit** [comment]
> Может вы не поняли, что иногда надо всем другим пользователям видеть неактивные записи.

Да, не понял.

> я могу заказать доработку, но такое на мой взгляд логичнее по-умолчанию предусмотреть.

Это частный случай. Но если вы заказываете доработку и желаете потом поделиться готовым решением, сообщество будет только в благодарности.

> Жаль, что вы все отфутболиваете не разбираясь.

Я не отфутболиваю. Мне не нравится, когда личные потребности в своих проектах пытаются решать за счёт внесения частных доработок в CMS. В CMS вносятся изменения и доработки, нужные большинству. Ключевые и фундаментальные изменения. А для кастомизации есть каталог дополнений, мозговые штурмы на форуме и свои доработки. 
Например, если архитектура CMS в чем то не даёт сделать то, что требуется, то мы корректируем её.

Также как и с вашим предложением группы полей как вкладки: во-первых есть такое дополнение, во-вторых, это вообще прерогатива шаблона и наконец табы полей решаются подключением любого скрипта табов. Вы считаете, что это нужно. Я считаю обратное. Что делать? Правильно, хотите или нет, но конечный выбор за мной. И обижаться на это глупо. Но за предложения спасибо.

**Comment by WebXRs** [comment]
Не считаю это только личной потребность, иначе бы не предлагал. Это дополнительная опция гибкости движка. Если я закажу доработку, то выложить без разрешения автора вряд ли смогу. 
По вкладкам возможно проще просто самому что-то с интерфейсом делать, но это тоже прибавляет гибкости и универсальности движку, а не только моим личным потребностям. Пишу об этом, потому что такая потребность появлялась не раз. 

Я у движка вижу хороший потенциал в его гибкости, это сильная его сторона. Поэтому мои предложения связаны с тем чтобы сделать его еще более универсальным для всех, а не только для меня. Но даже дополнения делают без серьезной проработки алгоритма реального использования. Поэтому тут не вопрос обиды, а вопрос пригодности. 

Хорошо, будет у меня что-то поделиться, поделюсь. Но пока мне надо найти решения задач либо на этом движке, либо другой движок.
