### ISSUE TITLE
Увеличить число символов в Title

### ISSUE THREAD

**Issue by WebXRs** [instantsoft/icms2#1240]
Для использования на сайтах с большими заголовками всегда упираешься в лимит символов. Например при создании сайта с законами название закона всегда обрезается. 
Хотелось бы увеличить лимит из коробки хотя бы до 200 символов.

**Comment by fuzegit** [comment]
Максимальная длина 255 сейчас по умолчанию. Это значение регулируется в настройках поля.

**Comment by WebXRs** [comment]
В версии с Гит?

**Comment by fuzegit** [comment]
> В версии с Гит?

В стабильной тоже.

**Comment by WebXRs** [comment]
У меня на instantcms_20200202_v2.13.1 стоит 100 символов на заголовок. 
Хорошо, скачаю заново, посмотрю. Если что, отпишу.
