### ISSUE TITLE
url ФИЛЬТРОВ по стране/региону/городу

### ISSUE THREAD

**Issue by Eva2577** [instantsoft/icms2#1242]
**Используемая версия InstantCMS**: 2.13.1

**Как воспроизвести проблему**:

* создать фильтр в Панель управления ⇒ Типы контента ⇒ Выбрать тип ⇒ Фильтры: создать фильтр с нужны url по стране или страна/регион или страна/регион/город
* перейти в нужны тип контента на сайте
* выбрать в фильтре страна или страна/регион или страна/регион/город нажать фильтровать (в зависимости от того на что настроен фильтр в пункте 1)
* нажать фильтровать и увидеть, что переключение на страницу с фильтром из пункта 1 не происходит, url имеет вид /board?country=3159&region=1998532
то есть не применяется вот это https://docs.instantcms.ru/manual/ctypes/filters

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

**Comment by Eva2577** [comment]
демо ссылка https://demo.instantcms.ru/board?country=3159&region=1998532

**Comment by Eva2577** [comment]
Решение от Fuze:

Добавить строку
$filter['filters'] = [];
https://instantcms.ru/upload/forum/77b9002942a7ebd7cc39d18ba3b1f937.jpg

Добавить строку
$field->is_denormalization = false;
https://instantcms.ru/upload/forum/e838422686c90bf1887c6b71baad6215.jpg

Пересохранить уже созданные фильтры.

Подробнее: https://instantcms.ru/forum/thread33723-1.html#new

**Comment by fuzegit** [comment]
Пожалуйста, самостоятельно закрывайте тикеты только если проблема не подтвердилась и/или тикет отклонён.

**Comment by Eva2577** [comment]
не знала, первый раз, а как открыть?

**Comment by fuzegit** [comment]
> не знала, первый раз, а как открыть?

Уже ничего не нужно делать. Я уже открыл и закрыл коммитом с изменениями. Спасибо за фидбэк.
