### ISSUE TITLE
Некоторые ошибки при создании категорий

### ISSUE THREAD

**Issue by goldman-sax** [instantsoft/icms2#1245]
Когда в типе контента очень много категорий (хотя может это и не связано) всплывают некоторые ошибки. На дефолте не проверял, так как не уверен, что смогу создать на нем очень много категорий. Итак:
1. При создании однобуквенных категорий некоторые категории имеют один адрес. Например, категории Е, Э, E (англ.). И поправить урл у них нет никакой возможности.
2. Иногда (у меня срабатывает где-то в 20-ти процентах), при создании новой подкатегории название у нее задается нужное, а вот урл присваивается от другой подкатегории. Исправляет ошибку пересохранение списка "порядок категорий".
3. При создании новой подкатегории, она создается не с учетом алфавита (если категории выставлены по алфавиту) или в конце списка подкатегорий, а появляется где-то в середине без всякой системы. Это неудобно.
Первые два пункта легко решить, если дать возможность редактировать адреса категорий из админки.

**Comment by goldman-sax** [comment]
4. При создании категории, скрипт не проверяет есть ли уже такая категория, поэтому может создаться две и более категорий с одним урлом и названием.

**Comment by fuzegit** [comment]
> если дать возможность редактировать адреса категорий из админки

Этот функционал есть. Отключите опцию в настройках типа контента опцию "Генерировать URL из названия категории".

> При создании новой подкатегории, она создается не с учетом алфавита

Они создаются согласно порядку дерева.

> При создании категории, скрипт не проверяет есть ли уже такая категория, поэтому может создаться две и более категорий с одним урлом и названием.

Нет, проверка есть. Как мне повторить эту проблему?

Полагаю, вся проблема в том, что у вас рушится дерево категорий по какой-то причине.

**Comment by fuzegit** [comment]
Забавный артефакт. Исправим.
