### ISSUE TITLE
URL фильтров, учесть ранее примененные фильтры

### ISSUE THREAD

**Issue by ghost** [instantsoft/icms2#1246]
**Используемая версия InstantCMS**: 2.13.1

**Как воспроизвести проблему**:

* создаем три поля местоположение: страна, область, город (в группировке), показ в фильтре
* создаем три фильтра / Типы контента - название -  Фильтры, первый фильтр по стране Россия, второй по стране Россия и области Московская, третий по стране Россия - область Московская - город Москва
* на странице списка фильтруем записи по стране Россия, применяется первый фильтр - все ок
* на этой же странице применяем далее фильтр и уже выбираем область Московскую - тут не происходит перехода на второй фильтр страна+область, (сам фильтр работает и записи нужные вам покажет).
* третий фильтр соответственно работать не будет как и второй

П.С. если на главной странице списка применяем фильтрацию по второму или третьему фильтру, они работают и переносят нас на нужные созданные страницы фильтров с нужным url и описанием.
П.С. если на главной странице списка применяем фильтрацию по второму фильтру, то есть страна+область, нас переносит на "адрес-сайта/url-страна+область", тут мы может переключать область и применяются фильтры - все ок

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: НЕТ, потому что у там еще не сделано это https://github.com/instantsoft/icms2/issues/1242 поэтому не могу там протестировать

**Comment by Eva2577** [comment]
дополню примером по пункту 4 (на этой же странице применяем далее фильтр и уже выбираем область Московскую - тут не происходит перехода на второй фильтр страна+область)
url имеет следующий вид: адрес-сайта/url-фильтра-по-стране-?oblast=15789411
