### ISSUE TITLE
Отображение в разделе контент полей местоположения (показаны id вместо названия)

### ISSUE THREAD

**Issue by Eva2577** [instantsoft/icms2#1248]
**Используемая версия InstantCMS**: 2.13.1

**Как воспроизвести проблему**:

* создать поле местоположение (к примеру страна)
* создать запись с выбором в поле страны
* перейти в админку в раздел контент и увидеть в столбце страна цифры id страны, вместо названия страны, пример с демо сайта на скриншоте.
![адрес](https://user-images.githubusercontent.com/71855594/95744661-5545c780-0c9c-11eb-83f6-11147b060563.png)

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

**Comment by Eva2577** [comment]
будьте добры, напишите решение, в каком файле что изменить, пользуюсь этими полями, чтобы не ждать выхода обновления, а уже хочется видеть в админке не циферки в нужных полях

**Comment by fuzegit** [comment]
@Eva2577 вы не одна. Как только будет решение, в этом тикете будет ссылка и он закроется. Не стоит быть излишне навязчиваой.

**Comment by Eva2577** [comment]
не знала что будет ссылка, теперь вижу на примере закрытых, спасибо
