### ISSUE TITLE
Добавить быструю регистрацию

### ISSUE THREAD

**Issue by rdimrs** [instantsoft/icms2#125]
Для начала регистрации нужен только email. После ввода почты приходит письмо с ссылкой (опционально с паролем), при переходе из письма нужно заполнить остальные регистрационные данные. Такой подход увеличит количество регистраций, и если даже пользователь не продолжит регистрацию, то можно делать рассылку с просьбой завершить регистрацию.

**Comment by fuzegit** [comment]
Так и так спрашивает только email, никнейм и пароль, если в минимуме.

**Comment by rdimrs** [comment]
Во-первых, многие бояться регится через соцсети, бояться что украдут их пароли, пока нет такой культуры у обычных пользователей.
Во-вторых, первоначальная регистрация только с почтой, это как бы ловушка для регистрации, люди ленивые, регится не хотят, а тут всего лишь почта нужна.
Такой подход более современен, и для icms2 был бы несомненным плюсом, потому что такого почти нигде нет, только встречал на паре буржуйских сайтов.

**Comment by facepoint** [comment]
Было бы удобно поставить кнопки атворзиации и входа через соцсети к форме комментариев, что мотивировало бы авторизоваться сразу перед написанием коммента.
