### ISSUE TITLE
Админка - контент - фильтр контента по полям

### ISSUE THREAD

**Issue by Eva2577** [instantsoft/icms2#1251]
**Используемая версия InstantCMS**: 2.13.1

в продолжении этих тем https://github.com/instantsoft/icms2/issues/1248 и https://github.com/instantsoft/icms2/issues/1249

**Как воспроизвести проблему**:

* заходим админка - контент
* жмем кнопку фильтр
* в нужных полях приходится вводить id или порядковый номер предустановленного значения (поля местоположения и поле список с предустановленными значениями). Например ввожу в поле страна не Россия, а 123456 (id  поля России в гео).

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: не пробовала, там не стоит исправления по полям ранее

**Comment by fuzegit** [comment]
Да, так и есть. Работает как и было задумано.
