### ISSUE TITLE
Админка - контент - все отображаемые поля не влезают в экран

### ISSUE THREAD

**Issue by Eva2577** [instantsoft/icms2#1252]
**Используемая версия InstantCMS**: 2.13.1

**Как воспроизвести проблему**:

* открываем админка - контент
* выбираем какие нужно поля отобразить
* если нужных полей много. то таблица выходит за пределы экрана, обрезается, нужна к примеру горизонтальная полоса прокрутки или ваш вариант.
В моем случае сейчас отображается 13 полей начиная с id заканчивая действием, к сожалению все не вмещаются в экран, если размер ставить 90, помещаются. это не перебор, поля нужны, чтобы визуально смотреть их заполненность и значение сразу из админки. На примерев демо 16 полей.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА , пример с демо 
![админконтент](https://user-images.githubusercontent.com/71855594/96095232-08016a00-0ed7-11eb-859c-e1616187ad0c.png)

Этот текст можно стереть, если вы сообщаете не о баге, а пишите пожелание/предложение.

**Comment by fuzegit** [comment]
Проблема в чём?
Это ожидаемо, что если полей много, появляется горизонтальная прокрутка.

**Comment by Eva2577** [comment]
вот именно. что прокрутка горизонтальная НЕ появляется, столбцы не влезающие обрезаются

**Comment by Eva2577** [comment]
> Проблема в чём?



> Проблема в чём?
> Это ожидаемо, что если полей много, появляется горизонтальная прокрутка.

вот именно. что прокрутка горизонтальная НЕ появляется, столбцы не влезающие обрезаются

**Comment by fuzegit** [comment]
@Eva2577 не нужно удалять сообщения, чтобы спустя время написать его заново, с целью обратить внимание. Я всё читаю. Излишняя навязчивость только всё портит. Спасибо.
Горизонтальная прокрутка действительно не появляться, исправим.

**Comment by Eva2577** [comment]
я вот совсем не собираюсь навязываться) вы неверно трактуете мои редактирования сообщений, принимая мое не знание этого сайта и уведомлений при закрытых тикетах, не знала что вы видите сообщения, даже если тикет закрыт, и пришло ли вам уведомление об ответе или нет, поэтому продублировала сообщение с цитатой, как ответ.
я вот совсем не собиралась навязываться, тем более с таким некритичным недочетом как полоска прокрутки в админке
