### ISSUE TITLE
Сделать стену в отдельной вкладке.

### ISSUE THREAD

**Issue by lakomet** [instantsoft/icms2#1256]
Предлагаю разделить данные профиля и стену профиля, на разные вкладки. То же сделать и для групп.
Во всех соцсетях, а так же в CMS для соцсетей, при переходе в профиль пользователя или в группу, показывают стену(кое где ленту), а данные профиля и данные "О группе", вынесены в отдельную вкладку.
На мой взляд, это будет выглядеть эстетичней, проще и привычней. И второе, это будет побуждать пользователей заполнять стену, по тому как когда я захожу в свой профиль и вижу пустоту, на подсознательном уровне срабатывает - нужно "заполнить" пустоту, опубликовать что нибудь ))
Если не убедил )) , то может создать опрос на форуме?

**Comment by fuzegit** [comment]
Не убедили

**Comment by ToxicSisters** [comment]
Или можно освободить все это полностью от шаблона и сделать все полями. А полям сделать настройку как в виджетах или связях, чтобы можно было собирать их в табы. Тогда все смогут собирать профиль и группы так как им нужно.

**Comment by vikontkg** [comment]
Если уж, говорить о движке, как движек для соцсетей, то лучше разделить информацию. Стены могут быть с большим количеством информации и лишняя инфа будет не только скрадывать пространство станицы, но и мешать контенту. А поэтому поддерживаю lakomet и предлагаю реализовать вариант WebMan:
1. В управлении вкладками добавить вкладку "Профиль" (можно неотключаемую). Чтобы на первое место можно было поставить ту вкладку, которая нужна по проекту, а не только данные профиля. И в итоге получить полноценное управление вкладками, а не с искусственными ограничениями.
2. Опция для "Стены": вкладкой или лентой под "Профилем".

**Comment by fuzegit** [comment]
В ближайшей перспективе однозначно нет. Слишком много переделывать.
