### ISSUE TITLE
Множественный выбор в свойстве типа контента СПИСОК

### ISSUE THREAD

**Issue by facepoint** [instantsoft/icms2#126]
Очень не хватает данной опции, чтобы можно было выбирать несколько значений в свойстве типа контента СПИСОК, при том, что в самом фильтре можно выбирать несколько значений.

Без данной опции сложно организовать хороший каталог, если товары в каталоге имеют множество значений по одному свойству.

**Comment by vlad7090** [comment]
согласен! катастрофа просто без множественого выбора в списках. а еще катастрофа без зависимых свойств друг от друга, или я не нашел?

**Comment by facepoint** [comment]
а в гитхабе как можно отслеживать, реализовалось ли данное дополнение?

**Comment by fuzegit** [comment]
Следить за коммитами и понимать, что решение данного вопроса может быть не сразу. Т.е. никто не дает никаких гарантий, что это будет реализовано, однако это не значит, что реализовано не будет.

**Comment by vlad7090** [comment]
ок, понял. было бы отлично в 2.4.1 такую опцию увидеть, о чем мечтают, думаю, большинство, кто делают каталог на своем сайте.
Еще свойство цвет было бы отлично, но наверное это уже невозможно:)

**Comment by globator88** [comment]
Поддерживаю. Зависимые поля и множественный выбор в свойствах очень не хватает.

**Comment by iAndroS** [comment]
Не к свойству цвет стремиться надо, а к тому, чтоб все типы полей были доступны в свойствах, ведь есть такой тип поля для двойки.

**Comment by fuzegit** [comment]
Невозможно все типы полей привязать к свойствам на данный момент.

**Comment by vlad7090** [comment]
согласен, что стремиться надо но пока трех главных не хватает - **множественный выбор**, флаг и цвета. И зависимость послей свойств. 
с остальными пока можно смириться, т.к уже можно будет делать качественные каталоги.

**Comment by vlad7090** [comment]
Если внести правки в 2.4.0 то должно работать? или еще в шаблонах надо вносить правки? почему то у меня после правок каталог начал выдавать 404 ошибку

**Comment by fuzegit** [comment]
> Если внести правки в 2.4.0 то должно работать? 

нет

**Comment by vlad7090** [comment]
т.е надо будет дождаться официального релиза, после чего вступят в силу изменения?

**Comment by vlad7090** [comment]
а то не хотел один проект полностью обновлять на новую версию, т.к неизвестен же еще выход. а встроить эту фишку очень необходимо:( не знаю как можно ли ее завести в итоге на 2.4.0
