### ISSUE TITLE
Доступ к чтению записей определённого или опредёленных типов контента, определённой группе или группе

### ISSUE THREAD

**Issue by Rivars** [instantsoft/icms2#1263]
**Используемая версия InstantCMS 2**: 2.13.1
Есть предложение добавить возможность для настройки контентов для группы пользователей, есть редактировани. Возможно ли добавить настройку для чтения.

**Comment by fuzegit** [comment]
Переформулируйте предложение. Ничего не понятно.

**Comment by Rivars** [comment]
Ладно
Есть тип контента - Новости
Есть группа пользователей - Группа 1
Хочу чтобы эта группа имела доступ на чтение записей в категориях этого контента

**Comment by Rivars** [comment]
есть надежда что данная возможность появится в релизе?

**Comment by fuzegit** [comment]
Вероятно, то, что нужно, уже есть
https://docs.instantcms.ru/manual/widgets/pages#показывать-группам

**Comment by Rivars** [comment]
Попробую реализовать, в своей задачи, позже отпишу

**Comment by Rivars** [comment]
спасибо, за помощь, решил
