### ISSUE TITLE
Если выбрать редактор для комментариев Textarea, то в админке он ну совсем кривой

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#1265]
**Используемая версия InstantCMS**: 2.13.1

![0](https://user-images.githubusercontent.com/16401582/99072624-72382800-25c5-11eb-80d6-8f8a4fde97eb.jpg)

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: ДА

**Comment by M0p94ok** [comment]
Добрый день! Подскажите пожалуйста, как удалить персонализированную обложку ролика?
