### ISSUE TITLE
Небезопасная рандомизация

### ISSUE THREAD

**Issue by s00py** [instantsoft/icms2#127]
Уязвимость позволяет предугадывать токен для восстановления пароля пользователя.

https://github.com/instantsoft/icms2/blob/master/system/controllers/auth/actions/restore.php#L35
Для генерации токена используется функция string_random
https://github.com/instantsoft/icms2/blob/master/system/libs/strings.helper.php#L188

` $string = md5(md5(session_id() . '$' . microtime(true) . '$' . uniqid()) . '$' . $seed);`
Функции microtime и uniqid возвращают результат основанный на времени сервера, session_id известно, $seed будет содержать email пользователя, для которого генерируется токен.

Пример аналогичных уязвимостей в opencart http://www.securitylab.ru/lab/PT-2012-34

**Comment by fuzegit** [comment]
Приведение функции к виду 

```php
/**
 * Генерирует случайную последовательность символов заданной длины
 * @param int $length
 * @return string
 */
function string_random($length=32, $seed=''){

    $string = md5(md5(md5(serialize(cmsConfig::getInstance()->getAll())) . '$' . microtime(true) . '$' . uniqid()) . '$' . $seed);

    if ($length < 32) { $string = mb_substr($string, 0, $length); }

    return $string;

}
```

вероятно решит проблему?

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/89fc627f657954b214f8aba56df5a914a9360096
