### ISSUE TITLE
Проблемы с полем дата и системными именами полей

### ISSUE THREAD

**Issue by 2murkin** [instantsoft/icms2#1277]
**Используемая версия InstantCMS**: 2.14.0

**Версия PHP**:  5.6.40

**Как воспроизвести проблему**:
1. Невозможно отредактировать поле дата публикации в настройках типа контента

2. При создании и редактирование записи появляется 503 ошибка, если в настройках типа контента создать поле с числовым системным именем (Например "2")

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
> Невозможно отредактировать поле дата публикации в настройках типа контента

На текущей версии с Github проблема решена. 

> При создании и редактирование записи появляется 503 ошибка, если в настройках типа контента создать поле с числовым системным именем (Например "2")

Вообще конечно странно создавать поля с числовым системным именем. Но я не смог повторить. Какая версия mysql? Включите режим отладки в админке и вместо 503 ошибки будет текст ошибки.

**Comment by 2murkin** [comment]
У меня такая ошибка Mysql сервер: 5.5.65 
Ошибка в запросе БД:
Неизвестный столбец '0' в 'field list'

INSERT INTO vcms_con_pages (`title`, `content`, `attach`, `0`, `slug`, `is_pub`, `is_approved`, `date_pub_end`, `user_id`, `category_id`, `date_approved`)
VALUES ('Заголовок', '

Текст страницы
', NULL, 'Строковое поле с ситемным именем 1', 'link', 1, 1, NULL, '1', '0', CURRENT_TIMESTAMP)

Вот скрины повторил на демо сайте
![1](https://user-images.githubusercontent.com/34476334/101611499-68221180-3a2b-11eb-8e83-b290b34d14f3.png)
![2](https://user-images.githubusercontent.com/34476334/101611506-69533e80-3a2b-11eb-928e-248374905ac6.png)
![3](https://user-images.githubusercontent.com/34476334/101611508-69ebd500-3a2b-11eb-8a86-c54ddc5e44dd.png)
