### ISSUE TITLE
Поле "Флаг" - фильтр

### ISSUE THREAD

**Issue by iton1** [instantsoft/icms2#1278]
**Используемая версия InstantCMS**: 2.14.0

**Версия PHP**:  7.4

Добавил поле "Флаг" в "Тип контента"

![изображение](https://user-images.githubusercontent.com/17750649/101515170-1e83e900-398f-11eb-8db1-4243424ff4d4.png)

Ставим галочку, что видно поле в фильтре, а в фильтре у поля видно только название.

![изображение](https://user-images.githubusercontent.com/17750649/101515633-9c47f480-398f-11eb-84bd-25e4f7a01aad.png)

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/24d4769ee640cccdb10e8d62ffa7a0f21246f148
