### ISSUE TITLE
Админка CoreUI - не видны элементы "Действия"

### ISSUE THREAD

**Issue by iton1** [instantsoft/icms2#1279]
**Используемая версия InstantCMS**: 2.14.0

**Версия PHP**:  7.4

Админка CoreUI, разрешение экрана 1280x800, не видны элементы "действий" удалить контент. Если вложенность большая под категорий, то не видно.

![изображение](https://user-images.githubusercontent.com/17750649/101516138-2ee89380-3990-11eb-871b-7ffa1ff41afb.png)

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: ДА

**Comment by Risgit** [comment]
Зажмите Ctrl на клавиатуре и крутите колесо мыши.

**Comment by iton1** [comment]
> 
> 
> Зажмите Ctrl на клавиатуре и крутите колесо мыши.

Гениально )) еще можно разрешение экрана изменить )

**Comment by Risgit** [comment]
Еще можно галочку в кружочке выровнять, а то она неровная.
