### ISSUE TITLE
Виджет категории

### ISSUE THREAD

**Issue by vikontkg** [instantsoft/icms2#1283]
InstantCMS: 2.14.0
В сообществе неоднократно поднимлся вопрос о необходимости в списке Категорий показывать количества материалов в категории. На сегодняшний день для этого нет даже опций! А ведь надо. Показ количества материалов возле категории повышает юзабельность сайта и повышает поведенческий фактор, так как мотивирует пользователя узнать, а что там в категории есть... Показ количества материалов категории лучше вывести в опцию. Кому надо включит.

Еще виджет Категорий показывает список категорий не в столбик (каждая категория с новой строки), а горизонтально (в строку). Категории с короткими именами оказываются на одной строке. Это, возможно, где то надо, но в основном категории нужны в столбик Сделайте вид вывода списка категорий опционально/

**Comment by fuzegit** [comment]
Не планируется

**Comment by vikontkg** [comment]
Почему не планируется? Сложно реализовать? Сделать складчину? Во сколько оцениваете?

А категории в столбик, тоже не планируете? Вроде бы всегда каждое наименование было с новой строки.

**Comment by fuzegit** [comment]
> Еще виджет Категорий показывает список категорий не в столбик (каждая категория с новой строки), а горизонтально

Нет. Виджет показывается "в столбик".

![Выделение_024](https://user-images.githubusercontent.com/13233234/113675826-6cea8f80-96c4-11eb-98f8-fd0d3cc69f3f.jpg)
