### ISSUE TITLE
при обновлении до 2.14.0 пропало верхнее меню

### ISSUE THREAD

**Issue by alexvai** [instantsoft/icms2#1284]
версия 2.14.0 от 29.11.2020

PHP 7,4

При обновлении до версии 2.14 пропало верхнее меню во всех шаблонах от Конструктора тем.
![2020-12-14_150942](https://user-images.githubusercontent.com/4194856/102084990-adc14e80-3e1e-11eb-9982-ec24be8681a9.jpg)

**Comment by fuzegit** [comment]
Запросите обновление Конструктора тем, если в нём используется не стандартный виджет меню.

**Comment by my-instantcms** [comment]
У меня тоже перестал работать такой код в main.tpl.php
`$this->menu('main', true, 'menu', 4, true, 'menu', 'Menu');`
Может что то изменили?

**Comment by alexvai** [comment]
Загрузил старую версию -почти все вернулось. В тонкости не вникал.
