### ISSUE TITLE
Странный артефакт в пагинации

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#1286]
**Используемая версия InstantCMS**: 2.14

В версии 2.14 в ссылках пагинации зачем-то нарисовалась решетка в конце. Это для чего-то нужно?
![0](https://user-images.githubusercontent.com/16401582/103534815-aaab0280-4ea0-11eb-850d-8fe10faa9eb5.jpg)
У себя убрал в system/core/paginator.php в строке 93, но при обновлении может опять появиться.

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
В 2.14.1 убрано.4 янв. 2021 г. 15:25 пользователь шэльдэ бердэ бельдэ <notifications@github.com> написал:
Используемая версия InstantCMS: 2.14
В версии 2.14 в ссылках пагинации зачем-то нарисовалась решетка в конце. Это для чего-то нужно?

У себя убрал в system/core/paginator.php в строке 93, но при обновлении может опять появиться.
Воспроизводится ли проблема на демо https://demo.instantcms.ru/: ДА

**Comment by asnenne** [comment]
Не обратил внимание, что демо-сайт не обновлен до 2.14.1.

Хорошо тогда, спасибо.
