### ISSUE TITLE
Не работает вывод постов в соответствии с наборами

### ISSUE THREAD

**Issue by yuri25** [instantsoft/icms2#1287]
**Используемая версия InstantCMS**: 2.14.1
**Версия PHP**: 7.4.3, fpm-fcgi
**Версия MySQL**:  8.0.22

Посмотреть проблему https://zrmc.ru

все было нормально, но перестало работать

**Воспроизводится ли проблема на демо //demo.instantcms.:/**: НЕТ

Поставил в настройках постов выводить лучшие за день, сначала вроде все сработало... потом смотрю порядок вывода на главной изменился вроде как на по времени публикации. Сделал вывод лучшие за неделю, за месяц.... пофиг, ничего не меняется. Хотя постов всего 5, у поста который должен быть на главной вверху  +4, у других 0 и -1.  Может я что то не понимаю? На всякий случай написал сюда на гит.

**Comment by yuri25** [comment]
У меня на сайте выводит по времени публикации... я так понимаю вот из скриншота, что за неделю, за месяц - это лучшие? Т.е. за кого больше плюсанули или что?

**Comment by yuri25** [comment]
![Снимок экрана 2021-01-05 032148](https://user-images.githubusercontent.com/253228/103593539-28a1f480-4f07-11eb-9102-039a6b5db9bc.png)

**Comment by yuri25** [comment]
Я прошу прощения, возможно что то сам не настроил... может еще какие то причины... Можете посмотреть на сайте https://zrmc.ru   Я думаю что посты у кого больше + должны быть наверху.... Почему не работает - не могу понять... 
![Снимок экрана 2021-01-05 043805](https://user-images.githubusercontent.com/253228/103596981-3740d980-4f10-11eb-9fdb-1819f19cd758.png)

**Comment by fuzegit** [comment]
Полагаю, вы неверно настроили наборы.
https://docs.instantcms.ru/manual/ctypes/datasets/add

> Я думаю что посты у кого больше + должны быть наверху.

Должна быть такая сортировка, которую вы задали в настройках набора. Вообще, такие вопросы лучше задавать на форуме, поскольку я пока что не вижу ни ошибки, нет понимания проблемы.

Всё, что могу посоветовать, так это отключить кэш в настройках и проверить.

**Comment by yuri25** [comment]
Прошу прощения, действительно не разобрался и не настроил в наборе порядок сортировки.
