### ISSUE TITLE
Ошибка при смене типа поля.

### ISSUE THREAD

**Issue by numinaki** [instantsoft/icms2#1288]
**Используемая версия InstantCMS**: 2.14.1

**Версия PHP**:  7.1-7.2
**Версия MySQL/MariaDB**:  10.3

Установка чистая, в код изменения не вносились, дополнения не устанавливались

**Как воспроизвести проблему**:

* Создать строковое поле в типе контента
* В записях внести в данное поле, число, в другой записи текст 
* зайти в типы контента, в поля, изменить тип данного поля со строкового поля на числовое, получим ошибку:
 Ошибка в запросе БД:
Encountered illegal value '' when converting to DECIMAL

ALTER TABLE `cms_con_catalog` CHANGE `kolpolvvodvikl` `kolpolvvodvikl` DECIMAL(9,2) NULL DEFAULT NULL

Последние вызовы:

    modelContent->updateContentField() @ /system\controllers\admin\actions\ctypes_fields_edit.php : 76
    actionAdminCtypesFieldsEdit->run() @ /system\core\controller.php : 582
    cmsController->runExternalAction() @ /system\core\action.php : 37
    cmsAction->__call() @ /system\controllers\admin\actions\ctypes.php : 11
    actionAdminCtypes->run() @ /system\core\controller.php : 582
    cmsController->runExternalAction() @ /system\core\controller.php : 453
    cmsController->executeAction() @ /system\core\controller.php : 429
    cmsController->runAction() @ /system\core\core.php : 779
    cmsCore->runController() @ /index.php : 46

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: НЕТ

**Comment by fuzegit** [comment]
Мы исправили, однако проблема решается и вот этой опцией:

![Выделение_025](https://user-images.githubusercontent.com/13233234/113773824-2b42fe80-972f-11eb-9b5f-61b536b81d5f.jpg)
