### ISSUE TITLE
При изменении порядка категорий меняются ссылки

### ISSUE THREAD

**Issue by Kapa6ac79** [instantsoft/icms2#1293]
**Используемая версия InstantCMS**: 2.14.1

Админка->Контент->(выбрать категорию)->Категории->Порядок->Сохранить
После этого у всех вложенных категорий поменяется URL, добавится в конце цифра 2.
Если еще раз сохранить порядок, то все URL исправляются. (Цифра 2 пропадает)

**Comment by iton1** [comment]
Тоже заметил, что при перетаскивание категории добавляется цифра 2 - НО это происходит если в типе контента выключено "Генерировать URL из названия категории".

![изображение](https://user-images.githubusercontent.com/17750649/105964683-96b78280-6093-11eb-9ff3-da0bb2165c25.png)

Еще заметил, перетаскиваю категорию "Москва" - добавилась цифра 2, еще раз перетаскиваю - цифра пропадает, беру другую категорию "Спб" и перетаскиваю добавляется цифра 2, еще раз перетаскивая цифра пропадает, НО она добавляется в категорию "Москва" у которой ее не было и ее я не трогал в этот раз!

**Comment by iton1** [comment]
На демо demo.instantcms.ru при перетаскивание под категории цифра добавляется и к категориям и под категориям. 

![изображение](https://user-images.githubusercontent.com/17750649/105965351-59072980-6094-11eb-8f1d-d20dc54bb435.png)

![изображение](https://user-images.githubusercontent.com/17750649/105965395-691f0900-6094-11eb-81db-1ffe77474bff.png)

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: ДА

**Comment by goldman-sax** [comment]
Та же двойка добавляется при включенной опции "Генерировать URL из названия категории". То есть она не влияет.

**Comment by goldman-sax** [comment]
Хорошо бы еще иметь возможность сортировать категории и подкатегории по алфавиту.
