### ISSUE TITLE
Показывать записи из подкатегорий внутри родительской категории 

### ISSUE THREAD

**Issue by iton1** [instantsoft/icms2#1296]
**Используемая версия InstantCMS**: 2.14.1

В категориях если отключить функцию "Показывать записи из подкатегорий внутри родительской категории"

![изображение](https://user-images.githubusercontent.com/17750649/106366184-3b171e80-634b-11eb-8032-a2160ca3b674.png)

то в разделе типа контента появляется надпись, как пример "Нет объявлений для отображения"

![изображение](https://user-images.githubusercontent.com/17750649/106366207-5e41ce00-634b-11eb-95a2-5d150c437e51.png)

может будет лучше не показывать эту надпись при включенной функции, вроде очевидно, что мы скрыли контент из раздела по какой то причине, а пользователя надпись вводит в заблуждение.

**Comment by fuzegit** [comment]
Всё это конечно хорошо, но вы видимо не так поняли опцию. 
Например, мы добавили в корневую категорию объявление и явно ожидаем его там увидеть, при этом из других категорий объявлений там не будет.
Мы можем конечно отключить добавление в корень, но тогда мы можем добавить объявление в "Недвижимость" и оно в этой категории должно показываться, при этому из вложенных в "Недвижимость" категорий объявлений не будет.
