### ISSUE TITLE
Ошибка при определенных настройках категорий типа контента

### ISSUE THREAD

**Issue by zau4man** [instantsoft/icms2#1297]
**Используемая версия InstantCMS**: 2.14.1

**Как воспроизвести проблему**:

В типе контента в блоке категории задать такие настройки

![Image2021-01-31-23-21-19](https://user-images.githubusercontent.com/13526431/106393972-e394b380-641b-11eb-8413-7b8559a5745a.png)

И получим ошибку

![Image2021-01-31-23-21-00](https://user-images.githubusercontent.com/13526431/106393979-eee7df00-641b-11eb-95f3-3bf4d9c73ec5.png)

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: да

**Comment by ovgrusin** [comment]
Подтверждаю проблему
