### ISSUE TITLE
 Генератор карты сайта sitemap.xml

### ISSUE THREAD

**Issue by iton1** [instantsoft/icms2#1299]
**Используемая версия InstantCMS**: 2.14.1

После генерации карты сайта, 

![изображение](https://user-images.githubusercontent.com/17750649/106566078-da513700-6540-11eb-8fe9-3b81eda410cf.png)

перехожу по ссылке https://сайт.ru/sitemap.xml и высвечивается ошибка "403 Forbidden"

![изображение](https://user-images.githubusercontent.com/17750649/106565921-9bbb7c80-6540-11eb-9b03-3785f6e6ea5f.png)

ее можно решить созданием папки sitemaps по адресу /cache/static/ , но может как то автоматизировать?

**Comment by Loadir** [comment]
> sitemaps по адресу /cache/static/ , но может как то автоматизировать?
Лучше расскажите, куда она у вас теряется, так как при установке движка, она идет в комплекте пакета установщика.
Возможно, чистите кэш вручную с удалением этой папки.

**Comment by iton1** [comment]
Действия такие, на новый сайт, скачал cms https://instantcms.ru/get , установил, сгенерировал файл sitemap.xml , папки sitemaps нет.
