### ISSUE TITLE
Неправильные склонения объектов в фильтре

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#1302]
**Используемая версия InstantCMS**: 2.14

В настройках типа контента указываем заголовки. Я так понимаю, в кнопке фильтра названия тянутся оттуда. Так вот, в заголовках у нас 1, 2 и много. Но в именительном падеже. В кнопке же у нас винительный падеж (кого?, что?). Если это объявление, вопросов нет, окончание будет правильное. Показать 1 объявление, показать 2 объявления. Но если это компания, то получаем косяк: **показать 1 компания**.

![ввв](https://user-images.githubusercontent.com/16401582/107760678-371bd100-6d3b-11eb-8bb3-09cd4c6b2c6b.jpg)

Спасибо.

**Comment by BorisRBJ** [comment]
Нам надо, чтобы склонялись:
1. существительные женского рода имеющие окончание -ИЯ (компания, партия, стадия), здесь меняем на -Ю
2. существительные женского рода и одушевленные существительные мужского рода с суффиксами -УТК-, -ЮШК-, -ЫШК-, -ИШК-, -ЕШК-, -ОШК-, -АШК-, -ОЧК-, -ОТК- и т.д. (по схеме: гласная(йотированная) - согласная - буква К в 90% (иногда Т и др.)) (мишка, мышка, мушка, зимушка, крышка, плюшка, флешка, плошка, бочка, пилотка, купчишка, трусишка, мальчишка), здесь меняем на -У. Но есть исключения, например ОЧКО (тут надо определять род (чем?)).

Можно гонять регулярками или дать пользователям возможность вводить нестандартную форму отдельно, либо правилами задавать, к примеру как здесь - https://github.com/nodkz/lvovich/blob/master/src/rules/cityRules.js
Но судя по тому, сколько в правилах исключений, да и род определять нечем, проще дать возможность вводить в заголовках нестандартную форму склонения числительных.

**Comment by fuzegit** [comment]
Как я понимаю, к числительным в настройках надо добавить винительный и предложный падежи (помимо существующего именительного). По идее других не требуется.
Всё верно?

**Comment by asnenne** [comment]
Насчёт родительного не знаю, где он может использоваться. Разве что в поиске (найдено столько-то записей), может ещё где-нибудь. В принципе, как резервный вариант, можно и родительный, вдруг пригодится))

**Comment by asnenne** [comment]
С контентом проблема решена, а вот с профилями и группами нет))
![0](https://user-images.githubusercontent.com/16401582/126078295-b0f161a0-7897-4981-a1d3-5b81c64aa8fc.jpg)
![0](https://user-images.githubusercontent.com/16401582/126078306-71043e9d-d32b-438f-9cbc-136c1c9d7198.jpg)
