### ISSUE TITLE
Компонент Редиректы обрезает ссылки

### ISSUE THREAD

**Issue by 2murkin** [instantsoft/icms2#1310]
**Используемая версия InstantCMS**: 2.14.1
Компонент Редиректы обрезает ссылку после знака &
Было так
https://demo.instantcms.ru/redirect?url=https://www.openstreetmap.org/query?lat=60.6530424&lon=56.84995535

Стало так
https://www.openstreetmap.org/query?lat=60.6530424

**Comment by fuzegit** [comment]
Где вы вставляете ссылку, чтобы она обернулась CMS в редирект? Поле, запись на стене, еще где-то?

**Comment by 2murkin** [comment]
Я вставляю ссылку в виджет на главной странице сайта и в поле типа контента

**Comment by fuzegit** [comment]
В какое поле? Ссылка редиректа формируется CMS или же вы сами вставляете уже готовую, завёрнутую ссылку на редирект?

**Comment by 2murkin** [comment]
Вставляю готовую завёрнутую ссылку на редирект в поле текст и в текстовый виджет "https://мойсайт.ru/redirect?url=https://www.openstreetmap.org/query?lat=60.6530424&lon=56.84995535"

**Comment by fuzegit** [comment]
Так делать нельзя. Знак & (амперсанд) в значении параметра должен быть в виде мнемоники **&amp;**

**Comment by 2murkin** [comment]
но так тоже обрезает https://demo.instantcms.ru/redirect?url=https://www.openstreetmap.org/query?lat=60.6530424&amp;lon=56.84995535

**Comment by fuzegit** [comment]
Ссылку, которую формирует CMS, выглядит вот так:

`/redirect?url=https%3A%2F%2Fwww.openstreetmap.org%2Fquery%3Flat%3D60.6530424%26amp%3Blon%3D56.84995535`
