### ISSUE TITLE
Улучшение и необходимый функционал в maps2

### ISSUE THREAD

**Issue by rdimrs** [instantsoft/icms2#132]
1) В картах гугл сделать поиск по радиусу.
Пример http://www.myjoom.com/demo-geocode-factory/41-radius-frontend-auto

2) Возможность включать/отключать новости, отзывы и события для каждой категории. У меня есть категории где это лишнее и не подходит для конкретной категории, однако я не могу отключит только там где мне нужно.

3) Мультивыбор в полях свойств мэпса.

**Comment by mafru** [comment]
Вот это вас "понесло"!!!  Здесь осуществляется поддержка данного [компонента](http://www.instantmaps.ru/contacts.html) 
К движку это не имеет отношения.

**Comment by rdimrs** [comment]
ничего страшного, разработчики удалят если не по теме, зато точно увидят.
