### ISSUE TITLE
Не сохраняется пустое значение поля "дата"

### ISSUE THREAD

**Issue by san-sanych-k** [instantsoft/icms2#1329]
**Используемая версия InstantCMS**: 2.14.2

**Как воспроизвести проблему**:

* добавить в тип контента поле типа "дата"
* создать запись с пустым значением поля дата, либо стереть до этого внесенное значение поля
* запись сохранится с текущей датой (не очищается)

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: ДА

UPD: причину не нашел, но вышеуказанное явление происходит если системное имя называется: date или date_ХХХ и подобное. если писать другое системное имя отличное от date то проблемы нет.

**Comment by narochnyi** [comment]
Присоединяюсь. Тоже столкнулся с такой проблемой. Нужно было сразу сюда зайти, я голову ломал несколько часов, почему мой код работает не правильно))
