### ISSUE TITLE
Невозможно вывести обложку альбома в виджете Список контента

### ISSUE THREAD

**Issue by zau4man** [instantsoft/icms2#1330]
**Используемая версия InstantCMS**: 2.14.2

С версии 2.14.0 нельзя в настройках виджета Список контента при выборе типа контента Фотоальбомы выбрать для вывода поле Обложка альбома

![Image2021-06-02-18-46-02](https://user-images.githubusercontent.com/13526431/120499410-739e3600-c3d9-11eb-8909-b0a97de3b067.png)

Обложку можно вывести только используя свой шаблон вывода списка контента и обратившись в нем напрямую к $item['cover_image']
Тема на форуме https://instantcms.ru/forum/thread34680-1.html

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: ДА

**Comment by ovgrusin** [comment]
Подтверждаю.
Но решение видится не в ещё одном варианте вывода виджета "Список контента" (или дополнительных опциях для него), а в создании нового виджета "Список альбомов" (компонент "Фотоальбомы")
