### ISSUE TITLE
Ошибка при создании поля в Свойствах Контента (2.14.2)

### ISSUE THREAD

**Issue by Zhigar777** [instantsoft/icms2#1334]
**Используемая версия InstantCMS**: ВЕРСИЯ 2.14.2

**Версия PHP**:  ВЕРСИЯ 5.4.16-48.el7.cloudlinux
**Версия MySQL/MariaDB**:  Версия сервера: 10.3.28-MariaDB-cll-lve - MariaDB Server/Версия клиента базы данных: libmysql - 10.1.28-MariaDB

**Как воспроизвести проблему**:  Панель управления / Типы контента/ Свойства контента / +Создать поле
При создании страница с ошибкой.

**Ошибка - пример 1**:
Fatal error: Uncaught Error: Call to undefined function ntval() in /var/www/probeaut/data/www/probeautyonline.ru/system/controllers/admin/actions/ctypes_props_add.php:17 Stack trace: #0 /var/www/probeaut/data/www/probeautyonline.ru/system/core/controller.php(605): actionAdminCtypesPropsAdd->run('9', '2') #1 /var/www/probeaut/data/www/probeautyonline.ru/system/core/action.php(45): cmsController->runExternalAction('ctypes_props_ad...', Array) #2 /var/www/probeaut/data/www/probeautyonline.ru/system/controllers/admin/actions/ctypes.php(11): cmsAction->__call('runExternalActi...', Array) #3 /var/www/probeaut/data/www/probeautyonline.ru/system/core/controller.php(605): actionAdminCtypes->run('props_add', '9', '2') #4 /var/www/probeaut/data/www/probeautyonline.ru/system/core/controller.php(476): cmsController->runExternalAction('ctypes', Array) #5 /var/www/probeaut/data/www/probeautyonline.ru/system/core/controller.php(452): cmsController->executeAction('ctypes', Array) #6 /var/www/probeaut/data/www/probeautyonline.ru/system/cor in /var/www/probeaut/data/www/probeautyonline.ru/system/controllers/admin/actions/ctypes_props_add.php on line 17

**Ошибка - пример 2**:
Fatal error: Uncaught Error: Call to undefined function ntval() in /var/www/probeaut/data/www/probeautyonline.ru/system/controllers/admin/actions/ctypes_props_add.php:17 Stack trace: #0 /var/www/probeaut/data/www/probeautyonline.ru/system/core/controller.php(605): actionAdminCtypesPropsAdd->run('9', '11') #1 /var/www/probeaut/data/www/probeautyonline.ru/system/core/action.php(45): cmsController->runExternalAction('ctypes_props_ad...', Array) #2 /var/www/probeaut/data/www/probeautyonline.ru/system/controllers/admin/actions/ctypes.php(11): cmsAction->__call('runExternalActi...', Array) #3 /var/www/probeaut/data/www/probeautyonline.ru/system/core/controller.php(605): actionAdminCtypes->run('props_add', '9', '11') #4 /var/www/probeaut/data/www/probeautyonline.ru/system/core/controller.php(476): cmsController->runExternalAction('ctypes', Array) #5 /var/www/probeaut/data/www/probeautyonline.ru/system/core/controller.php(452): cmsController->executeAction('ctypes', Array) #6 /var/www/probeaut/data/www/probeautyonline.ru/system/c in /var/www/probeaut/data/www/probeautyonline.ru/system/controllers/admin/actions/ctypes_props_add.php on line 17

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: НЕТ

![Снимок экрана 2021-06-09 в 18 26 22](https://user-images.githubusercontent.com/85634285/121394334-e703f280-c959-11eb-8223-02d9aa9d6f27.png)
![Снимок экрана 2021-06-09 в 18 31 52](https://user-images.githubusercontent.com/85634285/121394284-db183080-c959-11eb-94ce-218057f1def9.png)
![Снимок экрана 2021-06-09 в 19 42 49](https://user-images.githubusercontent.com/85634285/121395634-50383580-c95b-11eb-9680-688d5bab2dd3.png)

**Comment by fuzegit** [comment]
Исправлено
https://github.com/instantsoft/icms2/commit/7c38b46854e423c601bd394190c597e509ded5d3#diff-b5da172199f5d1658760e7e4b7b8cd6b926f107fbef3a4e73be5299030161edaR17

p.s.
> Версия PHP: ВЕРСИЯ 5.4.16-48.el7.cloudlinux

https://instantcms.ru/get
> Cистемные требования
> Интерпретатор PHP версии 5.5 или выше (PHP 7.X, 8.X поддерживается);

На приведённую вами ошибку это не влияет, но версию PHP стоит поднять.
