### ISSUE TITLE
Проблема с выводом виджетов

### ISSUE THREAD

**Issue by mafru** [instantsoft/icms2#134]
На странице просмотра записи в типе контента (выбранного в настройках сайта как тип контента по умолчанию) не выводятся виджеты.
Думаю из-за того, что страница просмотра записи не проходит проверку по маске url  в функции detectMatchedWidgetPages() в файле core.php.

**Comment by pin-git** [comment]
Подтверждаю, не работает.

**Comment by mafru** [comment]
В дополнение данному вопросу.
Необходимо внести в инсталлятор и скрипт обновления движка, записи в таблицу cms_widgets_pages, с положительными и отрицательными масками для типа контента Страницы (pages).

**Comment by mafru** [comment]
https://github.com/mafru/icms2/commit/cbcdb7b24fd83ca6b2770cdd8a8ed7eb60b1136c
https://github.com/mafru/icms2/commit/dfa9e5792a9b5788ee7b444729ecb789621f080d
https://github.com/mafru/icms2/commit/cbcdb7b24fd83ca6b2770cdd8a8ed7eb60b1136c

**Comment by mafru** [comment]
По решению вопроса направлен пулл для рассмотрения.
