### ISSUE TITLE
Отсортировать события в отладке по времени.

### ISSUE THREAD

**Issue by Risgit** [instantsoft/icms2#1343]
Просьба сделать сортировку событий в отладке по времени от медленных к быстрым.
Это улучшит удобство отладки, позволяя увидеть запросы mysql или другие события в порядке нарастания скорости. Самые медленные запросы будут сверху и не нужно будет крутить весь список, анализируя время выполнения.

У себя на сайте сделал так:
В файл \system\core\debugging.php добавил пару функций:
```
public static function sortData($data){
	
	usort($data, 'self::compareTime');
	
	return($data);
}
	
public static function compareTime($a, $b){
	
	if ($a == $b) {
        return 0;
    }
    return ($a['time'] > $b['time']) ? -1 : 1;
	
}
```
А в файл \templates\modern\assets\ui\debug.tpl.php после 
`<?php foreach($points_data as $tab_name => $data) { ?>`
дописал
`<?php $data = cmsDebugging::sortData($data); ?>`

Теперь все запросы и прочие события выводятся отсортированными по времени выполнения.
Самые медленные выводятся первыми.
Не думаю, что простая сортировка массива сильно замедлит время отладки.

**Comment by fuzegit** [comment]
Если делать, то только опционально. Т.е. добавлять селект с выбором сортировки на странице. 31 июл. 2021 г. 17:08 пользователь Risgit ***@***.***> написал:
Просьба сделать сортировку событий в отладке по времени от медленных к быстрым.
Это улучшит удобство отладки, позволяя увидеть запросы mysql или другие события в порядке нарастания скорости. Самые медленные запросы будут сверху и не нужно будет крутить весь список, анализируя время выполнения.
У себя на сайте сделал так:
В файл \system\core\debugging.php добавил пару функций:
public static function sortData($data){
	
	usort($data, 'self::compareTime');
	
	return($data);
}
	
public static function compareTime($a, $b){
	
	if ($a == $b) {
        return 0;
    }
    return ($a['time'] > $b['time']) ? -1 : 1;
	
}

А в файл \templates\modern\assets\ui\debug.tpl.php после
<?php foreach($points_data as $tab_name => $data) { ?>
дописал
<?php $data = cmsDebugging::sortData($data); ?>
Теперь все запросы и прочие события выводятся отсортированными по времени выполнения.
Самые медленные выводятся первыми.
Не думаю, что простая сортировка массива сильно замедлит время отладки.

**Comment by Risgit** [comment]
> Если делать, то только опционально. Т.е. добавлять селект с выбором сортировки на странице. 

Опционально даже лучше!
`<?php if(cmsDebugging::is_sort){$data = cmsDebugging::sortData($data);} ?>`

**Comment by fuzegit** [comment]
Да просто прикрутить при выводе что-то вроде этого https://vestride.github.io/Shuffle/

**Comment by Risgit** [comment]
> Да просто прикрутить при выводе что-то вроде этого
Можно. Но только установка node.js занимает полгига диска.
Всё же есть разница между двадцатью строчками кода и утраченными полгигами диска + висящей в оперативке нодой.
Да, это хорошо, когда ресурсы можно не экономить. Я, например, могу топить процессорами печку зимой. Но не все могут себе такое позволить.

**Comment by fuzegit** [comment]
Хм.., о каком nodejs речь?)

https://github.com/Vestride/Shuffle/blob/main/dist/shuffle.min.js

nodejs нужен для сборки из исходников. В комплекте есть собранный файл.

**Comment by Risgit** [comment]
Ну, я попытался решить проблему на понятном человеку языке php.
Яваскрипт, на мой взгляд, к человекопонятным языкам не относится.

**Comment by fuzegit** [comment]
Как то так

![Выделение_070](https://user-images.githubusercontent.com/13233234/133273934-3b05196e-002c-42a9-845a-c0fb3010fb1c.jpg)
![Выделение_071](https://user-images.githubusercontent.com/13233234/133273936-9c542284-a85f-46f6-8d5c-fdc3871eff6f.jpg)

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/e911bf41067a424945b234427c48a112c2b70374
