### ISSUE TITLE
Перестал работать пресет редактора tinymce

### ISSUE THREAD

**Issue by yuri25** [instantsoft/icms2#1344]
**Используемая версия InstantCMS**: 2.14.2

**Версия PHP**:  7.4.3
**Версия MySQL**:  8.0.22-0

**Как воспроизвести проблему**:

Взял редактор tinymce отсюда, создаю пресет, назначаю необходимые кнопки, назначаю этот пресет полю "Текст поста"
Все сохраняю, сбрасывю кэш, увеличиваю на 1 счетчик, при создании поста - шапка редактора не меняется и выглядит так:

![image](https://user-images.githubusercontent.com/253228/127752726-ff596c9c-4517-4ab8-9f2e-e41d562b65b3.png)

Еще неделю назад этот редактор отсюда нормально работал и настраивался.

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: НЕТ

**Comment by Loadir** [comment]
>Взял редактор tinymce отсюда
Надо к редактору ещё взять все измененные файлы движка за эту "неделю", тогда есть вероятность, что всё заработает.

**Comment by yuri25** [comment]
Да, Вы правы, на локальном проверил - все работает:)
