### ISSUE TITLE
Просьба отредактировать файл со ссылкой на обновление 2.14.2

### ISSUE THREAD

**Issue by Risgit** [instantsoft/icms2#1345]
**Используемая версия InstantCMS**: 2.14.1

**Версия PHP**:  7.4.22
**Версия MySQL/MariaDB**:  10.6.3

**Как воспроизвести проблему**: Попытаться обновиться с 2.14.1 до 2.14.2 в автоматическом режиме.

1. Нажимаем в админке ссылку "Доступно обновление 2.14.2"
2. Нажимаем кнопку "Установить обновление".
3. Видим сообщение об ошибке "Ошибка распаковки пакета. Файл не является zip архивом."
4. Вместо архива с обновлением в /update/installer появляется файл instantcms-update-2.14.2.zip размером 1kb являющийся HTML файлом следующего содержания:
```
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
Причина:
По ссылке на файл https://upd.instantcms.ru/info/2.14.1 имеется следующий текст:
2.14.2
20210412
http://upd.instantcms.ru/dist/instantcms-update-2.14.2.zip
То есть не хватает буквы "s" в http://
Просьба отредактировать файл.

**Comment by fuzegit** [comment]
Исправил, удалите файл update.dat предварительно.
