### ISSUE TITLE
Хлебные крошки в списках и тип контента по умолчанию

### ISSUE THREAD

**Issue by narochnyi** [instantsoft/icms2#1349]
**Используемая версия InstantCMS**: 2.14.2

Всем привет!

Если в настройках указать тип контента по умолчанию, и перейти на страницу записи этого типа, то в хлебных крошках, название тип контента не отображается, и это по логике хорошо, так и должно быть. Но что касается категорий (просмотр списка), то тут дела обстоят не так хорошо. В начало хлебных крошек добавляется название типа контента с возможность перейти в этот контент. Думаю раз в URL не отображается тип контента, тогда и из хлебных крошек нужно его убрать.
Предлагаю:
В файле \system\controllers\content\actions\category_view.php 
сделать так же как в файле \system\controllers\content\actions\item_view.php

такую проверку:
`$base_url = ($this->cms_config->ctype_default && in_array($ctype['name'], $this->cms_config->ctype_default)) ? '' : $ctype['name'];`

**Comment by fuzegit** [comment]
Эта опция закроет описанное.

![Выделение_006](https://github.com/user-attachments/assets/6c3d3515-a99a-47ec-b67d-471f3a7ee54a)
