### ISSUE TITLE
не авторизует пользователей домена .online

### ISSUE THREAD

**Issue by pin-git** [instantsoft/icms2#135]
У одно пользователя обнаружил что пользователей с мылом домена первого уровня .online (мыло@домен.online) регистрирует, но не авторизует, надо бы поправить.

**Comment by mafru** [comment]
В функции login файла system/core/user.php в строке 174 измените
 if (!preg_match("/^([a-zA-Z0-9\._-]+)@([a-zA-Z0-9\._-]+)\.([a-zA-Z]{2,4})$/i", $email)){
на
 if (!preg_match("/^([a-zA-Z0-9\._-]+)@([a-zA-Z0-9\._-]+)\.([a-zA-Z]{2,6})$/i", $email)){
Т.е. сейчас в регулярном выражении указана проверка почтовых доменов на длину до 4-х символов включительно.

**Comment by pin-git** [comment]
Спасибо, сам справился, оставил сообщение для оф разработчиков, чтобы не забылось.
Хотя... @mafru бросьте пожалуйста своё предложение в пулл, буду очень благодарен.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/5b6634973d1c72ee83c7eb21575500bb3439420a
