### ISSUE TITLE
Удаление вкладок профиля пользователя

### ISSUE THREAD

**Issue by deemon-74** [instantsoft/icms2#1351]
**Используемая версия InstantCMS**: 2.14.2

А админке  "Компоненты-Профили пользователей-Вкладки профилей" отсутствует функция удаления вкладок пользователей.
Критично если устанавливался сторонний компонент, который создаёт вкладку, но потом если компонент удалён, то вкладку не удалить.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/e911bf41067a424945b234427c48a112c2b70374
