### ISSUE TITLE
Сквозное поле html/php

### ISSUE THREAD

**Issue by web-studio-pro** [instantsoft/icms2#1357]
Сделать возможность добавлять сквозное поле в которое можно было вставить любой код и он выводился бы во всех записях.  
Сейчас Элементарно вставлять ссылку **Заказать через ватсап** приходится в html-поле в каждой записи.

Желательно с поддержкой php или чтоб вставить в код выражения {url} {title} ...

**Comment by fuzegit** [comment]
![Выделение_015](https://user-images.githubusercontent.com/13233234/134358025-8325a0ba-e369-4d9d-a2c4-c019684e5de9.jpg)

**Comment by web-studio-pro** [comment]
Кнопки Заказать... не уместно размещать внизу, особенно если описание листать длинное. 

Менять позицию через order:-1; тоже головняк, нужно всё во flex обволакивать, а от этого в теле записи рассыпается все поля.

**Comment by web-studio-pro** [comment]
Вот это здорово!
Сколько возможностей открылось. 
Большое СПАСИБО!
