### ISSUE TITLE
Добавить возможность увеличить размер сайдбара

### ISSUE THREAD

**Issue by numinaki** [instantsoft/icms2#1358]
**Используемая версия InstantCMS**: 2.14.2

Предлагаю добавить возможность регулировать мышкой размер сайдбара в админке, чтобы можно было прочитать названия категорий, а то все куда-то пропадает и не понятно, что там со структурой.

![image](https://user-images.githubusercontent.com/18723490/134774330-8ea857d9-6f64-4fe5-80d4-ca9bc43222e0.png)

**Comment by fuzegit** [comment]
В версии здесь проблема с обрезанием названий решена.
