### ISSUE TITLE
Настройки аватарки

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#136]
Сегодня прочитал на форуме вопрос, думаю актуально вынести его в гитхаб по поводу опций по настройке аватарки - дать возможность в даминке указывать пресеты для аватарки: в списке пользователей, в комментариях, в виджете пользователя и в профиле.
Идеально было бы, если бы можно было указывать область кропом.

**Comment by mafru** [comment]
Из всего описанного, мне только идея с кропом нравится.

**Comment by vsbook** [comment]
Согласен с тем,что кроп необходим.Но и...Рассудите сами.В стандарте.Идет 3 пресета.Normal,small,micro.Этого вполне достаточно при полной версии сайта.Но вот при мобильной адаптации...Да конечно,можно добавить свой пресет.Но каждый начнет выводить свое системное имя.В общем по моему мнению нужно четыре а не три пресета.Между пресетом normal и small большая брешь.которую я считаю надо заполнить.

**Comment by Val-Git** [comment]
Чем не устраивает вот это решение: [http://www.instantcms.ru/blogs/moi-razrabotki/obrezka-avatara-pri-zagruzke.html](url)

**Comment by vsbook** [comment]
Не много раньше вышла:http://www.instantcms.ru/blogs/moe-hobi/pole-izobrazhenie-s-obrezkoi.html
-эта разработка,которую я и приобрел.Не в этом суть,Суть в пресетах для аватара,настраивать их как в стандартом компоненте:загрузка изображений,думаю не стоит.Мое мнение сводиться лишь к четвертому пресету,что будетк примеру между normal и small.
Адаптивность...к примеру,я сейчас переделываю на свое усмотрения  шаблон OneNews.И при разрешении,к примеру 480,аватар в 250 или придётся сжать в css(что считаю не грамотно)или же поставить по центру(а если разрешение 600?).Впрочем так и стоит в данном шаблоне изначально.Думаю легче раз увидеть конечно если есть желание ( пока делаю на разрешениях 320-534) http://saratovplus.ru/users/1 .Думаю понятно почему я и говорю нужен четвертый пресет опять же к примеру между normall и small.

**Comment by vlad7090** [comment]
Можно и свои пресеты создавать. Зачем в движке их куча. В настройках аватарки в админке просто выбирать потом какие пресеты применять и тем самым кропить можно будет под 3-4-5 форматов.
Все равно вам приждется для мобильной версии прописывать пресет в шаблоне или в стилях

**Comment by vsbook** [comment]
Вот)))Зачем я их буду прописывать?Когда они будут в движке?

**Comment by vsbook** [comment]
Я уже не говорю,об усложнении при обновлениях,я не думаю,что запущенный сайт имеет виджеты,компоненты,только стандартные.

**Comment by Val-Git** [comment]
> Согласен с тем,что кроп необходим.

> Вот)))Зачем я их буду прописывать?Когда они будут в движке?

Тогда нужно не crop аватарки просить а дополнительный пресет =) Хотя это дело индивидуальное, кому-то нужно 10 пресетов для аватарки, кому-то 2-х достаточно.

**Comment by vsbook** [comment]
Конечно же можно обойтись и вообще без аватара,а фотографии перед тем как закинуть на сайт,прогнать через редактор...И проблем нет. Всё неважное — выбрасывать, тогда и получится краткость,что сестра таланта!так Чехов говорил))) А сам писал писал..
Crop нужен,90% пользователей  будут загружать фото,которое  только слово фотошоп слышали...
а у кого то альбомный вид,у кого то портретный...И четвертый пресет так же необходим-это мое мнение.

**Comment by pocus-1** [comment]
Ну и, для разнообразия, вынести в админку переменную $is_html_empty_avatar из файла ..\system\libs\template.helper.php
