### ISSUE TITLE
Поле файл в форме в админке

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#1363]
**Используемая версия InstantCMS**: 2.14.2

Не работает поле "Файл" в форме компонента в админке. Сохраняет данные в бд в json и дальше, при редактировании, выдает ошибку. 

Перевел в yaml, сохраняет нормально. При редактировании поле заполнено. Но при повторном сохранении оно уже пустое. 

Такая же беда с полем Изображение. Но оно при изменении формата на yaml работает нормально.

Предлагаю добавить возможность работать с этими полями из админки, чтобы не изобретать костыли.

Возможно я что-то делаю не так, документации-то нет совсем по этому поводу. Но проблема давняя и острая.

Спасибо.

**Comment by fuzegit** [comment]
Не очень понял. Как повторить проблему?

**Comment by asnenne** [comment]
Добавить поле файл в форму компонента в админке и попробовать загрузить файл в этом поле.

**Comment by asnenne** [comment]
`<?php class formControllerAction extends cmsForm{

    public function init($do, $id) {

        return array(

            'basic' => array(
                'title' => '',
                'type' => 'fieldset',
                'childs' => array(

                    new fieldFile('file_x', array(
                        'title' => 'Файл'
                    ))

                )

            )

        );

    }

}`

**Comment by fuzegit** [comment]
Никаких проблем

![Выделение_010](https://user-images.githubusercontent.com/13233234/135989115-818fd823-d3ba-442e-9d49-ae5e9a706601.jpg)

**Comment by fuzegit** [comment]
В экшенах контроллеров в админке всё так же работает без проблем, см. "Генератор RSS"

**Comment by fuzegit** [comment]
Полагаю, что вы при сохранении формы сохраняете в json, а потом, при выборке из базы конвертируете в Ямл.

**Comment by asnenne** [comment]
![1](https://user-images.githubusercontent.com/16401582/135989637-5db9d32a-4787-428b-a476-ea44b93f06a7.jpg)
![2](https://user-images.githubusercontent.com/16401582/135989653-911ae500-ae62-4ded-a731-2ebd287e0920.jpg)
Вот такая вот картина получается. Наверное я на самом деле что-то делаю не правильно.
**Полагаю, что вы при сохранении формы сохраняете в json**
Я просто добавил форму и просто ее пытаюсь сохранить))

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/blob/master/system/core/model.php#L2227

Есть четыре функции: две для ямл и две для json. По умолчанию массивы с формы сохраняются в ямле.
Но могут сохраняться и в json
https://github.com/instantsoft/icms2/blob/master/system/core/formfield.php#L502

**Comment by fuzegit** [comment]
> Вот такая вот картина получается. Наверное я на самом деле что-то делаю не правильно.

Полагаю, да)

> Я просто добавил форму и просто ее пытаюсь сохранить

Она и сохраняется.

В общем без всего кода сказать сложно, что там у вас.

**Comment by asnenne** [comment]
Не пытался я сохранить в yaml
```
<?php class actionSalesAddonsVersionAdd extends cmsAction {

    public function run($addon_id, $id = null) {

        $ver = [];
        $do = 'add';

        if ($id) {

            $do = 'edit';
            $ver = $this->model->getVersion($id);

            if (!$ver) return cmsCore::error404();

        } else {

            $vers_table = $this->model->get('sales_versions');
            $id = $vers_table ? max(array_keys($vers_table)) + 1 : 1;

        }

        $form = $this->getForm('version', array($do, $id));
        $errors = [];

        if ($this->request->has('submit')) {

            if (!$errors) {

                $ver = $form->parse($this->request, true);


                $errors = $form->validate($this, $ver);

                if (!$errors) {

                    if ($do == 'add') {

                        $ver['id'] = null;

                        $ver['addon_id'] = $addon_id;

                        $this->model->insert('sales_versions', $ver, true);
                        $vers_table = $this->model->get('sales_versions');
                        $id = $vers_table ? max(array_keys($vers_table)) : 0;

                    } else {
                        $this->model->update('sales_versions', $id, $ver, false, true);
                    }

                    if ($do == 'add') {
                        cmsUser::addSessionMessage('Версия добавлена', 'success');
                    } else {
                        cmsUser::addSessionMessage('Версия изменена', 'success');
                    }


                    $this->redirectToAction('addons_item', $addon_id);

                }

            }

            if ($errors) {

                if($do == 'edit') {

                    $ver['id'] = $id;

                }

                cmsUser::addSessionMessage('Произошла ошибка', 'error');

            }

        }

        $addon = $this->model->getItemById('sales_addons', $addon_id);

        return $this->cms_template->render('backend/version_form', array(
            'do'     => $do,
            'version' => $ver,
            'addon' => $addon,
            'form'   => $form,
            'errors' => $errors
        ));

    }

}
```

**Comment by asnenne** [comment]
Обычный код, ничего особенного))
И такая же беда с полем Изображение. Но там костылями выкрутился, а с файлом не получается ничего.

**Comment by fuzegit** [comment]
> Не пытался я сохранить в yaml

Вы сохраняете в JSON.


![Выделение_011](https://user-images.githubusercontent.com/13233234/135990711-462e0321-6cd4-42bd-bb1c-a47cf274c82e.jpg)
![Выделение_012](https://user-images.githubusercontent.com/13233234/135990716-87bfefa6-792f-4e27-b1b9-613b49bf3e92.jpg)

**Comment by asnenne** [comment]
Этот аргумент отвечает за перевод в yaml? Я знал, что истина где-то рядом)))

Спасибо.

**Comment by asnenne** [comment]
Сообщения почищу, пожалуй))

**Comment by fuzegit** [comment]
> Этот аргумент отвечает за перевод в yaml

Нет, за json. Еще раз: по умолчанию массивы в ямл. Но можно и в json, используя аргумент $array_as_json.

**Comment by asnenne** [comment]
Да, в json

**Comment by asnenne** [comment]
Но не всё хорошо)). Файл загрузился, при редактировании он в форме. Но при повторном сохранении пропадает.

**Comment by asnenne** [comment]
В общем-то в этом и была проблема. Когда я его в json перевел, я его назад потом вернул)) А вот повторно сохранить так и не смог.

**Comment by fuzegit** [comment]
> Файл загрузился, при редактировании он в форме. Но при повторном сохранении пропадает.

Это баг, да. Починю.

**Comment by asnenne** [comment]
С изображением нормально всё теперь, а вот с файлом беда))

**Comment by fuzegit** [comment]
/system/core/backend.php

в public function actionOptions(){

``$options = array_merge($options, $form->parse($this->request, true));``

заменить на

``$options = array_merge($options, $form->parse($this->request, true, $options));``

**Comment by asnenne** [comment]
Спасибо. Но не помогло))

**Comment by fuzegit** [comment]
> Но не помогло))

Я про общие настройки компонентов :)

В вашем случае 

``$ver = $form->parse($this->request, true, $ver);``

Т.е. при редактировании в экшене в parse третьим аргументом надо передавать существующие данные.

**Comment by asnenne** [comment]
Помогло, спасибо!)) Если добавить вот это
![1](https://user-images.githubusercontent.com/16401582/135995350-4dcfed33-813c-4e4d-899c-4ce8ac427a73.jpg)

**Comment by asnenne** [comment]
Еще раз спасибо!))
