### ISSUE TITLE
Список: мультивыбор - Предустановленные значения (заполнено поле)

### ISSUE THREAD

**Issue by iton1** [instantsoft/icms2#1365]
**Используемая версия InstantCMS**: InstantCMS 2.14.3

**Как воспроизвести проблему**:

Создал поле "Список: мультивыбор" в "Предустановленные значения" добавил значения:

![изображение](https://user-images.githubusercontent.com/17750649/137641105-b2337bce-2f22-4b37-8e9f-4647749c38e8.png)

Создаю на сайте страницу где это поле:

![изображение](https://user-images.githubusercontent.com/17750649/137641181-58ae892e-ee85-4f2a-95e5-0d1f41fb8834.png)

НО в поле уже выбрано значение, я его не выбирал, если у меня в "Предустановленные значения" добавлено больше значений, то будет выбрано несколько при добавление.

![изображение](https://user-images.githubusercontent.com/17750649/137641217-a004cca1-6a91-47ba-b6e7-c3dc2b633d84.png)

Конечно значение можно поменять на свое, но все же.

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/cb18fcd51b41ba36a7457b42c8f7d57a332ac772#diff-44f17de69b87d9e1963ad85614c17c66c61f508ce6b01d302ce6c51f3189071b
