### ISSUE TITLE
Некорректный Транислит изображений

### ISSUE THREAD

**Issue by Stas-Clear** [instantsoft/icms2#1367]
**Используемая версия InstantCMS**:  2.14.3

**Версия PHP**:  5.6
**Версия MySQL/MariaDB**:  5.6.43

**Как воспроизвести проблему**:
Проблем описана тут https://instantcms.ru/forum/nekorrektnyi-tranislit-izobrazhenii.html#post-346143

при добавлении изображения в статью в названии где присутсвует точка оно сохраняется как 
/upload/000/u1/0/f/v-cheboksarah-pri-plane-vakcinacii-v-329-tys-chel.-вакцинировано-около-52-photo-big.jpg
Половина на русском половина на латиннице.

* первый шаг.... В названии новости указать тему с точкой. типа "500 РУБ. в сутки"
* второй шаг....  в Поле изображение загрузить фото
* третий шаг....  проверить урл изображения.
 
**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: НЕТ

**Comment by ovgrusin** [comment]
Подтверждаю
