### ISSUE TITLE
Несколько предложений

### ISSUE THREAD

**Issue by my-instantcms** [instantsoft/icms2#137]
1) Хотелось бы, по умолчанию был подключен font-awesome.

2) Для функции getCategoriesTree() не хватает поле child_count как с меню, что бы проверить есть ли там подкатегории и делать какие то действия

3) В таблице cms_activity есть поле reply_url (для статусов), предлагаю переименовать и сменить тип на text, что бы хранить там массив и вывести в ленте, не только кнопку Ответить, еще и комментировать, нравится, поделиться, голосовать и т.д. в зависимости от типа

**Comment by Val-Git** [comment]
1) Категорически против! Иконочные шрифты - костыль, если кто хочет их использовать - пожалуйста, но не в коробку (очень не хочется их выпиливать постоянно)!

**Comment by mafru** [comment]
А в чем костыль?

**Comment by Val-Git** [comment]
@mafru на форуме уже обсуждалось. Также можно в интернете поискать множество статей на эту тему.
Если вкратце - шрифты используются для других целей, а не для показа картинок. Для иконок есть более лучшие и удобные способы (в частности применение svg).

**Comment by my-instantcms** [comment]
<b>Val</b>, сейчас почти все современные шаблоны, используют иконочные шрифты, думаю в будущем, всё ровно в инстанте будет, либо font-awesome либо bootstrap-иконки...
В SVG пока не разобрался, но для меня удобно использовать font-awesome в разработках, так как они масштабируются, меняют цвет, есть анимация иконок и т.д.

В любом случаи, если разработчики посчитают необязательным, то можно пропустить 1 пункт :)

**Comment by Val-Git** [comment]
@my-instantcms я не спорю, было время популярности иконочных шрифтов и их использовали везде где только можно (и я в том числе немного с ними баловался), но если ориентироваться на современные тренды и смотреть в будущее то оно НЕ в иконочных шрифтах.

> для меня удобно использовать font-awesome в разработках, так как они масштабируются, меняют цвет, есть анимация иконок и т.д.

все это и даже больше умеет и SVG! Советую потратить один вечер на изучение как юзать SVG и вы больше никогда не захотите возвращаться к шрифтам =)

Но конечно всё остается за разработчиками, если они посчитают нужным то придётся мириться))

**Comment by my-instantcms** [comment]
> Советую потратить один вечер на изучение как юзать SVG
Спасибо, попробую)

**Comment by fuzegit** [comment]
>Хотелось бы, по умолчанию был подключен font-awesome
если будем использовать, то в шаблоне подключим, но это никак не отразится на других шаблонах

> 2) Для функции getCategoriesTree() не хватает поле child_count как с меню, что бы проверить есть ли там подкатегории и делать какие то действия

зачем усложнять запрос? дерево меню строится иначе.

> 3) В таблице cms_activity есть поле reply_url (для статусов), предлагаю переименовать и сменить тип на text, что бы хранить там массив и вывести в ленте, не только кнопку Ответить, еще и комментировать, нравится, поделиться, голосовать и т.д. в зависимости от типа

нет, это неверно. для ваших целей нужно отдельное, другое поле

**Comment by my-instantcms** [comment]
с 1 и 2 пунктом согласен, уже не так важно, но с лентой пока возникают трудности, например: хочу сделать кнопку Поделиться, при нажатии соберу данные об статье и передаю в компонент Activity, но в БД поле принимает 140 символов, по этому текст обрезается, может для статуса, сделать проверку только в PHP а в БД сменить типа c varchar на text ?

**Comment by fuzegit** [comment]
@my-instantcms, нужно создать свое, нужное вам, поле, а вывод обрабатывать хуком. Поле reply_url предназначено... для url ответа) А вот если что-то не хватает в хуках, то это уже другой вопрос - пишите, добавим.
