### ISSUE TITLE
Ошибка приватности при сохранении фотоальбомов

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#1370]
**Используемая версия InstantCMS**:  2.14.2

**Версия PHP**:  7.0.33
**Версия MySQL/MariaDB**: 10.3.31-1.el7.centos
--

**Как воспроизвести проблему**:

* первый шаг - открываем любой фотоальбом
* второй шаг - редактируем его или нет.
* третий шаг - нажимаем кнопку СОХРАНИТЬ
* четвертый шаг - в поле Приватность выдает ошибку - Найдены ошибки в форме - Указано недопустимое значение
* пятый шаг - пытаемся менять выбор в поле Приватность - тоже самое - Найдены ошибки в форме - Указано недопустимое значение
* Менял шаблон на дефолтный, всё тоже самое.
![29-10-2021 18-19-01](https://user-images.githubusercontent.com/9349934/139462314-e6e02fb0-526f-42e8-9615-1469de25c5b0.jpg)
![29-10-2021 18-19-11](https://user-images.githubusercontent.com/9349934/139462335-a798a5cb-a3db-4986-a7ba-ee2185152fba.jpg)

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: НЕТ

**Comment by nomad48** [comment]
В консоли ошибка - **Uncaught SyntaxError: Invalid or unexpected token** - https://мой_домен/albums/edit/70:2428

При включенной отладке и редактировании альбома выскакивают предупреждения внизу в списке фотографий

`PHP Notice:  Undefined variable: editor_params in /var/www/u0006953/data/www/мой_домен/templates/default/controllers/photos/widget.tpl.php on line 38, referer: https://мой_домен/albums/edit/70
PHP Notice:  Undefined variable: types in /var/www/u0006953/data/www/мой_домен/templates/default/controllers/photos/widget.tpl.php on line 44, referer: https://мой_домен/albums/edit/70
PHP Notice:  Undefined variable: types in /var/www/u0006953/data/www/мой_домен/templates/default/controllers/photos/widget.tpl.php on line 80, referer: https://мой_домен/albums/edit/70
PHP Notice:  Undefined variable: editor_params in /var/www/u0006953/data/www/мой_домен/templates/default/controllers/photos/widget.tpl.php on line 90, referer: https://мой_домен/albums/edit/70
PHP Notice:  Undefined variable: ctype in /var/www/u0006953/data/www/мой_домен/templates/default/controllers/photos/widget.tpl.php on line 103, referer: https://мой_домен/albums/edit/70`

**Comment by nomad48** [comment]
А что делать то? Ошибка есть, как ее решить?

**Comment by fuzegit** [comment]
> А что делать то? Ошибка есть, как ее решить?

Ошибка есть только у вас. Я проверил на демо и на своей локальной копии, проблема не подтвердилась, чтобы её решать. Версия у вас 2.14.2, последняя стабильная версия 2.14.3.
Создайте тему на форуме.

**Comment by nomad48** [comment]
Ошибка возникает из-за того, что при редактировании альбома почему-то показывается виджет загруженных фото
![18-11-2021 11-26-13](https://user-images.githubusercontent.com/9349934/142378966-da35ea02-ad37-41aa-a031-e2b99d288eeb.jpg)

Если убрать `<fieldset>

    <legend>Фотографии</legend>

    <div id="album-photos-widget" data-delete-url="/photos/delete" data-wysiwyg_name="">

        <div class="previews_list">
                                                                    <div class="preview block" rel="655">
                        <div class="thumb">
                            <a rel="edit_list" class="ajax-modal hover_image" href="">
                                <img src="/upload/023/u2368/b/4/f1bd2f98.jpg" title="d89bb6b5" alt="d89bb6b5" class="img-fluid ">                            </a>
                                                        <div class="actions">
                                <a class="delete" href="#" onclick="return icms.photos.remove(655)">
                                    Удалить                                </a>
                            </div>
                                                    </div>
                        <div class="info">
                            <div class="title">
                                <input type="text" class="form-control input" name="photos[655]" value="d89bb6b5">                            </div>
                            <div class="photo_content">
                                <textarea class="textarea form-control" id="content[655]" name="content[655]"></textarea>                            </div>
                            <div class="photo_additional">
                                <div class="photo_privacy">
                                    <select class="form-control " name="is_private[655]">
	<option value="0" selected="">Показывать всем</option>
	<option value="1">Показывать только друзьям</option>
	<option value="2">Доступ по ссылке</option>
</select>
                                </div>
                                                            </div>
                        </div>
                    </div>
                                                        <div class="preview block" rel="656">
                        <div class="thumb">
                            <a rel="edit_list" class="ajax-modal hover_image" href="">
                                <img src="/upload/023/u2368/1/e/79d747b3.jpg" title="f3707d45" alt="f3707d45" class="img-fluid ">                            </a>
                                                        <div class="actions">
                                <a class="delete" href="#" onclick="return icms.photos.remove(656)">
                                    Удалить                                </a>
                            </div>
                                                    </div>
                        <div class="info">
                            <div class="title">
                                <input type="text" class="form-control input" name="photos[656]" value="f3707d45">                            </div>
                            <div class="photo_content">
                                <textarea class="textarea form-control" id="content[656]" name="content[656]"></textarea>                            </div>
                            <div class="photo_additional">
                                <div class="photo_privacy">
                                    <select class="form-control " name="is_private[656]">
	<option value="0" selected="">Показывать всем</option>
	<option value="1">Показывать только друзьям</option>
	<option value="2">Доступ по ссылке</option>
</select>
                                </div>
                                                            </div>
                        </div>
                    </div>
                                                        <div class="preview block" rel="657">
                        <div class="thumb">
                            <a rel="edit_list" class="ajax-modal hover_image" href="">
                                <img src="/upload/023/u2368/5/0/1d44ac8e.jpg" title="f931450a" alt="f931450a" class="img-fluid ">                            </a>
                                                        <div class="actions">
                                <a class="delete" href="#" onclick="return icms.photos.remove(657)">
                                    Удалить                                </a>
                            </div>
                                                    </div>
                        <div class="info">
                            <div class="title">
                                <input type="text" class="form-control input" name="photos[657]" value="f931450a">                            </div>
                            <div class="photo_content">
                                <textarea class="textarea form-control" id="content[657]" name="content[657]"></textarea>                            </div>
                            <div class="photo_additional">
                                <div class="photo_privacy">
                                    <select class="form-control " name="is_private[657]">
	<option value="0" selected="">Показывать всем</option>
	<option value="1">Показывать только друзьям</option>
	<option value="2">Доступ по ссылке</option>
</select>
                                </div>
                                                            </div>
                        </div>
                    </div>
                                                        <div class="preview block" rel="658">
                        <div class="thumb">
                            <a rel="edit_list" class="ajax-modal hover_image" href="">
                                <img src="/upload/023/u2368/3/7/02afe0c5.jpg" title="7a851ec1" alt="7a851ec1" class="img-fluid ">                            </a>
                                                        <div class="actions">
                                <a class="delete" href="#" onclick="return icms.photos.remove(658)">
                                    Удалить                                </a>
                            </div>
                                                    </div>
                        <div class="info">
                            <div class="title">
                                <input type="text" class="form-control input" name="photos[658]" value="7a851ec1">                            </div>
                            <div class="photo_content">
                                <textarea class="textarea form-control" id="content[658]" name="content[658]"></textarea>                            </div>
                            <div class="photo_additional">
                                <div class="photo_privacy">
                                    <select class="form-control " name="is_private[658]">
	<option value="0" selected="">Показывать всем</option>
	<option value="1">Показывать только друзьям</option>
	<option value="2">Доступ по ссылке</option>
</select>
                                </div>
                                                            </div>
                        </div>
                    </div>
                                                        <div class="preview block" rel="659">
                        <div class="thumb">
                            <a rel="edit_list" class="ajax-modal hover_image" href="">
                                <img src="/upload/023/u2368/9/b/eab92010.jpg" title="c2e19e9d" alt="c2e19e9d" class="img-fluid ">                            </a>
                                                        <div class="actions">
                                <a class="delete" href="#" onclick="return icms.photos.remove(659)">
                                    Удалить                                </a>
                            </div>
                                                    </div>
                        <div class="info">
                            <div class="title">
                                <input type="text" class="form-control input" name="photos[659]" value="c2e19e9d">                            </div>
                            <div class="photo_content">
                                <textarea class="textarea form-control" id="content[659]" name="content[659]"></textarea>                            </div>
                            <div class="photo_additional">
                                <div class="photo_privacy">
                                    <select class="form-control " name="is_private[659]">
	<option value="0" selected="">Показывать всем</option>
	<option value="1">Показывать только друзьям</option>
	<option value="2">Доступ по ссылке</option>
</select>
                                </div>
                                                            </div>
                        </div>
                    </div>
                                                        <div class="preview block" rel="660">
                        <div class="thumb">
                            <a rel="edit_list" class="ajax-modal hover_image" href="">
                                <img src="/upload/023/u2368/b/9/dd46bed7.jpg" title="03e86aa8" alt="03e86aa8" class="img-fluid ">                            </a>
                                                        <div class="actions">
                                <a class="delete" href="#" onclick="return icms.photos.remove(660)">
                                    Удалить                                </a>
                            </div>
                                                    </div>
                        <div class="info">
                            <div class="title">
                                <input type="text" class="form-control input" name="photos[660]" value="03e86aa8">                            </div>
                            <div class="photo_content">
                                <textarea class="textarea form-control" id="content[660]" name="content[660]"></textarea>                            </div>
                            <div class="photo_additional">
                                <div class="photo_privacy">
                                    <select class="form-control " name="is_private[660]">
	<option value="0" selected="">Показывать всем</option>
	<option value="1">Показывать только друзьям</option>
	<option value="2">Доступ по ссылке</option>
</select>
                                </div>
                                                            </div>
                        </div>
                    </div>
                                                        <div class="preview block" rel="661">
                        <div class="thumb">
                            <a rel="edit_list" class="ajax-modal hover_image" href="">
                                <img src="/upload/023/u2368/7/6/f7e9ae08.jpg" title="ed6c6307" alt="ed6c6307" class="img-fluid ">                            </a>
                                                        <div class="actions">
                                <a class="delete" href="#" onclick="return icms.photos.remove(661)">
                                    Удалить                                </a>
                            </div>
                                                    </div>
                        <div class="info">
                            <div class="title">
                                <input type="text" class="form-control input" name="photos[661]" value="ed6c6307">                            </div>
                            <div class="photo_content">
                                <textarea class="textarea form-control" id="content[661]" name="content[661]"></textarea>                            </div>
                            <div class="photo_additional">
                                <div class="photo_privacy">
                                    <select class="form-control " name="is_private[661]">
	<option value="0" selected="">Показывать всем</option>
	<option value="1">Показывать только друзьям</option>
	<option value="2">Доступ по ссылке</option>
</select>
                                </div>
                                                            </div>
                        </div>
                    </div>
                                    </div>

        
            <div class="preview_template block" style="display:none">
                <div class="thumb">
                    <a class="ajax-modal hover_image" href="">
                        <img src="">
                    </a>
                    <div class="actions">
                        <a class="delete" href="#">
                            Удалить                        </a>
                    </div>
                </div>
                <div class="info">
                    <div class="title">
                        <input type="text" class="form-control input" name="" value="" placeholder="Название фотографии">                    </div>
                    <div class="photo_content">
                        <textarea id="" class="textarea" name=""></textarea>
                    </div>
                    <div class="photo_additional">
                        <div class="photo_privacy">
                            <select class="form-control " name="">
	<option value="0" selected="">Показывать всем</option>
	<option value="1">Показывать только друзьям</option>
	<option value="2">Доступ по ссылке</option>
</select>
                        </div>
                                            </div>
                </div>
            </div>

            
            <div id="album-photos-uploader"><div class="qq-uploader"><div class="qq-upload-drop-area" style="display: none;"><span>Перетащите файлы сюда, чтобы загрузить</span></div><div class="qq-upload-button" style="position: relative; overflow: hidden; direction: ltr;">Выбрать и загрузить<input multiple="multiple" type="file" name="file" style="position: absolute; right: 0px; top: 0px; font-family: Arial; font-size: 118px; margin: 0px; padding: 0px; cursor: pointer; opacity: 0;"></div><ul class="qq-upload-list"></ul></div></div>

            <script type="text/javascript">
                var LANG_SELECT_UPLOAD = 'Выбрать и загрузить';var LANG_DROP_TO_UPLOAD = 'Перетащите файлы сюда, чтобы загрузить';var LANG_CANCEL = 'Отменить';var LANG_ERROR = 'Ошибка';                icms.photos.createUploader('/photos/upload', function(){
                    var _album_id = $('#album_id').val();
                    if(!_album_id){
                        icms.modal.alert('Выберите  для загрузки фото');
                        return false;
                    }
                    this.params = {
                        album_id: _album_id
                    };
                });
            </script>

        
    </div>

</fieldset>`

То всё сохраняется норм. Не подскажете как поправить это?
