### ISSUE TITLE
Отзывы

### ISSUE THREAD

**Issue by iton1** [instantsoft/icms2#1373]
**Используемая версия InstantCMS**: InstantCMS 2.14.3

Добавить в InstantCMS 2* отзывы как в "Каталог дополнений", возможность заменить комментарии на отзывы. Владелец сайта будет выбирать, что ему оставить комментарии или отзывы на странице или как дополнение в отдельной вкладке как в "Каталог дополнений".

![изображение](https://user-images.githubusercontent.com/17750649/140971967-b9895191-0b76-4a82-b4a2-41976e231788.png)

**Comment by fuzegit** [comment]
Напишите фразы "отзывы" в настройках и будут отзывы. Отдельного дополнения "отзывы" в комплекте не планируется. Если нужно что-то узко-специализированное, в каталоге дополнений есть соответствующие компоненты.

![Выделение_009](https://user-images.githubusercontent.com/13233234/140984481-9d3d1084-40de-46e7-8dc6-2895224e294b.jpg)
