### ISSUE TITLE
Адаптивность окна сообщении и всплывающее окно

### ISSUE THREAD

**Issue by Maratakziaplus** [instantsoft/icms2#138]
Возможно ли сделать окно личных сообщении адаптивным? В данный момент практически невозможно пользоваться им на мобильных устройствах. Так же было бы лучше, если бы появлялось всплывающее окно со звуковым сопровождением о входящем сообщении. В данный момент пока не перезагрузишь страницу, не увидишь входящие сообщения. Идеальный вариант, получать сообщения во всплывающем окне, независимо от того, находишься на сайте или нет.

**Comment by fuzegit** [comment]
> Идеальный вариант, получать сообщения во всплывающем окне, независимо от того, находишься на сайте или нет.

если открыто окно переписки, а бразуер свернут, то десктоп уведомления есть

**Comment by vlad7090** [comment]
а если закрыто окно сообщений и браузер свернут? было бы отлично, если бы также были пуш уведомления.

**Comment by fuzegit** [comment]
При закрытом очевидно ничего не приходит. В любом случае это не первоочередная задача.

**Comment by Maratakziaplus** [comment]
А как быть с адаптивностью?

**Comment by fuzegit** [comment]
> А как быть с адаптивностью?

Странный вопрос. Вам нужно срочно дать решение?
Написали пожелание - молодцы, мы увидели.
