### ISSUE TITLE
 Виджеты и страницы - Пользовательские - виджеты с других страниц

### ISSUE THREAD

**Issue by iton1** [instantsoft/icms2#1381]
**Используемая версия InstantCMS**: InstantCMS 2.14.3

**Как воспроизвести проблему**:

Создаю новую страницу "тест 1" в разделе " Виджеты и страницы" во вкладке "Пользовательские", но там видны виджеты с  других страниц:

![изображение](https://user-images.githubusercontent.com/17750649/145472208-cd6b154d-b2bc-4189-8438-cdfc0be6a26b.png)

Создал страницу "тест 2" а там виджеты с других страниц:

![изображение](https://user-images.githubusercontent.com/17750649/145472427-2f5386ed-417c-40f5-b552-b49eb06b4adc.png)

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
https://instantcms.ru/novosti/release2143.html#comment_117230

https://instantcms.ru/upload/012/u1205/6/e/6e24e55b.jpg
