### ISSUE TITLE
Не отображаются все наборы на малом разрешении

### ISSUE THREAD

**Issue by Yar-rus** [instantsoft/icms2#1382]
**Используемая версия InstantCMS**: ВЕРСИЯ 2.14.3

Например,смотрим демосайт на десктопе, раздел статьи - отображаются все пять наборов: Все, Рецензии, Переводы, Выбор редакции, Рейтинг

На смартфоне отображаются только два первых набора. 

На десктопе проблему можно увидеть в режиме консоли, уменьшив разрешение и перезагрузив.

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
> На смартфоне отображаются только два первых набора.

Свапьте вправо и увидите остальные.
