### ISSUE TITLE
Видимость наборов на мобильном

### ISSUE THREAD

**Issue by Yar-rus** [instantsoft/icms2#1383]
Предложение сделать так, чтоб посетитель сайта через мобильное устройство, смог догадаться, что наборов на странице более, чем два. Это, либо показывать часть следующей кнопки, либо дать возможность показывать все кнопки.
Опросил несколько человек - никто не догадался сделать свайп. В том числе и я.
Например так:
![2021-12-14_14-59-47](https://user-images.githubusercontent.com/25885167/145995417-4bb7996a-41f5-43fd-9cd1-92af4583a338.png)

**Comment by Panda58dev** [comment]
Имхо лучше сделать стрелку ( > ) как для слайдера, так будет и удобней и очевидней.
