### ISSUE TITLE
Инфобар не отображает всё содержимое на мобильном

### ISSUE THREAD

**Issue by Yar-rus** [instantsoft/icms2#1384]
В настройках ТК вставляем код социальных кнопок в соответствующее поле. Но в малом разрешении содержимое поля info_bar не отображается целиком.

Возможное решение: показывать содержимое в несколько строк.

![2021-12-16_11-31-19](https://user-images.githubusercontent.com/25885167/146337154-600c316f-0140-4186-8ca2-c16f70e6b5d4.png)

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
> Но в малом разрешении содержимое поля info_bar не отображается целиком.

А вы обновите страницу после изменения размеров браузера.

**Comment by Yar-rus** [comment]
Обновил, ничего не изменилось. На смартфоне также.

**Comment by Panda58dev** [comment]
![image](https://user-images.githubusercontent.com/71038326/146534444-7fcf8ad1-0bc2-4f64-a84f-c15031649b0b.png)
Тоже самое происходит, но при этом появляются "точки", нажатие на них ничего не даёт.

**Comment by Yar-rus** [comment]
Точки это в настройках самого яндексовского модуля. там по умолчанию выводятся три, остальные при нажатии. Я поставил больше просто, поэтому у менЯ без точек.

Тут стоит отметить, что этот инфобар и без яндексовского модуля обрезает содержимое. Если имя пользователя и дата это не так страшно, но вот звездочки...
![2021-12-17_17-06-34](https://user-images.githubusercontent.com/25885167/146556479-7d0d5ebe-ef00-4182-a37a-97fbd4f5d463.png)

**Comment by Yar-rus** [comment]
Предложение такое. Текст и звездочки это одна строчка, блок для социальных кнопок следующая.
Дата и автор после них. Это вообще техническая информация и было бы хорошо их показ иметь возможность вообще  отключать.

**Comment by Panda58dev** [comment]
> Точки это в настройках самого яндексовского модуля. там по умолчанию выводятся три, остальные при нажатии.

Так всё бы хорошо, да вот только я использую не яндекс-кнопки, а статические ссылки. Точки добавляет CMS
> Текст и звездочки это одна строчка, блок для социальных кнопок следующая.

Ну хз-хз, имхо это будет не очень красиво. Как по другому реализовать - без понятия. Может быть сделать кнопку `Поделиться` при нажатии на которую будет открываться модальное окно с кнопками соц. сетей.  Ну и если на то пошло, располагаться эта кнопка должна слева от колокольчика (имхо).

**Comment by Yar-rus** [comment]
Тогда здесь не важно, кто добавляет, главное, что обрезает...
Лучше, когда кнопки Поделиться видны, тогда на них больше тычут.

**Comment by Panda58dev** [comment]
>  "... тогда на них больше тычут"

Но перегруженный интерфейс - тоже плохо. Вообще надо к UX дизайнерам за ответом обращаться.

**Comment by Yar-rus** [comment]
За легким интерфейсом это к яндекс турбо )) А лично мне нужны хорошо видные кнопки, а сэкономлю я на чём-нибудь другом.

**Comment by Panda58dev** [comment]
Лично я считаю, что принцип "мне надо, а вы сделайте" не правильно :)
Если делать, то универсально.

**Comment by Yar-rus** [comment]
Вы считаете абсолютно правильно! ) А я высказал свою точку зрения. Перечислять другие точки я не стал...

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/b6679077787cf91d0fefe1e6dafcb2719453b831

**Comment by Panda58dev** [comment]
@fuzegit Благодарю за коммит :)
