### ISSUE TITLE
Значение по-умолчанию в виджетах. Баг

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#1385]
**Используемая версия InstantCMS**: 2.14.3

**Версия PHP**:  7.4

Не знаю, с какой версии это случилось, раньше было всё нормально. А теперь значения по-умолчанию прибиты гвоздями, значения опций не применяются.

![0](https://user-images.githubusercontent.com/16401582/147472085-d284196c-47aa-430c-94a8-245a090cc0fb.jpg)

Вот здесь если написано 10, то при изменении опций шаблона всё равно останется 10. Из-за этого перестали настраиваться многие виджеты, где раньше было оказано это значение по-умолчанию. Проверено на нескольких сайтах на множестве виджетов.

Спасибо.

**Comment by fuzegit** [comment]
Работает, как работало.
Метод getOption ищет в опциях и если такого ключа нет или он пустой, то возвращается второй параметр.

**Comment by fuzegit** [comment]
Проверил, всё работает как надо.

![Выделение_014](https://user-images.githubusercontent.com/13233234/147477836-aa618f20-6a04-4640-a090-09c7061e678e.jpg)
![Выделение_015](https://user-images.githubusercontent.com/13233234/147477838-5d7bcb93-7268-4f4b-a22f-f6f7dfa53f7b.jpg)
![Выделение_016](https://user-images.githubusercontent.com/13233234/147477839-e9a885d7-1182-434f-82e2-6ba994088df5.jpg)

**Comment by asnenne** [comment]
Странно, конечно. У Вас работает, а у меня не работает. Ну ладно.

**Comment by asnenne** [comment]
Ага, вот в чем подвох, дошло. Это про чекбоксы. Если чекбокс не отмечен, то там пусто и подставляется значение по-умолчанию. Наверное, вместо единицы надо что-то другое писать. В каких-то еще полях сталкивался.

В общем, раньше было не так. Раньше работало таким образом, что это значение по умолчанию применялось только в том случае, если с этой опцией еще не сохранили. А потом применялись опции из настроек. А сейчас, получается, если поле не заполнено, то берется это значение? А если нам надо оставить значение пустым?

**Comment by asnenne** [comment]
Было удобно при обновлениях, если поля новые в опциях появлялись. После обновления всё продолжало работать без ошибок даже без пересохранения. А если надо - пересохранили и применилось то, что сохранили. А теперь нифига так не выйдет.

**Comment by asnenne** [comment]
Видимо не отсутствие ключа проверяется, а и пустое значение тоже.

**Comment by asnenne** [comment]
> Метод getOption ищет в опциях и если такого ключа нет или он пустой, то возвращается второй параметр.

Да, вот про это я и говорю. Иногда надо по-умолчанию указать значение, но сохранить пустое поле. Если нет ключа - вот с этим согласен. А если пустое значение - здесь не согласен.

**Comment by fuzegit** [comment]
Такс, что-то я невнимательный стал, об опциях полей говорил)

В виджетах всё корректно, во всяком случае в текущей версии с гита

https://github.com/instantsoft/icms2/blob/master/system/core/widget.php#L57

**Comment by asnenne** [comment]
Может быть, 2.15 не ставил, не проверял. В 2.14.3 есть такая проблема. Если поле не заполнено, то тянет значение по-умолчанию.

**Comment by fuzegit** [comment]
В 2.14.3 точно так же
https://github.com/instantsoft/icms2/blob/2.14.3/system/core/widget.php#L57

**Comment by fuzegit** [comment]
А, всё понятно, в значении в options null.

Поправлю в общем.

**Comment by asnenne** [comment]
Да, вот это
`return $value !== null ? $value : $default;`

**Comment by fuzegit** [comment]
```php
public function getOption($key, $default = false){

    $is_array = strpos($key, ':');

    if ($is_array === false){
        $value = array_key_exists($key, $this->options) ? $this->options[$key] : $default;
    } else {
        $value = array_value_recursive($key, $this->options);
        if($value === null){
            $value = $default;
        }
    }

    return $value;
}
```
/system/core/widget.php

**Comment by asnenne** [comment]
Да я у себя поправил. Люди жалуются, что опции не работают.

**Comment by asnenne** [comment]
Спасибо.
