### ISSUE TITLE
Некорректный УРЛ в наборах, если задан редирект ТК в файле remap.php

### ISSUE THREAD

**Issue by facepoint** [instantsoft/icms2#1387]
**Используемая версия InstantCMS**: 2.14.3

**Версия PHP**:  7.2
**Версия MySQL/MariaDB**:  5.5.56

**Как воспроизвести проблему**:

Создать ТК
В файле remap.php задать редирект на другой адрес
Создать два набора, чтобы были активные
Перейти по второму набору - выдаст 404 ошибку

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: неизвестно, так как нужен FTP

**Comment by fuzegit** [comment]
Проверил, всё корректно.

![Выделение_021](https://user-images.githubusercontent.com/13233234/147760609-4a1c5a77-0211-4e44-b4df-64b3b432e88d.jpg)
![Выделение_022](https://user-images.githubusercontent.com/13233234/147760612-5b82f330-b5c2-4c45-8cbd-bd00d0d4c5da.jpg)
![Выделение_023](https://user-images.githubusercontent.com/13233234/147760614-2ee3dc0f-f658-4ed1-9fd1-449b98f1c5ca.jpg)
