### ISSUE TITLE
Шаблон

### ISSUE THREAD

**Issue by andrewua85** [instantsoft/icms2#1388]
Я не знаю, а точнее не смотрел все ваши изменения в шаблоне Modern с предыдущей версии до 2.15.0, но убить Шаблон вы постарались на славу. Советую вам хорошенько потестить его и поглядеть внимательно своими глазками. А то так нельзя...

**Comment by fuzegit** [comment]
Какие-то подробности будут или вы так, многозначительными намёками поговорить?
