### ISSUE TITLE
Последовательный выбор категорий

### ISSUE THREAD

**Issue by globator88** [instantsoft/icms2#139]
В малых количествах  категорий это не проблема. Но когда создали свыше 500 категорий для maps увидели что найти нужную категорию стало не так то удобна. Не говоря а пользователе который вообще не в тему. А когда создадим доску объявлении количество категорий наверно будет даже ближе к 1000.
Поэтому хотел бы увидеть в настройке типа контента вариант "последовательный выбор категорий". Полностью лишится от нынешнего варианта не хотелось бы так как у этого варианта тоже есть свои преимущества при малых количествах категорий.

**Comment by iAndroS** [comment]
Еще можно было бы прикрутить аякс выбор категорий аля "живой поиск" - было бы вообще круть и удобно. Как это сделано в яндекс-справочнике при добавлении новой организации. 
![wz2zjpl 1](https://cloud.githubusercontent.com/assets/17408903/13220514/970c392e-d9b1-11e5-8d89-1ed286c0c18e.png)

**Comment by globator88** [comment]
Это вообще вкусняшка ))

**Comment by iAndroS** [comment]
Конечно, вкусняшка... Вообще, в инстанте слишком много полей при добавлении контента, соответственно, неопытные пользователи или мобильные пользователи,коих сейчас реальное большинство, испытывают массу неудобств. Я специально тестирую многие моменты на своем мобильнике, но у меня он с большим экраном, и все равно очень много дискомфорта.

**Comment by fuzegit** [comment]
> Вообще, в инстанте слишком много полей при добавлении контента, соответственно

их ровно столько, сколько вы указали показывать в настройках.

Не знаю, понравится решение или нет, но оно уже есть.

![select cat](http://storage1.static.itmages.com/i/16/0327/h_1459115052_9769984_bd88765fe2.png)

![select custom cat](http://storage2.static.itmages.com/i/16/0327/h_1459115053_4802839_10e979cb91.png)
