### ISSUE TITLE
Не выводится список похожих новостей

### ISSUE THREAD

**Issue by goldman-sax** [instantsoft/icms2#1393]
Последние новости в виджете выводятся, переключаем на похожие - виджет не выводится.
Проверил на сайте обновлённом до последней версии (там всё было настроено и перестало выводиться), так же на сайте последней версии установленном с нуля и на демо сайте. Везде повторяется.

Используемая версия InstantCMS: 15.1
Воспроизводится ли проблема на демо https://demo.instantcms.ru/: ДА

**Comment by fuzegit** [comment]
Всё выводится.

![Выделение_008](https://user-images.githubusercontent.com/13233234/151317251-0456b536-06a0-4240-b84c-7b26f725af04.jpg)
