### ISSUE TITLE
Логотип в Modern

### ISSUE THREAD

**Issue by deemon-74** [instantsoft/icms2#1396]
**Используемая версия InstantCMS 2.15.1

В настройках шаблона modern есть функция замены логотипа, там прописано: Загрузите основной логотип В растровом формате
Или выберите основной логотип в SVG.
Но при загрузке SVG выводится сообщение: Файл имеет неподходящий формат. Допустимые типы файлов: jpg, png, gif, webp.
При загрузке указанных в сообщении форматов создаётся только пресет логотипа, логотип при этом не меняется, загрузка его в папку /templates/modern/images/ не происходит (даже если на папке права 777).

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: не тестировал. Тестировалось на 3-х сайтах.

**Comment by fuzegit** [comment]
Разные поля для загрузки логотипов.
![Выделение_009](https://user-images.githubusercontent.com/13233234/151712638-a6b1cf35-29fd-4064-a8ce-641191f23b82.jpg)

> создаётся только пресет логотипа, логотип при этом не меняется

Только что проверили, всё меняется. Если логотип выводится при помощи соответствующего виджета и в его настройках не задан иной.

> загрузка его в папку /templates/modern/images/ не происходит

И не должна. Фото грузятся в директорию upload.
