### ISSUE TITLE
Доработка свойств и типов полей АВТОПОИСКом

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#140]
На форуме уже писали, решил здесь дописать, может успеется добавить в 2.4.1, т.к фишка очень удобная и нужная для удобного поиска по каталогу по характеристике

В 1 ветке инстанта было http://www.instantcms.ru/upload/forum/6215ddd412d63d48e718cf68e36fc6bb.jpg.jpg

и в списке товаров показывалось http://www.instantcms.ru/upload/forum/2a9cc4168b1f4d61093d78ec0603dcd0.jpg.jpg

для второй ветки очень было бы полезна такая опция.

**Comment by globator88** [comment]
Vlad, это когда варианты становится ссылками да? При нажатии показывается материалы на которых оно добавлена.
Если так то незаменимая функция для каталога. Хотел бы создать раздел на сайте для любителей фильмов. Добавить жанр, имя актера и т. Вариантов много на самом деле.

**Comment by vlad7090** [comment]
совершенно верно. тем самым легко становится делать поиск по отдельно взятой характеристике

**Comment by vlad7090** [comment]
при чем такое надо делать не только с полями, но и свойствами, что позволит делать удобную фильтрацию и поиск нужной информации.
