### ISSUE TITLE
Notice Undefined index: category_id при назначении связей

### ISSUE THREAD

**Issue by Igor-san** [instantsoft/icms2#1401]
**Используемая версия InstantCMS**: 2.15.1

**Версия PHP**:  7.4.26
**Версия MySQL/MariaDB**:  8.0.17

**Как воспроизвести проблему**:

1) Устанавливаем демо
2) Включаем отладку
3) Для типа контента Страницы создаем связь Объявления
4) Привязываем объявление к странице (новые или имеющиеся)
5) Открываем подробности объявления (например /board/7-prodam-kvartiru-v-novostroike.html)

получаем 
`Notice
: Undefined index: category_id in
D:\AppServ\www\108.icms.local\system\controllers\content\model.php
on line
1741`

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: НЕТ (нужна настройка связей)

**Comment by fuzegit** [comment]
Уже исправлено коммитами ранее
https://instantcms.ru/novosti/release2151.html#comment_117924
