### ISSUE TITLE
Баг компонента "Контент"

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#1404]
**Используемая версия InstantCMS**: 2.15.1

Не могу говорить со 100% уверенностью, но порядок действий был такой:

1. Создал тип контента.
2. При создании включил категории, настроил и сохранил.
3. После сохранения отключил категории, так как передумал их использовать.
4. Добавил записи.

Не показываются записи в разделе "Контент" админки именно для этого типа контента.

Временно исправил закомментированием этой строки:
https://github.com/instantsoft/icms2/blob/f0b27ae6827fa34bc8f4b0d43c912a1949f85fff/system/controllers/admin/actions/content_items_ajax.php#L15

Но это временное решение, проблема в чем-то глубже.

**Comment by asnenne** [comment]
Наверное уже решено, пусть повисит пока. Про проблему в админке пока не видел.

**Comment by fuzegit** [comment]
> Временно исправил закомментированием этой строки

У вас передаётся видимо из кук id выбранной, **удалённой** категории. Выключение категорий в настройках не ведёт к исчезанию из их списка. 
Пока что не могу никак повторить.
