### ISSUE TITLE
XSS store in nickname paramerter when install

### ISSUE THREAD

**Issue by Nguyen-Trung-Kien** [instantsoft/icms2#1405]
Hi team, when i install i will check xss in it and it so bad when i found xss store in this
look that
![image](https://user-images.githubusercontent.com/65381453/154296268-31914d92-e939-47f6-9c63-d19d512b48a7.png)

and result

![image](https://user-images.githubusercontent.com/65381453/154296334-d4e4da32-da8f-465c-805a-dc4298b2939e.png)

it's so bad, please fix it

**Comment by fuzegit** [comment]
We'll fix it of course, but who in their right mind would do that when installing their own site?

**Comment by Nguyen-Trung-Kien** [comment]
I thinks it bug in your project, and i don't know who inject xss payload :))

**Comment by fuzegit** [comment]
We'll fix it, thank you.
But it's in the **CMS installer**, you understand that it's unrealistic to use this XSS.
