### ISSUE TITLE
Основной цвет (не меняется цвет)

### ISSUE THREAD

**Issue by iton1** [instantsoft/icms2#1411]
**Используемая версия InstantCMS**: InstantCMS 2.15.1

**Версия PHP**:  8.0
**Версия MySQL/MariaDB**:  MySQL 5.7.21-20

**Как воспроизвести проблему**:

 Настройки темы - Цвета - Основной цвет

Выбираю любой цвет, например красный, жму на "Сохранить и скомпилировать SCSS".
![изображение](https://user-images.githubusercontent.com/17750649/163712036-ca28af35-aeba-4465-98d6-8eb29fdb3b75.png)

В шапке сайта цвет не изменился.

![изображение](https://user-images.githubusercontent.com/17750649/163712103-a381f8fe-37cb-483e-81a4-c37f8e4106b5.png)

p.s. эта ошибка вроде и в InstantCMS 2.15.0 была.

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: Нет возможности проверить.

**Comment by fuzegit** [comment]
> В шапке сайта цвет не изменился.

А должен?

**Comment by iton1** [comment]
) ну на каких то предыдущих версиях менялся, мне показалось что так было задумано.

p.s. это было удобно.
