### ISSUE TITLE
Идеи для Модерна

### ISSUE THREAD

**Issue by my-instantcms** [instantsoft/icms2#1414]
**Используемая версия InstantCMS**: 2.15.1

При создании дочернего шаблон Модерн, обнаружил? что не хватает несколько доработок:
1) При добавлении ряда/вложенного ряда, добавить возможность выбор wrappera как это было раньше при ручной создании схемы <?php $this->widgets('header', false, 'wrapper_plain'); ?>
2) При создании позиции, для шаблона колонки было бы не плохо, что бы поддержала переменные из настройки шаблона, а не только {position}
3) Не нашел возможность перемещать вложенный ряд, пришлось в БД менять поле ordering
4) Не хватает хук для работы с массовом $rows например хочу проверить есть ли виджеты в сейдбар, если нет, растянуть основной блок на 100%, для этого в $rows надо найти ряд и дать ему класс col-12. Хук render_page не подошел, так как возвращает html

**Comment by fuzegit** [comment]
1. Зачем, если это решается самим виджетом?
2. Какие переменные?
3. Вложенные ряды не перемещаются.
4. Это плохая идея, т.к. подобное в стоковом шаблоне без переназначения работает.
