### ISSUE TITLE
Виджет "Список контента" (порядок вывода списка)

### ISSUE THREAD

**Issue by goldman-sax** [instantsoft/icms2#1417]
Было бы неплохо иметь возможность сортировать список контента в виджетах по заголовкам, полям, тегам и.т.п.
Также не хватает опции: пропустить в выводе одну, две, три и т.п. новости. Это надо для того, чтобы в одном виджете можно было бы вывести новости с 1 по 4, а в другом с 5 по 10.

**Comment by fuzegit** [comment]
> иметь возможность сортировать список контента в виджетах по заголовкам, полям, тегам и.т.п.
Также не хватает опции: пропустить в выводе одну, две, три и т.п. новости.

Для этого есть наборы.
