### ISSUE TITLE
Слайдер не выводит записи когда включён только один тип контента.

### ISSUE THREAD

**Issue by timtrella** [instantsoft/icms2#1422]
**Используемая версия InstantCMS**: 2.15.2

**Версия PHP**:  7.4.21
**Версия MySQL**:  5.7.33

**Как воспроизвести проблему**:

* 1 - зайти /admin/ctypes отключить все типы контента кроме например НОВОСТИ
* 2 - зайти /admin/widgets выбрать виджет СЛАЙДЕР КОНТЕНТА
* 3 - в виджете попытаться выбрать Тип контента - (Новости (там будет только этот тип))
* 4 - в виджете попытаться выбрать Категория (не получится, как и Поле изображения*, Поле краткого описания)
* 5 Попробовать сохранить (не сохраняет)
* 6 Просто закрыть и переключить внимание на вкладку с сайтом (допустим виджет на всех страницах, переходим на главную)
* 7 фронт часть наоборот позволяет выбрать тип контента из выпадающего списка при отключённых типов контента т.е Новости
* 8 Видео [по ссылке на ютубе](https://youtu.be/2Xhf3tGitO8)
**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
В слайдере до отключения вами типов контента и до всех ваших манипуляций был выбран не тип контента "Новости". Он же и остался выбранным. Весьма странно подобное записывать в баг.

Я убрал сиденья в машине - сидеть неудобно на полу и пропал регулятор наклона спинки, примерно так)
