### ISSUE TITLE
Помечать в списке поля "Категория" какие скрыты  статусом "скрыта"

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#1426]
Сейчас в админке и на фронте при добавлении записи нет никакого упоминания о том, что категория скрыта и в нее можно положить запись. 
В итоге при выводе записи, если поле категория активно, то показывается эта категория, но при клике по ней выдает 404 ошибку. 
Чтобы такого не происходило, было бы логично в поле вывода категории в записи не выводить скрытую категорию, а в списке выыбора категории для записи скрытые категории отмечать соответствующим статусом.

**Comment by Panda58dev** [comment]
@vlad7090, не обнаружил вашей проблемы: создал категорию , скрыл её, создал в ней запись. В родительской категории ссылка на скрытую не появляется, но если включить опцию `Показывать записи из подкатегорий внутри родительской категории`:
![изображение](https://user-images.githubusercontent.com/71038326/189986622-4e784e30-13f2-410a-a0ac-c0376cc395e7.png)
то запись из скрытой категории отображается. 

Что ещё за поле "категория"?

**Comment by vlad7090** [comment]
Есть системное поле "Категория". Если его вывести, то в нем показываются и скрытые категории, в которой может размещаться запись. Но при этом, при клике на категорию показывается 404 ошибка, так как категория скрыта. А какая категория скрыта в админке не видно, так как никак не отображается этот момент.
