### ISSUE TITLE
Убрать приведение строки к нижнему регистру при добавлении тегов

### ISSUE THREAD

**Issue by godyrev** [instantsoft/icms2#1428]
Убрать в 30-й строке файла **/system/controllers/tags/model.php** приведение строки к нижнему регистру перед сохранением в базе данных.

**Comment by fuzegit** [comment]
Зачем?

**Comment by godyrev** [comment]
Люди хотят сами решать, как будут отображаться теги - https://instantcms.ru/forum/kak-sdelat-tegi-zaglavnymi-bukvami.html#post-352634

**Comment by fuzegit** [comment]
Для частных случаев тег можно переименовать в админке.

**Comment by godyrev** [comment]
Нельзя. Всё по-кругу и опять на mb_strtolower.
