### ISSUE TITLE
Завести аналогичный сервис для премиум-компонентов

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#143]
Предлагаю завести гит-сервис для мапса, биллинга и других премиум-компонентов.

**Comment by nomad48** [comment]
Поддерживаю. Не помешало бы такое нужное дело.

**Comment by pin-git** [comment]
Для премиум в гит-репозитарии использовать только сервис Issues?! Как вы себе это представляете? По мне так это будет похоже на обычный форум в одну ветку

**Comment by fuzegit** [comment]
Зачем? Исходный код для премиум компонентов очевидно выкладываться не будет.

**Comment by nomad48** [comment]
> Зачем? Исходный код для премиум компонентов очевидно выкладываться не будет.
Просто найденные ошибки можно тут аккумулировать и обсуждать, и заодно будет видно когда их решат.

**Comment by iAndroS** [comment]
@fuzegit Но ведь код не весь закрыт, только лицензирующие файлы? Или не так? Просто делают люди улучшения мапса и шопа (по крайней мере судя по единичке), почему бы не прибегнуть к их помощи здесь?

**Comment by fuzegit** [comment]
> Просто найденные ошибки можно тут аккумулировать и обсуждать, и заодно будет видно когда их решат.

как вы увидите, если кода не будет?

> Просто делают люди улучшения мапса и шопа
делают, не правя основной код.

**Comment by iAndroS** [comment]
Тогда предлагаю другой вариант - офсайт планирует переезжать на двойку? Даже если нет, то на поддомене сделать свой аналог реформала для премиумовили может даже для всех разработок сообщества. Очень все же важно иметь представление о том, что из твоих или чужих хотелок запланировано или в разработке, да и обратная связь с разработчиком явно будет видна, что идет на пользу проекту

**Comment by nomad48** [comment]
> как вы увидите, если кода не будет?

Ну Вам видней.
