### ISSUE TITLE
Зависимость показа/скрытия полей от значения "родительского поля"

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#1430]
Было бы здорово иметь возможность как в наборах при работе с полями, когда можно было бы задать поведение показа/скрытия полей, в зависимости от значения или заполненности других полей. 

Например надо скрыть поле photo если заполнено поле video
Либо надо скрыть поле photo при условии, что значение поле status="1" и т.д

Так можно было бы удобно управлять показом полей в зависимости от значения других полей.

**Comment by fuzegit** [comment]
![Выделение_005](https://github.com/user-attachments/assets/c878a8bd-5ea3-4c5f-ac44-08c174296e6f)
