### ISSUE TITLE
Поле "Конструктор списков" + Фильтры (вкладка)

### ISSUE THREAD

**Issue by iton1** [instantsoft/icms2#1433]
**Используемая версия InstantCMS**: 2.15.2

Есть такое дополнение "Поле «Конструктор списков»" https://addons.instantcms.ru/addons/unilist.html после его установки, переходим во вкладку "Фильтры" и создаем страницу,

![изображение](https://user-images.githubusercontent.com/17750649/200306610-883ddc57-fad9-4416-9a0c-f08acaa1868f.png)

 при создание страницы в "Фильтры полей" этого поля нет.

![изображение](https://user-images.githubusercontent.com/17750649/200309636-defb1e19-acf3-4f71-82d6-bdedee42191c.png)

На странице блога https://instantcms.ru/blogs/kladovka-kodera/pole-konstruktor-spiskov.html автор говорит что это не проблема в поле.

На видео его комментарий:  https://youtu.be/R4u3MYPsX2o да он рассказал как это можно исправить.

Это предложение, может найдется какой то компромисс в данном вопросе.

**Comment by fuzegit** [comment]
> автор говорит что это не проблема в поле

Это проблема в поле. О чём сам автор же и говорит, меняя **свое** же поле. И да, для фильтра поле должно создавать индекс. Автор любит говорить, что проблема в чём угодно, но не у него.
