### ISSUE TITLE
Статистика посещаемости в админке

### ISSUE THREAD

**Issue by goldman-sax** [instantsoft/icms2#1437]
Для развития сайта очень важно знать на какие страницы заходят часто, а какие страницы посетителям неинтересны. В типах контента есть опция "Считать количество просмотров", но у нее есть большой недостаток - то, что вижу я, то видно всем. Включу я её, и увидят все. Нужен вариант, когда пользователям статистика не отображается, а вот при заходе в админку в раздел "Контент" можно было бы посмотреть на какие страницы сколько заходов, с возможностью сортировки по количеству просмотров.
Изначальный механизм статистики есть, остается немного допилить, чтобы у админа был хороший инструмент для развития сайта.

**Comment by my-instantcms** [comment]
Если вдруг интересует платное решения, можно реализовать с помощью этого дополнения https://my-instantcms.ru/catalog/41-reklamnye-bannery.html 
Просто создаете невидимый баннер и получите статистику по периодам Сегодня, Вчера, Неделя, Месяц, За все время.
А так же тип устройства ПК/Мобил, Город, IP, Браузер и т.д.

**Comment by makartsoft** [comment]
Поддержу, актуально!

**Comment by fuzegit** [comment]
![Выделение_080](https://github.com/instantsoft/icms2/assets/13233234/afe6b794-d9c5-410c-92f9-f0a0d4813ff6)

![Выделение_081](https://github.com/instantsoft/icms2/assets/13233234/bd182841-d564-47bc-a4f4-236ebaba12c5)
