### ISSUE TITLE
Хлебные крошки и правильные ссылки для связей

### ISSUE THREAD

**Issue by pumpuic** [instantsoft/icms2#1438]
InstantCMS**: 2.x
По следам [данного](https://instantcms.ru/forum/kak-pravilno-privjazat-tipy-kontenta-drug-k-drugu.html) топика, хотелось бы видеть в глубиномере и ссылке всю цепочку от начала и до конца, т.е. от родителя до последнего привязанного к нему ТК, сейчас этого нет, при переходе к последнему привязанному ТК родитель просто исчезает, его можно только вывести отдельно виджетиком но с точки зрения сео это неправильно да и в целом логика нарушается, более детально описал на форуме.
Спасибо.
Область применения: например страна(ТК) / город(ТК) / достопримечательность(пост) и т.д.

**Comment by fuzegit** [comment]
> и ссылке всю цепочку от начала и до конца

ссылка изменить не получится.

В лучшем случае глубиномер. Однако, как быть если:
- родителей более одного
- если переходят к записи не со связи

**Comment by lakomet** [comment]
Однако, как быть если:
> 
> * родителей более одного

Если родителей более одного, то всё остаётся как есть сейчас, если родитель один, то формируем крошки как предлогает ТС.
Больше одного родителя для записи думаю редко используется, я например не могу придумать ни одного варианта использования связей, где у записи больше одного родителя.

**Comment by pumpuic** [comment]
> ссылка изменить не получится.

жаль, было бы очень хорошо для сео.

> В лучшем случае глубиномер. Однако, как быть если:
>     * родителей более одного
может позволить где-то сделать выбор, кто из родителей главный, если их несколько? Тут поддержу lakomet. 

>     * если переходят к записи не со связи
Выводить весь путь вместе со связью т.к. у записи есть родитель, он должен быть везде виден иначе не совсем понимаю смысл от данного родителя, он вроде бы и есть а по-факту его нигде нет.

**Comment by fuzegit** [comment]
Как-то так.

![Выделение_002](https://github.com/user-attachments/assets/92e434cd-9fe0-4bac-9ada-5382b3683576)
![Выделение_003](https://github.com/user-attachments/assets/0d08df1d-2b66-48d8-a28d-e80545fbdb49)
![Выделение_004](https://github.com/user-attachments/assets/0696ac0a-3332-4fa9-917e-bf6b620d0c14)
