### ISSUE TITLE
Добавление контента в группы

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#144]
Предлагаю для админов групп разрешить указывать категории типов контента собственно для этих групп и разрешенные глобально админом сайта в настройках групп типы полей.
Добавление же контента сделать по примеру реформала плюс одноклассники - выпадающий список категорий контента, где при выборе определенной категории под полем текста/анонса компактно подгружаются снизу иконки или сами поля, которые были запланированы админом группы.

**Comment by iAndroS** [comment]
Дополню еще как вариант решения данной проблемы:
Можно было бы админам при редактировании группы разрешить создавать собственные типы контента внутри этой группы. Единственное, возможно, не все поля разрешить, но тут думать надо. А так было бы круто!

**Comment by klubnik** [comment]
Плюсую, что можно было бы сделать привязку, то есть разрешить или запретить использовать те или иные типы контента в группах. Достаточно галочек как это сделано в вк. 

По остальному не понял вообще.
