### ISSUE TITLE
Проблемы с системной очередью

### ISSUE THREAD

**Issue by Risgit** [instantsoft/icms2#1445]
**Используемая версия InstantCMS**: 2.15.2

**Версия PHP**:  8.1
**Версия MySQL/MariaDB**:  10.5.18

**Как воспроизвести проблему**: Неизвестно. Проблема случается раз в год.

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: НЕТ

Почему-то в таблице cms_jobs оказываются строки с поврежденным полем playload. И тогда рассылка писем по системной очереди останавливается и задачи очереди начинают скапливаться в таблице cms_jobs.
Можно ли сделать так, чтобы системная очередь не останавливалась на поврежденных строках, а игнорировала их и продолжала работу?

Вот описание, как приходится решать данную проблему (уже в третий раз):
https://instantcms.ru/forum/ne-hochet-rabotat-sistemnaja-ochered.html#post-350289

**Comment by fuzegit** [comment]
После этой строки https://github.com/instantsoft/icms2/blob/master/system/core/queue.php#L92 надо вставить return false; и проблема решится. Однако, хотелось бы знать, почему возникает ошибка при json_decode. Вероятно, не помещается текст в колонку playload, хотя не очень понимаю, что туда можно записать, чтобы не поместилось в 64 кб.

**Comment by Risgit** [comment]
Причем пустое оказывается не всё поле playload, а именно params.

**Comment by fuzegit** [comment]
params возникает после json_decode
