### ISSUE TITLE
Ошибка в form_ctypes_basic.php on line 512 на php 8.1

### ISSUE THREAD

**Issue by makartsoft** [instantsoft/icms2#1449]
**Используемая версия InstantCMS**: 2.15.2
**Версия PHP**:  8.1
**Как воспроизвести проблему**:

* В типе контента, например "новости", присваеваем одну и туже группу разным полям (например, для поля "Заголовок новости" и "Фотография" делаем группу "Изображение".
* Включаем режим отладки;
* В настройках типа контента /admin/ctypes/edit/10  в нижнем блоке "Сворачиваемые блоки в форме создания/редактирования записи" получаем ошибку `"Deprecated: md5(): Passing null to parameter #1 ($string) of type string is deprecated in /home/d44/ВАШ САЙТ/WWW/system/controllers/admin/forms/form_ctypes_basic.php on line 512"`

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: невозможно проверить, т.к. там php7

**Comment by fuzegit** [comment]
В текущей версии здесь этой проблемы уже нет, механизм переделан в связи с мультиязычностью.
