### ISSUE TITLE
БАГ - неправильное поведение виджетов при наличии в URL UTM-метки

### ISSUE THREAD

**Issue by Jestik** [instantsoft/icms2#1459]
**Используемая версия InstantCMS**: 2.15.2

**Версия PHP**:  7.4
**Версия MySQL/MariaDB**:  

**Как воспроизвести проблему**:

* Для любого типа контента создаем виджет для показа в списке записей
![Image 4](https://user-images.githubusercontent.com/16486858/231662448-e77d6b28-fac8-4a7d-bd4d-bdbf9d88fa34.jpg)
*При переходе из соц сетей или любом другом варианте когда добавляется UTM метка, виджет отображается на странице просмотра записи
![Image 1](https://user-images.githubusercontent.com/16486858/231662607-8edb8646-62e6-4286-9a74-8eb194a430ad.jpg)
![Image 2](https://user-images.githubusercontent.com/16486858/231662640-2a450866-4384-4e8e-86c0-7fbca17eddd6.jpg)
![Image 3](https://user-images.githubusercontent.com/16486858/231662655-f7c853e8-761c-4279-9c3c-7c01f3a80e4a.jpg)

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
Это не баг.
Внесите в страницу "Просмотр списка" отрицательную маску
`posts/*.html?*`
И всё будет нормально.
