### ISSUE TITLE
Мультиязычность в ICMS 2

### ISSUE THREAD

**Issue by facepoint** [instantsoft/icms2#146]
В 1-ке была встроена, было очень удобно, что можно быстро создать мультиязычный сайт, быстро добавив в виджетах, контенте и меню нужные языки.
Есть ли возможность в 2 ке также сделать? вроде наработки в плане выбора языка при установке 2ки есть.

**Comment by fuzegit** [comment]
Пожалуйста, задавайте вопросы на форуме. Есть мультиязычность интерфейса. Полноценной мультиязычности контента нет. Реализация ее есть в долгосрочных планах.

**Comment by facepoint** [comment]
А эта наработка не имеет права на жизнь http://addons.instantcms.ru/addons/unilang.html ? вроде автор бесплатно предлагает скачать. Если реализация достойная, то может включить в коробку?

**Comment by maxicms** [comment]
Эта наработка работает на 20-30% при этом много нюансов, которые в ней вообще не реализованы.

**Comment by facepoint** [comment]
Жаль. Как же сделать двуязычность контента, виджетов, меню)

**Comment by vlad7090** [comment]
многоязычность реально актуально.

**Comment by fuzegit** [comment]
Никто не спорит. Но пока что в приоритете еще более актуальные вопросы.
Дойдем и до мультиязычности, верьте)
