### ISSUE TITLE
Крестик в гридах контента

### ISSUE THREAD

**Issue by CEH9IRUS** [instantsoft/icms2#1460]
Версия CMS:  2.15.2

Просьба добавить крестик для очистки поля поиска в гридах контента, так же как это сделано в списках компонентов.
![image](https://user-images.githubusercontent.com/83751800/231678862-ed5509ee-01b3-419b-86bf-b8d825222ea5.png)
![image](https://user-images.githubusercontent.com/83751800/231678939-8c1f39ab-317f-400e-a53f-32cc50671e88.png)

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/aa7c54d360b86ae70f87172398fc63d530684425
