### ISSUE TITLE
Очистка дополнительных категорий

### ISSUE THREAD

**Issue by Kapa6ac79** [instantsoft/icms2#1468]
**Используемая версия InstantCMS**: 2.16.0

**Как воспроизвести проблему**:

При включенной опции "Разрешить несколько категорий для одной записи" добавляем к записям дополнительные категории. Затем в админке выбираем несколько записей, в которых установлены доп. категории, и делаем действие над выделенным "Изменить записи". Выбираем поле для изменения , например "Публиковать статью на сайте" и завершаем операцию. После этого у всех выбранных записей очищается поле "Дополнительные категории".

**Comment by fuzegit** [comment]
#1480
