### ISSUE TITLE
Не закрывается окно настройки виджета при включенном режиме откладки

### ISSUE THREAD

**Issue by uzunhair** [instantsoft/icms2#147]
На демо сайте включен режим откладки, разрабатываю новый виджет. В модальном окне настроек виджета в админке режим откладки показывает что не хватает языкой константы, не обращаю внимания, настраиваю как мне нужно виджет, жму на кнопку Сохранить, но модальное окно не закрывается. На самой странице вывода виджета, виджет  работает как и был настроен, то есть проблема только в закрытии модального окна. 
![2016-02-24 16-51-58](https://cloud.githubusercontent.com/assets/3851365/13287236/0106a90c-db17-11e5-972f-7693e90d78eb.png)

**Comment by fuzegit** [comment]
> не обращаю внимания

надо обратить и создать нужную константу
