### ISSUE TITLE
Пропала кнопка "Вернутся на сайт" в мобильной версии

### ISSUE THREAD

**Issue by CEH9IRUS** [instantsoft/icms2#1471]
**Используемая версия InstantCMS**: 2.16.0

**Как воспроизвести проблему**: Переключится на мобильное разрешение

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: ДА

![image](https://github.com/instantsoft/icms2/assets/83751800/0e0d4f63-709a-4d88-8143-b364795e4b66)

Убираю из файла templates/admincoreui/admin.tpl.php **"d-sm-down-none"**
 `<li class="nav-item d-sm-down-none">
                <a class="nav-link d-flex justify-content-center text-light" href="<?php echo href_to_home(); ?>" target="_blank" title="<?php echo LANG_CP_BACK_TO_SITE; ?>" data-toggle="tooltip" data-placement="bottom">
                    <?php html_svg_icon('solid', 'share-square'); ?>
                </a>
            </li>`

![image](https://github.com/instantsoft/icms2/assets/83751800/6e4d4520-5fd3-40b2-a03e-6c96d80995ee)

И все работает. Это баг или фича? Просто очень не хватало, после обновления это началось.

**Comment by fuzegit** [comment]
> Убираю из файла templates/admincoreui/admin.tpl.php "d-sm-down-none"

Да, так и было задумано, т.к. не помещалась.

**Comment by CEH9IRUS** [comment]
> т.к. не помещалась.

Если выводить много иконок то да, а если одну как у меня на скриншоте, то все помещается.  Просьба оставить в обновлениях данную кнопку для перехода на сайт, без неё неудобно.
