### ISSUE TITLE
Вывод скриптов в футере на примере $this->head()

### ISSUE THREAD

**Issue by uzunhair** [instantsoft/icms2#148]
Для быстрой загрузки сайта рекомендуется включать скрипты перед тегом закрывающим body, часть из них можно в ручную там прописать, но как быть с скриптами привязанными к компонентам и виджетам? Предлагаю создать переменную на подобие $this->head() для футера.

**Comment by pin-git** [comment]
Однозначно нужная вещь! Необходимо разделить скрипты и стили.

**Comment by uzunhair** [comment]
Уточню, я не имел в виду чтобы все скрипты грузились в футере, я предлагаю лишь сделать возможность для подключения в футере а потом пускай кому нужно подключает.

**Comment by pin-git** [comment]
С первого взгляда задача навязывает нагромождение и практическое дублирование кода, особенно на этапе ввода. Ведь хочется что-то типа addFooterJS(). Плюс становится не функционален такой замечательный приём проверки на дубли, даже не проверки, а избавление. Ну а если оставить один массив?! То куда скидывать маркеры? 
Задачка интересна, но ещё интересней будущее решение.

**Comment by pin-git** [comment]
Первый вариант: расширяем аргументы текущих функций, разносим по массивам, при необходимости можно завести упрощённый вызов отдельной функцией с ссылкой на текущую. В footer выводим только то, чего нет в head `array_diff_key`

**Comment by Val-Git** [comment]
Поддерживаю - очень полезная вещь!

**Comment by fuzegit** [comment]
```php
// для хедера
$this->head(true, false); 
// для футера
$this->printJavascriptTags(); 
```
