### ISSUE TITLE
Ошибка в поле привязанного ТК компонента "Группы"

### ISSUE THREAD

**Issue by Sergsoon** [instantsoft/icms2#1484]
**Используемая версия InstantCMS**: 2.16.1

**Версия PHP**:  7.2.34, apache2handler
**Версия MySQL/MariaDB**:  5.7.42

**Как воспроизвести проблему**:

* в ТК "Связь с группами" разрешаем "Создание в группах"
* в группе добавляем этот ТК
* в админке заходим в редактирование поля привязанного ТК
* Параметр Настройки поля -> Стиль вывода в записи : "простой список ссылок и список типа контента" выводятся наоборот. При выборе простой список ссылок выводится  список типа контента и соответственно список типа контента - простой список ссылок
* если выбрать "сохранить изменения" выдаёт ошибку 404 Страница не найдена. Это в каждом поле при "сохранить"

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
> Параметр Настройки поля -> Стиль вывода в записи : "простой список ссылок и список типа контента" выводятся наоборот. При выборе простой список ссылок выводится список типа контента и соответственно список типа контента - простой список ссылок

Это подтверждается

> если выбрать "сохранить изменения" выдаёт ошибку 404 Страница не найдена. Это в каждом поле при "сохранить"

Сохранить где? Если параметры полей в группах - то не подтверждается.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/9397d66f57484b9d974b6639f3765ab379d56380
