### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by u32i** [instantsoft/icms2#1490]
HI,

i'm trying to report a security vulnerability by sending an email to fuze@instantcms.ru but the mail server is rejecting my email, perhaps you can enable github security advisories ? so i can report it

**Comment by fuzegit** [comment]
The mail server works correctly if you send an email from a valid email server.

**Comment by u32i** [comment]
iam sending an email from u32i@proton.me and its not delivered

**Comment by fuzegit** [comment]
I get notifications from github. The mail server is working.

![Выделение_005](https://github.com/instantsoft/icms2/assets/13233234/17e22f1c-2b20-4c7f-b2dd-d18f85174179)

**Comment by u32i** [comment]
![Screenshot_2024-01-30_10-32-42](https://github.com/instantsoft/icms2/assets/109034767/037c50a0-901a-4723-9ff2-13e30c0c265a)

**Comment by fuzegit** [comment]
For some reason, the server considers your email to be spam. Probably because of the domain.

**Comment by fuzegit** [comment]
Why on huntr can't you add a report?

**Comment by u32i** [comment]
they changed their targets back in November, they now target AI/ML project only.

**Comment by u32i** [comment]
if you enabled github advisories it will be better than email

https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/about-repository-security-advisories

**Comment by fuzegit** [comment]
Security advisories enabled
