### ISSUE TITLE
Поле "Фотография" при изменение поля "503 Сервис недоступен"

### ISSUE THREAD

**Issue by iton1** [instantsoft/icms2#1492]
**Используемая версия InstantCMS**: 2.16.2

**Версия PHP**:  7.4

**Как воспроизвести проблему**:

Поле Фотография "photo" если менять на другое поле, например: "Ссылка", "Сквозной HTML", "HTML блок в форме", "Категории контента" выдает ошибку "503 Сервис недоступен". я проверял на типах контента "Объявления" и "новости".

![изображение](https://github.com/instantsoft/icms2/assets/17750649/0512811b-cd93-4594-83a4-5fa7a357c1d6)

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: ДА

**Comment by iton1** [comment]
Еще если поле "content" (которое по умолчанию) менять на "Сквозной HTML", тоже 503 ошибка при сохранение.

Воспроизводится ли проблема на демо https://demo.instantcms.ru/: ДА

**Comment by fuzegit** [comment]
На поле "Ссылка" всё будет нормально. Проблема при смене типа поля, которое не создаёт ячейку в таблице.
