### ISSUE TITLE
В поле "Участвует в полнотекстовом поиске"

### ISSUE THREAD

**Issue by iton1** [instantsoft/icms2#1493]
**Используемая версия InstantCMS**: 2.16.2

**Версия PHP**:  7
**Версия MySQL/MariaDB**:  не знаю.

В типе контента в поле "Текст"
![изображение](https://github.com/instantsoft/icms2/assets/17750649/0614cf72-bd27-4d84-af77-505305c7def9)

выбираем (включаем) "Участвует в полнотекстовом поиске" и сохраняем, все ок.
![изображение](https://github.com/instantsoft/icms2/assets/17750649/ea1fa0bb-c439-4c3c-837a-f59ba0c6a5a7)

В этом же типе контента в другом поле "Текст HTML" или "Текст"

![изображение](https://github.com/instantsoft/icms2/assets/17750649/66284a2a-b24a-4e80-bac4-7ede75dc790d)

выбираем (включаем) "Участвует в полнотекстовом поиске" и пытаемся сохранить
![изображение](https://github.com/instantsoft/icms2/assets/17750649/21ba9f60-545d-415c-a327-d501cb96cd59)

и выскакивает ошибка
![изображение](https://github.com/instantsoft/icms2/assets/17750649/1062f1fd-4079-47a6-b486-53ef9a8dbeb9)

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
@iton1 я не могу повторить. Включите отладку и вместо "Сервис недоступен" будет текст ошибки. Если вы просто тестировали демо, то могли попасть на автоматический сброс сайта два раза в час. Локально проблема у вас воспроизводится? Где вы поймали ошибку первый раз?

**Comment by iton1** [comment]
Да, на демо сайте ошибка уже не высвечивается. 

Я у себя на сайте где была ошибка, повторяю процедуру, но ошибки тоже нет, чудеса какие то. 
Но у меня на сайте еще установлены дополнительные поля и я игрался с "Участвует в полнотекстовом поиске" и ошибка появлялась (я не знал в чем дело и почитал вот эту тему на форуме https://instantcms.ru/forum/problemy-v-uchastiem-v-polnotekstovom-poiske.html и ошибка повторилась), буду дальше наблюдать может, ошибка опять появится.
