### ISSUE TITLE
Ругается на непереданный урл в компоненте геолокации

### ISSUE THREAD

**Issue by AtlantisWebSt** [instantsoft/icms2#1494]
**Используемая версия InstantCMS**: 2,16,2

**Версия PHP**:  7,2
**Версия MySQL/MariaDB**:  5,7

сайт/admin/controllers/edit/geo/city/3161 или любой другой город
консоль отдает ошибку Uncaught SyntaxError: Invalid or unexpected token (at 3161:1924:53)
ругается что урл не передан
![2024-03-20_03-07-49](https://github.com/instantsoft/icms2/assets/91555575/df025c40-1497-4c32-ad73-cd7a548c5579)

**Comment by fuzegit** [comment]
На текущей версии с гита не могу повторить проблему.

**Comment by fuzegit** [comment]
@AtlantisWebSt сможете прояснить проблему?

**Comment by AtlantisWebSt** [comment]
установил чистую InstantCMS: 2.16.3, проблема не повторилась!
