### ISSUE TITLE
Вложенность основного меню в Панели управления

### ISSUE THREAD

**Issue by AtlantisWebSt** [instantsoft/icms2#1504]
Очень хотелось бы увидеть в новых версиях движка вложенность в основном меню.
Сейчас вложенность есть только в тулбаре админки, что немного неудобно, т.к. его приходится формировать для каждого отдельного шаблона.

**Comment by fuzegit** [comment]
Что вы имеете в виду под основным меню?

**Comment by AtlantisWebSt** [comment]
При переходе в "компоненты", далее выбираем любой компонент и на открывшейся странице верхнее меню там где обычно написано "опции", скрин прикрепил.
![2024-11-01_16-45-03](https://github.com/user-attachments/assets/ed297d15-50bb-4eb1-be5c-0045a665cec6)

**Comment by fuzegit** [comment]
Строго говоря, функционал есть.

![Выделение_036](https://github.com/user-attachments/assets/276a571b-50be-4169-a249-3e60d6dc83bd)
![Выделение_037](https://github.com/user-attachments/assets/26cff4ee-1498-4a8f-8571-4b7d671b2da5)


https://github.com/instantsoft/icms2/blob/master/system/controllers/admin/frontend.php#L464

**Comment by AtlantisWebSt** [comment]
Благодарю, видимо пропустил((
