### ISSUE TITLE
Типограф и пустой тег video

### ISSUE THREAD

**Issue by zau4man** [instantsoft/icms2#1509]
**Используемая версия InstantCMS**: 2.16.3

В текущей версии пустой тег video, например `<video controls  src="https://cdn.fishki.net/upload/post/2024/08/06/4682615/d5ddad252d478f5b577e55f29aa22acc_1.mp4" type="video/mp4"></video>` будет вырезан типографом.

Предлагаю в файле типографа https://github.com/instantsoft/icms2/blob/master/system/controllers/typograph/frontend.php#L172 разрешить тегу video быть пустым.

Подробно проблема описана в теме https://instantcms.ru/forum/vopros-po-tipografu.html

**Comment by geminisf** [comment]
Поддерживаю
