### ISSUE TITLE
Аватарка пользователя в админке

### ISSUE THREAD

**Issue by kuzsa** [instantsoft/icms2#1511]
**Используемая версия InstantCMS**:[2.16.3]
При изменении размера пресета используемого для аватарки разваливается верстка, картинка описывается в стилях min-width: 32px. Правлю руками но при обновлении все слетает. Возможно ли при следующем релизе жестко ограничить в стилях размер аватарки в админке

**Comment by fuzegit** [comment]
Для шаблона modern при изменении размера пресетов, используемых для поля аватар, перекомпилируется scss в части размеров буквенных аватаров. Если вопрос в этом, то так должно и быть. Ограничивать стилями не планируется.

> Правлю руками но при обновлении все слетает.

Вероятно не там правите. Есть файл custom.scss.
