### ISSUE TITLE
Сделать мультиязычность кнопки "All news by the author"

### ISSUE THREAD

**Issue by AlexdChe** [instantsoft/icms2#1512]
**Используемая версия InstantCMS**: 2.16.3 

https://instantcms.ru/forum/kak-sdelat-multijazychnost-knopki-all-news-by-the-author.html#post-362327
  'multilanguage' => true,

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/4d81fa510fe171e4317d46ba5cebb85ec57514b1
