### ISSUE TITLE
Спойлер в режиме редактирования если активируешь в контенте "комментирование"

### ISSUE THREAD

**Issue by Sergsoon** [instantsoft/icms2#1514]
Используемая версия InstantCMS:  2.16.3

Версия PHP:  7.4
Версия MySQL/MariaDB:   5.7.42

Как воспроизвести проблему: В поле выставляет "Текст HTML" выбираем редактор где есть добавление спойлера, включаем в настройках контента, на первой вкладке, режим "комментирование"

При редактировании контента создаём спойлер, сохраняем и видим, что спойлер остался в режиме редактирования, есть курсор, можно менять текст. Конечно это не сохраняется, но в плане юзабилити не очень хорошо

Проверял на только установленной системе с нуля без каких-либо дополнений. 
Если комментирование отключить, то спойлер в нормальном режиме. 

И в комментировании если в комментарии сделать спойлер, он тоже в режиме редактирования, так я это и заметил.

В коде появляется строка — <div class=«spoiler» contenteditable=«true»>, если комментирование отключено то только <div class=«spoiler» > и всё в порядке, работает должным образом. 

Наблюдается если в редакторе комментариев стоит Tinymce, заменил на Redactor с настройками как в дема сайте, всё встало на места

всё конечно настраивамо, но в группах на стене стоит по умолчанию именно Tinymce и поэтому спойлер там в таком режиме((

Воспроизводится ли проблема на демо https://demo.instantcms.ru/: НЕТ

**Comment by Sergsoon** [comment]
![Видео-13-11-2024-182416](https://github.com/user-attachments/assets/4089306a-9012-4867-9758-4d75674c047a)

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/1719199cd2edc5e86c5d73f0f249d91a50863b26
