### ISSUE TITLE
Ошибка отображения версии mariadb в админке.

### ISSUE THREAD

**Issue by Risgit** [instantsoft/icms2#1515]
**Используемая версия InstantCMS**: 2.17-git

**Версия PHP**:  8.3
**Версия MySQL/MariaDB**:  11.7

На версиях mariadb выше 11 в информации о сервере версия mariadb отображается как N/A.
Можно ли заменить в файле 
        // mysql
        $o = console_exec_command('mysql -V');
на 
        // mysql
        $o = str_contains(console_exec_command('mysql -V')[0], 'Deprecated') ? console_exec_command('mariadb -V') : console_exec_command('mysql -V');

**Воспроизводится ли проблема на демо https://demo.instantcms.ru/**:  НЕТ

**Comment by fuzegit** [comment]
> Можно ли заменить в файле

Решение не годится. console_exec_command может возвращать null, str_contains >= php8.0.

Можете показать текст, который у вас выводит команда mysql -V в консоли?

**Comment by Risgit** [comment]
mysql: Deprecated program name. It will be removed in a future release, use '/usr/bin/mariadb' instead
mysql from 11.7.1-MariaDB, client 15.2 for debian-linux-gnu (x86_64) using  EditLine wrapper

**Comment by fuzegit** [comment]
Понял. Тогда проще это всё переделать на запрос
```sql
select version();
```

**Comment by fuzegit** [comment]
Проверьте, пожалуйста, сейчас всё корректно?

**Comment by Risgit** [comment]
Да, сейчас всё отлично.

![sysinfo](https://github.com/user-attachments/assets/a51aca55-30d3-4e6b-b599-84f95b358e73)
