### ISSUE TITLE
 private function __wakeup выдает E_WARNING на php 8.0.0 и выше

### ISSUE THREAD

**Issue by BorisRBJ** [instantsoft/icms2#1517]
https://github.com/instantsoft/icms2/blob/5ace6b06519c3f88588b697a32fdb80e053b88dd/system/core/autoloader.php#L28

**Comment by fuzegit** [comment]
> private function __wakeup выдает E_WARNING на php 8.0.0 и выше

Как повторить? При каких действиях варнинг?

**Comment by fuzegit** [comment]
В общем убрал эту строку.

**Comment by BorisRBJ** [comment]
Да там просто с 8 версии все магик методы кроме __construct(), __destruct() и __clone(), должны объявляться как public. Это имел в виду. 
https://www.php.net/manual/ru/language.oop5.magic.php
