### ISSUE TITLE
Поправить языковой файл контента

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#152]
В файле ...\system\languages\ru\controllers\content\content.php
`define('LANG_CONTENT_PRIVATE_FRIEND_INFO', '%s доступна только друзьям пользователя <a href="%s">%s</a>');`
где %s - тип контента как я понял, если приватный **пост**, то звучит так:
Пост **доступна** только друзьям пользователя.
Предлагаю убрать слово **"доступна"** и сделать так
`define('LANG_CONTENT_PRIVATE_FRIEND_INFO', '%s только для друзей пользователя <a href="%s">%s</a>');`
Тогда будет так:
_Страница только для друзей пользователя...
Статья только для друзей пользователя...
Пост только для друзей пользователя...
Новость только для друзей пользователя..._

**Comment by fuzegit** [comment]
поправили тут https://github.com/instantsoft/icms2/commit/708cc07b1f1bd723b48e82b7cb2de317f84f82e5
