### ISSUE TITLE
302 moved temporary

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#154]
Добрый вечер.
Вот такую проблему обнаружил.
1. Если в _Компоненты-Профили пользователей-Опции_ установить чекбокс в настройках **"Разрешить просмотр профилей только авторизованным пользователям"**, то у всех юзеров профили которых просмотрели при посещении сайта, ссылка http://lovelovely/users/1 становится  http://lovelovely/auth/login?back=/users/1, и она приобретает статус **"302 moved temporary"**
Чем это вредно, юзеры, зашедшие через браузер, и поисковые боты будут перенаправляться по новому адресу, при этом, для поисковых систем все свойства старого адреса (страницы) будут переданы новому. При редиректе случится склейка старого и нового адресов и вес страницы и ссылочный вес старого адреса будут переданы новому. А поскольку у меня допустим в robots Disallow: /auth/, то все полезные ссылки с профилями пользователей будут исключены из поиска и индекса. Как бы это не очень правильно реализовано. Я не знаю как, но это надо поправить.
![28-02-2016 20-01-56](https://cloud.githubusercontent.com/assets/9349934/13380901/d38f547e-de5e-11e5-8259-36d28868c2f8.png)

**Comment by r2git** [comment]
Если вы закрываете страницы от неавторизованных пользователей, то глупо ожидать что они будут индексироваться Яндексом. Таким же образом можно спросить почему не индексируется админка.

**Comment by nomad48** [comment]
@r2git админка закрывается файлом robots, и она не нужна поисковику, а здесь совсем по другому, отвалится полезная ссылка с контентом и информацией. При чем, через 302 редирект.

**Comment by r2git** [comment]
Эта ссылка не может быть полезной, потому что она недоступна для гостей. Вы либо откройте доступ, либо не ждите индексации. Это взаимоисключающие вещи.

**Comment by nomad48** [comment]
Для меня эта ссылка полезная, это профиль пользователя, все не полезное у меня закрыто
Disallow: /users$
Disallow: /users/index
Disallow: /users/*/*

**Comment by fuzegit** [comment]
> админка закрывается файлом robots, и она не нужна поисковику, а здесь совсем по другому, отвалится полезная ссылка с контентом и информацией

При чем тут файл robots? Админка не видна поисковикам, потому что туда доступа нет, как минимум авторизованным пользователям, и как максимум администраторам. Закрывать админку через robots по меньшей мере глупо и не имеет **вообще** никакого смысла. Поисковый робот туда не попадет **никак**. Тоже самое и с профилями. Их содержимое при включенной опции  "Разрешить просмотр профилей только авторизованным пользователям" **не видит поисковая система**. Вообще не видит, хоть что пишите в robots.

> Для меня эта ссылка полезная

а зачем вы запретили просмотр то тогда? Поисковая система для сайта и есть "гость".

**Comment by nomad48** [comment]
> а зачем вы запретили просмотр то тогда? Поисковая система для сайта и есть "гость".
@fuzegit вообще-то как я понимаю, закрытие профилей придумано для улучшения конверсии.

**Comment by fuzegit** [comment]
Закрытие профилей придумано для закрытия профилей. А вы, имхо, ищите кошку в темной комнате.

**Comment by nomad48** [comment]
> Закрытие профилей придумано для закрытия профилей. А вы, имхо, ищите кошку в темной комнате.

@fuzegit просто немного удивился увидев сегодня кучу 302. Я понял. Закрывайте.

**Comment by fuzegit** [comment]
Еще раз попробую объяснить: закрытые профили поисковые системы не видят, потому что для гостей сайта (а поисковые системы это гости, т.к. они не могут быть авторизованы) они закрыты для просмотра.
Соответственно при закрытых профилях движок редиректит на форму авторизации. Все работает как ожидается.
