### ISSUE TITLE
Не хватает файла шаблона виджета комментариев

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#156]
При включении на сайте виджета последних комментариев выдало 503 ошибку, включил отладку - проблему движок описал, что не хватает файла /templates/default/controllers/comments/widgets/list/list_comments.tpl.php
Проверил - его действительно нет, как и в дистрибутиве, собственно

**Comment by mafru** [comment]
Вы случайно в настройках виджета на вкладке дизайн в поле "шаблон виджета" - ничего не писали?

**Comment by iAndroS** [comment]
@mafru не писал, да и отношения это не имеет к делу - там просто файла не хватает. Видимо, в более ранних релизах он был, в 2.4.0 его нет.

**Comment by nomad48** [comment]
@iAndroS я проверил у себя /templates/default/controllers/comments/widgets/list/list_comments.tpl.php такого файла нет и в более ранних дистрибутивах не было, а вот /templates/default/controllers/comments/widgets/list/list.tpl.php есть.

**Comment by fuzegit** [comment]
Этого  файла там быть и не должно. Значит вы что-то меняли или прописывали свой шаблон в настройках, как уже выше отметил @mafru
