### ISSUE TITLE
InstantVideo2 - несколько пожеланий

### ISSUE THREAD

**Issue by SadKit** [instantsoft/icms2#157]
- При массовом импорте видео есть возможность сразу указать плэйлист, однако такой возможности нет при добавлении видео по ссылке или по коду. Соответственно более длинный путь становится еще длиннее, потому что затем нужно еще добавлять ролик в нужный плэйлист. Хотелось бы, чтобы выбор плэйлиста был доступен и при импортировании по ссылке или коду вставки.

- При большом количестве каналов при добавлении ролика любым способом, очень неудобно искать в выпадающем списке нужный канал, особенно если он где-то в середине списка. Было бы очень удобно если бы списки были реализованы как к примеру в Контакте, когда имеется возможность начать писать фразу и при совпадении подставляется значение из списка, если оно там есть. Тоже можно отнести к списку плэйлистов.

- Можно ли сделать массовый импорт по ссылкам, например, посредством загрузки списка ссылок или же при указании их в текстбоксе? Такое же пожелание к кодам вставки.

- Производить массовые изменения с роликами канала, такие как перемещение между каналами или плэйлистами, изменения названия, тэгов и т.д.

**Comment by mafru** [comment]
Зачем-же сюда это писать? Есть-же
https://instantvideo.ru/forum
https://instantvideo.ru/contacts.html
http://feedback.instantvideo.ru/
А вы сразу сюда.

**Comment by SadKit** [comment]
@mafru пардон, много форумов, уже немного запутался... просматривал эту ветку, тут и написал.
Закрыть?

**Comment by fuzegit** [comment]
1. Будет в обновлении InstantVideo
2. Будет в обновлении InstantCMS https://github.com/instantsoft/icms2/commit/b86aa06f6bd3c07640e19c2fbe6937038e408f53
3. Будет в обновлении InstantVideo
