### ISSUE TITLE
Не удобный выбор года в поле дата

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#159]
В поле дата, при выборе года во всплывающем календарике выводится список с 2006 по 2026 года (т.е. +-10 лет от текущей даты).
Если нужно выбрать какой нибудь 1980 год приходится выбрать 2006, затем снова открыть выбрать 1996 и т.д. либо ввести дату вручную.
Более того спилок "Годов в календарике только с 1970 года".
Было бы удобнее иметь более широкий диапазон лет.

**Comment by fuzegit** [comment]
> Более того спилок "Годов в календарике только с 1970 года".

в данном типе поля выбрать дату, ранее чем 1970 год невозможно технически. Для выбора даты ранее 1970 года необходимо использовать поле "Возраст"
