### ISSUE TITLE
ICMS2. Доска объявлений. При удалении набора ошибка: Unknown column 'i.index' in 'where clause'

### ISSUE THREAD

**Issue by EnotAlex** [instantsoft/icms2#163]
ICMS2. Доска объявлений. 
При удалении набора по адресу сайт.ру/admin/ctypes/datasets_delete/21
Ошибка в запросе БД:
Unknown column 'i.index' in 'where clause'

SELECT i.*
FROM cms_content_datasets i
WHERE (i.index IS NULL)
LIMIT 1
Последние вызовы:

getItem() @ ///////system/core/model.php : 1163
getItemByField() @ //////////system/controllers/content/model.php : 1112
deleteContentDatasetIndex() @ ///////system/controllers/content/model.php : 1265
deleteContentDataset() @ //////system/controllers/admin/actions/ctypes_datasets_delete.php : 9
run()
call_user_func_array() @ ///////system/core/controller.php : 304
runExternalAction() @ ////////system/core/controller.php : 235
runAction()
call_user_func_array() @ ////////system/core/action.php : 29
__call() @ ///////system/controllers/admin/actions/ctypes.php : 9
runAction() @ ////////system/controllers/admin/actions/ctypes.php : 9

**Comment by fuzegit** [comment]
обновление с предыдущей версии у вас прошло с ошибками. на чистой 2.4.0 проблема не воспроизводится.

**Comment by EnotAlex** [comment]
значит всё сношу и ставлю чистую((
спасибо.
