### ISSUE TITLE
Отключение показа пункта меню вместо удаления

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#165]
В 1 ветке было удобно управлять меню, если надо было на время скрыть пункт, а потом его вновь показать. Достаточно было просто отключить показ пункта на сайте.

**Comment by mafru** [comment]
А зачем удалять? Показ можно регулировать уровнями доступа.

**Comment by facepoint** [comment]
верно, доступы выставьте только для админа или вообще не показывать никому и будет счастье. хотя визально в один клик возможно и удобнее отключать.
