### ISSUE TITLE
Ошибка url

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#167]
Не знаю, ошибка ли в движке в целом или конкретно в мапсе - опишу ситуацию:
Создал запись (объект на карте), изменил вручную его url, через какое-то время приходят системные уведомления об этом объекте, а ссылка получается битой - ссылка идет на первоначально созданный url. То есть, скрипт выдает не текущий url объекта, а его url, который был задан при создании записи! Я так понимаю, в бд хранится две записи?

**Comment by mafru** [comment]
Нет. в базе данных только одно поле для хранения значения url записи.
