### ISSUE TITLE
Своя страница 404

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#169]
Хотелось бы иметь возможность задания собственной страницы 404. Как я это вижу:
Создаем контент-страницу, затем в настройках iCMS задаем эту страницу вместо 404 страницы

**Comment by Val-Git** [comment]
@iAndroS отредактируйте по своему вкусу файл **..\templates\default\assets\errors\notfound.tpl.php**

**Comment by iAndroS** [comment]
@Val-Git 
Не подскажите, каким образом правильно это сделать, чтоб и 404 ошибка отдавалась и страница определенная? Или просто редирект настроить во фрейме?

**Comment by Soul-git** [comment]
iAndroS , .\templates\default\assets\errors\notfound.tpl.php   измените  на свой вкус, простой - [пример](https://yadi.sk/d/uvpeAZYQq492H)

**Comment by nomad48** [comment]
@Soul-git по моему какой-то один тег <body> лишний.

**Comment by Soul-git** [comment]
nomad48, да "промахнулся немного", но это пример "на вскидку", я к тому, что такие вопросы легко решаемы на уровне шаблона.

**Comment by nomad48** [comment]
@Soul-git скажите пожалуйста, какой убрать (верхний)? я утащил для примера себе.

**Comment by Soul-git** [comment]
nomad48, первый. и смените в строке 94 ссылку редиректа на нужную.

**Comment by nomad48** [comment]
@Soul-git Благодарю
