### ISSUE TITLE
Возможность менять местами типы контента в меню пользователя

### ISSUE THREAD

**Issue by andriy85if** [instantsoft/icms2#171]
Если много разных типов контента, нужна возможность отсортировать их в меню пользователя (Создать - ...). По-умолчанию они отсортированы по id. Было бы хорошо, если была бы возможность сортировать их отображения в меню перетаскиванием на странице "Типы контента".

**Comment by WebManG** [comment]
Поддерживаю.

**Comment by iAndroS** [comment]
Простенькую правочку предлагаю сюда же добавить - убрать лишнее слово в системном меню {content:add}
![screenshot_1](https://user-images.githubusercontent.com/17408903/32199865-85968f94-be09-11e7-812c-15b8a9d2d438.png)
