### ISSUE TITLE
Сниппет мета-тегов

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#173]
Когда-то смеялся над этой темой http://www.instantcms.ru/forum/thread22063.html сейчас же надеюсь, что предложение будет рассмотрено.

**Comment by iAndroS** [comment]
Это немного не то... В типах контента есть поля в группе SEO (если включено в настройках типа контента). Так вот над ними можно было бы отобразить сниппет поисковый, которые показывал бы, как будет выглядеть в поиске материал

**Comment by fuzegit** [comment]
> Так вот над ними можно было бы отобразить сниппет поисковый, которые показывал бы, как будет выглядеть в поиске материал

это все слишком относительно и будет сбивать людей с толку, т.к. не факт, что сниппет будет выглядеть именно так (и поисковых систем у нас ведь не одна). Считаю достаточным показывать кол-во символов/кол-во сколько осталось.

**Comment by iAndroS** [comment]
В принципе, согласен. Тогда такой вопрос - если в настройках типа контента указывать, чтоб SEO автоматически подставлялось - данные будут браться из заголовка и краткого описания этого типа, верно ведь? Если так, то все ок.
