### ISSUE TITLE
Значение из поля профиля ТЕЛЕФОН

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#175]
Хотелось бы в коробке иметь данную возможность
http://www.instantcms.ru/blogs/zametki-na-poljah/maska-dlja-polja-icms2.html#c88899

**Comment by vlad7090** [comment]
еще и e-mail было бы хорошо выводить из профиля пользователя. почему то в админке нет возможности выбрать это значение из профиля пользователя.

**Comment by Val-Git** [comment]
> Хотелось бы в коробке иметь данную возможность

Если добавлять подобное поле то оно должно быть универсальным, а не только заточенным под телефон, в противном случае используйте указанное дополнение.

> еще и e-mail было бы хорошо выводить из профиля пользователя.

а чем ссылка не подходит?
`<a href="mailto:email@email.ru">email@email.ru</a>`

**Comment by vlad7090** [comment]
я писал про то, что если в типе контента создать поле e-mail то нельзя выбрать там же, что если мыло у пользователя заполнено, то его автоматом подставлять в это поле в типе контента.

**Comment by Soul-git** [comment]
@vlad7090, смотря каким образом Вы это поле создаете.
Системно в Значение из профиля пользователя можно вывести только поля типов: 'string', 'text', 'html', 'list' (текстовые поля и список).
Для подключения "других" типов полей:
\system\controllers\admin\forms\form_ctypes_field.php (прописать системное имя необходимого поля)/
строку 151 привести к виду:
`$fields = $model->filterIn('type', array('string', 'text', 'html', 'list', 'нужное поле'))->getContentFields('{users}');`

**Comment by vlad7090** [comment]
Да, именно так и прописал как раз. Вот и хотел уточнить, будет ли оно заимствоваться
