### ISSUE TITLE
Ошибка в ленте активности

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#177]
Доброй ночи уважаемые разработчики.

У меня ICMS 2.4.1 в ленте активности не отображаются никакие типы контента (страницы, статьи, блоги, новости).
Всё остальное отображается нормально.
Сегодня добавлял статью, в ленте активности ее нет. Она была с отложеной публикацией. То есть в 12 часов разместил, в 19 часов опубликовалась.
Ранее писал @r2git - думал что это проблема связана как-то с биллингом и модерацией, но сегодня, когда размещал сам, понял что и мои статьи и посты в ленте активности не отображаются.
Файлы сайта смерживал с дистрибутивом 2.4.1 - различий нет. В компоненте все тоже включено.
![16-03-2016 23-42-39](https://cloud.githubusercontent.com/assets/9349934/13828111/f1a9445e-ebd0-11e5-84f1-2bd5cc88c72f.png)

**Comment by mafru** [comment]
В логах ошибка есть?

**Comment by nomad48** [comment]
По ленте активности нет. По другим компонентам есть, по форуму и по фотоконкурсам от Kreator

**Comment by mafru** [comment]
Просто не могу у себя воспроизвести вашу ошибку. На последней версии с гита, в ленту все добавляется.

**Comment by nomad48** [comment]
Вот логи
[lovelovely.ru.error.log.0.gz](https://github.com/instantsoft/icms2/files/177517/lovelovely.ru.error.log.0.gz)
[lovelovely.ru.error.log.1.gz](https://github.com/instantsoft/icms2/files/177518/lovelovely.ru.error.log.1.gz)
[lovelovely.ru.error.log.2.gz](https://github.com/instantsoft/icms2/files/177519/lovelovely.ru.error.log.2.gz)

**Comment by mafru** [comment]
Вы пришлите записи лога в момент когда вы добавляете запись, которая не добавляется в ленту.

**Comment by nomad48** [comment]
Вот лог ошибок с 19.00 до 20.00, статья по cron была размещена в 19.45
[Лог ошибок.txt.gz](https://github.com/instantsoft/icms2/files/177529/txt.gz)

**Comment by mafru** [comment]
Поясните, проявляется только в отношении записей с отложенной публикацией или и при добавлении записи с сайта тоже проявляется.

**Comment by nomad48** [comment]
Я сейчас предметно не готов ответить, по отложенной точно, по размещению с сайта сейчас в течении 5 минут проверю и напишу.

**Comment by mafru** [comment]
Подтверждаю, при отложенной публикации не добавляется событие в ленту активности.
Нужно в компонент ленты добавить хук
PublishDelayedContent

**Comment by nomad48** [comment]
Так и есть, при размещении напрямую с сайта, всё работает. 
![17-03-2016 12-25-52](https://cloud.githubusercontent.com/assets/9349934/13841712/8afa64d4-ec3b-11e5-8900-60e40b2d0b99.png)

**Comment by nomad48** [comment]
@mafru Подскажете что добавить себе на сайт? что поправить ошибку? Спасибо.

**Comment by mafru** [comment]
Пока ничего. Возможно разработчики сделаю по своему. Я свой pull направил.

**Comment by nomad48** [comment]
@mafru я понял, я ваш вариант добавил, все сработало, но немного с задержкой. В целом норм.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/pull/178
