### ISSUE TITLE
PHP Warning при редактировании полей контента

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#179]
Сегодня редактировал поля контента, получил следующие PHP Warning в логах сервера. И они продолжают поступать даже просто при просмотре полей контента.

[PHP warning.txt.gz](https://github.com/instantsoft/icms2/files/180125/PHP.warning.txt.gz)

**Comment by mafru** [comment]
Боюсь данная ошибка связана со сторонним полем.

**Comment by nomad48** [comment]
Я понял, спасибо.
