### ISSUE TITLE
Тип поля: ТЕГ (активная ссылка)

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#181]
Навеяно форумом инвидео: данная фича не только в видео-сайтах пригодится. 
Данный тип поля предполагает введение строкового значения, которое бы работало по аналогии с тегом, но ТОЛЬКО в заданном типе контента.
Пример, по тому же видео:
Тип контента - Фильмы
Поле "Режиссер", тип поля - предлагаемый мною "Тег" (или "активная ссылка", чтоб не было путаницы). 
При добавлении какого-либо фильма юзер указывает в строковом поле одного или нескольких режиссеров, которые если ранее были зарегистрированы в этом типе контента, то они бы подставлялись автоматом.
При выводе самого фильма с фронта сайта каждый из режиссеров был бы ссылкой на все фильмы с его участием в роли режиссера. Тоже самое и по актерам.
Вообще, данное поле закрыло бы много имеющихся запросов при его применении на сайте.

**Comment by fuzegit** [comment]
Дубликат https://github.com/instantsoft/icms2/issues/140

**Comment by vlad7090** [comment]
согласен, когда можно фильтровать по значению в поле, т.к он будет ссылкой, будет мегаудобно и универсально. поиск и фильтрация по каталогам будет в разы легче и удобнее, чем задавать значения в фильтре.

**Comment by iAndroS** [comment]
Дополню хотелку: сделать возможность выбора более 1 тега для фильтрации контента. Выводить фильтр виджетом.
