### ISSUE TITLE
В файле конфига нет возможности отключить рекапчу

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#182]
По этой причине не могу авторизоваться на сайте, ибо ввел неправильно сначала пароль. Теперь не знаю, что делать, хоть переустанавливай все заново :(

**Comment by pin-git** [comment]
Подтверждаю, подождал и вошёл позже, мне было не принципиально, тестовый сайт, сроку прошло дня 2-3. По этой же причине (тестовый) каптчу не настраивал. 
Новая в связи с необходимостью обязательной регистрации сайта неудобна, уже подумал о возврате предыдущего варианта, но пока обхожусь её выключением в разделе компонентов.

**Comment by mafru** [comment]
А почему он там должен быть? Только потому, что Вы не правильно ввели пароль.
Зайдите в базу и отключите вывод капчи при неудачной попытке авторизации.

**Comment by pin-git** [comment]
@mafru всё так, но для обывателя как-то момент не додуман

**Comment by fuzegit** [comment]
По умолчанию теперь требование ввода капчи отключено.

p.s. для вопросов используйте форум

**Comment by iAndroS** [comment]
@mafru ткните, пожалуйста, что где конкретно отключить в базе?

**Comment by mafru** [comment]
Таблица controllers->Авторизация и регистрация->поле options->auth_captcha

**Comment by iAndroS** [comment]
@mafru спасибо, разобрался!
