### ISSUE TITLE
Права доступа к полю не действуют на фильтры

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#183]
Создал поле в типе контента, доступное только администратору, и выставил его доступным для фильтрации. При этом с фронта фильтр по данному полю виден даже гостю!

**Comment by fuzegit** [comment]
Вы считаете, что если поле имеет права доступа, то и в фильтре оно должно выводиться согласно этих прав?

**Comment by iAndroS** [comment]
Думаю, да. Если же я неправ, тогда и для вывода в фильтре нужны свои права доступа, получается.
Нужно смоделировать несколько ситуаций и обмозговать, нужна ли зависимость прав доступа на фильтры во всех случаях или это отдельный экземпляр. Но сейчас голова не варит толком, спать пора уже...

**Comment by fuzegit** [comment]
Как бы да, вы правы. Но нужно выслушать другие мнения.

**Comment by globator88** [comment]
Не обращал внимание раньше, но думаю так правильнее. Нету смысла показать филтр тем кто это видит не должны.
Еще хотел бы увидеть на инстанте скрытое поля для самого пользователя, а не толька для админа

**Comment by vlad7090** [comment]
лучше если будет опционально, т.к порой надо чтобы доступ был только у админа, но при этом фильтровать могли все. 
т.е опция у поля следующая: редактирование "указываем группы", просмотр "все....группы"

**Comment by globator88** [comment]
> лучше если будет опционально, т.к порой надо чтобы доступ был только у админа, но при этом фильтровать могли все

Согласен. Бывают такие случае. Когда информацию заполняет команда сайта а поиск нужен пользователю.
