### ISSUE TITLE
Автоопределение устройства просмотра: мобильное, планшет, ПК

### ISSUE THREAD

**Issue by pin-git** [instantsoft/icms2#185]
мнение по коммиту.

Считаю не верным включение в ядро обязательное определение устройств с детализацией до модели. Так же не считаю верным реализованное решение выбора используемого шаблона в зависимости от типа устройства.

Данная функциональность не основная, дополнительная, ей место либо в дополнениях, либо в шаблоне, пусть в default, но охватывающем только его и функциональность класса необходимо активировать из того же шаблона при необходимости.

Любой шаблон для конкретного типа устройств... Вижу только неразбериху. 

Моё предложение прописывать шаблону тип устройств для которых он предназначен и название основного. Выбор основного шаблона в настройках должен показать все совместимые с ним шаблоны по типам устройств.

Пример: создаю шаблон и к нему адаптированные по типам устройств, пользователь выбирает его как основной и далее он видит только адаптированные варианты данного шаблона и больше ни чьи.

**Comment by fuzegit** [comment]
> определение устройств с детализацией до модели

Так нет такой детализации. Определяется **один раз в год** для клиента - пк, планшет, мобильное устройство и запоминается в куках.

> не считаю верным реализованное решение выбора используемого шаблона в зависимости от типа устройства
так все же опционально. Надо отдельно, чтобы выводился другой шаблон  для телефонов, выбрали в настройках нужный.

> Любой шаблон для конкретного типа устройств... Вижу только неразбериху.

Какого конкретного? Три типа: пк, планшет и телефоны. Все.

> ей место либо в дополнениях, либо в шаблоне, пусть в default
дополнениями этот функционал сделать невозможно

> Моё предложение прописывать шаблону тип устройств для которых он предназначен и название основного. Выбор основного шаблона в настройках должен показать все совместимые с ним шаблоны по типам устройств.

А определять устройство то где и что будет? Вы предлагаете тоже самое, только наоборот, что шаблон определяет (как он это будет делать?), при этом тип устройства определяется по прежнему в самой CMS.
ИМХО, усложняете, а в итоге получается тоже самое.

**Comment by vlad7090** [comment]
а размеры подгружаемых картинок тоже можно будет назначать, в зависимости от устройства?

**Comment by fuzegit** [comment]
> а размеры подгружаемых картинок в виджетах и списках типах контента тоже можно будет назначать, в зависимости от устройства?

нет. это решается при помощи css.
