### ISSUE TITLE
При создании категории возможность задавать "Обложку категории"

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#192]
Для многих каталогов это очень полезно, т.к на главной странице каталога можно было бы вывести виджет категорий с картинками. В настройкахз виджета было бы возможно куказывать отображение - табличный вид или список.

**Comment by pumpuic** [comment]
И описание.
В итоге имеем: Заголовок | Описание | Изображение. Удобно выводить каталог какой, например.

**Comment by facepoint** [comment]
> В итоге имеем: Заголовок | Описание | Изображение. Удобно выводить каталог какой, например.
очень нужные функции, иначе приходится делать кастыли.

**Comment by pumpuic** [comment]
Еще для полного фэншуя, как кто-то написал на сайте - seo заголовки отдельно от самого заголовка, в идеале все сео данные - теги, описание, заголовок.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/issues/343
