### ISSUE TITLE
После обновлений пропали страницы

### ISSUE THREAD

**Issue by createzone** [instantsoft/icms2#193]
Обновил сайт 2.3 до 2.4, после этого половина сайта перестала работать, в чем может быть проблема пропадания страниц? а точней компонент модерация. аякс окна, невсплывают, еще некоторые страницы перестали работать, т.е. пишет страница не найдена.

**Comment by createzone** [comment]
решения нету?

**Comment by Val-Git** [comment]
@createzone Вы криво обновились! Перезалейте файлы снова, проверьте права на папки и файлы ну и т.д.

**Comment by createzone** [comment]
через админку обновлялся, удалял обновы и через фтп пробовал всеравно не отображает страницы, хотя баг с права доступа на виджет поправился, права на файлы те что были, в чем может еще быть проблема ?

**Comment by createzone** [comment]
подскажите что изменили в файле system\controllers\content\model.php для правки бага с гостями, гости не видели виджеты если даже им есть доступ, не многу обновить все по этому и хочу узнать как пофиксили баг
