### ISSUE TITLE
Виджет тегов - вывод по типам контента и их категорий

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#195]
Предлагаю в виджете тегов реализовать возможность выбора отображения тегов со всего сайта, с конкретного типа контента или же текущей категории контента (во вкладе ОПЦИИ).
К примеру, у меня какой-либо каталог. Чтобы не пложить кучу ненужных категорий в меню, я добавляю каждой записи каталога свои теги, а на странице данной категории каталога, или же на странице записи, выводятся только теги, относящиеся к данной категории каталога.
Удобно, практично, SEO-оптимизированно!

**Comment by fuzegit** [comment]
Вообще это уже реализовано
http://storage9.static.itmages.com/i/16/0401/h_1459512758_2631072_37b22d2633.png

**Comment by iAndroS** [comment]
@fuzegit это в 2.4.1 будет?
Из предложенного мною не хватает еще чекбокса "отображать теги категории", а так уже неплохо!

**Comment by fuzegit** [comment]
> это в 2.4.1 будет?

уже есть, если скачаете версию отсюда.

> отображать теги категории

теги не прикрепляются к категориям, поэтому увы, этого не будет. Т.е. сделать можно, но это существенно усложнит выборку из БД и как следствие нагрузка на сервер будет высокая.
