### ISSUE TITLE
Модерация комментариев

### ISSUE THREAD

**Issue by marenovmaxim** [instantsoft/icms2#198]
Очень не хватает данной возможности, причем не просто модерации, а полноценной, примерно как на wordpress, то есть например, если комментарий содержит не больше n-го количества ссылок, то публекуется автоматически, если больше, то идет на модерацию или вообще удаляется автоматически.

**Comment by pumpuic** [comment]
Для начала хотя бы самая простая модерация очень бы не помешала )

**Comment by asnenne** [comment]
И без ссылок могут такого написать, что мало не покажется... Удивился, когда узнал, что модерации нет. Не знаю, может это не относится к самому движку, а только к мапсу, но добавление отзывов для объектов почему-то тоже без модерации. Считаю, что опционально модерация должна быть применена ко всему, что могут добавлять пользователи. Также и к фото в фотоальбомах. Сам фотоальбом отправляется на модерацию, а после одобрения модератором, фотки уже можно грузить без модерации. Так быть не должно. Извините, если немного ушел от темы))

**Comment by WebManG** [comment]
> Считаю, что опционально модерация должна быть применена ко всему, что могут добавлять пользователи

Это очень здравая мысль. Поддерживаю!
