### ISSUE TITLE
Вывод фотографий из фотобальбомов

### ISSUE THREAD

**Issue by virelart** [instantsoft/icms2#200]
На данный момент времени абсолютно нет возможности простому пользователю организовать простенький виджет с выводом только ФОТОГРАФИЙ пользователя или всех пользователей, либо определённого пользователя, например, в его профиле. Да, есть модификации... Платные. И там куча лишнего. Фотоальбомы снова ставят на самое последнее место... а ведь кому-то они нужны... Почему бы по умолчанию не ввести виджет фотографий или хотя бы наборы, которые будут отвечать простым нуждам, указанным выше... Очень надеюсь, что наконец-то обрадуют тех, кто страдает из-за несовершенства фотоальбомов...(

**Comment by murlysja** [comment]
+ сделать возможным добавлять описания к фотографиям.

**Comment by fuzegit** [comment]
Ох, что же вы раньше не написали, уже релиз почти готов. Чтобы не возникло недопонимания думаю стоит примерно нарисовать что вы хотите от виджета и какие конкретно должны быть настройки. Пока что я вижу только такие настройки:
- автоопределение профиля и показ фото этого пользователя с ссылкой на все фото
- опция показа только общих фото
- опция показа только личных фото

**Comment by virelart** [comment]
Увы, я ждала, думала это само собой разумеется. ^^ А потом смотрю нету... Думаю надо написать.
**Думаю виджет должен иметь общий вид такой:**

**Выбор альбома откуда выводить изобр.: **
- какой-то из общих альбомов, 
- все альбомы, 
- альбомы определённого юзера: форма для вписки никнейма, 
- изображения самого юзера (Мои изображения)

**Этот выбор станет не доступен, если нажать галочку: выводить в профиле юзера его фотографии** _(в этом случае виджет считывает айди профиля и выводит фотки только того юзера - чей профайл)_

**Остальные настройки стандартные:**
- кол-во фоток
- размер
- какую информацию пристыковывать (название альбома, автор, дата загрузки и т.д.)

- прочие настройки как в выводе контента с дизайном там и т.д., чтоб каждый мог настроить вывод

Как-то так. Могу ещё более подробно разобрать, нарисовать макет, если идея воплотима, конечно, и если это нужно. =)

**Comment by fuzegit** [comment]
Все реализуемо конечно же, но уже не в этом релизе, код заморожен. Так что думаю в следующем все будет. Рисовать в принципе тут нечего, фото + доп. информация.

**Comment by virelart** [comment]
**Ну, конечно, нужно тогда ещё и к самим фото:** 
описания пристыковать, например 
и тэги., о чём просит так же и @murlysja. 
И думаю неплохо бы оригинал чтобы открывался.

Конечно, там думаю тоже не так много тогда. В любом случае будем ждать! Спасибо за быструю реакцию! =)

**Comment by fuzegit** [comment]
И вам спасибо за конструктив, это сейчас редкость)

**Comment by iAndroS** [comment]
> сделать возможным добавлять описания к фотографиям.

Которые бы дублировались в тег alt изображения. Хотя, наверное, правильнее в alt заголовок/название фото дублировать в виде {название фото}-{название фотоальбома}

**Comment by vlad7090** [comment]
не хватает описания к фотографиям и возможность выделить юзера на фото, если он ексть в друзьях с уведомлением юзера о том, что его отметили на фото.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/7f6107570b493f821a1a098d215e93feb85133a7

**Comment by fuzegit** [comment]
@virelart, @murlysja  проверьте пожалуйста работу нового фотоальбома и виджета. Скачать установочный архив CMS можно тут https://github.com/instantsoft/icms2 , нажав на зелёную кнопку справа вверху.
