### ISSUE TITLE
Подписка на новые записи типа контента

### ISSUE THREAD

**Issue by rdimrs** [instantsoft/icms2#202]
Добавить возможность подписываться на новые записи контента. 
В настройках: 
1) Оповещение на email и в уведомление на сайте, или только на email или только в уведомления.
2) Сроки рассылки (например присылать каждые 3 дня).
3) Подписка на определенную категорию.
4) Подписка на значение определенного поля или свойства ( пример использования в объявлениях о продаже авто, выбираем цвет - красный и марка - bmw, как только появилось объявление получаем извещение. Можно использовать подписку в новостях и в многих других специализированных типах контента.) 

Это дополнения конечно можно заказать у разработчиков, но я думаю был бы большой плюс для cms иметь эту функцию "из коробки".

**Comment by pumpuic** [comment]
С такой подпиской данный движок даст 100 очков фору остальным :)

**Comment by klubnik** [comment]
Очень сыро, но подписка одна из социальных функций. Ее обязательно надо использовать в разных вариантах.

**Comment by iAndroS** [comment]
> Подписка на значение определенного поля или свойства ( пример использования в объявлениях о продаже авто, выбираем цвет - красный и марка - bmw, как только появилось объявление получаем извещение.
Это подписка на фильтры контента. Очень нужная тема. Живой пример - сайта телдери. Очень удобно. На авито тоже так реализовано. 
При этом очень важно учитывать, что если юзер активен и посещает сайт хотя бы раз в сутки, то не присылать ему на email, а оповещать через систему уведомлений. Нужно избегать частых писем на email для активных юзеров, ибо рано или поздно почтовики, анализируя поведенческие факторы (открытие, прочтения) просто перестанут доставлять почту. Данный нюанс я уже ощущал на одном своем проекте (не на инстанте).
PS: наверное, это уже отдельная тема обсуждения...

**Comment by rdimrs** [comment]
Нужно сделать условия подписки на выбор пользователя, он сам решит как часто ему получать письма. И если человек даже находится на сайте ему в уведомление должно придти извещение, что "в таком то типе контента появилась запись с нужными вам критериями". Подписка в виде кнопки "подписаться", при нажатии на кнопку всплывает модальное окно, где предлагается выбрать: подписку по фильтру и выбор периода рассылки, присылать сразу как появится запись с нужными критериями или присылать раз в несколько дней.

> Еще можно/нужно в ленту событий добавить раздел ПОДПИСКИ 

Вот это хорошая идея.

**Comment by iWeb1** [comment]
Поддерживаю данное предложение !

**Comment by WebManG** [comment]
+1
