### ISSUE TITLE
URL в профилях и группах

### ISSUE THREAD

**Issue by WebXRs** [instantsoft/icms2#205]
Очень полезная функция использование username в url вида http://site.ru/users/username или http://site.ru/groups/groupname
Это очень хорошо использовать для SEO и PR 
Удобнее хотя бы для запоминания. Это была главная проблема при появлении ВК, люди не помнили свои цифры, чтобы передать кому-то ссылку устно 
Так же при выдаче выделенный ключевик вызывает больше доверия у ищущего, что он нашел именно то что искал. 

Еще лучше конечно вообще опустить одну вложенность http://site.ru/name Понимаю, что может возникнуть конфликт url и похоже нарушится MVC  Тем не менее, для каких-то сайтов это может было бы лучше.

**Comment by Val-Git** [comment]
@klubnik, объясните неандертальцу чем http://site.ru/users/username хорошо для SEO?

**Comment by klubnik** [comment]
Поисковики давно уже смотрят что написано в урлах.
Яндекс как один из важнейших в рунете особенно учитывает и выделяет, смотрим
https://yandex.ru/search/?lr=2&msid=22895.17755.1460026923.78294&text=username&suggest_reqid=261877029144276369933173440750071&csg=365%2C5214%2C8%2C16%2C0%2C0%2C0

**Comment by Val-Git** [comment]
Изучил поисковую выдачу по ссылке)) Ничего кроме описание что такое **username** не нашел. И тем не менее, пусть поисковики смотрят на URL, чем ссылка вида http://site.ru/users/vasya_pupkin лучше http://site.ru/users/328? И как это помогает в SEO? В обоих случаях поисковик покажет страницу Василия))

**Comment by klubnik** [comment]
Тут просто надо знать приоритеты выдачи.
Да, если в title есть вася пупкин, то это будет учитываться, но приоритетнее когда title дублируется в url 
Кроме того, каждый такой ник на сайте становится ссылкой на смысловой url, что сильно бодрее повышает нахождение нужного васи

**Comment by Val-Git** [comment]
> Да, если в title есть вася пупкин, то это будет учитываться, но приоритетнее когда title дублируется в url 

Хоть какая то конкретика)) А в этом случае поисковик распознает что vasya_pupkin и Василий Пупкин это один и тот же персонаж?

>Кроме того, каждый такой ник на сайте становится ссылкой на смысловой url, что сильно бодрее повышает нахождение нужного васи

Можно поподробнее каким образом такой ник становится ссылкой? Или вы имеете ввиду что зная ник васи другой пользователь может ручками вбить необходимый URL? Теоретически ДА, но практически не уверен что пользователи будут набирать такой линк, проще найти этого васю каким либо другим методом))

**Comment by klubnik** [comment]
> Можно поподробнее каким образом такой ник становится ссылкой? Или вы имеете ввиду что зная ник васи другой пользователь может ручками вбить необходимый URL? Теоретически ДА, но практически не уверен что пользователи будут набирать такой линк, проще найти этого васю каким либо другим методом))

Это паук поисковика смотрит )) Это же азы SEO

**Comment by Val-Git** [comment]
@klubnik я в SEO не силен, потому и спрашиваю)) Абсолютно без претензий, а для понимания. Потому как если мне что-то понравится из услышанных/увиденных идей - беру их на вооружение и в будущем могу реализовать на практическом уровне.
Тем не менее вы не ответили на вопрос. Ссылка будет вида `<a href="url">имя пользователя</a>` Поисковик вытаскивает имя пользователя из текста внутри тега **<a>** а ссылку на этого пользователя из атрибута **href** Поэтому я и понимаю что линк в виде **id** совершенно спокойно ассоциируется с именем пользователя для поисковика.

**Comment by klubnik** [comment]
> @klubnik я в SEO не силен, потому и спрашиваю)) Абсолютно без претензий, а для понимания. Потому как если мне что-то понравится из услышанных/увиденных идей - беру их на вооружение и в будущем могу реализовать на практическом уровне.
Тем не менее вы не ответили на вопрос. Ссылка будет вида <a href="url">имя пользователя</a> Поисковик вытаскивает имя пользователя из текста внутри тега а ссылку на этого пользователя из атрибута href Поэтому я и понимаю что линк в виде id совершенно спокойно ассоциируется с именем пользователя для поисковика.

Да, и связанные с ним материалы. Грубо говоря, SEOКГБ поисковика заводит на него дело  ))

**Comment by klubnik** [comment]
Еще важный момент. Поисковик учитывает возраст url. Если мы создаем сайт, у нас он уже большой и все проиндексировано, то как только мы меняем url, страница становится новой и может потерять свой траст. Для этого обычно используют страницу 301, чтобы переносить пользователя, но это нам придется мучатся.
Поэтому чем раньше мы создаем основную структуру сайта, тем она надежнее в этом смысле.

**Comment by iAndroS** [comment]
Очень правильная мысль: поисковики любят, чтобы заголовок страницы был идентичен его url (или наоборот, неважно). Чем больше их (заголовка и url) сходства (пусть и в транслите) и чем короче адрес url - тем выше эта страница в выдаче!

**Comment by Margauza** [comment]
Извините что вклиниваюсь, у меня нет мнения по этому поводу, и я не знаю насколько тема важна, но хочу подкинуть инфы для раздумий. 

Реальный пример: есть девушка(не я) она шьет дизайнерские, уникальные костюмы для гимнасток несколько(много) лет выкладывала их и продавала только через соц. сети. Сделала себе кучу постоянных богатых клиентов и открыла мастерскую, недавно заказала себе сайт. Но в интернете ее знают, знали не по имени а как **lana leotards.** 

Попытаюсь прикрепить изображения, так вот когда ее клиенты в интернете, говорят о ней они ее так и называют и так ищут, они не знают(или не помнят) ее по имени/фамилии или название ее сайта. Ее профиль в соц. сетях стал ее брендом. 

Кстати смешно но ее сайт гораздо ниже в выдаче по многим запросам нежели профайлы и при поиске выходят только те страницы где есть их упоминание, Я узнала о нем (о сайте) только потому что увидела что крутится в адсенс блоке на моем сайте. Могла бы зарегать домен **lanaleotards.ru** и он бы сам себя раскрутил, как минимум целевая аудитория была бы ей обеспечена. Таких примеров я знаю несколько, когда мастеров ищут не по сайту, или реальному имени а по нику или профилью в соц.сети. 
![lanaleo](https://cloud.githubusercontent.com/assets/18312974/14411948/1799090a-ff5f-11e5-8e5e-9592e79fafc2.jpg)
![lanaleo2](https://cloud.githubusercontent.com/assets/18312974/14411951/1fae8692-ff5f-11e5-80c9-c43cfa7743f8.jpg)

**Comment by WebManG** [comment]
Нужное дело. Поддерживаю!
