### ISSUE TITLE
Программируемое автозаполнение SEO

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#206]
Предлагаю в iCMS реализовать возможность программирования автоматически заполняемых мета-тегов контента, его типов и категорий.
Очень нравится аналогия, что представлена ниже на скрине

![descr-15](https://cloud.githubusercontent.com/assets/17408903/14349083/14761cd6-fcf3-11e5-89d0-f40d1c62150f.png)

PS: навеяно нерабочим компонентом http://addons.instantcms.ru/addons/seogenerator.html

**Comment by rdimrs** [comment]
Полезная штука для интернет магазина, каталогов. Заливаешь кучу товара, и в "один клик" заполняешь все теги.

**Comment by iAndroS** [comment]
Мне понравилось по скрину, что можно и альты заголовками обозвать

**Comment by rdimrs** [comment]
Я пользуюсь подобным модулем в опенкарт, очень удобно. 
![screenshot-rai-home ru 2016-04-07 16-58-32](https://cloud.githubusercontent.com/assets/17247271/14353551/386984cc-fce2-11e5-9c27-7309e9bb4d6b.png)

**Comment by vlad7090** [comment]
да, это было бы круто!

**Comment by facepoint** [comment]
Очень полезная фишка. Еще бы добавлять город автоматом

**Comment by iAndroS** [comment]
> Еще бы добавлять город автоматом

Хорошая мысль! А также еще и регионы :)

**Comment by iton1** [comment]
Я тоже за, это очень нужная вещь! Еще бы в полях тоже пригодилось!
