### ISSUE TITLE
Проработать работу с видео

### ISSUE THREAD

**Issue by pumpuic** [instantsoft/icms2#208]
Как я уже писал, фэйсбук последнее время больно сильно раскручивает свои видео поэтому нужна удобная система для встраивания такого видео.
В системе есть такая возможность:
`<facebook>ссылка на видео</facebook>`, но нет кнопки фб видео, или если использовать систему [кнопки видео](http://i.imgur.com/aKr4QvO.png) то нужные теги для фэсбук видео не пропишутся.
Это первое, ну а второе, при редактировании материала видео оборачивается в ссылку и получается что-то этакое: http://i.imgur.com/YVfCLUv.png и весь смысл от тегов исчезает.
Ну и последнее, после вывода видео ничто не говорит о том что это видео как в ютуб плеере: http://i.imgur.com/T480rCE.png

В идеале конечно же просто парсер всех возможных видео, тот же вк, фб, рубут и иже, вставляешь ссылку в [окошко видео](http://i.imgur.com/aKr4QvO.png) и оно оборачивается на автомате нужными тегами, под самим заголовком видео написать сервисы которые поддерживаются.

**Comment by fuzegit** [comment]
> В идеале конечно же просто парсер всех возможных видео

Этого не будет в коробке. для этих целей есть InstantVideo.

**Comment by pumpuic** [comment]
Жаль. Посмотрел упомянуты
