### ISSUE TITLE
Доработка фильтра по полю 'city'

### ISSUE THREAD

**Issue by maxicms** [instantsoft/icms2#209]
Возможно стоит сделать более удобную работу поля city в фильтре, чтобы можно было выбирать не только город, но и регион и страну. просто пример доска объявлении если интересует контент по целому региону, а не только по отдельному городу.

**Comment by fuzegit** [comment]
> чтобы можно было выбирать не только город, но и регион и страну

так все же есть с 2.5.0 http://demo.instantcms.ru/board
http://docs.instantcms.ru/manual/ctypes/fields/types#местоположение

**Comment by maxicms** [comment]
Отстаю от жизни.
