### ISSUE TITLE
Группы

### ISSUE THREAD

**Issue by deranon** [instantsoft/icms2#211]
Группам не хватает некоторых проверок. Таким образом, если иметь два аккаунта, один может пригласить второго в любую группу, даже если та приватная через панель справа (проще говоря, в поле пригласить высвечиваются даже те группы, в которых пользователь не состоит, включая как открытые, так и закрытые). А сам владелец группы в свою очередь не может удалять пользователей из группы, что не есть хорошо.

**Comment by klubnik** [comment]
Управление пользователями очень необходимо.
