### ISSUE TITLE
Хуки и доп.возможности в группах

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#214]
(со стороны разработчика)
1. Не хватает возможностей расширения функциональности групп:
Пример как это сделано в профилях пользователей: добавляем хук - имеем свою вкладку в группе.
В настоящее время группам не хватает гибкости.
(со стороны пользователей)
2. + предыдущий камент в управлении пользователями админами групп
3. Во вновь созданной группе нет вкладки "Контент", следовательно пользователю остается только догадываться куда нажать чтобы опубликовать пост. Либо отдельно выводить спец ссылку.
4. Дополнительное управление опубликованным в группе контентом со стороны администрации группы (создатели группы должны иметь возможность моерировать контент в своей группе)

**Comment by klubnik** [comment]
Не совсем хорошо вкладка контент.  По-возможности контент должен быть сразу же на странице группы. Хорошо бы и форма так же.
Тип контента можно было бы выбирать примерно как это сделано в Tumblr. Самый логичный вариант, который вижу.
