### ISSUE TITLE
Ошибка в виджете Список контента.

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#220]
Не правильно выводится количество материалов в виджете "Список контента". На примере видео.

Если видео добавлено в несколько категорий, у которых один родитель, то в этом случае проявляется такая ошибка. Например, есть _категория_ **Фильмы**, внутри нее _подкатегории_ **Боевики**, **Комедии**, **Триллеры**. Если фильм добавлен во все эти 3 _подкатегории_, то он выводится один вместо 3-х, когда в настройках виджета указано выводить контент из _категории_ **Фильмы**. Есть еще _категория_ **Мультфильмы**, внутри которой, например, _подкатегория_ **Советские**. Так вот, если добавить один фильм в _подкатегории_ **Боевики** и **Комедии** (которые внутри категории **Фильмы**), а также в _подкатегорию_ **Советские** (в _категории_ **Мультфильмы**), то в виджете списка для _категории_ **Фильмы** этот фильм будет занимать **2 позиции, вместо одной**. 

Шаблон default либо другой - значения не имеет. Для всех типов контента.

**Comment by vikontkg** [comment]
На сегодняшний день Виджет Список категорий вообще не показывает количества материалов в категории и для этого нет даже опций! Даже удивлен, что это когда то было! А ведь надо.
Еще виджет Списка категорий показывает список категорий не в столбик (каждая категория с новой строки), а горизонтально. Категории с короткими именами оказываются на одной строке. Это, возможно, где то надо, но в основном категории нужны в столбик Сделайте вид вывода списка категорий опционально/
