### ISSUE TITLE
Ошибка доступа 2.5.1

### ISSUE THREAD

**Issue by mk198** [instantsoft/icms2#221]
При выставлении в пункте меню "Не показывать группам" - Гости, сам пункт меню исчезает, но страница по прежнему открывается, а должна выдавать 404

**Comment by asnenne** [comment]
Не должна. Настройки приватности для страницы при редактировании самой страницы. Причем здесь пункт меню? Это в джумле так кажется.

**Comment by mk198** [comment]
В первой ветки было именно так. А каким образом тогда можно закрыть страницу /users некоторым группам пользователей?

**Comment by asnenne** [comment]
Никак нельзя.

**Comment by mk198** [comment]
В том и вопрос. Если сделать аналогично первой ветке, чтобы при скрытии пункта меню также и сама страница отдавала 404 или страницу с информацией, что у вас нет доступа, то все бы решилось на этом уровне.

**Comment by mk198** [comment]
Попробуйте закрыть страницу /albums от некоторых групп, через тип контента у меня также не получилось.

**Comment by fuzegit** [comment]
> но страница по прежнему открывается, а должна выдавать 404

не должна
