### ISSUE TITLE
Интегрировать датапикер в стиле windows 7/10

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#225]
Удобный выбор даты - демо http://nazar-pc.github.io/PickMeUp/
Обсуждение на хабре https://habrahabr.ru/post/202640/

**Comment by iAndroS** [comment]
Вот еще варианты:
https://github.com/eternicode/bootstrap-datepicker
http://eonasdan.github.io/bootstrap-datetimepicker/
http://t1m0n.name/air-datepicker/docs/index-ru.html
Последний вроде самый симпатичный )

**Comment by nomad48** [comment]
а чем не устраивает который сейчас, все что Вы показали - имхо колхоз темный.

**Comment by Val-Git** [comment]
Не все так просто)) Т.е. конечно же поменять datepicker не проблема, но iCMS по умолчанию пользуется набором компонент jQuery UI (в который входит и datepicker). Указанный набор компонентов достаточно тяжеловесный, и заменяя датапикер вы добавляете веса странице, что не скажется положительно на производительность.

> Последний вроде самый симпатичный )

Это вообще не критерий функциональности! Даже тот который используется сейчас можно стилизовать абсолютно в любом виде (в том числе и под air-datepicker). Нужно смотреть в первую очередь на функционал и UX

**Comment by iAndroS** [comment]
@nomad48 не устраивает выбором даты, в частности, года. Кто день рождения отмечает или какое-то историческое событие, гораздо удобнее в одном квадратике наблюдать и листать десятилетиями, чем из выпадающего списка выбирать или вручную забвать. Да, и с мобилки выпажающие списки не очень удобны. В этом же случае было бы очень удобно выбирать год (если конечно багов не будет)!

**Comment by iAndroS** [comment]
@Val-Git ну, я ж не говорю, что конкретно какой-то из этих скриптов нужен. Просто предложил как вариант, может и на ui такой найдется. Важен более удобный способ выбора года.
Я еще видел, как время удобно выбирать можно, но это уже другая тема совсем )))

**Comment by Val-Git** [comment]
@iAndroS про выбор года, согласен с вами, от того и использовал у себя не стандартный, т.к. мне не понравился именно этот момент))
Со временем, в рамках iCMS в том виде как оно есть сейчас, сомнительный функционал. Я к тому, что время вместе с датой пока ни где не надо было))

**Comment by nomad48** [comment]
@iAndroS я сегодня выбор года поправил все норм теперь выбирается, в новости про 2.5.1 Лоадырь подсказал.
