### ISSUE TITLE
В redaktor не работает редактирование заголовков 

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#226]
Добрый вечер!

Сегодня добавлял контент на сайт, в redaktor не работает редактирование заголовков (**Заголовок 1, Заголовок 2, Заголовок 3, Заголовок 4, Заголовок 5**), то есть нельзя изменить цвет, сделать заливку для них. Пробовал отключать, включать типограф - не помогает. Вручную, через "Код" цвет добавляется и сохраняется. Редактирование обычного текста работает нормально.
![25-04-2016 21-07-55](https://cloud.githubusercontent.com/assets/9349934/14795649/10b72ca0-0b32-11e6-87f8-01c44eaf104b.png)

**Comment by Val-Git** [comment]
думаю причина в **../wysiwyg/redactor/css/redactor.css** строка 911:
`color: #000;`

**Comment by Alex-HAV** [comment]
Как мне кажется потому что стили для заголовков задаются в файлах css

**Comment by nomad48** [comment]
@Alex-HAV  я проверил, не из-за этого на версии ICMS 2.4.0 все редактировалось.

**Comment by nomad48** [comment]
Скажите пожалуйста, а как посмотреть решение? Или закрыли просто?

**Comment by fuzegit** [comment]
здравствуйте, @nomad48 . Текущая версия на гите не содержит указанного бага, см. список коммитов.

**Comment by pocus-1** [comment]
**nomad48**, это здесь, так понимаю.
[https://github.com/instantsoft/icms2/commit/455a70d2233246469f609ed331d6bd5f5ed74e00](url)

**Comment by nomad48** [comment]
@pocus-1 там 404

**Comment by pocus-1** [comment]
Ссылка зарезана, надо через ctrl+copy
А лучше отсюда
https://github.com/instantsoft/icms2/commits/master
Там что-то про безопасность добавили.

**Comment by nomad48** [comment]
@pocus-1 не могу найти, тыкните носом

**Comment by pocus-1** [comment]
Так в самом верху по [предыдущей ссылке](https://github.com/instantsoft/icms2/commits).
Короче, там [откат Redactor-а к версии 9.2.6](https://github.com/instantsoft/icms2/commit/455a70d2233246469f609ed331d6bd5f5ed74e00). Видимо, как раз к той, которая у вас работала без ошибок на 2.4.0. По хорошему надо новую версию покупать.

**Comment by nomad48** [comment]
@pocus-1 благодарю, теперь понял
