### ISSUE TITLE
Закрепление типов контента.

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#229]
Добрый день. 
Было бы не плохо внедрить в типы контента закрепить (прилепить) статью, пост, новость, чтобы запись всегда находилась сверху. В данный момент, при добавлении новой записи, старые уходят вниз. И чтобы закрепленные записи в виджетах контента, тоже отображались первыми.
Это вижу таким образом, при добавлении записи, вместе со служебными полями, должен быть чекбокс - закрепить (прилепить) запись, ну и соответственно в админке в типах контента дать доступ, кто может этой функцией пользоваться (обычно модератор, админ)

**Comment by my-instantcms** [comment]
можно реализовать с помощью [Наборы](http://docs.instantcms.ru/manual/ctypes/datasets)

**Comment by nomad48** [comment]
@my-instantcms это немного не то, потому что в виджете не будет работать. Мне надо допустим чтобы Важная новость в потоке других новостей не терялась, а была всегда закреплена на первой позиции. А в случае наборов, нажмёт не нажмет юзер.

**Comment by pumpuic** [comment]
Поддержу, полезно, особенно со всякими новостями. 
Что касается виджетов, думаю тут должен быть выбор, будет ли зависеть вывод от того что прикреплено или нет, а так же выводить только прикрепленное, например(так можно монетизировать, те же объявления, например).

**Comment by fuzegit** [comment]
> это немного не то, потому что в виджете не будет работать

будет, если в виджете выберите набор также.
Собственно да, это все решается наборами.

**Comment by nomad48** [comment]
@fuzegit мне кажется это немного не то, как с помощью набора новость будет закреплена на первом месте? Чтобы при добавлении других, менее важных, она не уходила вниз.

**Comment by fuzegit** [comment]
Сортировкой по полю

**Comment by nomad48** [comment]
@fuzegit а нельзя так реализовать? Как это сделать наборами я просто не представляю.
![30-04-2016 19-11-42](https://cloud.githubusercontent.com/assets/9349934/14937162/7f381a26-0f07-11e6-8e43-453c03adc197.png)

**Comment by fuzegit** [comment]
1. Создаете поле типа чекбокс "Закрепить на главной"
2. Создаете датасет, где указываете сортировку по этому полю по убыванию, а второй сортировкой делаете нужную вам сортировку записей, например по дате.

Если этот датасет будет первым в списке, то он применится по умолчанию.

**Comment by nomad48** [comment]
@fuzegit  я прошу прощения, а что такое датасет?

**Comment by fuzegit** [comment]
@nomad48 датасет это синоним набора

http://docs.instantcms.ru/manual/ctypes/datasets

**Comment by nomad48** [comment]
@fuzegit понятно, будем пробовать. Спасибо.
