### ISSUE TITLE
Ручная сортировка контента

### ISSUE THREAD

**Issue by numinaki** [instantsoft/icms2#231]
В первой ветке есть возможность сортировать контент в том порядке, каком нужно вручную, т.е. указать последовательность без фильтров и сортировки. Этой функции не хватает и во второй ветке, т.к. часто бывает невозможно сортировать контент в нужной последовательности без создания дополнительных полей и других заморочек. Примерно также как сортируются категории. Спасибо.

**Comment by vlad7090** [comment]
да, этого очень сильно не хватает 2-ке. оптимальнее всего организовать это перетаскиванием контента в админке, как можно перетаскивать остальные эллементы интерфейса. и во фронтенде было бы тоже отлично админу иметь такую возможность. удобно при создании каталогов.

**Comment by numinaki** [comment]
В виджетах было бы круто!)
