### ISSUE TITLE
Добавить "модальность" полю изображение

### ISSUE THREAD

**Issue by pumpuic** [instantsoft/icms2#232]
Имеем поле изображение. оно не увеличивается по клику, это неправильно.
Желательно чтобы был выбор, т.к. разрешить увеличивать изображение по клику или нет.

**Comment by nomad48** [comment]
@pumpuic дополнение [colorbox](http://www.instantcms.ru/blogs/esli-dolgo-muchitsja/colorbox-v-pole-ft-html-tipa-kontenta.html) не смотрели? я поставил неплохо работает.

**Comment by pumpuic** [comment]
@nomad48 все это не вопрос, я говорю за то, чтобы это было по умолчанию.

**Comment by Margauza** [comment]
Да очень удобная штука, имею ввиду колорбокс. Думаю большинству он будет полезен, если нужно сопроводить статью пошаговыми фотками например (мастерклассы). В дефолте либо нужно вставлять огроменные фотки в статьи, либо уменьшать их, но тогда ничего не видно да и с адаптивностью не все в порядке. Я себе поставила, но теперь, на странице где он установлен, невозможно голосовать, так как он пытается открыть картинку голосования за статью, вместо того чтобы плюснуть или минуснуть. Никто не хочет попросить автора идеи с колорбоксом пульреквестнуть на гит?

**Comment by nomad48** [comment]
@Margauza Марго, все давно решено, тем картинкам которым вы не хотите чтобы открывал colorbox,  пропишите  класс no_colorbox, а автор все описал [тут](http://www.instantcms.ru/blogs/esli-dolgo-muchitsja/colorbox-v-pole-ft-html-tipa-kontenta.html#c89495)

**Comment by vlad7090** [comment]
да, по умолчанию такое надо этому полю
