### ISSUE TITLE
Изменить вывод в списке поля "Дополнительные фотографии"

### ISSUE THREAD

**Issue by pumpuic** [instantsoft/icms2#233]
Всем привет. Есть непреодолимое желание избавиться от поля "изображение" в некоторых типах контента(доска объявлений, например) и использовать только "Дополнительные фотографии", т.к. юзеру зачастую лениво выбирать два раза фотки, тут все понятно. Все с этим полем шикарно, кроме одного - вывод в списке, т.е. выводятся все изображения из этого набора, а надо бы только одно, как в [виджетах](http://i.imgur.com/AjniC4h.png), например. 
![screenshot_1](https://cloud.githubusercontent.com/assets/18246784/14909651/52885592-0e10-11e6-8320-8173cfbc106a.jpg)

**Comment by fuzegit** [comment]
Назовите поле именем photo и будет одно изображение в списке, см. демо сайт.
