### ISSUE TITLE
Возможность создать дополнительные группы пользователей

### ISSUE THREAD

**Issue by pumpuic** [instantsoft/icms2#235]
Вдохновленный биллингом и такой функцией как "подписка", подумалось, а на что подписывать юзера, на модератора, админа? Поэтому предлагаю создать возможность администраторам самим создавать группы пользователей с нужными им правами и возможностями.
Для примера: доска объявлений, создаем группу "премиум" с возможностью неограниченного постинга объявлений в разные категории, при этом обычный юзер не сможет столько постить.

Либо, на худой конец, добавить две лишние группы аля менеджер и премиум.

**Comment by mafru** [comment]
Не совсем ясно, что имеется ввиду. Никто-же не обязывает вас делать подписку на модератора или администратора. 
В админке есть возможность создания любой группы пользователей и дать ей необходимые права.
Добавлять в коробку указанные вами группы, не рационально, т.к. не всем необходимы указанные группы.
