### ISSUE TITLE
Счетчик контента в категориях списка контета

### ISSUE THREAD

**Issue by iWeb1** [instantsoft/icms2#237]
Здравствуйте ! Очень было бы удобно когда пользователь видит количество (счетчик)
контента в просмотре списка категорий контента когда он включен на сайте! Пожалуйста примите во внимание для icms 2.5.1 и выше ! Спасибо !

![2016-05-08_021801](https://cloud.githubusercontent.com/assets/19244500/15095184/a7ed5744-14c3-11e6-8dc0-860f803c9b62.jpg)

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/1677b98c59d6bd5ea3a61f9f316a117ff0911489
