### ISSUE TITLE
Open Graph протокол - для все видов контета

### ISSUE THREAD

**Issue by iWeb1** [instantsoft/icms2#238]
Здравствуйте ! Так как на сайте стоят кнопки социальных сетей то актуально было внедрить Опен граф, который дает нам возможность управлять внешним видом анонсов статей, которые пользователи отправляют в социальные сети, «лайкая» и «плюсодинкая» наши статьи.

`<meta property="og:title" content="Мэрилин Монро"/>
<meta property="og:description" content="Американская киноактриса и певица"/>
<meta property="og:image" content="https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Marilyn_Monroe_-_publicity.JPG/210px-Marilyn_Monroe_-_publicity.JPG">
<meta property="og:type" content="profile"/>
<meta property="og:url" content= "https://ru.wikipedia.org/wiki/Мэрилин_Монро" />`

Когда пользователь кликает лайки то в социальных сетях конкретно отобоажается тот или иной материал!

**Очень просим разработчиков внедрить Open Graph протокол !**

![og](https://cloud.githubusercontent.com/assets/19244500/15095253/48d7d092-14c6-11e6-85ee-44e18a242aea.png)

**Comment by fuzegit** [comment]
все давно есть и работает http://addons.instantcms.ru/addons/ogp-me.html
