### ISSUE TITLE
Генерация URL

### ISSUE THREAD

**Issue by deranon** [instantsoft/icms2#241]
При генерации URL статей или любого другого контента в конце приписывается месяц создания/редактирования вопреки всем настройкам и свойствам заданным в поле "Шаблон генерации URL"
![byfqw8p_4ry](https://cloud.githubusercontent.com/assets/7442248/15174617/2352b704-176b-11e6-946e-571cc1107060.jpg)
![gkcwbhs4z_4](https://cloud.githubusercontent.com/assets/7442248/15174625/2cef880a-176b-11e6-8398-8e9b874f51d9.jpg)

**Comment by fuzegit** [comment]
Потому что урл не может состоять только из одних цифр.
Если все же нужно убрать такое поведение, то http://www.instantcms.ru/forum/thread24427.html

**Comment by deranon** [comment]
До обновления 2.5.0 такой проблемы не возникало и URL генерировался из цифр без проблем. Тому доказательством будут URL сгенерированные ранее, до обновления. Если сомневаешься, могу дать ссылку, сам посмотришь.
![7_jcmvom4cc](https://cloud.githubusercontent.com/assets/7442248/15174963/d01d21a8-176c-11e6-8d8e-134bb4f17464.jpg)

**Comment by fuzegit** [comment]
Мне нечего смотреть и сомневаться, я прекрасно понимаю о чем вы пишите.

**Comment by deranon** [comment]
Так или иначе, с апреля к ссылкам прибавляется месяц.

**Comment by fuzegit** [comment]
Я вам дал ссылку выше как изменить поведение по-умолчанию. Невозможность делать циферные урл сделано осознано.
