### ISSUE TITLE
Кнопка для администратора - "Поднять объявление выше всех"

### ISSUE THREAD

**Issue by iWeb1** [instantsoft/icms2#242]
Здравствуйте Уважаемые разработчики icms2! В очередном обновлении очень хотелось бы в контенте объявления иметь кнопку или галочку - "Поднять объявление выше всех" (разово) -не постоянно на первом месте, например в объявлениях Джумлы есть такая кнопка, точнее галочка. Рассмотрите пожалуйста это предложение в очередном обновлении v 2.5.1 и выше! Спасибо, что Вы  есть !

**Comment by Val-Git** [comment]
Уважаемый @iWeb1, пожалуйста думайте о всей CMS а не только удовлетворение своих потребностей! Хотите вы эту кнопку в объявлениях напишите

> очень хотелось бы в  любом типе контента иметь кнопку или галочку - "Поднять объявление выше всех"

У многих тип контента "объявления" вообще может отсутствовать! И как в таком случае использовать ваш функционал?

_Вообще, по последним коммитам создается впечатление что InstntCMS - это всего лишь движок для создания досок объявлений =(_

P.S. мой коммент не означает "за" или "против" предлагаемого функционала, просто крик души...

**Comment by fuzegit** [comment]
> по последним коммитам

последним предложениям все же наверное?) а не коммитам

> пожалуйста думайте о всей CMS а не только удовлетворение своих потребностей

бесполезно, уже говорилось. пусть пишет)

**Comment by iWeb1** [comment]
Не соглашусь с Вашим мнение - многие на истанте имеют порталы и соответственно объявления ! А кнопка "Поднять объявление" - просто необходима в коробке !!!

**Comment by nomad48** [comment]
@iWeb1 это всё есть в компоненте Биллинг

**Comment by iWeb1** [comment]
Спасибо ! Хоть один человек подсказал !

**Comment by Val-Git** [comment]
> последним предложениям все же наверное?) а не коммитам

@fuzegit , да, конечно же предложениям)) Подумал про коммит, и написал по ошибке

> Не соглашусь с Вашим мнение - многие на истанте имеют порталы и соответственно объявления ! А кнопка "Поднять объявление" - просто необходима в коробке !!!

Смысл моего сообщения был не в кнопке, а в направлении взгляда на движок. Если вы пишете предложение внести какой-либо функционал, продумайте его так чтобы он мог использоваться не только вами, но и другими пользователями. Т.е. фича которая будет универсальна для широкого круга задач.
