### ISSUE TITLE
Аватар по умолчанию (если не загружен свой)

### ISSUE THREAD

**Issue by iWeb1** [instantsoft/icms2#245]
Здравствуйте Уважаемые разработчики ! Очень удобно и эстетично, было бы сделать Аву по умолчанию, если пользователь не загрузил свою в виде первой буквы Никнейма например  А с выбором цвета заднего фона для всех, т.е. чтобы цвета Аватаров были одинаковае для всех а не в разнобой ! 
Пример:
![ava_default](https://cloud.githubusercontent.com/assets/19244500/15215766/d2d3bace-185c-11e6-9e7b-388a8c8fb54a.jpg)

**Comment by Val-Git** [comment]
@iWeb1, а чем удобно и чем эстетично?

**Comment by iWeb1** [comment]
Вот например в почтовом сервисе mail.ru такая функция есть и если по какой либо причине (отсутствие фото или не имение желания загружать аву!)
**Выглядит лучше, чем ава "Человека Невидимки"**

**Comment by Val-Git** [comment]
Вы сами себе противоречите =)
Не нравятся буквы, отключите их и будет аватарка по умолчанию, как на приведенном вами рисунке. В чем проблема?

**Comment by iWeb1** [comment]
Где отключить или включить буквы ?
Вот они "Невидимки" и выглядит это не красиво !!!
![nevidimki](https://cloud.githubusercontent.com/assets/19244500/15217431/399558d8-1864-11e6-8fa8-b8b15dc5b145.jpg)

**Comment by mafru** [comment]
http://www.instantcms.ru/novosti/release250.html#c90346
