### ISSUE TITLE
Виджет подписка для всех видов пользователей в том числе и гостей 

### ISSUE THREAD

**Issue by iWeb1** [instantsoft/icms2#246]
Здравствуйте Уважаемые разработчики  icms2 ! Пожалуйста сделайте коробочный витжет "Подписаться на  (название контента)" с автоматической регистрацией на сайте подписанного пользователя - очень нужный витжет с одновременным увеличением юзеров !

Пример:

![podpiska](https://cloud.githubusercontent.com/assets/19244500/15216346/6431761c-185f-11e6-8b5d-642944ba5f30.jpg)

**Comment by iWeb1** [comment]
Почему Отклонили ? Тема же актуальная !

**Comment by fuzegit** [comment]
> Тема же актуальная

Так и сделайте эту актуальную тему себе. Ваш спам здесь в части доработок вашего сайта уже начинает надоедать.

**Comment by iWeb1** [comment]
**Это не СПАМ** - _Это актуальные и важные предложения по у темы по улучшению сервисов icms2  !_

**Comment by iWeb1** [comment]
**Где в данном предложении усматривается СПАМ согласно его трактовке ?**
