### ISSUE TITLE
Мета-теги для тегов

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#251]
Навеяно [темой с форума](http://www.instantcms.ru/forum/thread24778-1.html) и последующим изучением на примере wordpress. 
Предлагаю реализовать мета-теги для тегов. Извиняюсь для тавтологию, но посмотрите на оные в wordpress и все будет ясно и понятно. Добавляем тег (метку), а в админке на странице тегов добавляем уже описание для них. Причем для разных типов контента, а возможно и для его категорий, необходима возможность указания своих мета-тегов к тегам.
Пример. У меня каталог компаний на мапсе. Региональные кеи (а, соответственно, и трафик), нам собрать практически нереально. В случае же реализации данного предложения мы сможем собрать большую массу тематического трафика при грамотном применении этих тегов.
Что мы сделаем для записей: добавляем. к примеру, следующие теги "Новосибирская область", "Бердск" и "Круглосуточно". К тегам прописываем мета-теги "Все автосервисы Новосибирской области", "Все автосервисы Бердска" и "Все кругосуточные автосервисы". Данные мета-теги ОЧЕНЬ помогут собрать кучу трафика!

**Comment by WebManG** [comment]
Хотя бы один вариант мета-тега для каждого тега без привязки к типам контента и категориям - и то уже было бы полезно для СЕО.
