### ISSUE TITLE
Нельзя удалить значение в поле "город"

### ISSUE THREAD

**Issue by altroid** [instantsoft/icms2#254]
Отсутствует кнопка удаления значения в поле "город"
Если мы ставим поле необязательным, но значение уже было указано зарание - убрать его не получится без входа бд.

**Comment by perervar** [comment]
Поддерживаю! Такая проблема не только с полем выбора города. Также невозможно удалить поле координаты (если ранее было выставлены), также невозможно удалить из выпадающих списков, например если ранее было выбрано какое либо значение, то после этого нельзя его отключить.

Решается только путем удаления данных из базы данных, но естественно только администратору а не пользователям. Хотелось бы что можно было удалять (выключать) поля таких типов, если ранее в них были выбраны значения.
