### ISSUE TITLE
Добавить возможность добавлять страны и города

### ISSUE THREAD

**Issue by altroid** [instantsoft/icms2#255]
В данный момент есть необходимость добавить страну в профиль пользователя, понятное дело что можно через текстовое поле, но через стандартное поле "страны" не получается. Значение страны "Колумбия" отсутствует, и как видимо многих других стран.
Добавьте пожалуйста настройки компонента гео.

**Comment by StAlKeRxXl** [comment]
Есть дополнение бесплатное для этого.. поищите внимательнее
