### ISSUE TITLE
Добавить возможность скрыть системные поля профиля

### ISSUE THREAD

**Issue by altroid** [instantsoft/icms2#256]
Добавьте пожалуйста возможность скрыть системные поля профиля для разных групп пользователей, например такие как "Последний визит", "Регистрация"

**Comment by fuzegit** [comment]
Это не поля, а вывод значений. Решается в шаблоне.

**Comment by altroid** [comment]
Решается через шаблон для разных групп пользователей?

**Comment by fuzegit** [comment]
Решается так, как вам необходимо на вашем проекте.
