### ISSUE TITLE
Добавить в админку кнопку "Редактировать профиль"

### ISSUE THREAD

**Issue by altroid** [instantsoft/icms2#258]
Добавьте пожалуйста в админку в раздел "пользователи" кнопку "редактировать профиль", будет намного удобнее и быстрее управлять пользователями

**Comment by WebManG** [comment]
А чем именно неудобен существующий вариант? Сейчас есть две кнопки: "Редактировать" основные данные пользователя прямо в Админке и открыть "Профиль", в котором можно щёлкнуть пункт действий "Редактирование профиля", если нужно.

**Comment by Vampireos** [comment]
@altroid карандашик справа и есть редактировать, или желаете просто кнопку более заметную?

![image](https://cloud.githubusercontent.com/assets/1193738/16711076/8ee3fe4c-465a-11e6-869c-21203bba947a.png)
