### ISSUE TITLE
Наборы - SEO и детали

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#260]
В данный момент функционал наборов применяется ко всем типам контента, а хотелось бы реализовать также и для его категорий отдельно. Также к наборам необходимы мета-теги.
Для чего это может быть полезно? Для выведения быстрого результата фильтрации объектов из каких-либо каталогов (не обязательно мапса, как в моем примере). Например, у меня каталог обуви. Я могу вывести в категории Детская обувь наборы "Школьная", "Для младенцев" и т.д. Вопрос можно было бы решить тегами, но движок не поддерживает возможность фильтрации контента по нескольким тегам! И опять-таки, у тегов нет meta-тегов...
В текущем виде наборы не нравятся поисковикам, и это факт, приходится их закрывать от индексации. Опять-таки, url наборов формируются вне структуры сайта, что также не есть хорошо http://prnt.sc/b9vcnf

**Comment by fuzegit** [comment]
> В данный момент функционал наборов применяется ко всем типам контента, а хотелось бы реализовать также и для его категорий отдельно.

наборы распространяются и к категориям.

> Также к наборам необходимы мета-теги.

добавим.

> Опять-таки, url наборов формируются вне структуры сайта

с этим ничего не сделать
