### ISSUE TITLE
Перемещение виджетов среди неактивных

### ISSUE THREAD

**Issue by san-sanych-k** [instantsoft/icms2#262]
При перемещении виджетов drug-and-drop в админке между другими виджетами доступно только между активными, что не совсем удобно. Нельзя поставить виджет выше неактивного или между неактиными. Только вниз.

**Comment by my-instantcms** [comment]
У меня всё работает.
Под словом "активные" вы наверно имеете ввиду, виджеты из **Все страницы**

**Comment by krylos** [comment]
Вот на скрине пример со стрелкой какой виджет куда не перемещается.
http://prntscr.com/bcrfn2

**Comment by WebManG** [comment]
Да, это было бы удобно.
