### ISSUE TITLE
Ошибка при генерации карты сайта

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#266]
В карту сайта sitemap.xml при генерации записываются также не опубликованные страницы (Публиковать на сайте - Нет). Это не правильно! Так как робот пытается проиндексировать их, но получает ответ 404.

Проверял на разных типах контента.

**Comment by fuzegit** [comment]
2.5.1 не подтверждается.

**Comment by asnenne** [comment]
Поставил чистый движок 2.5.1, установил мапс, импортировал объекты (900 примерно), но они не опубликованы - обрабатываю вручную. Опубликованных 5. Сгенерировал карту сайта - в ней 900 объектов. Также и со статьями. Вот пример: http://w-17.com

**Comment by fuzegit** [comment]
может кеш включен и при нем такое поведение. я разумеется проверил тоже - неопубликованные в карту не попадают.

**Comment by asnenne** [comment]
Кеширование отключено.

**Comment by asnenne** [comment]
Установлены дополнения: мапс, биллинг, опенграф, пинг, ulogin. Остальное из коробки.

**Comment by fuzegit** [comment]
вы проверяйте не на InstantMaps, а на том, что в комплекте

**Comment by asnenne** [comment]
Проверял на статьях. Такая же ситуация.

**Comment by fuzegit** [comment]
![1](http://storage7.static.itmages.com/i/16/0614/h_1465898398_4507368_ca5b93f53f.png)

![2](http://storage8.static.itmages.com/i/16/0614/h_1465898400_6112885_60b680955d.png)

![3](http://storage9.static.itmages.com/i/16/0614/h_1465898401_3688886_5d40f12c59.png)

**Comment by asnenne** [comment]
Вот второй сайт - опубликован только 1 объект. В карте все. А вот со страницами порядок. `https://stro.by`

**Comment by fuzegit** [comment]
Проверю еще раз

**Comment by asnenne** [comment]
Попробуйте с постами (posts) проверить.

**Comment by asnenne** [comment]
Я демо-контент не ставил. Тип контента posts создавал сам. И с ним проблемы. Может быть не правильно работает именно с теми типами контента, которые добавлены после установки движка? Предположение.

**Comment by asnenne** [comment]
Да, со страницами нормально и на первом сайте. Одна опубликована, одна - нет. В карте 1 запись.

**Comment by fuzegit** [comment]
Понял в чем проблема, ожидайте коммит.

**Comment by asnenne** [comment]
Спасибо.

**Comment by fuzegit** [comment]
Проверяйте, исправил.

**Comment by asnenne** [comment]
Всё ОК. Спасибо.
