### ISSUE TITLE
В объявлениях не работает сторонний пресет

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#267]
Добрый вечер, Уважаемые разработчики ICMS.
Обнаружил у себя проблему (ICMS 2.5.1 - шаблон свой)
1. В типе контента объявление создал отдельный пресет small_board размером 64х64 для поля Фотографии, так как системный small у меня 130х130 и используется практически по всему сайту.
2. Все настройки сделал и проверил как на демо-сайте в объявлениях.
3. После загрузки изображений в объявление отображается только фото выбранное первым, остальные фото загружаются, пресеты создаются, но в самом объявлении их не видно. Они есть в базе и они есть на сервере. Все фото с размером "big" отображаются корректно в модальном окне.
4. Если снять чекбокс "Выделять первое изображение в записи" - то фотографии вообще не отображаются.
Консультировался с @my-instantcms - Парвиз выразил предположение, что это баг системы.
Системные файлы не менял и не правил.
Ссылка на проблемное объявление http://lovelovely.ru/board/11-poznakomlyus-s-devushkoi.html
Скрины прилагаю.

![16-06-2016 13-56-39](https://cloud.githubusercontent.com/assets/9349934/16127654/103c8bb0-3406-11e6-9589-9ceb841ab173.png)
![16-06-2016 14-01-09](https://cloud.githubusercontent.com/assets/9349934/16127652/1034572e-3406-11e6-88f3-e2e203825a11.png)
![16-06-2016 14-11-07](https://cloud.githubusercontent.com/assets/9349934/16127653/10362af4-3406-11e6-9bb4-1ba5065be14a.png)
![16-06-2016 14-28-31](https://cloud.githubusercontent.com/assets/9349934/16127651/0ff10fd2-3406-11e6-9b23-ea7e2ffddfd1.png)
![16-06-2016 20-28-30](https://cloud.githubusercontent.com/assets/9349934/16127655/1053f502-3406-11e6-9110-b16fd3542515.png)
![16-06-2016 21-03-00](https://cloud.githubusercontent.com/assets/9349934/16127650/0fe85536-3406-11e6-94a7-6f8bdabc083d.png)

**Comment by Dimson-Git** [comment]
У меня то же самое. Недавно также  столкнулся с этим

**Comment by nomad48** [comment]
`if($this->getOption('first_image_emphasize') && !$small_preset){
                $small_preset = $this->getOption('size_full');
                $a_class = 'first_type_images';
            } else {
                $small_preset = 'small';
             }`
Вот тут прописан small жестко. Можно ли как-то сделать чтобы был выбор пресета из созданных.

**Comment by Val-Git** [comment]
@nomad48 вчера, на сон грядущий пришла идея, попробуйте протестировать:

В файле **..\system\fields\images.php** вверху в функцию getOptions() добавляете опцию выбора пресета:
```
            new fieldList('size_others', array(
                'title' => 'Размер в записи 2-ого и последующих фото', // <- Название опции
                'default' => 'small',
                'items' => $presets
            )),
```
а затем вместо `$small_preset = 'small';` прописываете `$small_preset = $this->getOption('size_others');`
как-то так:
```
            if($this->getOption('first_image_emphasize') && !$small_preset){
                $small_preset = $this->getOption('size_full');
                $a_class = 'first_type_images';
            } else {
                $small_preset = $this->getOption('size_others');
            }
```

**Comment by nomad48** [comment]
@Val-Git Доброе утро, так не работает
```
new fieldList('size_others', array(
                'title' => 'Размер в записи 2-ого и последующих фото', // <- Название опции
                'default' => 'small',
                'items' => $presets
            ))
```
а вот так работает
```
new fieldList('size_others', array(
                'title' => 'Размер в записи 2-ого и последующих фото', // <- Название опции
                'default' => 'small_board',
                'items' => $presets
            ))
```

**Comment by Val-Git** [comment]
@nomad48, не должно так быть... Если 'small_board' работает, то и стандартный 'small' также должен отрабатывать. Вы в настройках (в новом поле "Размер в записи 2-ого и последующих фото") выбрали свой пресет? Сохранили все опции после выбора?

**Comment by nomad48** [comment]
Да, проверил еще раз, всё работает как Вы написали! 
![22-06-2016 13-57-00](https://cloud.githubusercontent.com/assets/9349934/16264322/89e0b2aa-3881-11e6-81a1-430442218972.png)
![22-06-2016 13-57-59](https://cloud.githubusercontent.com/assets/9349934/16264321/89e0ba48-3881-11e6-9c86-a5d48edb1055.png)

**Comment by nomad48** [comment]
Проблема решена с помощью правки кода от @Val-Git

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/3ba60516b340c2aabba3056a1ddb5b22a851e688

**Comment by nomad48** [comment]
@fuzegit Скажите пожалуйста, внесенные изменения, исправляют тот недочёт который я описывал, просто @Val-Git немного другой код подсказал. Спасибо за ответ.
