### ISSUE TITLE
Назначение пользователя модератором

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#268]
При выборе модератора в админке не очень удобно всё сделано. Поясню. Выбор модератора осуществляется по имени пользователя (никнейму). Вводим первые буквы имени пользователя и вуаля - выдает список совпадений. Это конечно же здорово! Но как быть, если модератором нужно назначить пользователя с ником "Николай", если на сайте зарегистрировано 12 человек с таким ником?

То же и с владельцами мапса - как выбрать владельца, если с одинаковым ником несколько пользователей?

Предложение к разработчикам сделать выбор пользователя не по имени пользователя, а по id - в этом случае путаница будет исключена.

Спасибо.

**Comment by iAndroS** [comment]
Можно сделать универсальное поле поиска юзеров, которое ищет по id, email, телефону и логину одновременно и выдает список совпадений с указанием всех этих полей и аватаркой...

**Comment by zau4man** [comment]
Апну http://www.instantcms.ru/forum/thread25569-1.html
Это ошибка. И требует решения.
