### ISSUE TITLE
Ошибка при загрузке фотографий в альбомы

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#269]
Добрый день уважаемые разработчики ICMS 2.

Сегодня обнаружил такую ошибку:
1. Если пользователь заходит на страницу фотоальбомов http://домен/albums  и нажимает кнопку загрузить фотографии,
![25-06-2016 16-48-22](https://cloud.githubusercontent.com/assets/9349934/16357069/cea7f5d6-3af4-11e6-987e-9fe668e52bb9.png)
 то при переходе на следующую страницу http://домен/photos/upload ему предлагается два действия:
1-действие - Выбрать фотоальбом или создать новый;
2-действие - Выбрать и загрузить фотографии.
![25-06-2016 16-36-13](https://cloud.githubusercontent.com/assets/9349934/16357059/8c65539e-3af4-11e6-9f26-6db15f631123.png)
![25-06-2016 16-36-27](https://cloud.githubusercontent.com/assets/9349934/16357063/a791b54a-3af4-11e6-9c96-73fc254adee4.png)
Ошибка заключается в том, что если пользователь выберет первым действие № 2 и не совершит действие № 1, а после загрузки фото нажмёт кнопку СОХРАНИТЬ, то фотографии сохраняются на сервере, но ни в какой альбом не загружаются. В базе в таблице: cms_photos фотографии сохраняются, но в столбце album_id прописывается NULL, то есть фотографии нигде не видны.
Проверил и на admin и на тестовом юзере - подтверждается. Обнаружил когда пользователь написал в личные сообщения, что не может загрузить свои фото.

**Comment by nomad48** [comment]
Прошу помочь решить проблему, актуально, пользователи путаются и не знают как разместить фото.

**Comment by Vampireos** [comment]
@nomad48 самым простым решением будет добавить атрибут required к select, который обозначает обязательный выбор в списке, если не выбрано то покажет алерт, но как оказалось картинки грузятся до выбора)
да и этот хак затронет все селекты, которым и не нужно

второй способ более действенный, но тоже есть ньюансы. В дефолтной теме нужно  
в шаблоне _/templates/default/controllers/photos/widget.tpl.php_  изменить 4 строку , таким образом `<fieldset id="js_show_hidden" hidden>` ,а в шаблон _/templates/default/controllers/photos/upload.tpl.php_ вставить кусок скрипта 
`$('select').on('change',function(){
      $('#js_show_hidden').removeAttr('hidden');
  });`
после 44 строки

в итоге всё поле с кнопкой выбора, при открытии страницы Загрузить фотографии, будет спрятано. До того как альбом не выбран. Но есть ньюанс) если нажать кнопку Создать альбом, и создать, по умолчанию он будет уже выбран но поле не появиться пока не выбрать другой альбом)

Вообщем нужна помощь более продвинутого чем я)

**Comment by nomad48** [comment]
@Vampireos я думаю Вы правы, данный баг нужно устранить, но надо правильно сделать.
