### ISSUE TITLE
При автовходе не обновляется время последнего входа

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#273]
Если пользователь зашел на сайт, и прошел автовход (до этого нажимал кнопку "Запомнить меня"). То время последнего визита, после того как он вновь закроет страницу сайта стоит то - которые было в момент авторизации на сайте.

**Comment by nomad48** [comment]
Подтверждаю, тоже самое!

**Comment by fuzegit** [comment]
Не подтверждается. Всё работает корректно. Вероятней всего у вас сессия не "умирает" и срабатывает не автовход, а просто возобновляется старая сессия.
