### ISSUE TITLE
Невозможно установить движок

### ISSUE THREAD

**Issue by pumpuic** [instantsoft/icms2#274]
При попытке установить вылетает [такое](http://image.prntscr.com/image/f32df03ba7f9406eb652edf2da6f163a.png), в бд успевает записаться [это](http://image.prntscr.com/image/fcc17eeb022b4370800cc15d08bea319.png).
Движок с гит-а.

**Comment by pumpuic** [comment]
Что с демо, что без, ошибка одна.

**Comment by Vampireos** [comment]
Подтверждаю, та же самая ошибка, на шаге ввода базы данных, по нажатию **Далее** показывается алерт:

![image](https://cloud.githubusercontent.com/assets/1193738/16710932/b5f85b56-4653-11e6-9d79-e1ee29109ed0.png)

протестировал на php 7 и 5.6 версиях, и на _Apache2_ и _Xampp_ веб серверах, ОС Ubuntu

непонятно куда копать Т Т

поскриптум: самый простой способ добавлять картинки сюда, это копировать картинку в буфер обмена ( через меню или CTRL+C ), и вставкой по ( CTRL+V или также меню ), сильно не пинайте если слишком доходчиво описал)

**Comment by Val-Git** [comment]
А зачем вы устанавливаете CMS из git'а? Если вы решите покупать автомобиль, то возьмёте его у дилера или с конвейерной ленты?
Как выйдет релизная версия, и если в ней вдруг будет такая проблема, тогда действительно стоит об этом написать, а так получается сняли авто с конвейера и заявляем что колес нет и дверей =D

**Comment by fuzegit** [comment]
> А зачем вы устанавливаете CMS из git'а? Если вы решите покупать автомобиль, то возьмёте его у дилера или с конвейерной ленты?

Совершенно верно. @pumpuic  за сообщение конечно же спасибо, проверим, поправим, но CMS все же нужно ставить последнего релиза отсюда http://www.instantcms.ru/get

**Comment by Vampireos** [comment]
@Val-Git @fuzegit мы безумно маниакальные тестеры на стероидах)) проверяем даже то что ещё не вышло)

**Comment by fuzegit** [comment]
> мы безумно маниакальные тестеры на стероидах

это правильно, нам такие нужны) Но CMS все же ставить нужно из официальных релизов.

**Comment by pumpuic** [comment]
@fuzegit все верно, просто я периодически ставлю движок отсюда и смотрю на нововведения которые появляются тут но их пока нет в релизе. 
Это просто заметка, вдруг вы не заметили, не более )
