### ISSUE TITLE
Ограничение создания категорий

### ISSUE THREAD

**Issue by globator88** [instantsoft/icms2#278]
1. Не возможна создать большое количества категорий, так как при выборе, через определенное количество категорий Instant остальных  проста вырезает. Это касается и к выбору с сайта и через админку.
   На пример, я создал 1211 категорий но потом нету возможности выбирать больше 999 что бы создать под категории. http://joxi.ru/a2XQG7nTyG0EXA
2. При категорий с вложенностью 3, первая категория не показывается на странице добавление контента http://joxi.ru/l2Z6Q3xh8d1xM2  Сказали что это баг браузера. В Chrome и Opera точна не работает.

**Comment by Vampireos** [comment]
Скиньте базу данных для повтора ошибки и выяснения причин^ ^

**Comment by globator88** [comment]
Сайт на скринах тестовой сайт (чистый Instant) Vampireos, вам это БД нужно?

**Comment by Vampireos** [comment]
Ваше письмо получено
Мастер ответит вам сразу же как его прочитает

с уважением ИИ КотБегемот^ ^

**Comment by Vampireos** [comment]
@globator88 я про базу на 1200 категорий

**Comment by mafru** [comment]
Случаем не из-за этого лимита https://github.com/instantsoft/icms2/blob/master/system/core/model.php#L19

**Comment by globator88** [comment]
Да кажется из за этого, спасибо!
Надеюсь если поменяю это негативно не на что не будет повлиять :-)
