### ISSUE TITLE
Выбор загруженных изображений во избежание дублирования

### ISSUE THREAD

**Issue by DorimenUkraine** [instantsoft/icms2#280]
Добрый день.

Предлагаю сделать при добавлении контента (например, статьи или новости) возможность выбрать изображение из уже загруженных изображений. Например, на моем сайте без превью статьи не обойтись для эстетики, но очень часто они просто повторяют друг  друга. Какой смысл захламлять сервер одинаковыми картинками? Почему бы не сделать выбор изображения как в том же Wordpress?

Спасибо.

**Comment by fuzegit** [comment]
#80
