### ISSUE TITLE
При удалении записи типа контента из админки не удаляются картинки из поля photo

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#282]
При удалении записи типа контента из админки не удаляются фото из поля. (например поле photo)
Если же удалять штатно с фронтенда - то удаляются.
Вероятно это может касаться не только поля photo, но и других полей с изображениями.

**Comment by mafru** [comment]
Можно подробнее, как это не удаляются фото из поля?
С сервера изображение вроде удаляется, если запись удалить из админки.
Что вы имели ввиду?
