### ISSUE TITLE
При смене названия альбома не обновляются урлы комментариев в профиле

### ISSUE THREAD

**Issue by hard990** [instantsoft/icms2#284]
Если написать/отредактировать комментарий в альбоме и после этого сменить название альбома, то при заходе в профиль этот комментарий ведет на несуществующую страницу т.е по старому урлу, а так же название альбома указанного в комментарии не изменяется!

**Comment by makartsoft** [comment]
Рекомендую поставить галочку "Не изменять URL при редактировании записи" в типе контента . Смена URL -не очень хорошая вещь, особенно, если содержимое уже проиндексировано.
