### ISSUE TITLE
Компактный вариант списка категорий

### ISSUE THREAD

**Issue by globator88** [instantsoft/icms2#289]
Предлагаю добавить опцию для показа компактного (список) варианта категорий над списком записей. При больших количествах категорий список выглядит вот так http://joxi.ru/KAx97gJh4NM90r

Показ категорий над списком записей удобна и в декстопе и в адаптивной версии для мобильников. При меньших количествах категорий это очень удобна, но когда количество категорий много, ситуация меняется. Поэтому можно добавить в настройку типа контента еще одну опцию "Показывать компактный список категорий над списком записей" и сделать последовательный выбор категорий через список. Именно последовательный а не Chosen, так как Chosen вообше не работает в мобильной версии а это делается именно для удобства использование с мобильников. Найти в одном списке нужную категорию среди 4000 категорий если нету возможности ввода, это очень "удобна" в Chosen  ))

А в нашем варианте сначала выбирается главное категория -> переходить на страницу и подгружается второй список если есть подкатегории и так далее.

**Comment by murlysja** [comment]
Поддерживаю, жесть еще та: [http://ugra.ru/places](url). Как вариант, прикрутить алфавитный указатель.

**Comment by fuzegit** [comment]
Всё это прекрасно конечно, но какие будут конкретные предложения? Нарисуйте или как-то словами поясните, как должен выглядеть "компактный" вид категорий. Может покажите сайты с уже сделанным "удобным и компактным" выводом категорий. Потому что я не знаю, как сделать еще более компактно.
Вообще, категории конечно не предназначены для такого их количества.

**Comment by globator88** [comment]
В принципе я написал выше но постараюсь найти пример. Но ясно одно, при больших количествах категорий без списка не как.

**Comment by fuzegit** [comment]
Да, пример бы существенно упростил понимание, как должно быть.

**Comment by murlysja** [comment]
Пример
![alfabet](https://cloud.githubusercontent.com/assets/17600180/18029160/27eb84f2-6c99-11e6-875f-6cb04fece35b.jpg)

**Comment by fuzegit** [comment]
@murlysja отлично, один вариант есть. Если бы еще вместо скриншота была бы ссылка на пример, было бы вообще шикарно.

**Comment by globator88** [comment]
murlysja, при больших категориях тоже будет не то. Лучше списком, последовательный выбор вроде такого http://ruseller.com/lessons/les1321/demo/index.html  
На этом примере кажется список с chosen, лучше без chosen.

**Comment by fuzegit** [comment]
@globator88 я может чего-то не понимаю, но вам важен в **списке категорий** некий последовательный выбор. Последовательный выбор подразумевает выбор первой категории, после чего идет выбор последующей и так далее. Однако, в списке категорий всё именно так. На странице выводятся категории. При входе в одну из них - выводятся её подкатегории и так далее. Как последовательный выбор вяжется с тем, о чем этот тикет?
Вот стандартные статьи и корневые категории

![CMS](http://storage4.static.itmages.com/i/16/0827/h_1472326461_9673776_de85b3c339.png)

Вот мы заходим в категорию и видим её подкатегории

![CMS](http://storage1.static.itmages.com/i/16/0827/h_1472326546_6392841_fedf6450a7.png)

Вопрос. Что вы имеете в виду?

**Comment by globator88** [comment]
Мы об этом и говорим. Что если количество категорий 300 - 500 как на примере? Вместо того что бы занимать столько место можно показать одним списком. потому что список занимает мало места. Мы не отказываемся от стандартного варианта категорий Instant, проста добавляем дополнительный вариант для больших количествах категорий.

**Comment by fuzegit** [comment]
Так я об этом и спрашиваю, как сделать тот самый вариант. В случае с вашим примером последовательного вывода, как сделать тот самый вывод, если все выводимые категории на одном уровне дерева? Если выводит неким списком, то как? @murlysja ответила в контексте обсуждаемой темы - делить по алфавиту. Ваш последовательный выбор мне, увы, непонятен.

**Comment by globator88** [comment]
Вот так http://joxi.ru/ZrJy0Ekf1EwpeA
При больших количествах категорий вообше не занимает место и удобна для мобильных устройств.

**Comment by Val-Git** [comment]
@globator88 проматывать 300-500 категорий на мобильном или десктопе это удобно??? =D

**Comment by fuzegit** [comment]
@globator88 предложенный вами вариант - вообще не вариант. Собственно, мне уже стало очевидно, что вы просто ошиблись в проектировании своего сайта и неверно используете категории, вот и всё.
А в целом проблема в вашем случае решается небольшой корректировкой CSS или же добавлением показанного вами селекта в шаблоне вывода категорий.

Я еще соглашусь, что последовательный выбор категорий, возможно, был бы удобен в форме редактирования и только для дерева категорий, но тут, увы, тикет будет закрыт.

**Comment by globator88** [comment]
Val-Git, в этом случае http://joxi.ru/KAx97gJh4NM90r мы заставляем пользователя проматывать категории каждый раз когда он переходить на вторую, третью и далее страницу. Потому что в узких экранах это почти что тоже самый список. Я на примере показал модели машин, но и в мапс тоже наблюдается где то столько категорий.

**Comment by Val-Git** [comment]
@globator88, Fuze вам уже ответил, поэтому повторюсь - изначально неверно делать такое  большое количество категорий, они не для этого созданы. Пролистать это в любом виде будет очень неудобно! Спрячете вы это в список или выведете все разом не важно.
Меняйте архитектуру своего проекта. Чтобы что-то конкретней подсказать нужно знать ваши задачи. Создайте тему на форуме, опишите детально задачу и, уверен, вам подскажут в чем ошибка и как будет правильней сделать.

**Comment by Val-Git** [comment]
Кстати, очень неплохо сделано на Хабре! Вариант с разделением на потоки, несколько спорен в части указания этих глобальных категорий перед темой поста (очень бросается в глаза и мешает увидеть саму тему). Но интересно другое. Подразделов там также много, но все они, при желании пользователя, выводятся отдельным списком [https://habrahabr.ru/flows/develop/hubs/](https://habrahabr.ru/flows/develop/hubs/) с небольшим описанием и другими сопутствующими параметрами.

**Comment by fuzegit** [comment]
Думаю в данном случае связи категорий одного типа контента с другим типом контента решили бы все вопросы с категоризацией. Или в целом связи типов контента, т.е. связь по-умолчанию + возможность переопределить связь для категории.

**Comment by murlysja** [comment]
Может не в тему, но можно встроить "поиск по списку" в поле выпадающий список. Как-то так: 
![2](https://cloud.githubusercontent.com/assets/17600180/18083354/751167c4-6eab-11e6-8232-00c9e685ed2b.jpg)
