### ISSUE TITLE
Микроразметка Schema.org

### ISSUE THREAD

**Issue by makartsoft** [instantsoft/icms2#296]
По аналогии с компонентом Open Graph, хотелось бы видеть на InstantCms микроразметку Schema.org.

Т.е.:
1. Для "Тип контента" можно указать схему разметки (например, Organization или Article)
2. Для "Полей" можно указать свои свойства (itemprop).

Можно делать через файлы шаблонов, но логичнее это внедрить сразу в движок.

**Comment by Val-Git** [comment]
Чем Schema.org лучше Open Graph? Почему Open Graph не устраивает?
Аргументация "хотелось бы видеть" не совсем подходит. На оф. сайте есть раздел фрилансеров, где вы можете найти специалиста который реализует все ваши хотелки. А потом можете и с сообществом поделиться! ;-)

**Comment by makartsoft** [comment]
OG хорошая разметка, но у нее нет тех возможностей и преимуществ, которые дает Schema (которая поддерживается и развивается поисковиками). 
В OG классы исчисляются десятками, в Schema.org их уже несколько сотен. Можно размечать рейтинг, количество голосов, цены, жанры фильмов, адреса и др.
Приминимо к ICMS2, где есть возможность добавлять новые поля, мне видится что было бы логично иметь возможность размечать эти поля разметкой Schema.

**Comment by makartsoft** [comment]
https://search.google.com/structured-data/testing-tool

**Comment by makartsoft** [comment]
@Val-Git делюсь [своим шаблоном](http://www.instantcms.ru/forum/thread25452-1.html) для типа контента "Новости".
Единственное, не смог решить вопрос с отображением itemprop="width" и itemprop="height"

**Comment by my-instantcms** [comment]
`Единственное, не смог решить вопрос с отображением itemprop="width" и itemprop="height"`
Я просто написал 
`<meta itemprop="width" content="600"><meta itemprop="height" content="400">`
А определять высоту и ширину, это очень долго если на странице много картинок, по этому просто пишите 600х400

**Comment by makartsoft** [comment]
Хорошее решение для микроразметки! [Добавляем schema.org к Open graph](http://instantcms.ru/blogs/moi-razrabotki/dobavljaem-schema-org-k-open-graph.html)
