### ISSUE TITLE
Эффекты при загрузки изображений

### ISSUE THREAD

**Issue by makartsoft** [instantsoft/icms2#297]
Хотелось бы предложить такое улучшение при загрузки изображений, как возможность выбора эффекта для пресета.
1. Создаем новый пресет
2. Прежде чем указать размеры пресета, указываем один из эффектов: 
3. Обрезка: удаляет часть изображения, чтобы привести его в соответствие с указанными размерами (точная ширина и высота в пикселях).
4. Изменение размера: -делает изображение соответствующим введённым размерам, без соблюдения исходных пропорций.
5. Масштабирование:  позволяет изменить размеры изображения с сохранением пропорций. Если введён размер только одной стороны, то размер другой будет вычислен автоматически. Если оригинальное изображение меньше указанных значений, то оно будет увеличено.
6. Масштабирование и обрезка: сначала масштабирует изображение, а затем обрезает большее значение. 

Таким образом (особенно использую последний эффект) на сайте в списках можно получить идеально ровные картинки (не только квадратные).

Спасибо

**Comment by vlad7090** [comment]
Отличная идея! И еще помимо настроек пресета - дать возможность при клике по пресету открывать в лайтбоксе изображение с большим пресетом.
