### ISSUE TITLE
Не блокируется смена пользователем "Никнейм" на никнейм из списка запрещенных.

### ISSUE THREAD

**Issue by ifork-git** [instantsoft/icms2#298]
Если в компоненте "Авторизация и регистрация" в списке запрещенных никнеймов есть таковые, то при регистрации эти никнеймы разумеется недоступны для регистрации. Но после регистрации под любым другим доступным, пользователь в настройках пользователя может с легкостью поменять никнейм на любой из списка запрещенных (например admin или moderator). При этом ему будет выведено сообщение о том что такой никнейм запрещен.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/002b77c620b69ed9efef411df5cffbe5eacc1034
