### ISSUE TITLE
Не корректное отображение Title на странице друзья

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#300]
Добрый день уважаемые разработчики ICMS 2.
Обнаружил сегодня такую ошибку:

1. Если в компоненте "Профили пользователей" в разделе "вкладки профилей" включить отображение вкладки "Друзья"
![28-08-2016 09-39-38](https://cloud.githubusercontent.com/assets/9349934/18032135/e76ce92c-6d04-11e6-98ee-f791d90396ae.png)
то в этом случае на странице http://lovelovely.ru/users/1/friends - 
тайтл отображается правильно
![28-08-2016 09-40-29](https://cloud.githubusercontent.com/assets/9349934/18032163/27687820-6d05-11e6-871e-0d826e619b59.png)
2. Если в компоненте "Профили пользователей" в разделе "вкладки профилей" отключить отображение вкладки "Друзья"
![28-08-2016 09-41-01](https://cloud.githubusercontent.com/assets/9349934/18032165/489f3312-6d05-11e6-869c-22eef7b1b512.png)
то в этом случае на странице http://lovelovely.ru/users/1/friends - 
тайтл отображается не правильно
![28-08-2016 09-42-04](https://cloud.githubusercontent.com/assets/9349934/18032167/579736da-6d05-11e6-9844-265131194b3f.png)

**Comment by fuzegit** [comment]
> Если в компоненте "Профили пользователей" в разделе "вкладки профилей" отключить отображение вкладки "Друзья" 

То вкладка не должна показываться и ни о каком title речи быть не может.

**Comment by nomad48** [comment]
@fuzegit так, а если у меня тут ссылка на друзей стоит, 
![30-08-2016 19-31-45](https://cloud.githubusercontent.com/assets/9349934/18097933/b4688992-6ee8-11e6-96b6-ad565ef88937.png)

мы с Вами этот вопрос на форуме обсуждали. Просто не возможно все вкладки разместить в горизонтальном меню. А в левом или правое самое то.

**Comment by fuzegit** [comment]
Если вкладка выключена в админке, то она не должна показываться и при переходе к ней должно быть 404. Именно так и будет в обновлении. А то, что выключенная вкладка всё равно показывается - это баг.

**Comment by nomad48** [comment]
Понятно!
