### ISSUE TITLE
Фильтр по полю в записи типа контента

### ISSUE THREAD

**Issue by murlysja** [instantsoft/icms2#313]
Добавить возможность отфильтровать поле непосредственно в записи типа контента, не прибегая к виджету "Фильтр контента", т.е., например, сделать активными значения "глина" и "круглая" полей "Материал" и "Форма" (пример на фото) при нажатии на которые контент бы автоматически отфильтровался? Типы поля "Ссылка" и "Текст HTML" не подходят т.к. в них нужно указывать определенную ссылку/адрес.

![qwer](https://cloud.githubusercontent.com/assets/17600180/18559023/1107aa74-7b7e-11e6-9a78-dd5d09e25e1e.jpg)

**Comment by fuzegit** [comment]
Вероятно дубликат? https://github.com/instantsoft/icms2/issues/140
