### ISSUE TITLE
У таблиц типов контента MyISAM а не InnoDB

### ISSUE THREAD

**Issue by my-instantcms** [instantsoft/icms2#314]
Здравствуйте, у таблиц типов контента, система хранения данных MyISAM а не InnoDB, так задумано или это недочет?
Сейчас делаю установщик для одного типа контента и хотелось бы знать что написать?

**Comment by fuzegit** [comment]
Здравствуйте
>  у таблиц типов контента, система хранения данных MyISAM а не InnoDB, так задумано или это недочет

Так задумано. Innodb не поддерживает полнотекстовые индексы (только в новых версиях только) и полнотекстовый поиск. Используйте MyISAM.
