### ISSUE TITLE
Возможности для разработчиков

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#315]
Прошу добавить в следующий релиз следующие возможности, которые добавят движку гибкости при установке и обновлении сторонних дополнений:
1. /system/core/template.php - не хватает метода для получения шаблона "заявленного" компонента для его получения в виде Html. Сейчас мне пришлось сделать так:
`getRenderedChild($tpl_file, $data=array(), $controller=false){`
в этой функции добавил имя компонента чтобы получить содержимое шаблона нужного компонента
2. При работе с компонентами "Группы" не хватает следующих выполняющихся вызовов хуков:
- Перед входом пользователя в группу (нужно чтобы проверять данные пользователя и была возможности запретить вход, если пользователя например заблокировать в группе)
- Перед вызовом меню группы (О группе, Контент, Активность, Участники) чтобы была возможность добавлять пункты меню из сторонних компонентов
- После удаления группы
3. Хук выполняющийся после добавления данных в ленту активности (чтобы модно было использовать добавляющиеся данные и следить за активностью в сторонних разработках)
4. Хук выполняющийся до или после отправки личных сообщений пользователей

**Comment by fuzegit** [comment]
1. Непонятно что имеется в виду, но шаблоны формируются от контекста. Используйте метод setContext($controller_obj) для смены контекста контроллера.

**Comment by krylos** [comment]
Приведу конкретный пример, на который я не смог найти метода. Имеется сторонний компонент в котором часто используется один и тот же файл шаблона данного компонента. Для интеграции компонента в тело компонента content создаю поле в котором планирую вывести имеющий файл шаблона своего компонента. Сейчас я данную вышеуказанную функцию изменил так: (если скажете что не правильно и можно по другому то буду только раз, других методов не нашел):
`public function getRenderedChild($tpl_file, $data=array(), $controller=false){
if($controller=='moicomponent') $tpl_file = $this->getTemplateFileName('controllers/moicomponent/'.$tpl_file);
else $tpl_file = $this->getTemplateFileName('controllers/'.$this->controller->name.'/'.$tpl_file);
extract($data); ob_start(); include($tpl_file);
return ob_get_clean();
}`
ниже есть метод renderControllerChild, и он вроде подходит но не возвращает html шаблона а генерирует его сразу на страницу. поэтому пришлось изменить вышеуказанный метод для временного решения.

**Comment by fuzegit** [comment]
В вашем случае необходимо использовать метод renderInternal, которому передать объект нужного вам контроллера.

**Comment by krylos** [comment]
при использовании указанного метода:
`$template->renderInternal('moicomponent', 'filetpl', array()`
показывается ошибка:
`Не найден шаблон для отображения или он недоступен для чтения: /var/www/ext/data/www/ххх.ru/templates/default/controllers//filetpl.tpl.php`
хотя в данном случае не понятно почему имя компонента в эту строку не попало. там видно что переменная с именем шаблона пропущена при вызове. данный метод пытался вызывать в разных компонентах. везде подобная ошибка. "//"

**Comment by Loadir** [comment]
'moicomponent' - это "строка", а вам нужно передать "объект" нужного вам компонента. Что-то типа $moicomponent = cmsCore::getController('moicomponent');
$template->renderInternal($moicomponent, 'filetpl', array());

**Comment by krylos** [comment]
Loadir, спасибо. Надо было догадаться мне))) Остальные просьбы в силе)
