### ISSUE TITLE
"Пустое" первое значение в поле список

### ISSUE THREAD

**Issue by murlysja** [instantsoft/icms2#316]
При добавлении записи в типе контента в поле список невозможно выбрать "пустое" первое значение после выбора "предустановленного значения". Так же и в опциях виджетов. Например, в виджете "Список контента" в поле "Поле изображения" невозможно выбрать пустое значение после выбора какого-либо значения - приходится создавать виджет заново.

**Comment by fuzegit** [comment]
уже исправлено https://github.com/instantsoft/icms2/commit/ea8418ce864613f50f13fb8d1bc505d70a25949e
