### ISSUE TITLE
Ошибка 404 добавления контента гостями

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#317]
Предлагаю для гостей показывать не 404 ошибку, а шаблон сайта с телом в виде надписи типа"Гости не могут добавлять информацию на нашем сайте! Пожалуйста, авторизуйтесь или зарегистрируйтесь" И виджеты авторизации с помощью соцсетей и встроенные отобразить.

**Comment by iAndroS** [comment]
Имеется в виду на странице добавления контента для неавторизованных пользователей

**Comment by vlad7090** [comment]
так как гость попадет на страинцу добавления контента?
