### ISSUE TITLE
Фильтр контента в админке

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#319]
Нужен более полный фильтр контента в админке: сейчас есть только фильтр по id и заголовку, а хотелось бы еще по дате и юзерам. Мне понадобилась данная задача, чтоб выяснить, сколько новостей добавляет конкретный юзер в месяц. Понимаю, что могу в бд запрос написать, но все же хотелось бы встроенной статистики по активностям пользователей.
Это минимальное, что можно предложить по данному функционалу и вроде несложно реализовать. Если копать глубже - нужна расширенная статистика по авторам контента: средние показатели производительности, количества показов их материалов, выплаты им и т.д. для оценки эффективности их работы и затраченных средств.

**Comment by my-instantcms** [comment]
Админка - Контент - Фильтр http://prntscr.com/ckjrs3

**Comment by fuzegit** [comment]
@iAndroS всё конечно хорошо, но фильтры есть. А задачи, необходимые вашему проекту, типа расширенной статистики, вы всегда можете заказать http://www.instantcms.ru/freelancers
