### ISSUE TITLE
Форма комментирования

### ISSUE THREAD

**Issue by my-instantcms** [instantsoft/icms2#320]
Есть один неудобный момент в формах комментирования. Сегодня например писал длинный текст комментарий, потом кое какой текст хотел скопировать из другого коммента, но при нажатии на текст, форма закрылась и содержимое пропала.
То есть если форма открыта и при нажатии на любой элемент сайта (кроме формы коммента) закрывается форма и удаляется содержимое.
![f7568834ee414605bb6c2fddbc5fc429](https://cloud.githubusercontent.com/assets/12434575/18712291/73a255b6-8016-11e6-955e-b263443a850f.png)
Можно закрытие формы, сделать только по нажатию кнопки Отмена?

**Comment by fuzegit** [comment]
> Можно закрытие формы, сделать только по нажатию кнопки Отмена?

уберу, хорошо.

**Comment by my-instantcms** [comment]
Есть еще один похожий баг.
В стене нажимаем загрузить файл из компа и при нажатии Выберете файл, форма закроется.

**Comment by fuzegit** [comment]
На текущей версии этой проблемы нет.

**Comment by my-instantcms** [comment]
Не давно исправили или вообще не было?
У меня версия 2.6 скачал 5-6 дней назад, т.е. некоторые последние коммиты еще не загрузил

**Comment by fuzegit** [comment]
Давно исправил с комментариями. А на стене да, действительно есть. Сначала не понял просто.
