### ISSUE TITLE
Настройки уведомлений в профиле пользователя

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#324]
Предлагаю реализовать возможность настройки не только по email и на сайте, но и учитывая такой параметр, как "Только если я офф более xxx часов/минут/дней"

**Comment by iAndroS** [comment]
Плохо, что долгосрочная... Получается, наши сайты с точки зрения спамерские, необходимо это учитывать. Ведется у нас активная переписка в личке между юзерами, и получают они потом на почту кучу писем, которую удалят без прочтения. И так несколько раз десятки пользователей сделают. Или сотни, тысячи таких писем. 10 активных диалогов - и наш ip сервера может уйти в базу спам-адресов

**Comment by fuzegit** [comment]
@iAndroS любой каприз за ваши деньги. А мы вольны сами  решать  приоритет разработки.

**Comment by globator88** [comment]
Тот же принцип можно для третьего пункта этой темы https://github.com/instantsoft/icms2/issues/190 реализовать. Что бы избавится от спама.
