### ISSUE TITLE
Ошибка: слетает дерево категорий контента в админке

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#325]
Изменил порядок категорий в одном из типов контента. Теперь у этого типа контента и у соседнего категории в админке перестали отображаться
http://image.prntscr.com/image/acd3f254fda945bca2ecac520e408929.png

**Comment by fuzegit** [comment]
Пожалуйста, задавайте вопросы по своим проблемам на форуме. Максимально информативно. Проблем с изменением порядка категорий в последней версии InstantCMS нет.

**Comment by iAndroS** [comment]
Не помню, каким образом, но проблему помог решить Loadырь. И проблема эта была актуальна не так давно
