### ISSUE TITLE
Очистка уведомлений в instantcms2 реализована только по одному(единично) уведомлению,

### ISSUE THREAD

**Issue by kir24** [instantsoft/icms2#330]
Очистка уведомлений в instantcms2 реализована только по одному уведомлению, в первой ветке была возможность очистить папку уведомлений. Не досмотрели или что?
файл обработки в папке темплейта дефолтного в /js/messages.js
http://www.instantcms.ru/forum/thread25728-1.html#246379

Нужно реализовать прием массива, тогда можно будет сгенерировать ссылку на удаление всех уведомлений

**Comment by kir24** [comment]
Данное будет реализовано или нет?

**Comment by fuzegit** [comment]
Будет. Немного непонятна ваша настойчивость и требовательность.

**Comment by kir24** [comment]
Это не настойчивость а желание уточнить примерные сроки и стоит дождаться решения или городить огороды.

**Comment by fuzegit** [comment]
Тикет не удалён, да, сделаем кнопку. Когда - не могу сказать.

**Comment by zau4man** [comment]
Вариант решения есть в теме http://www.instantcms.ru/forum/thread26345-1.html во втором сообщении.
Неплохо бы подобный вариант внедрить в коробку. Уведомлений и правда бывает очень много.
