### ISSUE TITLE
Расширение функционала групп

### ISSUE THREAD

**Issue by Alex-HAV** [instantsoft/icms2#332]
Добавить группам возможность выбирать кому разрешено добавлять материалы от имени группы (администраторам группы, модераторам, участникам)

Добавить возможность создавать поля, как в профилях пользователей, с возможной их продажей/покупкой в биллинге 

Также было бы полезно свои наборы для вывода групп

**Comment by iAndroS** [comment]
Также для вкладок групп не хватает SEO - сейчас на странице описания группы выводятся в мета-тегах заголовки и описания, которые берутся из настроек группы, а вот во вкладке Контент уже мета-теги с сайта по умолчанию!
