### ISSUE TITLE
Хук после отправки сообщений

### ISSUE THREAD

**Issue by my-instantcms** [instantsoft/icms2#336]
С выходом API движка, думаю многим будет необходим отправка уведомлении в своих приложениях, по этому хотелось бы увидеть в движке хук после отправки сообщении или более универсально, внутри функции **sendNoticeEmail()**

Если такая реализация есть в планах, надеюсь увидит в версии 2.6 :)

**Comment by fuzegit** [comment]
Не очень понял зачем это. Поясните цель хука.

**Comment by my-instantcms** [comment]
Что бы отправить PUSH уведомления тем, кто пользуется android/ios приложением.
Гугл в последнем обновлении, внедрил технологию Firebase там есть готовый API для отправки PUSH уведомления.
Но при получении сообщения или уведомления на сайтах инстанта, надо дергать API что бы тот отправил уведомления. https://firebase.google.com/docs/cloud-messaging/server#auth
