### ISSUE TITLE
Логика поля "Список:мультивыбор"

### ISSUE THREAD

**Issue by Alex-HAV** [instantsoft/icms2#337]
На данный момент есть набор чекбоксов, который мы задаем в админке. Он выводится ровно в том порядке, в каком указан. Когда сохраняем запись то в БД записывается например так 0100. Т.е. первый чекбокс выключен, второй - галочка установлена, третий и последующие также отключены (значения 0). Когда мы добавляем во вторую позицию новый чекбокс, то по сохраненной схеме он становится включенным =)) И не важно что это уже другой чекбокс, совсем не тот что сохранялся ранее.

А хотелось бы что бы было как в обычном списке id | элемент, что даст возможность менять и добавлять позиции в предустановленые значения

**Comment by fuzegit** [comment]
Это невозможно сделать с данным типом поля. Набор чекбоксов необходимо определять сразу.
