### ISSUE TITLE
Пропажа свойств при добавлении контента в несколько категорий

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#338]
![screenshot_1](https://cloud.githubusercontent.com/assets/17408903/19414314/3f72f048-937b-11e6-85fc-a9ade4e83502.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/17408903/19414315/3f98ef14-937b-11e6-8e69-8dab703773b4.png)

Имеем тип контента с категориями. У каждой категории свои свойства. При добавлении записи в тип контента с указанием дополнительных категорий, свойства к ним (этим дополнительным категориям) не отображаются (хотя указаны обязательными для заполнения), отображаются свойства только первичной категории.
Например, тип контента - товары (подарки). Имеем категории: Для детей, На 8 марта. Категория "Для детей" основная и пусть у нее нет свойств в принципе (проверял специально, баг тот же). У категории "На 8 марта" есть поле (список-мультивыбор) свойства "Маме", "Бабушке", "Дочери". Если в дополнительных категориях указать категорию "На 8 марта", наши свойства показываться при добавлении товара не будут!

**Comment by iAndroS** [comment]
Приблизительно так представляю себе правильный вариант вывода свойств при добавлении контента в несколько категорий
![screenshot_4](https://cloud.githubusercontent.com/assets/17408903/19414356/dd540d14-937c-11e6-8712-23f3544dc224.png)

**Comment by iAndroS** [comment]
@fuzegit подскажите, будет ли в ближайшем релизе поправлено? Очень важный момент!

**Comment by fuzegit** [comment]
Нет, не будет в ближайшее время. Это не баг. Сейчас так работает.

**Comment by iAndroS** [comment]
Не соглашусь с вами все же. Если я добавляю материал в одну категорию, у меня есть ее свойства, добавляю материал в другую категорию, у нее тоже есть свойства. Если же я добавляю в обе категории, почему свойства только одной отображаются? При этом у меня во второй категории, свойства которой при добавлении материала не отображаются, отмечены как "Поле должно быть заполнено".
Разве ли это не баг?

**Comment by fuzegit** [comment]
Вы можете соглашаться, можете не соглашаться :) Но есть так, как есть. Показываются свойства только основной категории. Улучшать это поведение в этом релизе не планируется.

**Comment by iAndroS** [comment]
На правах апа хотел бы вернуться к обсуждению этого немаловажного вопроса... Неужели меня одного смущает данный момент?

**Comment by iAndroS** [comment]
@fuzegit , а закрыли зачем предложение? Как по мне, по этой причине приходится создавать сотни типов контента (((
Могу я вынести на обсуждение этот вопрос на форуме?
