### ISSUE TITLE
Свойства категории (Описание, иконка, обложка)

### ISSUE THREAD

**Issue by web-studio-pro** [instantsoft/icms2#343]
Выполняя такую огромную работу по не нужному или редко используемому функционалу не доделали основные самые необходимые функции, для мощнейшего каталога контента. 
Даже в старой 1.хх были такие функции. Тем более там дел то, добавить несколько полей...

При добавлении/редактировании категории, необходимы такие поля: 
1. **Описание категории**(выводится в категории над списком контента) и галочку: отображать только на первой странице категории, 
2. **Краткое описание категории**(выводится в списке категорий),
3. **Иконка**(выводится меню и в списке перед категорией(в списке категорий выводится если нет обложки), на страницах категории и страницах контента категории перед титл). Поле для загрузки картинки или вставки кода <img...> либо <i class="fa fa-list-alt" aria-hidden="true"></i> ( http://fontawesome.io/icons/ )
4. **Обложка**(выводится в списке категорий вместо иконки и в виджете) Поле для загрузки картинки либо хотя бы для вставки url.

Ну и можно **виджет** с выводом категорий с кратким описанием, иконкой и обложкой.  

Это конечно можно всё сделать созданием страниц виджетов и вставкой виджетов и средствами css, но тогда уже CMS не будет такой хвалёной простой в управлении.

**Comment by fuzegit** [comment]
> Выполняя такую огромную работу по не нужному или редко используемому функционалу не доделали основные самые необходимые функции, для мощнейшего каталога контента.

Позвольте нам принимать решение о нужности и о том, что мы для ВАС делаем. Бесплатно. Первые три предложения лишние. Подобное пожелание уже есть  в списке тикетов и оно не удалено. Это говорит о том, что мы согласны с данным предложением.

**Comment by web-studio-pro** [comment]
Для начала конечно извеняюсь, за то что отвлекаю. 

 > Позвольте нам принимать решение о нужности.

 Не навязываю и не заставляю, только предложил исходя из своих 10 летних наблюдений за тем что нужно для клиентов(пользователей cms).

> что мы для ВАС делаем. Бесплатно. 

Я думал хоть одну просьбу выполните за оплаченные мною спонсорские 40 т.р. :) (этот параграф можно скрыть)

> Первые три предложения лишние. Подобное пожелание уже есть в списке тикетов и оно не удалено. 

Ну вот видите какое попадание 3 из 4, а говорите о ненужности моих пожеланий. 
Хотя 4 тоже нужен. Уточню, иконка и обложка это разное, можно заполнить и иконку вставив урл картинки 32*32 которая будет использоваться к примеру в меню, и обложку 300*300 для списка категорий(блоками), в фотоальбомах же есть обложка...

**Comment by fuzegit** [comment]
> Я думал хоть одну просьбу выполните за оплаченные мною спонсорские 40 т.р

Не очень понял о чём вы. Но видимо спонсорские вы платили по условиям, описанным тут http://www.instantcms.ru/sponsorship.html Поэтому упрёк не уместен.

> а говорите о ненужности моих пожеланий

я этого не писал.

Про "первые три предложения" я имел в виду предложения, как единицу человеческой речи. Т.е. вот это:

> Выполняя такую огромную работу по не нужному или редко используемому функционалу не доделали основные самые необходимые функции, для мощнейшего каталога контента.
Даже в старой 1.хх были такие функции. Тем более там дел то, добавить несколько полей

**Comment by web-studio-pro** [comment]
Спасибо за создание Описание категории, надеюсь в следующем релизе доработаете и сделаете иконка и обложка.

**Comment by web-studio-pro** [comment]
> надеюсь в следующем релизе доработаете и сделаете иконку и обложку.

**Comment by web-studio-pro** [comment]
т.ж. к виджету категории их надо тоже привязать.

**Comment by web-studio-pro** [comment]
Подскажите пожалуйста, почему во всех топиках закрыли ворк на возможность задавать "Обложку категории"  
Эту возможность даже перестали планировать? Можно не ждать?

**Comment by fuzegit** [comment]
Потому что все дубликаты этого тикета наверное) Тут всё открыто.

**Comment by web-studio-pro** [comment]
Ясно, извиняюсь, я просто не совсем  понимаю систему githaba

**Comment by pumpuic** [comment]
Прошло почти три года, изображение категории столько людей просили...

**Comment by fuzegit** [comment]
> Прошло почти три года, изображение категории столько людей просили...

![_009](https://user-images.githubusercontent.com/13233234/46469499-3e7e5780-c7dc-11e8-9dc7-fe7c2609cee6.png)

**Comment by web-studio-pro** [comment]
УРААА! Свершилось! Спасибо!!! 
Надеюсь в скором времени в виджете категории тоже появится вывод этих обложек.

**Comment by web-studio-pro** [comment]
С наступающим! А это чтоб веселей работалось с новогодним настроением: 
http://novogodnie-pesni.vladivostok.online
