### ISSUE TITLE
Как удалить из "Друзей"?

### ISSUE THREAD

**Issue by tsv2k** [instantsoft/icms2#350]
Добрый день.
Установил ICMS 2.6.0, очень приятная система. Спасибо разработчикам за труд.
Обратил внимание, что успешно действует возможность добавить экаунты в число друзей...но не соображу, как пользователь может удалить себя из друзей кого-то? Либо надо добавить функционал, либо я просто не нашел как это делать - может кто-то подскажет? - буду признателен.

Всего наилучшего

**Comment by shuma375** [comment]
Заходишь на страницу пользователя, которого необходимо удалить из друзей и жмешь кнопку **Убрать из друзей**

**Comment by fuzegit** [comment]
В issues пишутся предложения и сообщения об ошибках. Для вопросов есть форум.
