### ISSUE TITLE
Возможность редиректа

### ISSUE THREAD

**Issue by Mikhail29** [instantsoft/icms2#351]
Прошу разработчиков дописать для новой версии в опции возможности редиректа на https протокол и редиректа касательно www. или хотя бы просто добавьте hook после строк `$core->runController();
    $core->runWidgets();` 
чтобы я мог просто адаптировать уже написанный компонент редиректа для движка. В связи с таким функционалом думаю половина вопросов о редиректе на форуме отпадёт сама собой.

**Comment by fuzegit** [comment]
1. Это должно реализоваться средствами веб сервера, CMS не должна регулировать такие редиректы.
2. Префикс WWW морально устарел, это пережиток начала эры Интернет. Сейчас это просто домен третьего уровня.
3. Делать редирект после того, как и компоненты и виджеты отработали, неразумно.
4. В комплекте есть хук engine_start, который для указанных действий подходит идеально.
