### ISSUE TITLE
Опция "Показывать записи из подкатегорий внутри родительской категории" работает только в админке.

### ISSUE THREAD

**Issue by ovgrusin** [instantsoft/icms2#357]
Можно одну и ту же опцию использовать и для админки и для фронта.
Лучше: отдельная опция для фронта; а для отображения в админке - опция при работе с контентом.
В идеале: опционально для категорий.

**Comment by fuzegit** [comment]
Вероятно имеется в виду, что при снятии данного чекбокса на главной странице типа контента всё также продолжают выводиться все записи, верно?

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/4e98bda393c95dd1e7803f370a31251258771dc5
