### ISSUE TITLE
Нет возможности сортировать записи типа контента по алфавиту.

### ISSUE THREAD

**Issue by ovgrusin** [instantsoft/icms2#358]
Нужно либо сделать такую сортировку по умолчанию, либо добавить возможность создавать набор по алфавиту. В идеале: нужно и то и другое.

**Comment by fuzegit** [comment]
@ovgrusin так создаёте набор с сортировкой по названию по возрастанию, ставите его первым - получаете сортировку по алфавиту. http://docs.instantcms.ru/manual/ctypes/datasets/add
Или я не так понял ваше пожелание?

**Comment by ovgrusin** [comment]
В 2.6.0 нет возможности выбрать заголовок при создании набора (раньше была) 

15 листопада 2016, 07:59:21, від Fuze < notifications@github.com >: 

@ovgrusin так создаёте набор с сортировкой по названию по возрастанию, ставите его первым - получаете сортировку по алфавиту. http://docs.instantcms.ru/manual/ctypes/datasets/add 
Или я не так понял ваше пожелание? —
