### ISSUE TITLE
Правки в методах сохранения и ресайза изображений

### ISSUE THREAD

**Issue by zau4man** [instantsoft/icms2#359]
Добавит универсальности, а также позволит более гибко использовать методы 

resizeImage($source_file, $size), 
getUploadDestinationDirectory(), 
increaseFilesCount()

если определять пользователя не внутри функций, а передавать id пользователя в эти методы в качестве параметра.

Также будет полезно, если в метод getUploadDestinationDirectory() можно будет передать параметр с названием папки, которая будет создана в корне папки uploads, тогда можно будет разбивать папку upload на составляющие компонентов и типов контента при закачке, т.е. вложенность будет  не 000/u1/000/sdfsd.jpg, а posts/000/u1/000/sdfsd.jpg

Подробнее в теме форума http://www.instantcms.ru/forum/thread25985-1.html

**Comment by WebManG** [comment]
Да, надо бы как-то систематизировать папку загрузок. У меня тоже по ней [есть вопросы](http://www.instantcms.ru/forum/thread26026-1.html). Раскладывать изображения по компонентам и типам контента - вполне здравая мысль.

**Comment by WebManG** [comment]
**r2** [дал свой комментарий](http://www.instantcms.ru/forum/thread26026-1.html#250059) по этому вопросу.

**Comment by zau4man** [comment]
Не ко всему вопросу. $user->id и $user->files_count нужно убирать из этих методов.
Иначе приходится делать 4 своих метода, которые по сути - копия тех, что есть в движке, для того, чтобы скопировать картинку без участия пользователя.

**Comment by fuzegit** [comment]
@zau4man посмотрим, уберём.
