### ISSUE TITLE
Контент (описание) категорий

### ISSUE THREAD

**Issue by Brain8torm** [instantsoft/icms2#360]
Добрый день команда разработчиков Instant CMS!

Ооочень давно жду когда все-таки реализуете очень важную вещь и с каждым релизом вижу ее отсутствие.
У категорий различных типов контента  отсутствует поле Контент (Содержимое, Описание, не важно как называется) - поле в которое вводится само содержимое (контент, текст) для оптимизации категорий под нужные ключи. К сожалению есть только поле описания для поисковых систем (meta description).

И каждый раз приходится применять "костыли" для добавления этого поля.

**Comment by fuzegit** [comment]
#343 
Запланировано на следующий релиз.
