### ISSUE TITLE
Поддержка фото 360 градусов

### ISSUE THREAD

**Issue by klubnik** [instantsoft/icms2#362]
Хотелось бы на сайте использовать 360 фото
Необходимо, чтобы такое фото можно было вертеть в браузере
Желательно чтобы можно было делать фуллскрин и листать для просмотра в очка vr

**Comment by WebManG** [comment]
Функция интересная. Но на мой взгляд её лучше делать отдельным компонентом.

**Comment by klubnik** [comment]
Возможно. Но нужно это в коробке. 
Причем есть два вида 360 градусного фото.  Это панорамное фото, есть все вокруг. И есть объектное фото, то есть вокруг объекта. 
Панорамное фото хорошо развивается для самых разных случаев, а второй вариант больше применим к Интернет-магазинам.

**Comment by WebManG** [comment]
Зачем это именно в коробке?

**Comment by klubnik** [comment]
Потому что это не просто опция, а фото которое должно как можно раньше стать обычным явлением. Если кто-то сделает дополнительный компонент тоже хорошо, но тогда желательно, чтобы не было проблем с обновлениями и конфликтами в скриптах.

**Comment by klubnik** [comment]
Конкретно меня интересует больше панорамное фото. По функционалу нужна возможность удобного использования на смартфоне и очках виртуальной реальности. То есть фото должно крутиться и открываться во весь экран.

**Comment by WebManG** [comment]
Я лично не вижу смысла встраивать это прямо в "коробку". Пока востребованность этого функционала совсем невелика, слишком мало сайтов это могут использовать.

**Comment by r2git** [comment]
Решается вставкой JS/Flash плагина для панорам на нужные страницы.

**Comment by pumpuic** [comment]
Конкретно вы, можете заказать такую разработку у разрабов. В коробке это не нужно, от слова вообще.

**Comment by klubnik** [comment]
@pumpuic, сейчас рано конечно говорить о распространенности формата, но тем не менее оно распространяется и для CMS это было бы хорошей фишкой. Ну раз все такие консерваторы, то смысла убеждать мало. Надо искать решения.
