### ISSUE TITLE
Ошибка в работе хештегов при использовании цвета с атрибутом #

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#366]
InstantCMS 2.6.0

Версия PHP: 5.4.38

Если в компоненте поиск "Включить поддержку хештегов" - то возникает ошибка с в контенте, с теми частями текста где используется цвет с атрибутом #, пример. Ошибка возникает везде и в тексте и в списках.

* первый шаг - включаем поддержку хэштегов
* второй шаг - выделяем фрагмент и ставим цвет в тексте допустим - #ec155a
* третий шаг - сохраняем и везде появляется такая ошибка 
![23-11-2016 23-34-14](https://cloud.githubusercontent.com/assets/9349934/20578278/a7459a8e-b1d7-11e6-8682-22cf03fd0cdd.png)

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: - НЕТ, я не смог ее воспроизвести, потому что там видно ограничение стоит, чтобы демо не ломали.

**Comment by fuzegit** [comment]
Думаю проблема в вашем шаблоне. Не смог воспроизвести.

**Comment by nomad48** [comment]
Можно у меня глянуть, могу дать доступы.

**Comment by Loadir** [comment]
**nomad48** каким редактором забиваете тексты. Вероятно у вас инлайновые стили для цвета прописываются через "#..." вместо "rgb(...)".

**Comment by nomad48** [comment]
@Loadir  у меня везде стоит так 
![24-11-2016 07-18-50](https://cloud.githubusercontent.com/assets/9349934/20586610/a98fd590-b216-11e6-9f08-f286463f2e75.png) я цвет #ec155a допустим, меняю в "код" 
![24-11-2016 07-20-53](https://cloud.githubusercontent.com/assets/9349934/20586640/125cfef4-b217-11e6-93fe-f79413401fc3.png)
, потому набор цветов rgb честно говоря отстойный.

**Comment by Loadir** [comment]
Набор предустановленных да слабоват. Но вы же можете вручную в коде ставить нужный цвет в формате rgb или rgba. А так да, у вас везде будут определяться как хэштеги.

**Comment by nomad48** [comment]
@Loadir ну это как вариант, надо только подобрать, я ставил цвет с тегом # в тон сайта, какими цветами сверстан.

**Comment by nomad48** [comment]
Странно, ошибка же есть в работе. Почему закрыли? 
![28-02-2017 20-18-53](https://cloud.githubusercontent.com/assets/9349934/23416249/2b8164b0-fdf3-11e6-85b1-297dd6aaddb2.jpg)
