### ISSUE TITLE
Поддержка helper.php только в соотвествии с настройками Интерфейса

### ISSUE THREAD

**Issue by softsolution** [instantsoft/icms2#370]
Проблема:
При использовании своего шаблона + файла helper.php - он подключается и в админке, даже если в админке в настройках для Админки выбран свой шаблон. Мне нужно переопределить классы всех инпутов на фронте - но такое изменение затрагивает и админку, даже если для админке определен шаблон default.
Хотелось бы чтобы  helper.php для админки не подключался, если такого файла нет в default

**Comment by uzunhair** [comment]
Тоже хочу решить этот вопрос. 
В данный момент я решаю вопрос переделкой файла стилей для админки. Ставлю его в свой шаблон и меню стили, чтобы все работало. У меню input  например вынужден содержать два класса, один дефолтный один свой.

**Comment by fuzegit** [comment]
Уточните более подробно, я ничего не понял.

**Comment by softsolution** [comment]
Подробно:
На сайте есть два шаблона: 1) default 2) свой шаблон. Свой шаблон применяется для фронта (шаблон по-умолчанию). 
Хочу для всех полей форм, что на фронте изменить class со стандартного "input" на form-control (это шаблон на основе bootstrap). Варианты такие - 1) во всех шаблонах менять (добавлять параметр для полей типа Input) - этот вариант не очень подходит т.к. не все формы можно менять в шаблоне. И 2) вариант: через файл /templates/свой-шаблоне/assets/helper.php - внести изменения в функцию html_input. Это хороший вариант. Но если добавить этот файл и внести в него изменения - классы меняются и в админской части сайта, так как helper.php активной темы используется и в админке (файл bootstrap.php):
`    // подключаем хелпер шаблона, если он есть
    if(!cmsCore::includeFile('templates/'.$config->template.'/assets/helper.php')){
        cmsCore::loadLib('template.helper');
    }`

По идее в настройках сайта есть параметр - Тема оформления для панели управления - но по факту, даже если там выбан default - helper.php подключается от активной темы. 

В общем пока решил это дело таким костылем:
`if(strstr($_SERVER['REQUEST_URI'], 'admin')){
    cmsCore::loadLib('template.helper');
} else {
    if(!cmsCore::includeFile('templates/'.$config->template.'/assets/helper.php')){
        cmsCore::loadLib('template.helper');
    }
}`
