### ISSUE TITLE
В альбомах компонента "Фотоальбомы" фотографии выводятся в обратном порядке (от последнего фото к первому) без возможности это исправить

### ISSUE THREAD

**Issue by rubesslov** [instantsoft/icms2#372]
**Используемая версия InstantCMS**: 2.6.0.

**Версия PHP**:  5.6

**Как воспроизвести проблему**: 

Создать фотоальбом и загрузить в него фотографии

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

В альбомах компонента "Фотоальбомы" фотографии выводятся в обратном порядке (от последнего фото к первому) без возможности это исправить
Прошу поправить или сделать функционал, позволяющий задать выборку по умолчанию.

**Comment by fuzegit** [comment]
В чем ошибка и/или проблема? Фотографии выводятся в порядке новые вверху. Сортировка задается в настройках компонента.

**Comment by rubesslov** [comment]
Это крайне неудобно в бытовом использовании. Например, при загрузке фотоотчета с мероприятия (концерт, фестиваль, где выступает ряд артистов) фотографии идут от конца (салют, выход на поклон, некий пиковый момент, и т.д.) , и далее фотографии идут к началу (набор зрителей в зале, подготовка сцены, и т.д.) . Таким образом у обычного пользователя напрочь сбивается хронология события.

**Comment by rubesslov** [comment]
а сортировки, которая есть в настройках компонента - недостаточно. нет ни одного варианта, который позволял бы сортировать фотографии "от начала к концу"

**Comment by Margauza** [comment]
Печально что "не требует решения" таким образом каждый альбом с фотками о соревнованиях начинается с их завершения то есть награждения или завершающего парада. А фоторасказ о том "как мы отдыхали на Ямайке" будет начинаться с отбытия.

**Comment by fuzegit** [comment]
Дак я не закрыл тикет пока что. Но сейчас проблема легко решается загрузкой фото в обратном порядке.

**Comment by rubesslov** [comment]
К сожалению, решение проблемы обратной загрузкой сейчас обернется необходимостью заново перезаливать все "обратные" альбомы после решения тикета. Не делать же сортировку "Asc - Desc" на каждый отдельно взятый альбом :-)

**Comment by Margauza** [comment]
А если процесс еще не завершен например "как растет мой малыш" ... или как мы отдыхаем на багамах прямо сейчас.

**Comment by fuzegit** [comment]
> А если процесс еще не завершен например "как растет мой малыш" ... или как мы отдыхаем на багамах прямо сейчас.

так тогда вам текущая сортировка самый раз. Новые вверху. Так в вконтакте например.

> К сожалению, решение проблемы обратной загрузкой сейчас обернется необходимостью заново перезаливать все "обратные" альбомы после решения тикета. Не делать же сортировку "Asc - Desc" на каждый отдельно взятый альбом :-)

Направление сортировки будет задаваться в админке вероятно. И конечно же мы не сделаем сортировку ASC заменив текущую.

**Comment by Margauza** [comment]
> так тогда вам текущая сортировка самый раз. Новые вверху. Так в вконтакте например.

Бесспорно это тоже интересный взгляд, но привычнее все таки в обратном порядке т.е как все начиналось как развивается и к чему все пришло(идет) 
А во многих других случаях расположение "новые сверху" в самый раз.

> Направление сортировки будет задаваться в админке вероятно. И конечно же мы не сделаем сортировку ASC заменив текущую.

Спасибо огромное

**Comment by Margauza** [comment]
А может дать возможность сортировки на страничке фотоальбома самому юзеру выбрать в какой последовательности смотреть фотки. Там где 
- последние загрузки
- по дате съемки 
и.д добавить еще с конца альбома или сначала смотреть фотки.

**Comment by zau4man** [comment]
> А может дать возможность сортировки на страничке фотоальбома самому юзеру выбрать в какой последовательности смотреть фотки.
Поддерживаю. Сейчас, если в альбоме очень много фотографий, чтобы посмотреть последнюю нужно много-много раз тыкать по "показать больше". Добавка еще одного метода сортировки в альбомах необходима. И ее вряд ли слишком сложно добавить.
Даже в том же вк, который приводится выше как пример, есть стрелочка, которая меняет порядок от начала к концу.
![image-2017-02-11-14-02-35](https://cloud.githubusercontent.com/assets/13526431/22852723/6efa8f42-f064-11e6-9280-958c8c9c9d3d.png)
