### ISSUE TITLE
Seo в наборах

### ISSUE THREAD

**Issue by numinaki** [instantsoft/icms2#373]
Спасибо разработчикам за уделенное внимание Сео на icms, в частности речь пойдет об icms2.6.0
1. В наборах указываем теги: описание и ключевые слова и получаем их на всех страницах данного типа контента, а именно: 
1. site.ru/board-expensive - теги, описание.....
2. site.ru/board-expensive/nedvizhimost - теги и описание одни и те же.
3. site/board-expensive/nedvizhimost/kottedzhi - теги и описание одни и те же.
Предлагаю:
1. Возможность добавлять теги и описание для типа контента и каждой категории типа контента.
2. Сделать возможность указывать title для набора, а не только дескрипшн и кейвордс.
3. Возможность не выводить набор на сайте, но публиковать его, что позволит делать некую посадочную страницу для поиска, но не обязательно, чтобы человек дальше мог по клику на нее перейти, а мог пользоваться навигацией на сайте, фильтром и т.п.
4. Да, и соответственно, если для каждой категории будет возможность выбора наборов, т.е. показывать именно те, которые нужны в этой категории, то это будет отличный прорыв для сео.

Как пример, можно зайти на сайт ситилинк, там точь-в-точь как на icms2 выводятся наборы.

**Comment by fuzegit** [comment]
5. Так сейчас и есть. Только если смотрим категорию через набор, то сео параметры категории затираются параметрами набора. Это конечно недочёт. Думаю стоит исправить так, чтобы сео параметры категории и набора суммировались, если смотрим категорию из под набора. Либо предлагайте свои варианты.
7. Наборы можно снимать с публикации, после чего они не будут видны на сайте.

**Comment by numinaki** [comment]
5. Да, для типов контента работает все хорошо, но с категориями нужно поработать. Лучше, если для каждой категории, можно будет создавать свой набор. Например:
Есть раздел статьи: /articles, там можно сделать наборы: новые, популярные и т.д., в общем, кто как хочет. Далее в статьях есть категории: сео, php, css и др. Для этих категорий можно задать другие наборы: обучающие, для новичков, для опытных, готовые решения и т.д. 
Т.е. наборы можно создавать с привязкой к категориям, и выводить наборы отличающиеся от набора в типе контента. С возможностью писать теги для каждого набора.
Еще как пример: имеем интернет магазин строительных материалов:
тип контента - сухие смеси: набор - гипсовые, цементные и т.п. Далее заходим в категорию: штукатурки: набор - гипс, цементная, для наружных работ, для внутренних и т.д. Если мы для них сможем задать теги, то получится так: 1. Сухие смеси гипсовые купить и т.д. 2. Штукатурки гипсовые купить и т.д. Это даст большое преимущество в сео и исключит дубли, т.к. сейчас дубли получаются.
7. Если снимаем, то по адресу выдает ошибку 404, а было хорошо иметь возможность не выводить на странице набор, но саму страницу набора иметь в поиске. Иногда это бывает нужно, если есть цель получить трафик на сайт, но не нужно чтобы человек на сайте мог перейти на это страницу. Такое встречал у лидеров интернет магазинов.

**Comment by fuzegit** [comment]
5. Согласен. Но нужно сделать максимально гибко и универсально. Поэтому не в 2.6.1 реализуем.
6. Сделаем.

**Comment by numinaki** [comment]
Спасибо! Есть интернет магазин, называется ситилинк, там хорошо реализовано это дело, заходишь в категории, выбираешь набор и меняется title и desc, соответственно через виджет можно подкрепить текстом. В сочетании с instshop будет работать идеально.

**Comment by iton1** [comment]
И сделать возможность менять заголовок в наборах т.к. сейчас там выводиться название категории!
