### ISSUE TITLE
Небольшие правки в cron_publication.php

### ISSUE THREAD

**Issue by zau4man** [instantsoft/icms2#374]
**Используемая версия InstantCMS**: 2.5.1, 2.6.0

В файле system/controllers/content/hooks/cron_publication.php нужно добавить проверку на пустоту массива $is_pub_items перед выполнением хука publish_delayed_content.

В противном случае, если в настройках выбрать записи скрывать, они на сайте есть, задача постоянно выполняется, и получаем кучу дублей в ленте активности.

Подробнее в теме http://www.instantcms.ru/forum/thread26105-1.html

**Comment by fuzegit** [comment]
Так проверяется же https://github.com/instantsoft/icms2/blob/master/system/controllers/content/hooks/cron_publication.php#L30

**Comment by zau4man** [comment]
Так переменная в начале объявляется 
$is_pub_items = array();
и проверка в 30 строке всегда будет истинна. Или я не прав?

**Comment by fuzegit** [comment]
array() - это пустой массив. if(array()){ никогда не выполнится }

**Comment by fuzegit** [comment]
Там нужно корректировать запрос с учетом того, что есть поле окончания публикации.
