### ISSUE TITLE
Добавить права для доступа/изменению к типу контента и всем его записям

### ISSUE THREAD

**Issue by rdimrs** [instantsoft/icms2#377]
Столкнулся с тем что захотел создать тип контента только для определенной группы пользователей, который будет не доступен для других пользователей и поисковиков. К сожалению такой возможности нет. 

Мой пример использования: Мини CRM система
Сайт корпоративный портал, на нем информация как для клиентов, так и для внутреннего пользования. Разные группы работников со своим доступом к разному закрытому контенту.

**Comment by WebManG** [comment]
Управление правами создания/редактирования записей в типах контента есть. Не хватает управления показом.

**Comment by vipartem** [comment]
Вот это очень полезная функция.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/6521f938a0aaf565a3ea257be3070f12adb4885e
