### ISSUE TITLE
Возможность вывода групп полей в контенте

### ISSUE THREAD

**Issue by numinaki** [instantsoft/icms2#380]
Предлагаю добавить опцию вывода групп полей в контенте. Это даст дополнительную гибкость для отображения контента. Например, блок можно будет стилизовать определенным образом. А также это удобно пользователям при просмотре контента, когда у полей может быть общее название.
Скажем вывести блок, контакты, доставка, еще какая-либо важная информация, может быть сгруппирована и подана отлично от других полей.

**Comment by Val-Git** [comment]
> блок можно будет стилизовать определенным образом.

А сейчас что вам мешает это сделать?

> А также это удобно пользователям при просмотре контента, когда у полей может быть общее название.
Скажем вывести блок, контакты, доставка, еще какая-либо важная информация, может быть сгруппирована и подана отлично от других полей.

Можно подробнее расписать как вы себе это видите с алгоритмической точки зрения? Т.е. чтобы по желанию можно было часть полей объединять стилистически, а часть не трогать? При том что вам заранее не известно вообще какие будут поля в типе контента.

**Вывод:** Если вам лично нужно где-то объединить часть полей, вы можете уже сейчас воспользоваться стандартным методом движка - создать/скопировать шаблон вывода нужной записи типа контента и настроить его как вам требуется.

**Comment by numinaki** [comment]
В данный момент при редактировании ведь поля объединяются в группу, только не выводятся в контенте. Я не программер, я вам не могу сказать как именно это реализовать. Есть такое предложение, если вы не можете это реализовать, просто так и ответьте, и не будем устраивать дискуссий, вопрос закроется.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/07dca265db42c3a8319be3754d6aae45dbde978d

**Comment by numinaki** [comment]
Возможно ли добавить гибкости в выведенных группах, чтобы класс у них отличался, например хотя бы по номерам, сейчас класс у разных групп одинаковый.
