### ISSUE TITLE
Отключение показа пункта меню

### ISSUE THREAD

**Issue by zau4man** [instantsoft/icms2#382]
В данный момент (версия 2.6.1 и ранее) есть возможность только редактировать/удалить/ограничить доступ для пункта меню.
Будет лучше, если в новых версиях появится возможность включения/выключения показа пункта меню.

**Comment by ovgrusin** [comment]
Чем не подходит ограничение доступа?

**Comment by zau4man** [comment]
Давайте уберем отключение/включение виджетов и будет управлять показом через права доступа. 
Вопрос не в подходит/не подходит, а в удобстве, улучшении системы и т.п.

**Comment by WebManG** [comment]
Поддерживаю. Это удобно.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/issues/165
