### ISSUE TITLE
После загрузки аватара, его изображение "мутное".

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#388]
**Используемая версия InstantCMS**: 2.6.1

**Версия PHP**:  5.4.38

**Как воспроизвести проблему**: поменять аватар у пользователя, после загрузки изображение аватара "мутное".

* первый шаг - редактировать профиль
* второй шаг - удалить аватар
* третий шаг - загрузить новый аватар

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА 
![17-12-2016 08-58-03](https://cloud.githubusercontent.com/assets/9349934/21284805/04b1c9e6-c438-11e6-8c9d-e6aabbb3a025.png)

Ранее, аватар так загружался 
![17-12-2016 09-04-30](https://cloud.githubusercontent.com/assets/9349934/21284818/572a1282-c438-11e6-8f51-297f62cd4c9d.png)
Мне кажется размер в 64px мелковат.

**Comment by nomad48** [comment]
я прямо на вашем сайте делал, почему не подтверждается, у меня тоже самое, кэш зачистил.

**Comment by BorisRBJ** [comment]
А у меня на демосайте всё подтверждается:
![rete](https://cloud.githubusercontent.com/assets/14174951/21965484/96ac100c-db69-11e6-95b0-e9022f9eee44.jpg)
После обновы 2.6.1 для всех полей с изображениями пресеты в базу стали записываться в обратном порядке, из-за этого (в данном случае на официальном демосайте инстанта) подхватывает пресет "micro" (32*32), хотя css размечен под "normal" (64*64), отсюда и размытое изображение.

Пример моей базы:

1. контент сохранённый до обновы:

![default](https://cloud.githubusercontent.com/assets/14174951/21965568/59b20646-db6b-11e6-9f65-75b6607c4ebc.jpg)

2. после обновы:

![default](https://cloud.githubusercontent.com/assets/14174951/21965590/d11e4cee-db6b-11e6-8979-5f904de34b76.jpg)

**Comment by nomad48** [comment]
@BorisRBJ у меня тоже самое: 
1. У юзеров которые до обновления аватар загружали - в таком порядке пресеты в базе 
![15-01-2017 23-38-20](https://cloud.githubusercontent.com/assets/9349934/21965993/d746a50c-db7b-11e6-8312-c76972a689ad.png)
2. У юзеров которые после обновления аватар грузили - в обратном порядке
![15-01-2017 23-37-15](https://cloud.githubusercontent.com/assets/9349934/21965997/edc933ee-db7b-11e6-8c92-b75afa3a03a1.png)

**Comment by Val-Git** [comment]
**Подтверждаю**. И на локалке и на демо сайте воспроизводится указанная выше проблема. 
Поле загрузки одного изображения (**..\templates\default\controllers\images\upload_single.tpl.php**) в цикле перебирает все установленные пресеты:
 ```
            <?php foreach($paths as $type=>$path){ ?>
                <?php echo html_input('hidden', "{$name}[{$type}]", $path); ?>
            <?php } ?>
            ...
            <img src="<?php if ($is_image_exists) { echo cmsConfig::get('upload_host') . '/' . $path; } ?>" />
```
И отображается последний по порядку. Почему не разбирался, но ранее последним был пресет **big**, сейчас (в обратном порядке) - **micro** - с размерами 32x32 px которые растягиваясь до 64px мылят картинку в превью

**Comment by uzunhair** [comment]
Давно заметил что картинка при загрузке имеет пресет micro, но думал что так специально сделали, хотя не удобно.
