### ISSUE TITLE
Ошибка вывода полей "Местоположение"

### ISSUE THREAD

**Issue by ValenokPC** [instantsoft/icms2#389]
**Используемая версия InstantCMS**: 2.6.1

**Версия PHP**:  5.6.23

**Как воспроизвести проблему**: Создать два поля местоположение, в одном контенте

При создании в одном контенте 2-а дополнительных поля "Местоположение". То при заполнении одного из них второе выводится пустым!

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: Думаю да, по скольку у меня не получилось заполнить поля.

**Comment by pumpuic** [comment]
Без проблем.
![screenshot_1](https://cloud.githubusercontent.com/assets/18246784/21287298/1d8f5ada-c471-11e6-99c6-30171972b9a5.png)

**Comment by KaRpIkS** [comment]
Ты наверно не понял, выкладываю картинки аналогию надеюсь поймешь!
![image 1](https://cloud.githubusercontent.com/assets/3881858/21289964/96c2a6ce-c4bb-11e6-97a9-35c3330d4894.png)
![image 2](https://cloud.githubusercontent.com/assets/3881858/21289965/96c2e2b0-c4bb-11e6-9c11-090a812e3553.png)
![image 3](https://cloud.githubusercontent.com/assets/3881858/21289967/96c38170-c4bb-11e6-9ca2-1560dfe28e4e.png)
![image 4](https://cloud.githubusercontent.com/assets/3881858/21289966/96c38bac-c4bb-11e6-870b-c45a4adec398.png)
![image 5](https://cloud.githubusercontent.com/assets/3881858/21289969/96c4783c-c4bb-11e6-845d-d4c38c89cbf7.png)
![image 6](https://cloud.githubusercontent.com/assets/3881858/21289968/96c3f826-c4bb-11e6-9a3e-e50836b6404b.png)
![image 7](https://cloud.githubusercontent.com/assets/3881858/21289970/96dc5ea2-c4bb-11e6-8f98-2b584151b2bf.png)
![image 8](https://cloud.githubusercontent.com/assets/3881858/21289971/96de0cc0-c4bb-11e6-9b40-577ce9c14825.png)

**Comment by KaRpIkS** [comment]
Можно исправить. 
В **templates\default\content\albums_item.tpl.php**, **templates\default\content\default_item.tpl.php**.

Найти :
`<?php if ((empty($item[$field['name']]) || empty($field['html'])) && $item[$field['name']] !== '0') { continue; } ?>` 
Выше вставить : 
`<?php if (empty($field['html'])) { continue; } ?>`

**Comment by pumpuic** [comment]
Выводится не поле а его заголовок.
Да, подтверждается.
