### ISSUE TITLE
Возможность делать привязку вывода виджетов к типу устройства (modile, table, desktop)

### ISSUE THREAD

**Issue by maxicms** [instantsoft/icms2#393]
В большинстве случаев нужно иметь возможность гибкого вывода виджетов по типу устройства на котором просматривают сайт.

**Comment by WebManG** [comment]
Согласен. На форуме уже обсуждали эту необходимость. Сходу не нашёл обсуждение, к сожалению.
Нужно, во-первых, не просто такая опция в настройках виджета, а и визуальное отображение в виджете на схеме. Чтобы с одного взгляда понять, на каких устройствах этот виджет будет отображаться, а не лазить к каждому в настройки и переключаться по вкладкам.
Во-вторых, на форуме предлагали сделать на странице виджетов в Админке переключение типа устройства, как это сделано для тем. Чтобы при переключении оставались только виджеты для выбранного устройства. И добавить пункт "Все устройства" - для показа всех виджетов.

**Comment by globator88** [comment]
А может сделать так, чтобы в шаблоне для разных устройств можно было выбрать разные схемы и привязывать виджеты этим схемам? Ведь многое в этом случае не будет меняться. Дизайн остается тот же, меняется только позиции. 
На пример scheme, scheme_tablet, scheme_mobile. В этом случае будет гибкие настройки. На пример scheme_mobile сделаем одно колонной, scheme_tablet возможна две.
