### ISSUE TITLE
Недочет при выводе ссылки Друзья в профиле пользователя (блок под аватаром)

### ISSUE THREAD

**Issue by mafru** [instantsoft/icms2#402]
**Используемая версия InstantCMS**: 2.6.1 и ниже

Необходимо в данной [строке](https://github.com/instantsoft/icms2/blob/master/templates/default/controllers/users/profile_view.tpl.php#L105) добавить условие, для проверки на включеннность вкладки "Друзья".
При отключении одноименной вкладки, ссылка друзья выводится битой и ведет на страницу 404.
Т.е. если вкладка включена выводим ссылкой, при отключении вкладки, выводим просто текстом.

**Comment by nomad48** [comment]
Подымали этот вопрос на Форуме - [404 ошибка в разделе мои друзья](http://www.instantcms.ru/forum/thread25434-1.html)

**Comment by mafru** [comment]
Я про эту ссылку в общем, а не в персональном меню. 
![friends](https://cloud.githubusercontent.com/assets/6131327/21748316/08f2e9ba-d593-11e6-9e06-90eff5e2210b.jpg)

**Comment by nomad48** [comment]
@mafru у неё такой же вид users/{user.id}/friends и если друзей нет, то по идее как объяснил @fuzegit она не выводится. Но проблема если отключить вкладку профиля, но друзья есть - присутствует.
Вот - я воспроизвёл проблему!
![08-01-2017 20-50-16](https://cloud.githubusercontent.com/assets/9349934/21752130/68635028-d5e4-11e6-88ef-a93808423e50.png)
![08-01-2017 20-51-12](https://cloud.githubusercontent.com/assets/9349934/21752132/6db806c2-d5e4-11e6-863f-2d4c91c48974.png)
![08-01-2017 20-52-05](https://cloud.githubusercontent.com/assets/9349934/21752134/72b73b5c-d5e4-11e6-861b-89952d3767b3.png)

**Comment by mafru** [comment]
Все правильно. Я же об этом здесь и написал, что необходима доп. проверка на наличие вкладки друзья.
