### ISSUE TITLE
При переносе домена ссылка в лого ведет на старый домен.

### ISSUE THREAD

**Issue by VadymVolos** [instantsoft/icms2#407]
Был перенесен портал с одного домена на другой.
Тема стандартная.

После чего две проблемы:

1. На портале если нажать на лого, то ссылка ведет на старый домен. Обыскал всю админку где прописать ссылку на новый домен не нашел. Все другие ссылки на портале работают правильно, ведут на новый домен.

2. В админке сверху кнопка "Вернуться на сайт" если на нее нажать она ведет на старый домен, а нужно на новый. Обыскал всю админку не нашел где прописать ссылку на новый домен.

3. Третья проблема, я в админке хочу увидеть какая версия установленого движка, обыскал всю админку, Версия PHP5.6.28 написана, а версии движка нигде нет. Вот как мне в поддержку сообщить какая версия движка? 

Увидел в самом низу в админке версия InstantCMS v2.6.1 Напишите возле версии пхп версию движка, опытные конечно в курсе где смотреть, но новички ожидают возле версии пхп увидеть версию движка, или сверху возле кнопки "Проверить обновления" версию написать.

**Comment by fuzegit** [comment]
Вопросы, которые вам непонятны, необходимо спрашивать на форуме. Здесь сообщают о багах и/или пожеланиях.

1, 2. Необходимо отредактировать файл конфигурации. В документации к движку об этом написано.
3. В админке на главной странице всё очевидно.
