### ISSUE TITLE
Свойства категории (Дата)

### ISSUE THREAD

**Issue by instantcms** [instantsoft/icms2#411]
Добавить к Свойствам категории (Описание, иконка, обложка)" дополнительное поле "Дата".

**Comment by iAndroS** [comment]
Можете пояснить на примере, зачем это может пригодится?

**Comment by instantcms** [comment]
Нужно сделать подшивку изданий, и чтоб можно было выводить дату выхода. Например.
За рулем №1 от 12-12-2012.
Я так предполагаю. Имеется тип контента "Журналы", Категория -"За рулем", Категория с датой -"№1". Где нибудь в виджете или компоненте можно было бы выводить журналы по дате.
