### ISSUE TITLE
Некорректная работа рейтинга

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#419]
1. При нажатии на рейтинг - работает. После обновления страницы виджет рейтинга в активном состоянии. При повторном нажатии выводится сообщение что уже голосовали. Раньше для тех кто голосовал виджет становился неактивным. В таком случае если в админке стоит "Показывать результат только тем кто голосовал" то увидит результат пользователь только 1 раз после того как проголосовал. После обновления страницы не видно.

2. Интеграция в свой компонент. В 2.6.1 контроллер  рейтинга дописан и как я заметил добавлена принудительная проверка на права доступа по метке rate. Это затрудняет гибкость. Т.к. в своем компоненте я хочу использовать несколько target элементов для виджета, но в данном случае могу только добавить одно правило mycomponent, rate в настройки доступа. Раньше на доступ не проверялось.

**Comment by nomad48** [comment]
@krylos была тема и комит вот тут можно [http://www.instantcms.ru/novosti/release260.html#c95230](url)

**Comment by krylos** [comment]
Данная тема по ссылке про 2.6.0. Я пишу про 2.6.1 там эти указнные каммиты внесены.

**Comment by nomad48** [comment]
> В таком случае если в админке стоит "Показывать результат только тем кто голосовал" то увидит результат пользователь только 1 раз после того как проголосовал. После обновления страницы не видно. - это **подтверждаю** есть такое

**Comment by fuzegit** [comment]
> Т.к. в своем компоненте я хочу использовать несколько target элементов для виджета, но в данном случае могу только добавить одно правило mycomponent, rate в настройки доступа. 

Создаёте правило на ваш контроллер в таблице cms_perms_rules: **controller: mycomponent, name: rate** и т.д. В таблице списка правил формируете правила с нужными субъектами. http://docs.instantcms.ru/dev/controllers/backend/perms

> Раньше на доступ не проверялось.

Это был баг очевидно. Вам просто нужно разобраться с логикой работы. Вопрос на форуме давно бы прояснил вам всё.

По первому пункту подправим.
