### ISSUE TITLE
Пропала возможность вставки контента по коду для пользователей во всех редакторах

### ISSUE THREAD

**Issue by ermakover** [instantsoft/icms2#420]
**Используемая версия InstantCMS**: 2.6.1

**Версия PHP**:  5,6

**Как воспроизвести проблему**: Попробовать создать статью, зайдя пользователем и увидеть, что в редакторе нет < >
У админа есть < >

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА, ещё как!

**Comment by nomad48** [comment]
@ermakover  это и ранее было, сделано для безопасности или Вы хотите чтобы Вам на сайт загрузили "интересный код"

**Comment by ermakover** [comment]
Да, в принципе логично. Просто у меня модераторы добавляли спарсенные статьи по коду, чтобы не париться с разметкой. Теперь придётся повысить их до админов и они зазнаются :-)
