### ISSUE TITLE
На мультиязычных сайтах невозможно создать маску урл для языка на странице привязки виджетов

### ISSUE THREAD

**Issue by BorisRBJ** [instantsoft/icms2#427]
**Используемая версия InstantCMS**: 2.6.1

**Версия PHP**: 5.6.29

**Как воспроизвести проблему**:

* включаем мультиязычность (например, второй язык английский)
* в урл у нас добавляется включение "/en/"
* хотим вывести некий виджет только на страницах англоязычной версии
* создаём пользовательскую страницу привязки виджетов
* указываем в фильтрации урл положительную маску "`*en*`"
* добавляем любой виджет
* в англоязычной версии на сайте он не отображается

**Comment by fuzegit** [comment]
Фильтр страниц не учитывает язык сайта. Вероятно для этих целей нужно сделать опции "для какого языка показывать виджет" в настройках самого виджета.

**Comment by FinCheck** [comment]
А как бы вернуть на рассмотрение,  данную возможность?

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/issues/922
