### ISSUE TITLE
Регистрация пользователей

### ISSUE THREAD

**Issue by lakomet** [instantsoft/icms2#428]
**Используемая версия InstantCMS**: 2.7

**Версия PHP**:  7.0.15

**Как воспроизвести проблему**:

При регистрации пользователя, нельзя задать пароль, в котором есть спец символы.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: Регистрация закрыта, поэтому не знаю.

**Comment by Val-Git** [comment]
> InstantCMS: 2.7
Я похоже что-то пропустил! Застрял где-то на 2.6.1...
(к тому что если система еще не вышла официально, т.е. альфа или бета версия, то возможно не так страшно =) )

**Comment by lakomet** [comment]
> система еще не вышла официально

Поэтому и пишу сюда, чтоб до выхода 2.7, поправили, если это ошибка.

**Comment by fuzegit** [comment]
> При регистрации пользователя, нельзя задать пароль, в котором есть спец символы.

Движок никак не ограничивает символы в пароле. Укажите подробнее о каких символах речь. Да и в целом, было бы неплохо, если сообщение, на ваш взгляд об ошибке, было максимально понятным и однозначным.

**Comment by lakomet** [comment]
Переустановил всё с нуля, ошибка ушла.
