### ISSUE TITLE
Не добавляются пункты меню.

### ISSUE THREAD

**Issue by lakomet** [instantsoft/icms2#431]
**Используемая версия InstantCMS**: 2.7

**Версия PHP**:  7.0.15

Не добавляются пункты меню. Выбивает ошибку 404.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: НЕТ

Т.к. на демо сайте проблема не воспроизводится, возможно это из-за https?

**Comment by Val-Git** [comment]
> Воспроизводится ли проблема на демо http://demo.instantcms.ru/: НЕТ

Вывод - ошибка на вашей стороне, а не в системе. Зачем сюда писать? Есть форум, где вы можете задать вопрос и найти решение вашей ошибки.

**Comment by lakomet** [comment]
> Зачем сюда писать?

На форуме, меня отправили сюда. Отсюда отправляют на форум, замкнутый круг.

> ошибка на вашей стороне, а не в системе

Ошибка на чистой, вновь установленной системе, разница возможна только в версии и https, или на https система не расчитана?

**Comment by fuzegit** [comment]
На текущей версии отсюда всё добавляется, я првоерил. https тут не при чём. https движок поддерживает в полной мере, и не может не поддерживать априори, ибо это протокол.
Однако, если вы опишите полноценно шаги, которые вы выполняли и которые привели к ошибке, возможно мы сумеем воспроизвести проблему и исправить её. До Выполнения шагов, включите режим отладки в админке.
Также. Если на этом домене, где вы тестируете ранее стояла другая версия InstantCMS, более ранняя, то перед всеми манипуляциями очистите полностью кэш браузера.

**Comment by lakomet** [comment]
> если вы опишите полноценно шаги, которые вы выполняли и которые привели к ошибке

Снял видео https://youtu.be/gbmFgzXKRlM
Отладку включил, а где логи этой отладки искать, не знаю.

**Comment by fuzegit** [comment]
> Отладку включил, а где логи этой отладки искать, не знаю.

В админке включили? Нужны логи вебсервера тогда, без текста ошибки ничего сделать нельзя, т.к. у себя проблемы не наблюдаю.

**Comment by lakomet** [comment]
Переустановил всё с нуля, ошибка ушла.
