### ISSUE TITLE
Возможность перемещать записи в нужной очередности 

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#439]
Было бы отлично иметь аткую возможность, просто перетаскиванием записей. Позволило бы быстро упорядочивать записи в нужном порядке.

**Comment by zau4man** [comment]
Требуется очень редко.
Вы можете добавить числовое поле сортировка, видимое только админу, и создать набор с сортировкой по этому полю http://docs.instantcms.ru/manual/ctypes/datasets

**Comment by RomanTap** [comment]
zau4man, можно конечно и так, но если много записей и придется неоднократно менять их порядок, то возникнет путаница)

**Comment by vlad7090** [comment]
Да, верно, если записей много, то придется записывать какой и где номер. А если вдруг какую то запись надо будет впихнуть посередине, то будет жесть, придется переписывать все последующие порядковые номера.

**Comment by Val-Git** [comment]
Согласен с @zau4man Потребность крайне редкая и сугубо индивидуальная. Тем более вполне решаема стандартными методами системы. Зачем тогда хардкодить такую настройку?

**Comment by zau4man** [comment]
> А если вдруг какую то запись надо будет впихнуть посередине
Так для этого давайте номера кратные 10. Так делает в Битриксе.

**Comment by vitaliyremi** [comment]
А что по поводу вип записей?

**Comment by zau4man** [comment]
Про вип записи и биллинг легко. Делаете поле вип, даете к нему доступ платный. В типе контента создаете набор с такой настройкой фильтрации (во втором  случае у вас должно сортироваться по дате). И вперед к светлому будущему.
![image-2017-05-17-19-05-29](https://cloud.githubusercontent.com/assets/13526431/26158896/903c68d4-3b36-11e7-81c8-330fa856aa96.png)

**Comment by vitaliyremi** [comment]
Спасибо за ответ, но в этом же "одном окне" бывает нужно разместить запись третей, а записей много вручную проставлять аля айди много времени занимает.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/issues/231
