### ISSUE TITLE
Очередность вкладок комментариев

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#440]
Есть стандартная система комментирования, есть Вконтакте. Есть возможность подключать новые. Хорошо бы иметь возможность указывать порядок вывода данных вкладок.

**Comment by Val-Git** [comment]
Выводить все вкладки комментирования одновременно вообще не имеет никакого смысла - не удобно пользоваться! Тогда зачем указывать порядок вывода? Показывайте любую систему комментирования и будет вам счастье =)

**Comment by krylos** [comment]
Видимо есть смысл, раз я предложил. И еще как минимум 10 человек ко мне обратились чтобы я сделал смену порядка вывода. Я решил это сменой сортировки массива при выводе систем комментирования. Хотелось бы иметь сортировку в коробке. Это расширит возможности при создании различного рода дополнений.

**Comment by Val-Git** [comment]
Смысла нет никакого, я это объяснил выше.

> Хотелось бы иметь сортировку в коробке. 

С таким подходом, мне тоже много чего бы хотелось. Если предложение абсолютно неконструктивно зачем тратить на него свои силы? Если вам и вашим 10 последователям в частном порядке потребовалось поменять вкладки местами, то это в частном порядке и решается. Могу повторить, что вывод одновременно нескольких вкладок комментирования абсолютно не юзабельно. А по одной вкладке выводится замечательно.

**Comment by pumpuic** [comment]
Ну а мне, а мне бы выводить их всех без вкладок, друг под другом, вот тут бы и выбор, кто первый :)

**Comment by Val-Git** [comment]
> Ну а мне, а мне бы выводить их всех без вкладок, друг под другом, вот тут бы и выбор, кто первый :)

Полностью согласен! [вот пример](http://cackle.me/demo/comments) того как надо делать комментарии с интеграцией соц. сервисов

**Comment by iAndroS** [comment]
> Полностью согласен! вот пример того как надо делать комментарии с интеграцией соц. сервисов
Да, вывод комментариев в таком виде был бы прекрасен!
