### ISSUE TITLE
Hook: comment_systems (проверить)

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#445]
При подключение хука, действующие вкладки комментирования становятся неактивными.
То есть появляется своя вкладка и при переходе на существующие vk или системную - пусто
[Пример](http://openblog.ru/posts/120-molchalivyi-voditel.html)

**Comment by Val-Git** [comment]
> При подключение хука
при подключении хука как?
Из описанной вами информации понятно ровным счетом **ничего**

Если вы используете указанный хук где-то в ваших доработках, вероятнее всего вы не возвращаете данные из  него обратно в систему, оттого она и не знает что надо что-то выводить.
