### ISSUE TITLE
Изменить тип для поля Дата

### ISSUE THREAD

**Issue by maxicms** [instantsoft/icms2#446]
Скорее всего нужно изменить тип mysql для поля Дата, так как timestamp не поддерживает даты меньше 1970 и нет возможность полноценно использовать данное поле.

**Comment by Val-Git** [comment]
Так вроде она специально так задумано?! Зачем память расходовать)) Для всего остального есть поле Возраст

**Comment by maxicms** [comment]
Как всегда лаконично! просто поле возраст использовать для даты события или чего то еще это как полить по воробьям из танка да и поля возраст другое предназначение. Ну да ладно ....
