### ISSUE TITLE
Приватность записей для участников групп.

### ISSUE THREAD

**Issue by lakomet** [instantsoft/icms2#447]
Сейчас, при создании записи любого типа контента, в разделе приватность, есть два варианта: "Показывать всем" и "Показывать только друзьям". Предлагаю добавить пункт: "Показывать только участникам группы" - при условии, что запись добавлена в какую либо группу. Данный пункт, будет полезен для мотивации вступления в группу. Для примера - пишем серию статей, первые две - три делаем открытыми, а остальные, закрываем предлагаемой настройкой, кто заинтересовался статьями вступит в группу - профит. Так же есть ещё примеры, когда будет полезна данная настройка.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/e2b76ccaef6e017491b084789aff3cded49b5700
