### ISSUE TITLE
Ask about notifications

### ISSUE THREAD

**Issue by Anti067** [instantsoft/icms2#448]
How can I do all notifications to the site are via private message, not via email?
Version is 2.7.1

**Comment by fuzegit** [comment]
Only for each user

![02-19- _001](https://cloud.githubusercontent.com/assets/13233234/23100822/d13476aa-f69a-11e6-80fb-49c04414a23c.png)

or edit the CMS PHP code.

**Comment by Anti067** [comment]
What and how to edit? Many frivolous maintenance.

**Comment by fuzegit** [comment]
Community (only russian) for this CMS here http://www.instantcms.ru/
I can not explain in English the solution to your problems, sorry.

**Comment by Anti067** [comment]
да го сложа на майка ти в устата :)

**Comment by BorisRBJ** [comment]
А ведь в принципе адекватная просьба.
Унифицировать уведомления в настройках профилей пользователей.
Для всех сделать: Не уведомлять, По e-mail, На сайте, По e-mail и на сайте.
