### ISSUE TITLE
Поиск по тегу не работает если результатов больше чем 1 страница

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#449]
**Используемая версия InstantCMS**: 2.7.1

**Версия PHP**:  5.4.38

**Как воспроизвести проблему**: произвести поиск по тегу ,чтобы было 2 или более страниц результата, допустим "красивые девушки", открывается страница с [ссылкой](https://lovelovely.ru/tags/search/news?q=%D0%BA%D1%80%D0%B0%D1%81%D0%B8%D0%B2%D1%8B%D0%B5%20%D0%B4%D0%B5%D0%B2%D1%83%D1%88%D0%BA%D0%B8) в результатах 2 страницы, когда нажимаешь на вторую страницу результатов, то открывается просто весь отмеченный  контент (допустим новости) 
ссылка [вида](https://lovelovely.ru/news)
А кнопка 2 пагинации имеет [ссылку ](https://lovelovely.ru/tags/search/news?page=2)
![19-02-2017 08-13-18](https://cloud.githubusercontent.com/assets/9349934/23099557/7df2d5dc-f67b-11e6-9ac1-5d3f388463c6.jpg)
![19-02-2017 08-13-46](https://cloud.githubusercontent.com/assets/9349934/23099560/83159a18-f67b-11e6-9863-e9e9af50a68a.jpg)

То есть по тегу поиск работает правильно, только на первой странице, при переходе на следующую, результаты поиска по тегу аннулируются.

* первый шаг 
* второй шаг
* третий шаг....

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**:  не могу воспроизвести, потому что нет такого количества контента

**Comment by BorisRBJ** [comment]
есть такое
