### ISSUE TITLE
Свойства типов контента

### ISSUE THREAD

**Issue by asphix** [instantsoft/icms2#45]
В данном функционале крайне необходимо применение всех типов полей, которые предусмотрены, а не только тех, которые строго прописаны. В идеале от раздела свойств вообще отказаться, добавив функционал привязки полей типов контента к категориям

**Comment by lokanaft** [comment]
А опишите, как вы себе представляете хранение этого всего?

**Comment by asphix** [comment]
Точно также, как сейчас идёт хранение свойств. Дополнительная таблица связей 
id типа контента - id поля - id категории и указание в поле, что есть связь. 
А ещё лучше в таблице полей типа контента добавлять опцию, где хранить массив принадлежности к id категорий. А категории уже имею связи с типом контента.

**Comment by lokanaft** [comment]
Значения как и где хранить, а потом ещё и фильтровать по ним?

**Comment by asphix** [comment]
Там же где и сейчас хранятся. В чём сложность?

**Comment by lokanaft** [comment]
Допустим записать поле типа текст в нынешний varchar 255

**Comment by fuzegit** [comment]
> Там же где и сейчас хранятся. В чём сложность?

сделайте реализацию. а мы посмотрим. заодно и увидите все сложности.

>  в поле options добавлять опцию, где хранить массив принадлежности к id категорий

фильтровать то потом как?

**Comment by asphix** [comment]
А в чём тогда смысл "свойств" у типов топиков и какие сложности в том, чтобы добавить к ним все типы полей. Если бы я был кодером я бы сделал реализацию, а так я предлагаю то, чего не хватает многим.

1) Сейчас есть поля (fields) и свойства (props)
2) props имеют связи с категориями, fields нет
Дак почему эти связи с категориями нельзя отдать fields?

**Comment by asphix** [comment]
и убрать вообще props

**Comment by fuzegit** [comment]
> Дак почему эти связи с категориями нельзя отдать fields?

потому что fields создают поля в таблице контента. В общем сложности есть и не маленькие. Поэтому не стоит аппелировать "какие сложности". Не было бы сложностей, было бы изначально так, как вы пишите.
