### ISSUE TITLE
Модерация фотоконтента

### ISSUE THREAD

**Issue by Yar-rus** [instantsoft/icms2#450]
**Используемая версия InstantCMS**: 2.7.1

Необходима полноценная модерация фотоконтента в фотоальбомах. 
Сейчас есть модерация только альбомов при создании. Аннонсы фото из непроверенного альбома отображаются в списке последних фото  и ведут на 404. 
Фотографии из альбома с установкой «Показывать только друзьям» также отображаются в списке с 404.
Зачастую модерировать придется пустые альбомы, т.к. сначала пользователь создаёт альбом и наполнять его не станет, т.к. смутившись появившейся надписью «Ожидает проверки» они покорно станут ожидать одобрения, не сообразив, что фото можно уже добавлять. Сужу по себе в данном  случае.  Всё это время в списке альбомов будут отображаться одобренные пустые альбомы, пока пользователь не вернется на сайт и не загрузит фото. Удалить их тоже нельзя, ведь они одобрены и готовы к наполнению.
Так же стоит учесть случаи, когда пользователи удалят все фото из альбома, а сам альбом нет. В этих условиях он не должен отображаться в списках фотоальбомов.

**Comment by nomad48** [comment]
Все что описал @Yar-rus  так и есть, я из-за этого отключил модерацию альбомов, потому что, альбом еще на модерации, а юзер уже фоток в него напихал, но... альбома нет еще, а фото уже в ленте отображаются. Некоторые бросали альбом не заполненый, так как для пользователей не понятна логика самой модерации альбома.
