### ISSUE TITLE
Сообщение  «Ожидает проверки» 

### ISSUE THREAD

**Issue by Yar-rus** [instantsoft/icms2#455]
**Используемая версия InstantCMS**: 2.7.1

Этому сообщению будет лучше в верхней части записи, чем внизу. Как вариант, после заголовка.
Смысл в том, чтоб пользователь сразу увидел сообщение, что его запись на модерации и пока не будет нигде отображена.  После перезагрузки открывается верх страницы, а запись может быть сколько угодно длинной. 
Некоторая часть пользователей сразу пойдут смотреть свою запись в общий список, которой там, естественно, нет. Многие причину долго не поймут.

**Comment by Val-Git** [comment]
Чтобы пользователи не бежали искать свою новосозданную запись нужно кнопку
"Сохранить" называть "Отправить на модерацию" ;)

вс, 19 февр. 2017 г., 22:00 Yar-rus <notifications@github.com>:

**Comment by Yar-rus** [comment]
На крайний случай можно и так. Но на совсем крайний.

**Comment by globator88** [comment]
Пользователю при сохранении сообщается же что материал отправлен на модерацию

**Comment by Yar-rus** [comment]
Понять это можно только прокрутив свой материал в самый низ. До этого не каждый догадается. А дать понять о том, что его материал на модерации и, соответственно, НЕ отобразится, сколько бы он не рыскал по списку, нужно.
Если имеете ввиду уведомление на почту, то я писал - "Смысл в том, чтоб пользователь сразу увидел сообщение".  
Если есть мнение, что это не существенно, то спорить я не буду. У себя я как-нибудь поправлю.
