### ISSUE TITLE
404 пока запись на модерации

### ISSUE THREAD

**Issue by Yar-rus** [instantsoft/icms2#456]
**Используемая версия InstantCMS**: 2.7.1

Записи, находящиеся на модерации имеют ошибку 404.
Из списка такая запись пропадает, но по ссылке на нее попадают и пользователи и поисковики.
Возможен вариант с надписью на странице "Страница на модерации, зайдите позже."

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/f7adc0b3b835cd0d8d84021cf7624a7f690386e9
