### ISSUE TITLE
Проверка на дубли системного имени при создании типа контента

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#458]
При создании типа контента логично сделать проверку на существование компонента с данным системным именем.
Не знаю почему но много пользователей создают тип контента и указывают системное имя уже существующего другого компонента.
Возникают конфликты. Вопросы.

**Comment by fuzegit** [comment]
Так [есть же](https://github.com/instantsoft/icms2/blob/master/system/controllers/admin/actions/ctypes_add.php#L20)

**Comment by krylos** [comment]
Сорри тогда за беспокойство. Сам не проверил. Сегодня просто трое уже обращались найти глюк. И было так.
