### ISSUE TITLE
Значения свойства типа "Список" "съезжает" при изменении (добавлении\удалении) значения

### ISSUE THREAD

**Issue by alexeyaa** [instantsoft/icms2#466]
**Используемая версия InstantCMS**: v2.6.1

Версия PHP: 5.6.29-0+deb8u1

**Как воспроизвести проблему**:

1. Создаём ново свойство типа Список.
2. Добавляем допустимые значения "Один, Два, Три"
3. Создаем материал выбираем значение "**Три**"
4. Редактируем Свойство добавляем между Один и Два значение "Полтора"
5. Открывает созданный в п. 3 материал и видим значение поля "**Два**".

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: НЕТ
Сайт глючит созданная статья выдаёт 404 при открытии..

**Comment by Val-Git** [comment]
Как то всплывал на форуме подобный вопрос.

Список представляет из себя элемент вида **"значение" - "текстовая строка"**. В вашем примере это выглядит так:
```
0 - Один
1 - Два
2 - Три
```
Когда вы выбрали значение "**Три**" в БД сохраняется не текстовое содержимое вашего выбора а его значение, т.е. число **2**.
Теперь вы добавляете "Полтора", получается так:
```
0 - Один
1 - Полтора
2 - Два
3 - Три
```
т.к. нумерация всегда идет в порядке возрастания от 0 до плюс бесконечности.
Теперь при открытии страницы, из БД достаётся ранее сохраненное значение (**2**) и отображается строка этого значения - сейчас это "**Два**".

Таков механизм работы свойства типа Список. Необходимо это учитывать.

**Comment by fuzegit** [comment]
Стоит изучить [документацию](http://docs.instantcms.ru/manual/ctypes/fields/types#список)

**Comment by alexeyaa** [comment]
Про механизм работы понятно. Скажем так, не очень нравится как он работает.)
Есть, например, значительное количество материалов, у которых уже прописаны свойства. И тут захотелось добавить ещё значение. Добавляю одно значение свойства и все свойства поехали.. Теперь единственный путь это исправлять весь материал..

В принципе всё это сильно напрягает, только если хочется чтобы свойства были в нужном порядке. Если всегда добавлять свойства в конец, то проблемы не будет. Но в этом случае нет возможности свой порядок пунктов сделать.  Если бы они, например, отображались с сортировкой по алфавиту, то проблема была бы не столь критичной. Тогда можно было бы учитывать эту особенность и добавлять только в конец списка.

Ну или при изменении свойства проходить по всему материалу и исправлять его значения.

**Comment by Val-Git** [comment]
> Стоит изучить документацию

Действительно)) Спасибо, буду знать!

**Comment by Val-Git** [comment]
> Но в этом случае нет возможности свой порядок пунктов сделать.

В документации же написано что можно указывать свои значения через вертикальную черту:
```
1 | Килограмм
100 | Центнер
1000 | Тонна
```
Если вдруг потребуется что-то прописать посередине то ничего не поломается:
```
1 | Килограмм
10| Десять килограмм
100 | Центнер
1000 | Тонна
```

**Comment by alexeyaa** [comment]
@Val-Git Спасибо за разъяснение!
