### ISSUE TITLE
Нельзя перенести в корневую категорию

### ISSUE THREAD

**Issue by Jestik** [instantsoft/icms2#467]
**Используемая версия InstantCMS**: 2.7.1

**Версия PHP**:  5.6

**Как воспроизвести проблему**:

* Создаем тип контента, " Разрешить добавлять записи в корневую категорию" - галочка снята
* Добавляем категории и свойства к ним
* Добавляем записи в категории и добавляем к ним свойства (у меня было 2 свойства - тип поля список)
* "Разрешить добавлять записи в корневую категорию" - ставим галочку в админке
* Пытаемся зайти в запись, меняем категорию на корневую - не можем сохранить запись
Поля свойство выдают ошибку: "Указано недопустимое значение"

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: Новые записи добавляються с ошибкой, а существующие нельзя полностью отредактировать

**Comment by Alex-HAV** [comment]
И в другую категорию также нельзя перенести

**Comment by Alex-HAV** [comment]
Таке же когда отключил категории для данного типа контента, то поля свойств остались на странице редактирования записи, на демо сайте так же
