### ISSUE TITLE
Универсальность типографа

### ISSUE THREAD

**Issue by san-sanych-k** [instantsoft/icms2#469]
Сделать типограф более универсальным, позволяющим в админке произвести более тонкую настройку. А точнее: он не работает корректно с редакторами live и redactor. Происходит это когда в исходном коде встречаются теги, которые типограф не обрабатывает и выводит сущностями.

Нужно добавить разрешенные теги и возможные значения.

**Comment by geminisf** [comment]
Поддержу. Хотел предложить то же самое.

**Comment by fuzegit** [comment]
Объединено с #923
