### ISSUE TITLE
Исключить js и css файлов при объединении 

### ISSUE THREAD

**Issue by my-instantcms** [instantsoft/icms2#47]
Некоторые файлы не правильно работаю когда в админке включена Объединить js/css файлов.
Хочется при добавлении файлов передавать еще один параметр, например:
$this->addJS('файл', false); 
что бы исключить этого файла из объединения.

**Comment by mafru** [comment]
Если не изменяет память, то данная возможность заложена в движке.
вместо $this->addJS('файл', false); 
используйте
$this->addJS('файл', ' ', false);

**Comment by fuzegit** [comment]
my-instantcms, вы в сам метод addJS загляните) mafru подсказал совершенно верно.

**Comment by my-instantcms** [comment]
<b>mafru</b>, спасибо.
<b>fuzegit</b>, извиняюсь за не внимательность) вроде раньше не было)
