### ISSUE TITLE
В наборах "Не показывать в категориях"

### ISSUE THREAD

**Issue by numinaki** [instantsoft/icms2#471]
**Используемая версия InstantCMS**: icms2

**Как воспроизвести проблему**:

В наборах при отметке: "Не показывать в категориях", набор не выводится в категории, но выводится во всех подкатегориях этой категории.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
> набор не выводится в категории, но выводится во всех подкатегориях этой категории.

отметьте его для подкатегорий, в чем проблема?

**Comment by numinaki** [comment]
В этом и проблема, что такой возможности нет, можно поставить отметку только для категорий, а в подкатегриях все равно выводится.

**Comment by fuzegit** [comment]
> Пункт "Не показывать в категориях" выбираю категорию, но там не выплывают подкатегории.

так надо было об этом и написать, что в списке нет подкатегорий.

**Comment by numinaki** [comment]
Наверное надо было, не догадался)
