### ISSUE TITLE
Информационное поле при модерации контента

### ISSUE THREAD

**Issue by Yar-rus** [instantsoft/icms2#473]
**Используемая версия InstantCMS**: 2.7.1

Сейчас модерируемый контент можно или одобрить или удалить. Удалить без объяснения причин не логично, а функции отправки на редактирование пользователю нет. Запись так и будет висеть, а пользователь будет думать, что никто пока его запись не рассматривал. 

Оптимальным вариантом было бы наличие кнопки "Необходима корректировка", к примеру, с указанием причины и уведомлением, а рядом с кнопкой "Ожидает проверки" (или уже "Необходима корректировка") разместить текстовое поле для пометок администратора,  где можно написать, что нужно пользователю предпринять.

Ну, или как временное решение, хотя бы, текстовое поле рядом с текстом "Ожидает проверки".

**Comment by Val-Git** [comment]
Тема поднималась ранее.
IMHO удалять контент на модерации не следует. Модератор должен только отправлять его на доработку автору бесчисленное количество. А автор, если не хочет дорабатывать - удалит сам.
И, да, при отправлении на доработку нужен фидбек что и как исправлять.

Также при создании записи, автору, вместо кнопки "сохранить" лучше показывать "отправить на модерацию" (т.е. поменять заголовок кнопки) - получается более правильный UX.

**Comment by Yar-rus** [comment]
> вместо кнопки "сохранить" лучше показывать "отправить на модерацию"

Не все используют функцию модерации.  Им такой текст на кнопке ни к чему. )

**Comment by Val-Git** [comment]
> Не все используют функцию модерации. Им такой текст на кнопке ни к чему. )

Так я и говорю о тех кто использует))
Если заметили, сейчас при модерируемом контенте внизу формы справа есть подпись указывающая на то, что запись должна пройти модерацию. И этой записи нет, в тех случаях когда модерация отключена в настройках.

Когда кнопка будет называться "Отправить на модерацию", пользователю будет понятнее куда он посылает запись - это написано в любых UX мануалах.

**Comment by Yar-rus** [comment]
При включенном режиме модерации и кнопка по другому называется... ааа, вон оно чё. Ну, может быть. А можно прост сообщение, после сохранения. Может для кого-то слово Модерация будет звучать пугающе.
Осталось дело за малым - полноценный функционал модерации, т.е. то, о чём, как раз, данный топик.
А ещё, неплохо бы, чтоб возможность отправки на модерацию была и у уже активных записей. Ведь можно что-то упустить...

**Comment by iAndroS** [comment]
Для уже активных и существующих записей при отправке на доработку автору на сайте должна отображаться предыдущая версия материала, возможно, опционально. 
К примеру, у вас на сайте была статья, закрепившаяся в ТОПе Псов, но либо стала неактуальной, либо содержит неприменимый контент (мат, запрещенное что-то новым законом). Скрывать с сайта такую статью не есть хорошо.
Также было бы неплохо отправлять на доработку не только автору, но и группе пользователей. К примеру, на сайте есть группа Журналисты. Все они получают уведомление о необходимости доработать материал, если кто-то берет его в работу, остальные видят уведомление, что опоздали. Ну, тут нужна тесная интеграция с биллингом, дабы мотивировать Журналистов редактировать чужие материалы.

**Comment by Margauza** [comment]
> IMHO удалять контент на модерации не следует. Модератор должен только отправлять его на доработку автору бесчисленное количество. А автор, если не хочет дорабатывать - удалит сам.

Вирусню, спам, порно, материалы нарушающие законодательство нужно удалять сразу, зачем держать их в подвешенном состоянии и набивать ими сайт, даже если они не опубликованы. Или вы думаете спамеры будут редактировать свой контент? Модераторы для того и нужны чтобы чистить сайт.

**Comment by Val-Git** [comment]
> Вирусню, спам, порно, материалы нарушающие законодательство 

Обычно я с другим контентом создаю сайты))
Я к тому, что описанные вами вещи надо удалять вместе с их автором. А это работа администратора. Модератор это больше из серии проверить контент на соответствие критериям сайта: подходит - пропускаем, не проходит заворачиваем назад с указанием что не так.
