### ISSUE TITLE
403 В поле Ссылка (https -> http)

### ISSUE THREAD

**Issue by Alex-HAV** [instantsoft/icms2#481]
**Используемая версия InstantCMS**: 2.7.1

**Как воспроизвести проблему**:

Сайт с https
Тип поля ссылка
Вставляем ссылку на http сайт
при переходе по ссылке 403, даже не показывается страница редиректа

**Comment by fuzegit** [comment]
Не подтверждается.

![04-01- _001](https://cloud.githubusercontent.com/assets/13233234/24569581/72d2678a-166f-11e7-8c5b-11a1fb90f596.png)
![04-01- _002](https://cloud.githubusercontent.com/assets/13233234/24569582/72d3be3c-166f-11e7-93eb-22bbbe60825a.png)
