### ISSUE TITLE
Улучшения вывода групп полей

### ISSUE THREAD

**Issue by numinaki** [instantsoft/icms2#482]
**Используемая версия InstantCMS**: icms2

Стало удобно, что можно вывести поля в группах на страницах, тем самым можно задавать стиль целого блока полей, но хотелось бы улучшения:
сейчас выводится все под одним классом fields_group, сколько бы мы разных групп не создали, все имеют один класс, тем самым, невозможно сделать стилизацию разных групп полей с разными значениями, даже задать ширину, высоту и т.п. Поэтому хотелось бы, чтобы названия классов были уникальные fields_group_1 или по названию группы fields_group_kratkie_svedeniya или что-либо подобное.

**Comment by globator88** [comment]
Идея давно стоит у меня в голове. Даже хотел компонент заказать для этого. Такое возможность сделает Instant еще гибким. У каждого будет возможность настроить страницу записей по своему вкусу. На пример список мультивыбор можно сделать так http://joxi.ru/eAO1N5WixZy4Nm 
А полей сортировать вот так http://joxi.ru/nAy8MeJFY3OYX2  и т. 
Не знаю на столько сложна реализация, но все же ждем )
Еще можно добавить возможность не показывать заголовок группы.

**Comment by danil050405** [comment]
Полностью поддерживаю

**Comment by lakomet** [comment]
Поддерживаю на все 100%

**Comment by globator88** [comment]
Думаю еще нужно и свойствам добавить класс. То есть не группировать отдельно как в типах полей, а хотя бы всем свойствам один класс добавить. Что бы как то слить их с типами полей в записи.
