### ISSUE TITLE
Авто удаление не верифицированных пользователей

### ISSUE THREAD

**Issue by globator88** [instantsoft/icms2#484]
Не прошедших верификацию пользователи автоматически не удаляются. Если точнее крон запускается, но результата нету. На демо не смог проверить.

**Comment by nomad48** [comment]
Подтверждаю, тоже самое, пользователи не прошедшие верификацию не удаляются. 
ICMS 2.7.1 крон работает.

**Comment by mafru** [comment]
Судя по всему данный фильтр лишний.
https://github.com/instantsoft/icms2/blob/master/system/controllers/auth/hooks/cron_delete_expired_unverified.php#L14

**Comment by mafru** [comment]
Только что проверил работает на версии 2.7.1.

**Comment by nomad48** [comment]
@mafru в смысле проверили, после удаления фильтра лишнего?

**Comment by mafru** [comment]
Нет, ничего в фильтре удалять не нужно. Создал пользователя. Зашел в базу, переставил дату в поле date_reg, чтобы дата регистрации стала удовлетворять условию для удаления пользователя.
После выполнения задачи, пользователь благополучно удалился с сайта.

> в смысле проверили, после удаления фильтра лишнего?
Это или у меня был баг или еще что, но один пользователь был не верифицирован, а в базе у него было заполнено значение IP.

**Comment by nomad48** [comment]
@mafru вот я тоже это заметил, что не верифицированные пользователи удаляются как-то избирательно, некоторые удаляются по крон, некоторые нет. Но какая-то ошибка присутствует.

**Comment by nomad48** [comment]
готов обсудить и дать доступ в админку, у меня сегодня зарегистрировался такой юзер, через три дня проверю как его перевел крон. 
![31-03-2017 20-17-41](https://cloud.githubusercontent.com/assets/9349934/24561391/44e63fec-164f-11e7-8b97-4764e32ff6a7.jpg)

**Comment by globator88** [comment]
У меня тоже стоит 3 дня. Еще, в версии 2.5.1, пустой IP не было. А сейчас встречается.
![94acbc532d](https://cloud.githubusercontent.com/assets/17290016/24561622/801fff9a-1658-11e7-8fb9-5841822e9221.png)

**Comment by globator88** [comment]
После тестирование пришел к выводу, что не удаляются только те пользователи к которым добавлен последний IP, даже если они не верифицированы. Значить проблема в добавлении IP не верифицированным пользователем. Но могу ошибаться, поэтому продолжаю тест.

**Comment by nomad48** [comment]
У меня не верефицированные юзеры тоже двух видов, одни с IP другие без, вот слежу какие удаляться какие нет, при срабатывании cron. Потом отпишу сюда.

**Comment by nomad48** [comment]
Вот сегодня прошло три дня как один юзер не подтвердил email - крон сработал, юзер не удалился, был переведен из группы новые в группу пользователи.
![03-04-2017 20-50-21](https://cloud.githubusercontent.com/assets/9349934/24622973/91082e00-18af-11e7-9589-b17c237d6d24.jpg)
![03-04-2017 20-50-57](https://cloud.githubusercontent.com/assets/9349934/24622981/95be1162-18af-11e7-95a2-3375fc9063ab.jpg)
Отсюда у меня возникает мысль, если крон по переводу из группы в группу срабатывает раньше чем удаление не верифицированных пользователей, может поэтому удаление не срабатывает?

**Comment by globator88** [comment]
Тестил 3 дня. Не удаляются те пользователи к которым добавлен IP

**Comment by nomad48** [comment]
@globator88 подтверждаю, тоже самое, у кого нет IP удаляются, у кого есть IP не удаляются по cron

**Comment by globator88** [comment]
А у Вас крон запускается? У меня и крон не запускается почему то.

**Comment by nomad48** [comment]
@globator88 с кроном всё ок у меня 
![10-04-2017 08-56-34](https://cloud.githubusercontent.com/assets/9349934/24847773/c5749d06-1dcb-11e7-8537-24c754f20d34.jpg)
Проверьте задачи крон, которые у вас стоят раньше чем эта, если какая-то не правильно работает, то на ней будет задача останавливаться.

**Comment by shuma375** [comment]
У меня не удаляются и с IP и без него. Крон запускается, не знаю в какую сторону рыть

**Comment by pocus-1** [comment]
Присоединюсь к компании.
У меня тоже не удаляются заблокированные аккаунты с неподтвержденным e-mail. Зависимости от IP не заметил.
Заглянул в хук cron_delete_expired_unverified. Удаление должно происходить через 48 часов, если в настройках не указано другое. Сейчас попробую очистить это поле, посмотрим что будет. Ну а всё остальное там для меня не понятно.

**Comment by pocus-1** [comment]
Происходит что то непонятное. Одному из пользователей сменил ip на NULL, и он прекрасно удалился  по крону. А с другим это фокус не проходит.

**Comment by iAndroS** [comment]
2.13.1 - проблема сохранилась - юзеры заблокированы, но не удалены. При просмотре профиля IP под аватаркой не обнаружены. Профили явно ботовые (емайлы-кракозябры в аналогичных доменных зонах).
