### ISSUE TITLE
Виджет "Фильтр контента"

### ISSUE THREAD

**Issue by danil050405** [instantsoft/icms2#487]
В виджете "Фильтр контента " не отображаются поля свойств контента как в обычном фильтре над списком контента, на мой взгляд это недоработка, иногда необходимо вывести фильтр именно виджетом, но виджет получается с неполноценным функционалом, пожалуйста включите поля свойств в виджет

**Comment by pocus-1** [comment]
Всё отображается. Не забываем включать зеленые галочки "фильтр".
