### ISSUE TITLE
Немного адаптивности в комментариях

### ISSUE THREAD

**Issue by zau4man** [instantsoft/icms2#489]
Сейчас отступ в дереве комментариев указывается в пикселях, и на мобильных телефонах для нескольких уровнях комментарии выстраиваются в узкую полосочку.
Может быть стоит внеси правки в файл templates/default/controllers/comments/comment.tpl.php

В 31 строке убрать нолик
`$level = (($limit_nesting && $entry['level'] > $limit_nesting) ? $limit_nesting : ($entry['level']-1))*3;`

В 35 строке заменить px на %
`<div id="comment_<?php echo $entry['id']; ?>" class="comment<?php if($is_selected){ ?> selected-comment<?php } ?><?php if($target_user_id == $entry['user_id']){ ?> is_topic_starter<?php } ?>" <?php if ($is_levels) { ?>style="margin-left: <?php echo $level; ?>%" data-level="<?php echo $entry['level']; ?>"<?php } ?>>`

**Comment by uzunhair** [comment]
Может через important на мобильниках убрать отсутп?
