### ISSUE TITLE
Не работает фильтрация по полю список:мультивыбор

### ISSUE THREAD

**Issue by asphix** [instantsoft/icms2#49]
При фильтрации по одному из значений поля "список:мультивыбор" набор не выводит на странице ничего.
В настройках набора фильтр = название поля: мультисписок, содержит = id значения
При установке фильтр = название поля: мультисписок, содержит = 1 - выводит все записи этого типа контента

**Comment by fuzegit** [comment]
> Не работают наборы типов контента

> При фильтрации по одному из значений поля "список:мультивыбор" набор не выводит на странице ничего.

Так что не работает то? Все наборы или все же фильтрация по типу поля список:мультивыбор?
Пожалуйста, пишите так, чтобы можно было однозначно понять. Не будет лишним, если вы опишите свою последовательность действий. Гадать врятли кто-нибудь будет и ваше сообщение останется лежать не рассмотренным долгое время.

**Comment by asphix** [comment]
Фильтрация по значению типа поля список:мультивыбор (мульти).
Порядок действий.
Создаю тип контента -> В нём поле мульти со значениями "Один", "Два", "Три".
Создаю запись -> в поле мульти выбираю значения "Два", "Три"
Настраиваю набор для типа контента -> Выбираю в качестве фильтрации поле мульти
со значением "содержит" - и ставлю 2.
Открываю набор, Материал, в котором отмечено "Два" не отображается.
Если ставлю в фильтрации "содержит" - 1, то набор выводит все материалы данного типа контента.

**Comment by fuzegit** [comment]
Вот теперь все понятно, благодарю за подробности

**Comment by fuzegit** [comment]
Вы неправильно делали фильтрацию.

> Выбираю в качестве фильтрации поле мульти со значением "содержит" - и ставлю 2.

откуда цифра 2 взялась? Вы смотрели по какому принципу сохраняет данное поле значения?

**Comment by asphix** [comment]
да, увидел, что сохранение идёт по типу 1 или 0. тогда не хватает документации по тому, как фильтровать подобные поля

**Comment by fuzegit** [comment]
> тогда не хватает документации по тому, как фильтровать подобные поля

не хватает, согласен. но пока подобную фильтрацию нужно делать исходя из значений, формируемых в БД

**Comment by vlad7090** [comment]
В профиле создал поле список:мультивыбор

В предустановленых значениях указал 5 значений каждый с новой строки

В профиле указал три значения из 5

Если в фильтре на сайте искать по данному полю и указать все 5 значений чекбоксами, то ни одного пользователя не находит.

Так и задумано или всеже он должен найти пользователя, который совпадает хотя бы с одним из 5 значений?
