### ISSUE TITLE
В списке контента, на сайте, в поле краткого описания, вместо города выводятся цифры.

### ISSUE THREAD

**Issue by EnotAlex** [instantsoft/icms2#490]
Версия InstantCMS 2.7.2
Версия PHP 5.4.16

**Как воспроизвести проблему**:

1) Размещаем на главной странице виджет: **Список контента**;
2) Редактируем виджет **Список контента**;
3) Открываем ->>**Опции**->>**Поле краткого описания**->>**Город**
4) Сохраняем настройки.
5) Смотрим главную страницу, и видим вместо названий городов, цифры.

Что получается смотрите по ссылкам ниже:
https://yadi.sk/i/MPuZOIcv3GchoP
https://yadi.sk/i/tMzqhABL3Gchk5

**Comment by EnotAlex** [comment]
на демо http://demo.instantcms.ru/ пока не могу проверить, т.к. на сайте выдаёт ошибку Forbidden

You don't have permission to access / on this server.

**Comment by EnotAlex** [comment]
как не требует решения??

**Comment by fuzegit** [comment]
В поле краткого описания в виджете подразумевается описание (т.е. текстовые поля), а не специфические поля.

**Comment by EnotAlex** [comment]
Простите не знал, а мне вот именно так и понадобилось.
