### ISSUE TITLE
Возможность отключения ненужных городов и регионов.

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#492]
**Используемая версия InstantCMS**: 2,7,2

Было бы отлично иметь возможность отключать ненужные страны, регионы и города. Т.к позволит сделать сайт для определенных регионов, а не всю страну сразу.

**Comment by ShushkovEV** [comment]
это есть в функционале системы, редактируйте компонент география и удаляйте ненужные страны и регионы

**Comment by Dimson-Git** [comment]
Удалять не всегда нужно и полезно, а вот отключить иногда бывает надо

**Comment by elipss** [comment]
Geo для Регистрации ,  Профиля

Geo 1  для Тип контента 1

Geo 2  для Тип контента 2
