### ISSUE TITLE
Не работает запрет регистрации если IP внесён в черный список.

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#493]
**Используемая версия InstantCMS**: 2.7.1

**Версия PHP**:  5.4.38

**Как воспроизвести проблему**: внести ip в черый список и попробовать зарегистрироваться.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: не могу проверить

На моем сайте - внёс IP одного чудака, на букву М в список запрещенные IP-адресов для регистрации, но этот чудак всё равно смог зарегистрироваться.

![14-04-2017 15-33-50](https://cloud.githubusercontent.com/assets/9349934/25043342/eac1bb3e-2127-11e7-9de7-911157fec7c6.jpg)
![14-04-2017 15-34-41](https://cloud.githubusercontent.com/assets/9349934/25043343/eaddf704-2127-11e7-912b-a3baf7d14fc3.jpg)

**Comment by fuzegit** [comment]
Не могу повторить, всё блокируется. Может у вас он регистрируется через TOR например, а потом авторизуется уже обычно.

**Comment by nomad48** [comment]
@fuzegit добрый день, этот чудак регистрировался у меня ранее и его ip я внёс в черный список еще полгода назад. В этот раз он регистрировался через компонент uLogin. Но ip один и тот же, TOR сделал бы подмену ip.

**Comment by fuzegit** [comment]
> В этот раз он регистрировался через компонент uLogin

так а при чем тут штатная регистрация? штатная регистрация блокирует по указанным ip.

**Comment by nomad48** [comment]
Написал разработчикам uLogin для проверки.
