### ISSUE TITLE
Модерация фото

### ISSUE THREAD

**Issue by Yar-rus** [instantsoft/icms2#494]
**Используемая версия InstantCMS**: 2.7.2

Ранее уже поднимал вопрос о модерации фотоальбомов, но не могу найти эту запись.
С тех пор еще более убедился, что модерация фотоальбомов бессмысленна в принципе. Особенно пустых. )

Нужна модерация фотографий. А так как все фото пользователей, тем более, если они нигде не выводятся, кроме профиля, модерировать тоже бессмысленно, то устанавливать модерацию фото, можно дать только выбранным альбомам или категориям, к примеру. А в частных альбомах пусть творят, что хотят. Там и после размещения можно удалить. А вот в основных альбомах сайта долго может пакость присутствовать, пока админ не проснется.

В таком случае ликвидируется ситуация, когда у админа две крайности - либо позволить добавлять всё, что угодно в общие альбомы сайта (не общие альбомы пользователей, это принципиальная разница, логическая), либо материал, который мог бы быть весьма интересен для всех, добавляется в частный альбом, где и теряется. Уверен, что ни один админ не пойдёт на первый вариант. Ну а второй вариант лишает многого.

**Comment by mafru** [comment]
Случайно не это https://github.com/instantsoft/icms2/issues/450 ?

**Comment by Yar-rus** [comment]
Да, эта. Но там речь вёл об альбомах, но со временем стало более ясно, что альбомы это не главное... )
Главное их содержимое.
