### ISSUE TITLE
Верстка личных сообщений

### ISSUE THREAD

**Issue by zau4man** [instantsoft/icms2#495]
**Используемая версия InstantCMS**: 2.7.2

Надо, наверно, добавить в личные сообщения отслеживание ресайза окна... а то при переписке после отправки сообщения форма блокируется, андроидовская клавиатура прячется, окошко прыгает, форма отправки сообщения появляется, клавиатура андроидовская появляется, и форма ответа прячется под нижним краем.

См. скриншот
![0c1c548f-e2c2-4b00-b5a1-48aa3deb539e](https://cloud.githubusercontent.com/assets/13526431/25071778/4a6dfb62-22d9-11e7-9104-c3200a7bf7f6.jpg)

И так постоянно при переписке. Приходится после написанного сообщения немного доскроливать, чтобы увидеть форму написания сообщения.

**Comment by fuzegit** [comment]
В файле /templates/default/js/messages.js функцию **scrollChat** заменить на:
```
this.scrollChat = function(){
    $('#pm_chat').stop().animate({
        scrollTop: $('#pm_chat')[0].scrollHeight
    }, 500);
    $('.nyroModalCont').stop().animate({
        scrollTop: $('.nyroModalCont')[0].scrollHeight
    }, 500);
};
```
> андроидовская клавиатура прячется, окошко прыгает, форма отправки сообщения появляется, клавиатура андроидовская появляется

А если в этом же файле убрать 
`$('textarea', form).prop('disabled', true);`
клавиатура не будет прятаться?

**Comment by zau4man** [comment]
> А если в этом же файле убрать
Теперь форма появляется при прыгании окна. Но последние написанные сообщения так и скрыты за нижним краем. И чтобы их увидеть (т.е. убедиться, что отправил то, что хотел). См. скриншот, видно, что после написания сообщения на экране сообщения за вчера, сегодняшние, где-то внизу.
Правки this.scrollChat ничего не принесли.
![9d734b0b-e410-4867-8e0e-22fb51c04a61](https://cloud.githubusercontent.com/assets/13526431/25083714/f550e31c-2371-11e7-9cd8-c4e160db8feb.jpg)

**Comment by fuzegit** [comment]
> Правки this.scrollChat ничего не принесли

должны были принести, мб кэш?

**Comment by zau4man** [comment]
> должны были принести, мб кэш?

Каждый раз дописываю версию
`<?php $this->addMainJS("templates/default/js/messages.js?ver=6"); ?>`

И предыдущее сообщение не актуально. Оказывается, форма не пропадает, если контент страницы до или после вызова окна сообщений прокрутить до низу.

Никакие из правок, предложенных выше, не дают действий. Вы просто попробуйте открыть окно личных сообщений (где их не 2-3, а больше чем на один экран). Вы сразу увидите, как при появлении клавиатуры гугла происходит изменения размеров окна, но сообщения и форма остаются на месте и скрываются за краем.

Если сообщений в личке 2-3 вы не поймете проблемы.
