### ISSUE TITLE
Ошибки при добавлении объявлений на демо-сайте

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#496]
**Используемая версия InstantCMS**: 2.7.2

**Версия PHP**:  5.3.3-7+squeeze19

**Как воспроизвести проблему**:

* Переходим ПОД АДМИНОМ в объявления в раздел автомобили - Audi
* Открываем страницу добавления автомобиля 
* При сохранении получаем 404 ошибку

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

В итоге объявление появляется в списке, но при переходе ссылка объявления вида http://demo.instantcms.ru/**# board/.html**

Через несколько минут объявления найти не смог уже и в списке объявлений (срабатывает восстановление бд по крону?)

**Comment by fuzegit** [comment]
Не нужно тестировать **только** на демо сайте. Тестируйте на своих сайтах. На демо сайте есть ограничения и автовосстановление.
