### ISSUE TITLE
Ошибка сортировки и фильтров в наборах

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#497]
**Используемая версия InstantCMS**: iCMS 2.7.2
**Версия PHP**:  5.6.29-0+deb8u1

**Как воспроизвести проблему**:

* Заходим в созданный тип контента, создаем новый набор
* Смотрим настройки сортировки, видим там отображение типов полей "Список" и "Список-мультивыбор". Считаю, что данные поля в настройках сортировки не нужны: сортировать можно уникальные текстовые поля по алфавиту и числовые значения, даты... Это можно рассматривать как недочет, но не ошибку, тут некритично. Вопрос, как оно будет отрабатывать на сайте...
* В настройках фильтра по свойствам выбираем какой-нибудь тип поля "Список". При этом у нас отображаются параметры подбора, будто не для текстовых, а для числовых полей
![screenshot_1](https://cloud.githubusercontent.com/assets/17408903/25084973/3a733e7a-2392-11e7-9e55-646da0a54913.png)
Если же выбрать тип поля с мультивыбором, то получим нормальную картину
![screenshot_2](https://cloud.githubusercontent.com/assets/17408903/25084987/536d7ed6-2392-11e7-9c3f-4d6f6a0aa928.png)
* При вышеуказанных фильтрах в наборах отображение фильтрованного контента на сайте не происходит! Полагаю, проблема в том, что движок ищет по id полей, а не их значениям! 

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: Не удалось проверить, уперся в проблему добавления контента на сайте.

**Comment by fuzegit** [comment]
http://docs.instantcms.ru/manual/ctypes/datasets/add
