### ISSUE TITLE
Невозможно установить превью в списке, отличные от превью в записи.

### ISSUE THREAD

**Issue by Yar-rus** [instantsoft/icms2#504]
**Используемая версия InstantCMS**: 2.7.2

Поле "Набор изображений" - видимость поля "Показывать в списке".  Тут какое бы превью не ставилось режиме "Размер в списке", в списке будут показываться те превью, которые стоят в режиме "Размер в записи".

**Comment by fuzegit** [comment]
На текущей версии не подтверждается.
