### ISSUE TITLE
Убрать пустые группы свойств в контенте

### ISSUE THREAD

**Issue by AHTEPO** [instantsoft/icms2#506]
**Используемая версия InstantCMS**: 2.7.1

**Версия PHP**:  5.6

**Как воспроизвести проблему**:

Здравствуйте, други!
Не знаю почему никто ещё не задался этим вопросом? Собственно проблема: нужно убрать пустые группы свойств.

Пример:
Берём к примеру тип контента "Объявления" (board) и для него делаем нужные "свойства" (цвет, размер, вес и т.д.), а потом эти свойства для удобства группируем в группу (например, "Характеристики").
Создаём объявление, заполняем все свойства, сохраняем и видим красоту:

> **Характеристики:**
> Цвет: красный
> Размер: 20*30см
> Вес: 1кг

Супер! То что нужно. Кроме "Характеристик" можно наделать кучу групп свойств для удобства отображения.
Но стоит не заполнить ни одного свойства в группе на странице объявления мы видим:

> **Характеристики:**

И собственно всё. Название группы отображается вне зависимости, заполнили вы свойства или нет! Выглядит крайне некрасиво.

Имеется в виду этот код:
`    <?php if ($props && array_filter((array)$props_values)) { ?>
        <?php
            $props_fields = $this->controller->getPropsFields($props);
            $props_fieldsets = cmsForm::mapFieldsToFieldsets($props);
        ?>
		<div class="content_item_props <?php echo $ctype['name']; ?>_item_props">
			<table>
				<tbody>
					<?php foreach($props_fieldsets as $fieldset){ ?>
						<?php if ($fieldset['title']){ ?>
							<tr>
								<td class="heading" colspan="2"><?php html($fieldset['title']); ?></td>
							</tr>
						<?php } ?>
						<?php if ($fieldset['fields']){ ?>
							<?php foreach($fieldset['fields'] as $prop){ ?>
								<?php if (isset($props_values[$prop['id']])) { ?>
								<?php $prop_field = $props_fields[$prop['id']]; ?>
									<tr>
										<td class="title"><div><?php html($prop['title']); ?><div></td>
										<td class="value">
											<?php echo $prop_field->setItem($item)->parse($props_values[$prop['id']]); ?>
										</td>
									</tr>
								<?php } ?>
							<?php } ?>
						<?php } ?>
					<?php } ?>
				</tbody>
			</table>
		</div>
    <?php } ?>`

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

**Comment by iAndroS** [comment]
Вообще, свойства свойственны многие неприятные свойства, прошу прощения за тавтологию ))) Например, если ваша запись числится в нескольких категориях типа контента, то свойства неосновной категории вы даже не сможете заполнить, и это есть большой НЕ ГУД! Правда, Fuze так не считает (((
