### ISSUE TITLE
Поддержка нескольких ячеек в  "Полях"

### ISSUE THREAD

**Issue by maxicms** [instantsoft/icms2#507]
Стоит сделать возможность указания в типах полей составной набор ячеек для записи в БД.

Пример: поле "координаты"

текущая реализация - поле coords с данными в yaml

желаемая реализация - поля cords_lng и coords_lat  с типом полей float

**Comment by fuzegit** [comment]
http://www.instantcms.ru/novosti/release282.html
> Для всех полей доступны для реализации методы hookAfterAdd, hookAfterUpdate и hookAfterRemove, которые вызываются соответственно при создании поля в админке, редактировании и удалении
