### ISSUE TITLE
Установка icms без демо данных

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#510]
При установке движка без демо данных, в профилях пользователя имеются дополнительно созданные поля (пол, возраст, город т тд.) может лучше чтоб если без демо данных то совсем без демо-данных?

После установки движка без демо данных много времени уходит, чтобы все это удалять. Проходить по всем компонентам и отключать неиспользуемый функционал, добавления в друзья, ненужные вкладки в профиле и т.д.

Может если без демо данных то пусть все возможности и настройки будут отключены? Затем по мере необходимости включить что нужно.

**Comment by fuzegit** [comment]
> При установке движка без демо данных, в профилях пользователя имеются дополнительно созданные поля (пол, возраст, город т тд.) может лучше чтоб если без демо данных то совсем без демо-данных?

с этим можно согласиться

> Проходить по всем компонентам и отключать неиспользуемый функционал, добавления в друзья, ненужные вкладки в профиле и т.д.

с этим нельзя согласиться
