### ISSUE TITLE
Добавить общий хук на обработку форм в контенте 

### ISSUE THREAD

**Issue by maxicms** [instantsoft/icms2#511]
Добавить по аналогии с 

list($form, $item) = cmsEventsManager::hook("content_{$ctype['name']}_form", array($form, $item));

общий хук 

list($form, $ctype, $item) = cmsEventsManager::hook("content_add_form", array($form, $ctype, $item));

и 

list($form, $ctype, $item) = cmsEventsManager::hook("content_edit_form", array($form, $ctype, $item));

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/blob/master/system/controllers/content/frontend.php#L851
