### ISSUE TITLE
Добавить в Группы "Поля" и "Вкладки"

### ISSUE THREAD

**Issue by AHTEPO** [instantsoft/icms2#513]
**Используемая версия InstantCMS**: 2.7.2

**Версия PHP**:  7.0
Компонент Группы имеет встроенные 3 Поля - название, описание и аватара. Было бы целесообразно добавить в компонент "Поля групп" и "Вкладки групп" по аналогии с "Поля профилей" и "Вкладки профилей" компонента "Профили пользователей". Это позволит более тонко настраивать Группы.

**Comment by fuzegit** [comment]
поля уже в текущей версии здесь, на гите, добавлены. управление вкладками пока не планируется.
