### ISSUE TITLE
Хук 'comments_list_filter' нельзя ли добавить?

### ISSUE THREAD

**Issue by HiAndy** [instantsoft/icms2#515]
В InstantCMS2 весь контент, активность и комментарии из скрытых групп при листинге или в виджетах просто не показываются никому, даже участникам групп. Везде стоит простой фильтр скрытого контента. 
`$model->filterHiddenParents();`
У меня появилась потребность, чтобы участники групп все таки видели контент, комментарии и активность из скрытых групп.
Если в контенте и активности при помощи хуков 'content_list_filter' и 'activity_list_filter' можно легко добавить в выдачу содержимое скрытых групп, в которых состоит пользователь, то с комментариями полная засада.
Вывод комментариев еще можно дополнить при помощи хука 'comments_datasets', но с виджетом ничего без изменения системного файла \system\controllers\comments\widgets\list\widget.php путного не выходит.
Пробовал использовать хук 'comments_before_list', но это ужас какой-то. Весь компонент комментариев приходится дублировать.

Я, конечно дописал после строчки 
```
if (!cmsUser::isAllowed('comments', 'view_all')) {
 $model->filterEqual('is_private', 0);
 }
```
новый хук
`$model = cmsEventsManager::hook('comments_list_filter', $model);`
Но это же изменение системных файлов.
Нельзя ли в будущих версиях воткнуть в виджет и фронтенд вызов этого хука для облегчения жизни сайтостроителей?

**Comment by my-instantcms** [comment]
+1
Хуки для изменение запросов, очень помогает в доработках
