### ISSUE TITLE
Заголовок Виджета

### ISSUE THREAD

**Issue by ValenokPC** [instantsoft/icms2#517]
**Используемая версия InstantCMS**: 2.7.3
**Версия PHP**:  7.1
**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: НЕТ
**Как воспроизвести проблему**:
При изменении заголовка виджета непосредственно в самом виджете то при включении кеша заголовок пропадает.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/b17643e43dd48826777c13d7c4f84c90a326deed#commitcomment-24624889
