### ISSUE TITLE
Связи - Вкладки без перезагрузки страницы

### ISSUE THREAD

**Issue by Lesnierf** [instantsoft/icms2#519]
Связи порой гораздо удобнее было бы использовать без перезагрузки страницы при переходе по вкладкам. Да и для сео в ряде случаев это плюс. 
Это сильно увеличит нагрузку на бд? 
Или сделать динамическую подгрузку. Пользователи не очень любят ждать.

**Comment by KaRpIkS** [comment]
А кто тебе мешает сделать якс загрузку страницы.?

**Comment by Margauza** [comment]
> А кто тебе мешает сделать

А как вы думаете?

**Comment by KaRpIkS** [comment]
> Ну я даже и не знаю!
