### ISSUE TITLE
Видимость контента, активности и комментариев из закрытых групп для членов групп.

### ISSUE THREAD

**Issue by HiAndy** [instantsoft/icms2#520]
Если уж занялись приватностью контента из закрытых групп, так может сделать доступным для членов закрытых групп просмотр контента и комментариев при просмотре списка контента на всех страницах сайта?

Пока этот вопрос я решаю при помощи трех хуков: content_list_filter.php, activity_list_filter.php и comments_list_filter.php.

К примеру, content_list_filter.php выглядит так:

```
<?php
	class onContentContentListFilter extends cmsAction {
		public function run($data){
			list($ctype, $model) = $data; // Разворачиваем массив входящих данных
			$cname = $ctype['name'];  // Получаем имя типа контента
			If (!strstr($_SERVER['REQUEST_URI'], '/groups')){ /* Чтобы не показывать все посты при просмотре группы*/
	        $user = cmsUser::getInstance();
			$groups = cmsCore::getModel('groups')->getUserMemberships($user->id);
			if ($groups) {foreach ($groups as $value=> $gr){
				$gro[] = $gr['group_id'];	
			}
			$model->filterIn('parent_id', $gro)->filterOr();} /*Добавляем доступный юзеру контент к скрытому*/
			}
			// Отправляем данные обратно в компонент
			return array($ctype, $model);
			}
		}
```
А в файлы шаблона добавил отображение глаза на контенте , чтобы юзер понимал, что он видит этот контент, но это доступно не всем:

```
<?php if ($item['is_private'] || $item['is_parent_hidden'] != NULL ) { ?>
                 <span class="is_private" title="<?php html(LANG_PRIVACY_PRIVATE); ?>"></span>
<?php } ?>
```

**Comment by lakomet** [comment]
> Если уж занялись приватностью контента из закрытых групп
Не закрытых групп, а наоборот, можно в открытой группе, скрыть контент от всех, кроме участников группы. Т.е. если вы участник открытой группы, вы видите весь контент группы везде, а если вы не являетесь участником открытой группы, то видите не весь контент, а только тот, который автор контента, в приватности отметил как "видят все".
