### ISSUE TITLE
Не отключаются уведомления на почту

### ISSUE THREAD

**Issue by HiAndy** [instantsoft/icms2#522]
**Используемая версия InstantCMS**: 2.7.2

**Версия PHP**:  5.3.3

**Как воспроизвести проблему**:

1. Настроить уведомления об ответе на комментарий "Не уведомлять"
2. Добавить ответ на комментарий от другого пользователя.
3. Проверить почту.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: неизвестно.

Все дело в том, что тип уведомления notify_options comment_replay сохраняется в виде comment_replay: , а не comment_replay: none и уведомления на почту продолжают приходить.
Решение проблемы:
В файлах \system\controllers\comments\hooks\user_notify_types.php и \system\controllers\wall\hooks\user_notify_types.php заменить 
```
return array(
            'users_wall_write' => array(
                'title' => LANG_WALL_NOTIFY_NEW,
                'options' => array('', 'email')
            ),
        );
```
на 
```
return array(
            'users_wall_write' => array(
                'title' => LANG_WALL_NOTIFY_NEW,
                'options' => array('none', 'email')
            ),
        );
```

**Comment by fuzegit** [comment]
Проверьте, пожалуйста, на версии с гита, должно работать корректно.
