### ISSUE TITLE
Redactor символы & преобразует в &amp;

### ISSUE THREAD

**Issue by pocus-1** [instantsoft/icms2#524]
**Используемая версия InstantCMS**: 2.7.2

При вставке кода видео, в которым присутствуют спецсимволы "__\&amp;__", типограф портит url вставкой сора в виде "__amp;__". 
Если амперсанты в коде обычные, то все нормально - "__\&__" заменяется на "__\&amp;__"

Исходный код:
```html
<iframe allowfullscreen="" src="//vk.com/video_ext.php?oid=-137751788&amp;id=456239856&amp;hash=33e4787ec00ce522&amp;hd=1"width="620" height="360" frameborder="0"></iframe>
```
А это результат после типографа:
```html
<iframe class="video_frame" src="//vk.com/video_ext.php?oid=-137751788&amp;amp;id=456239856&amp;amp;hash=33e4787ec00ce522&amp;amp;hd=1" allowfullscreen="" frameborder="0"></iframe>
```
Другие спецсимволы пока не проверял.

**Comment by fuzegit** [comment]
вообще это называется  кривой код iframe. Оригинальный код вконтакте с полноценным символом амперсанда. &amp; это и есть символ &
