### ISSUE TITLE
Ошибка типографа + Instant Video

### ISSUE THREAD

**Issue by pocus-1** [instantsoft/icms2#525]
**Используемая версия InstantCMS**: 2.7.2

Если в поле любого контента, которое обрабатывается типографом, встречается фраза вроде 
"__Начало в 14:00__", то время преобразуется в ссылку. Примерно так:
```html
<p>Начало в <a href="#" class="playerseekto" onclick="return (window.iPlayerWrap ? iPlayerWrap.playerSeekToWrap(840) : false);">14:00</a>.</p>
```
Поиском по сайту класса "playerseekto" выяснилось, что он принадлежит компоненту Instant Video и используется во всех установленных плеерах. Сама конструкция обрабатывается функцией:
```javascript
function onclick(event) {
      return (window.iPlayerWrap ? iPlayerWrap.playerSeekToWrap(840) : false);
}
```
Типограф реагирует именно на такое сочетание - две цифры + двоеточие + две цифры. Если двоеточие отделить пробелами, то первый пробел вырезается, но преобразования в ссылку не происходит.

**Comment by fuzegit** [comment]
Проблема InstantVideo https://instantvideo.ru/contacts.html

**Comment by pocus-1** [comment]
Ну, если вы считаете что типограф здесь ни при чем, пусть так и будет.
Просто сообщу другим пользователям обходной манёвр
```html
<p>14:00</p> - Типограф преобразует в ссылку
<p>14&#58;00</p> - Не помогает
<p>14&#x3A;00</p> - Вот оно! Типограф не реагирует
```

**Comment by fuzegit** [comment]
> Ну, если вы считаете что типограф здесь ни при чем, пусть так и будет.

обрабатывает это хук InstantVideo. Отключите для проверки InstantVideo и проблема исчезнет.
