### ISSUE TITLE
Значение по умолчанию в поле "Местоположение"

### ISSUE THREAD

**Issue by maxisoft-git** [instantsoft/icms2#531]
Добавить возможность задавать значение по умолчанию для поля местоположение (гео).

**Comment by fuzegit** [comment]
![Выделение_052](https://user-images.githubusercontent.com/13233234/97117013-2f93d600-1712-11eb-9665-472a34d51a52.jpg)
![Выделение_053](https://user-images.githubusercontent.com/13233234/97117014-302c6c80-1712-11eb-96ee-c1fd57194697.jpg)
