### ISSUE TITLE
Копирование виджетов на странице.

### ISSUE THREAD

**Issue by maxisoft-git** [instantsoft/icms2#534]
Сделать возможным копировать уже добавленные виджеты на станице.

Упрощает задачу когда на странице выводить например 20 виджетов которые отличаются только категории материалов, удобно заполнить один виджет и скопировать его, после чего изменить только категорию.

**Comment by zau4man** [comment]
Или текстовых виджетов, с определенными настройками классов, шаблонами.
Чтобы не настраивать каждый раз многократно. Плюс таким образом можно будет сдублировать виджет на другую страницу, созданную вручную.
