### ISSUE TITLE
Выбор языка сайта в URL сайта.

### ISSUE THREAD

**Issue by maxicms** [instantsoft/icms2#539]
При включенной опции все работает правильно за исключением, варианта когда указываемый язык равен языку по умолчанию. Например язык сайта ru то при вводе site.ru/ru мы получаем 404 ошибку когда логичным действием было бы сделать 301 редирект на страницу без ru в URL 

например /ru/news/article.html = /news/article.html

**Comment by pumpuic** [comment]
Думаю тут нужен все же выбор, т.е. мне например сейчас надо запустить сайт на русском, он будет /ru, чуть позже добавить еще английский, /en, но, кто будет главный я не решил(нестабильный рынок), для меня в идеале было бы чтобы с дефолтного site.com перекидывало пока что на /ru, а если со временем все изменится то меняем настройки и с дефолта перекидывало на /en. 
Ошибка из главпоста действительно присутствует.

**Comment by fuzegit** [comment]
Все работает, как задумано.
https://github.com/instantsoft/icms2/blob/master/system/core/core.php#L71
