### ISSUE TITLE
Скрытие категорий без контента

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#54]
Можно ли добавить в обновление, чтобы категории, в которых нет контента, не выводились в списке категорий? Например, как это сделано на WordPress... Спасибо.

**Comment by my-instantcms** [comment]
Поддерживаю

**Comment by lokanaft** [comment]
Я против

**Comment by asnenne** [comment]
Как вариант, чтобы всем угодить - в настройках типов контента в разделе "Категории" опционально.

**Comment by pin-git** [comment]
Данная реализация вопрос шаблона, если хотите и опций, шаблона default, т.е., как я это понимаю, возникла потребность в __примере__ реализации скрытия категорий контента от оф.разработчика. Или народ, поставив InstantCMS2, сидит на шаблоне из коробки?

p/s: а вообще то я ЗА ;) - опционально. /* ну и проблема - проблема одной строчки */

**Comment by my-instantcms** [comment]
PIN, подскажите пожалуйста, как скрыть пустую категорию в шаблоне? я как то делал, но долго мучился в запросах, а так если бы в шаблон получали информацию о количество записях, то можно было бы поставить условие if($subcats['item_count']){вывод категории}

**Comment by Loadir** [comment]
pin-git мне тоже интересно, как вы подобное http://www.instantcms.ru/forum/thread23115.html#220936 решение в шаблон выносите?

**Comment by pin-git** [comment]
в прошлом году подобное реализовывал, с того времени база эволюционировала - появился **_bind**. Что можно придумать?! А вот как предлагает **my-instantcms** - посчитать. Для этого немного расширим существующий запрос, вот пример запроса на основе статьей:
```mysql
SELECT i.*, (
  SELECT COUNT(*) AS COUNT
  FROM cms_con_articles_cats b
  JOIN cms_con_articles_cats_bind AS u ON u.category_id = b.id
  WHERE b.slug LIKE CONCAT(i.slug,'%'))
  AS items_count
FROM cms_con_articles_cats i
JOIN cms_con_articles_cats_bind AS u ON u.category_id = i.id
WHERE (i.parent_id = '1')
ORDER BY i.ns_left 
```
, и соберём в поле **items_count** общее число записей в папке включая и вложенные. Ну а далее, как говорил выше, работаем с шаблоном.

**Comment by elipss** [comment]
https://instantcms.ru/forum/thread24150-1.html#294124
Нужная функция, так как ,например, после восстановления категорий когда некоторые пока не будут заполняться и потом будут нужны их нужно удалять, а потом как восстановить не через БД ? А можно было бы скрыть.
