### ISSUE TITLE
Не очень удобное редактирование профиля

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#540]
**Используемая версия InstantCMS**: 2.7.2

**Версия PHP**:  5.4.38

Можно ли сделать так, чтобы при редактировании профиля не приходилось каждый раз нажимать на кнопку сохранить переходя по вкладкам.
![06-07-2017 01-56-19](https://user-images.githubusercontent.com/9349934/27888415-8d29395e-61ee-11e7-9c51-54ca8c5b3b7f.jpg)
Поменял в одной вкладке, перешёл на другую поменял там, а потом всё сразу сохранил одним нажатием - СОХРАНИТЬ.
В данный момент, если что-то меняешь в одной вкладке, надо каждый раз сохранять - не очень удобно.

**Comment by nomad48** [comment]
Закрыли? @fuzegit это не ошибка была, а предложение по улучшению функционала.

**Comment by fuzegit** [comment]
Я понял, что улучшение. Именно его и отклонил.

**Comment by nomad48** [comment]
Это невозможно или я не правильно изложил?

**Comment by fuzegit** [comment]
Я вас понял правильно.
