### ISSUE TITLE
Не правильное количество записей в списке

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#541]
Версия 2.7.2.

Тип контента содержит категории:
Родительская
-Дочерняя 1
-Дочерняя 2

Разрешено добавление записей в несколько категорий, разрешен показ записей в родительской категории.

На странице должно показываться 7 записей.

Записи добавлены в обе дочерние категории.

Ошибка заключается в том, что на странице списка выводится только **4 записи**, но в счетчике (там, где постраничная навигация), пишет, что **показано 7 из 12**, хотя всех добавлено **только 6**.

Пробовал то же самое сделать в категориях, родитель которых Корневая - ошибки нет. И в корневой категории в любом случае показывается правильное количество записей.

![1](https://user-images.githubusercontent.com/16401582/27950392-bf2db472-6309-11e7-9808-249dcf108a38.png)

![3](https://user-images.githubusercontent.com/16401582/27950412-d2d07348-6309-11e7-88fc-d7284a4b58dd.png)

![2](https://user-images.githubusercontent.com/16401582/27950419-d6dc255e-6309-11e7-914b-f7ffab3de75a.png)

А вот так выглядит список контента в Родительской категории, когда все 6 записей добавлены в 3 дочерние категории: 
![1](https://user-images.githubusercontent.com/16401582/27950835-6b300f80-630b-11e7-8c5f-1ceb3038a901.png)

Спасибо.

**Comment by fuzegit** [comment]
Раскомментируйте эту строчку 
https://github.com/instantsoft/icms2/blob/master/system/core/model.php#L823
+ изменения от связанного коммита
