### ISSUE TITLE
Сортировка списка связанного контента

### ISSUE THREAD

**Issue by kuzsa** [instantsoft/icms2#543]
**Используемая версия InstantCMS**: УКАЖИТЕ ВЕРСИЮ
v2.7.2 
**Версия PHP**:  УКАЖИТЕ ВЕРСИЮ
5.4
**Как воспроизвести проблему**:
Сортировка прикрепленных элементов к материалу через функцию связи имеет сортировку по дате. Это может быть и задумка такая но хотелось бы либо дублирование сортировки основного списка прикрепляемого типа контента либо индивидуальная настройка

**Comment by fuzegit** [comment]
уже решено в версии здесь
