### ISSUE TITLE
Функционал "Сохранить как новую запись"

### ISSUE THREAD

**Issue by holodoff** [instantsoft/icms2#545]
Я думаю это было бы очень удобно как для интернет магазинов, так и других ресурсов-каталогов. Периодически приходится сталкиваться с необходимость добавления большого количества похожих материалов. Хорошо если бы можно было, например, перейти в редактирование имеющейся записи, поменять в ней что-то и после этого сохранить как новую запись.

**Comment by iAndroS** [comment]
Хах, только что предложил подобное ))) Копировать записи )

**Comment by vlad7090** [comment]
интересно, планируется ли в 2.12.3, очень актуально

**Comment by fuzegit** [comment]
#567
