### ISSUE TITLE
Предложение: редактирование полей записи с фронта

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#547]
Предлагаю реализовать удобную функцию редактирования полей записи с фронта сайта.
У многих есть некоторые типы контента, в которых масса полей для заполнения. А сами записи динамично редактируются/обновляются...
Было бы очень удобно, как это реализовано на современных развивающихся сайтах, сделать редактирование для авторов и редакторов отдельных полей, при наведении на которые отображается иконка редактирования... Вот пример с сайта baza.drom.ru
![screenshot_1](https://user-images.githubusercontent.com/17408903/28125876-7d717a82-675a-11e7-8d04-c1cd59177211.png)
Еще понравилась возможность отдельного вывода незаполненных полей, по щелчку на которых отображается удобная и компактная форма редактирования...
![screenshot_2](https://user-images.githubusercontent.com/17408903/28126085-16cac602-675b-11e7-9564-58697578f210.png)

**Comment by Loadir** [comment]
Насколько я понимаю, речь идёт о добавлении пунктов в поле типа "Список"?. Другие типы полей в этом функционале не нуждаются.

**Comment by iAndroS** [comment]
@Loadir, не обязательно. Речь идет обо всех полях записи. Удобно было бы навести мышку на поле и появляется карандашик, при клике по которому поле становится редактируемым...

**Comment by lakomet** [comment]
> Насколько я понимаю, речь идёт о добавлении пунктов в поле типа "Список"?. Другие типы полей в этом функционале не нуждаются.
Мне кажется @iAndroS говорит о таком карандашике
![2](https://user-images.githubusercontent.com/20047445/28218316-bc29a06a-68ea-11e7-8a25-5a327edea295.png)
нажав на который можем редактировать поле так
![1](https://user-images.githubusercontent.com/20047445/28218394-fd8034d4-68ea-11e7-9909-9630ac0b1b08.png)
Я за.

**Comment by iAndroS** [comment]
@lakomet, да, что-то вроде того

**Comment by fuzegit** [comment]
если честно, я вообще не понял зачем это нужно и кто будет так редактировать.

**Comment by iAndroS** [comment]
@fuzegit, в моем случае это будут админы и модеры. Есть типы контента с огромным количеством полей. Записи в этих типах контента требуют постоянного контроля, так как описания/характеристики в этих записях могут динамично изменяться. Допустим, это описания программ. Внедрили в программе новую функцию, соответственно, в поле, описывающем эту функцию, необходимо внести изменения.
Предложение вдогонку - для админов и модеров показывать под записью незаполненные поля. На том же baza.drom.ru это реализовано, что очень удобно и наглядно!
![screenshot_3](https://user-images.githubusercontent.com/17408903/28220803-78317b40-68f3-11e7-8f8c-a3baf9e5dd3a.png)
