### ISSUE TITLE
Фильтр флагов в одну строку

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#550]
Настроил в типе контента несколько полей "Флаг" с их отображением в фильтре. Выглядит не очень, когда название поля сверху, а чекбокс ниже названия. Нужно сделать в одну строку. С CSS не разобрался (((
Поможет ли редактирование .ft_checkbox div.value или .ft_checkbox div? Если да, то что нужно выбрать в инстайлере, чтоб отредактировать правильно?

**Comment by fuzegit** [comment]
Для вопросов есть форум.
