### ISSUE TITLE
Некорректная работа URL-маски

### ISSUE THREAD

**Issue by mafru** [instantsoft/icms2#552]
**Используемая версия InstantCMS**: 2.7.2

**Версия PHP**:  5.6.29-0+deb8u1

**Как воспроизвести проблему**:

1) Выбрать в админке тип контента по-умолчанию (например страницы).
2) Устанавливаем любой виджет, на странице просмотра записи, для выбранного по умолчанию типа контента (Страницы: Просмотр записи)
3) Указанный виджет будет выводиться не только на странице просмотра записей типа контента по-умолчанию, но и на всех страницах записей всех типов контента.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: НЕТ (нет возможности настроить тип контента по-умолчанию, но думаю должна воспроизвестись, т.к. воспроизводится на текущей сборке с гита).

**Comment by iAndroS** [comment]
Добавлю по теме: Компонент по умолчанию также "Страницы". Создаю пользовательскую страницу для виджетов вида stranica.html
добавляю виджеты для это страницы, а они не отображаются на фронте сайта!

**Comment by fuzegit** [comment]
@iAndroS , я ничего не понял.

**Comment by iAndroS** [comment]
@fuzegit 
1. Админка - Настройки - Тип контента по умолчанию - Страницы - Сохраняем
2. Админка - Виджеты и страницы - Пользовательские - Создать страницу - Заголовок: Страница -
 Фильтрация URL - Положительные маски - Указываем: stranica.html (предварительно создана!) - Сохраняем
3. Добавляем любойвиджет в любую позицию - Сохраняем
4. На фронте этого и кучи других виджетов не отображаются!

**Comment by fuzegit** [comment]
@iAndroS на версии с гита всё работает как нужно.
![07-14- _001](https://user-images.githubusercontent.com/13233234/28226672-aca4ef56-68df-11e7-8116-a51bdffc30f4.png)
![07-14- _002](https://user-images.githubusercontent.com/13233234/28226673-aca6a5c6-68df-11e7-84a2-baad9f8c67f5.png)
![07-14- _003](https://user-images.githubusercontent.com/13233234/28226674-aca896d8-68df-11e7-8716-1121dee058b8.png)

**Comment by iAndroS** [comment]
@fuzegit повторюсь, что у меня изначально тоже все оторажалось, но потом почему-то перестало. Закономерности не выявил, ничего нового не устанавливал на сайт. Сразу после установки виджетов работало, через пару часов уже нет.

**Comment by mafru** [comment]
Указанный недостаток с масками все еще наблюдается на страницах просмотра записи в тех типах контента к которым привязаны компоненты (places, video и т.д.), т.е. метод компонента
```
public function routeAction($action_name) {
 
		$core = cmsCore::getInstance();
 
		if (!$this->isActionExists($action_name)){					
			$core->uri_controller = 'content';		
			$core->runController();			
			$this->current_params = array();
			return 'exit';
		}
 
		return $action_name;
 
	}
 
	public function actionExit(){ return; } 
```
