### ISSUE TITLE
Активные кнопки у заблокированных юзеров

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#557]
**Используемая версия InstantCMS**: 2.7.2

**Версия PHP**:  5.4.38

**Как воспроизвести проблему**: заблокировать юзера и проверить его профиль, у заблокированного пользователя остаются рабочими кнопки писать на стене и рабочее меню действий.
![15-07-2017 19-04-47](https://user-images.githubusercontent.com/9349934/28240813-d2e9682a-6990-11e7-8524-5a929de74c5f.jpg)
По идее у заблокированного пользователя их надо скрыть, потому что заблокированный юзер виден, в отличии от тех кто свой профиль удалил.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
Что смущает? Пользователь не удалён, с чего запрещать всё это?

**Comment by nomad48** [comment]
Бывает что блокируются юзеры не только по личной просьбе. Бывает за СПАМ или за какие-то нарушения, Ну допустим чтобы исключить не понятные вопросы в случае чего. Жалобы различные со стороны заблокированного. Там же кнопка биллинга активна тоже.
