### ISSUE TITLE
Количество материалов в списках

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#56]
По-умолчанию в списках выводится 15 записей (новостей, объявлений, объектов на карте и т.д.). Однако, если материал опубликован в двух категориях, то он в списке выводится один за два! Т.е., если в списке должно быть 15 материалов, а последние 3 добавлены в 5 категорий каждый, то на странице всего 3 и будет выведено. Еще по этому же поводу - объекты на карте iMaps - если у объекта есть, например, 5 точек, то на странице выводится один объект за пять! А если он еще и в 5 рубриках, то выводится вообще один, и плюс еще на второй странице один за десять! Исходя из этого предлагаю изменить алгоритм вывода записей в списках таким образом, чтобы не учитывалось ничего, кроме самого объекта как такового. Например, можно было бы сделать вывод в списке только по ID, ведь один материал в типе контента может иметь кучу категорий, но ID будет один единственный!

Спасибо.

**Comment by fuzegit** [comment]
Напишите подробнее как повторить. На версии из гита воспроизвести не могу.

**Comment by asnenne** [comment]
Установил для теста движок из гита. Да, действительно в списке теперь выводится правильно. Но в виджетах все равно так, как я описал выше. http://mozyr.j8.by/ - в сайдбаре виджет "Список контента" - в настройках поставил выводить 10 объектов на карте. Так как некоторые объекты находятся в нескольких категориях, в виджете выводятся только 4 объекта, вместо 10. С несколькими адресами проблему больше не наблюдаю.

Спасибо.
