### ISSUE TITLE
2.7.2 - контент в ленте отображается для тех, кому не должен отображаться

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#564]
Есть тип контента для админов. Скрыт доступ гостям и обычным пользователям через страницы и виджеты, а также на создание и редактирование в настройках типа контента. Тем не менее в ленте активности добавляемые записи отображаются!

**Comment by fuzegit** [comment]
![07-19- _001](https://user-images.githubusercontent.com/13233234/28384571-df5f139e-6ccd-11e7-8150-a9dc94329076.png)

**Comment by iAndroS** [comment]
@fuzegit а вот тут самое интересное (хорошо, что вы внимание обратили) - в настройках ленты активности данный компонент вообще не выделен! Получается, двойная ошибка!

**Comment by fuzegit** [comment]
В том, что от скрытых таким образом записей видны события в ленте ошибки нет.
> в настройках ленты активности данный компонент вообще не выделен

проверю конечно, но не уверен, что так и есть.

**Comment by fuzegit** [comment]
Всё работает корректно.

![07-19- _002](https://user-images.githubusercontent.com/13233234/28385054-629c1b0c-6ccf-11e7-98a2-40063deb7ba4.png)
![07-19- _003](https://user-images.githubusercontent.com/13233234/28385053-6298e374-6ccf-11e7-9994-0ccb91686098.png)
![07-19- _004](https://user-images.githubusercontent.com/13233234/28385055-629f18a2-6ccf-11e7-9a33-bf019635404f.png)

**Comment by iAndroS** [comment]
@fuzegit 
1. Я создал новый тип контента для админов для админов и модеров сайта, чтобы обсуджать рабочие моменты по доработкам и планам.
2. Закрыл доступ на создание и редактирования во вкладке ДОСТУП этого типа контента
3. Закрыл доступ в виджетах и страница, оставив только модерам и админам.
![screenshot_2](https://user-images.githubusercontent.com/17408903/28385102-734a2280-6cf9-11e7-8ee7-21c7b839c59f.png)
4. В настройказ компонента Лента активности этот тип контента оказывается нужно было отметить, но я этого не сделал, соответственно, он в принципе не должен отображаться
![screenshot_1](https://user-images.githubusercontent.com/17408903/28385178-b7f7d350-6cf9-11e7-9be3-5cb50f69c11e.png)
5. В итоге и по ссылке /activity контент виден из-под обычного юзера, и в виджете ленты активности тоже!

**Comment by fuzegit** [comment]
То, что в ленте видны, я уже ответил, что это не баг.
С отсутствием галочки и при этом фиксации события проблему понял, исправлю. При создании типа контента по умолчанию фиксация событий включена, но галочка не стоит. Если вы пересохраните настройки ленты, то всё исправится.

**Comment by iAndroS** [comment]
То, что в ленте видны, я уже ответил, что это не баг.
Ок. Как убрать эти события из ленты обычных юзеров?

**Comment by fuzegit** [comment]
Текущие удалить. Чтобы новые не добавлялись пересохранить настройки ленты активности.

**Comment by iAndroS** [comment]
Хорошо. То есть, выдать все же ленту модерам и админам не удастся? Потому как им эта инфа нужна... Если только в виджете выводить...
