### ISSUE TITLE
Категории в списке связанных записей

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#565]
Предлагаю в списке связанных записей выводить категории, в которые добавлены эти записи в дочернем типе контента, с целью упорядочить эти записи. 

Пример: Есть родители - компании. И есть дочки - каталог товаров. Товары все разделены на сотни категорий. К одной компании могут быть привязаны тысячи товаров из разных категорий. И все они выводятся одним не упорядоченным списком.

Сейчас, если вывести связанный контент во вкладке, то url имеет вид родитель/view-типконтента. Предлагаю категории выводить по такому же принципу -> родитель/view-типконтента/категория.

Также, так как это не основной список типа контента, а список привязанных к определенному родителю записей, выводить только те категории, в которых есть связанные записи данного родителя.

Спасибо.

**Comment by fuzegit** [comment]
> Предлагаю категории выводить по такому же принципу -> родитель/view-типконтента/категория

по такому принципу, в текущей версии на гите, подключены наборы. поэтому категории в списке связанных записей будут и лишними и не получатся по указанному принципу.
