### ISSUE TITLE
Связи. Вывод на странице дочернего типа контента дополнительных полей родителя

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#566]
Предлагаю добавить возможность на странице дочернего типа контента кроме названия родителя выводить также дополнительные его поля. Как это сделать напильником я нашел в одном из системных файлов. Но минус этого способа в том, что, во-первых, все эти настройки слетят при ближайшем обновлении, а во-вторых, если сделать правки в файле, то теряется гибкость, так как эти настройки будут применимы ко всем связям всех типов контента.

Пример. Есть родительский тип контента Компании, и есть дочерний тип контента Товары. Родители в связанных дочках выводятся полем с заголовком "Где купить" - список ссылок на страницы родителей. Было бы лучше, если бы выводился не просто список, а полноценный блок родителя - картинка, заголовок, адрес и телефон, время работы и т.д. 

Предлагаю включать/отключать вывод дополнительных полей при создании (или редактировании) связи. Например, в Компаниях создаем связь с Товарами, кроме всех настроек, которые есть сейчас, отмечаем чекбоксы тех полей, которые также нужно выводить.

Спасибо.

**Comment by iAndroS** [comment]
Если я правильно понял вашу мысль, вам просто связь нужно не вкладкой, а списком сделать, тогда контент дочерней связи будет выводиться под родителем

**Comment by asnenne** [comment]
> Если я правильно понял вашу мысль

Не правильно поняли.

**Comment by fuzegit** [comment]
Как то так.

![Выделение_010](https://user-images.githubusercontent.com/13233234/100376822-3a979a00-3021-11eb-9f56-8aaac3392e7a.jpg)

![Выделение_011](https://user-images.githubusercontent.com/13233234/100376825-3bc8c700-3021-11eb-86dd-23cd494e0ad7.jpg)
