### ISSUE TITLE
Поле родительской связи в фильтре

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#569]
2.7.2
Если в настройках родительского поля дочернего контента разрешить фильтр для показа всем, то он показывается только админам (требует проверки), в моем случае пробовал дважды на разных типах контента.
Также смущают неработающие фильтры по полям родительской записи в нем. Ищут только по полю название, остальные же не работают. 
Нужно либо убрать их вовсе, либо сделать тогда уж автокомплит-поля поиска. Также предлагаю опционально выбирать в настройках поля для фильтрации по родительским записям.

**Comment by fuzegit** [comment]
Это актуально еще?
Если да, то перефразируйте, я ничего не понял. Фильтр весь рабочий.

**Comment by fuzegit** [comment]
> Если в настройках родительского поля дочернего контента разрешить фильтр для показа всем, то он показывается только админам

Решено
