### ISSUE TITLE
Автосохранение материала при его написании в типе контента

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#57]
Очень не хватает данной опции, т.к бывают и обрывы интернета и порой проблемы с электроэнергией, когда отключают свет. Также наверняка у людей бывают свои ПО, что приводит к завершению работы браузера, что в свою очередь приводит к потере напечатанного материала.
Пожалуй лучшее решение если раз минуту или в две минуты будет происходить автосохранение и в случае обрыва соединения можно просто зайти в свой профиль , выбрать материал и продолжить его редактировать.

**Comment by klubnik** [comment]
Опция хорошая, но не будет ли она нагружать сервер?
Если будут делать, лучше бы иметь возможность в случае нагрузки отключать.

**Comment by vlad7090** [comment]
у вас так часто люди создают новые материалы?)

**Comment by fuzegit** [comment]
Объединено с https://github.com/instantsoft/icms2/issues/710
