### ISSUE TITLE
Группировка фильтров как в типах контента

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#575]
Предлагаю реализовать опциональную (с возможностью включения/отключения) группировку полей фильтров как в типах контента. 
В некоторых случаях могут быть аналогичные поля в группировках, а в фильтре непонятно, о чем идет речь, либо придется делать слишком длинные заголовки к полям, что выглядит не очень эстетично.

**Comment by fuzegit** [comment]
#661
