### ISSUE TITLE
Возможность смены автора записи

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#576]
Предлагаю реализовать возможность смены авторов записей из админки или при редактировании записи админом/модером (без лазанья в бд) по аналогии с тем, как это сделано в мапсе.
Это может быть удобно для предоставления возможности редактировать определенные записи определенным людям, чтоб не давать доступа к другим разделам/функциям сайта.

**Comment by iAndroS** [comment]
@fuzegit, складывается ощущение предвзятости ко моей персоне, либо я вам просто надоел со своими бесконечными предложениями и хотелками )))
Вы бы хоть обсуждали предложение, чтоли...
В мапсе эту функцию R2 сделал - красота и удобство на лицо!
Допустим, у меня тип контента каталог чего-либо. У этого типа контента куча дочерних типов контента (сейчас если не статейник, то именно сайты-справочники рулят). Данные динамично обновляются администрацией сайта. Как правило первичное наполнение делается либо парсером, либо же админом ручками, по мере наращивания сайтом трафа или каких-то других показателей, подтягиваются заинтересованные люди в наполнении контента в данном справочнике, либо замотивированные чем-то другим люди. Например, фанаты, модераторы или владельцы бизнесов. Соответственно, реализованное мною предложение позволило бы решать такой вопрос одним кликом модератора о смене владельца/автора записи, а не ковырянием вручную админу сайта. Предоставлять доступ ко всему типу контента человеку, которому нужна только правка его компании, глупо и небезопасно, а создавать для него отдельную группу пользователей тоже не совсем рационально!

**Comment by fuzegit** [comment]
Я же пометил, что данное предложение "дубликат", что означает, что здесь есть такая же открытая задача.

> складывается ощущение предвзятости ко моей персоне

скорее второе. При этом большую часть "предложений" я оставляю, некоторые даже решаются. Но кто будет делать ваши предложения и когда, мне неведомо.

**Comment by iAndroS** [comment]
> скорее второе.

Прошу прощения, но все же я продолжу свою писанину по мере возникновения таковой необходимости )))
Понимаю, что у вас завал и по мере решения своих финансовых трудностей готов профинансировать большую часть своих предложений. То, что здесь я публикую - далеко не все мои пожелания и хотелки, просто в неопубликованных как раз скрывается именно то, что нужно конкретно мне и врядли пригодится в массовом пользовании iCMS (это я к претензиям в мой адрес, что тяну одеяло на себя) )))
Когда-то и по связям так говорили, что тяну одеяло на себя, зато сейчас все радуются данному функционалу и гибкости движка!
