### ISSUE TITLE
Ручная правка SEO при включенной автогенеренке

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#578]
Обнаружил такую необходимость в редактировании некоторых автоматически генеренных мета-тегов - это довольно частая ситуация. Иногда запрограммированный нами шаблон не очень удачно вписывается в некоторых записях, а иногда просто нужно расширить описания для поисковых сниппетов.
Предлагаю реализовать данную возможность для админов и модераторов, а также владельцам записи, в случае наличия такового доступа у них.

**Comment by sipaj** [comment]
Кстати, да. Тоже столкнулся с такой необходимостью. Может добавить флажок: "Создать seo данные автоматически, если поле не заполнено".
И в случае, если при сохранении записи поля seo пустые, делается автоматическая генерация.
