### ISSUE TITLE
Виджет "Фильтр контента" - ошибка

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#579]
**Используемая версия InstantCMS**: 2.8

**Версия PHP**:  5.6.29-0+deb8u1

**Как воспроизвести проблему**:

* Настраиваем любой тип контента
* Идем в виджеты - главная страница сайта
* Устанавливаем виджет "Фильтр контента" для нашего типа контента
* Ничего не видим - виджет не определяет url типа контента и ставит параметры фильтрации сразу после ТЕКУЩЕЙ страницы, но не url выбранного нами типа контента!

То есть, если виджет стоит не в типе контента, по которому должна фильтрация происходить, то он просто добавляет конструкцию вида "?page=1&title=&goal_task%5B%5D=4&submit=Фильтровать" к текущему url

**Comment by iAndroS** [comment]
Проблема до сих пор актуальна

**Comment by fuzegit** [comment]
> Проблема до сих пор актуальна - ничего не изменилось

Проблема решена. Почему у вас не так, я не могу знать.

**Comment by iAndroS** [comment]
Да, действительно. Проверил на демо-сайте и на другом сайте на 2.10.
Не подскажите, как продиагностировать проблему? Обновлялся по инструкциям, только что заменил файлы из гита из папки system/controllers/content/widgets/filter/ - не помогло.
В исходном коде в инспекторе кода просматривается <form action="/tip_kontenta/adres-stranicy.html" method="get">
В каком файле искать ошибку?
