### ISSUE TITLE
Опции по работе с аватарками

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#58]
Очень не хватает настроек для работы с аватарками, чтобы можно было задать размер для маленькой и большой аватарки. Маленькая отображается везде на сайте кроме профиля, а большая - в профиле. При этом было бы полезно для унификации добавить возможность обрезки аватарки, для маленькой например квадрат, для большой прямоугольник, ну или как будет задано в админке.

**Comment by vlad7090** [comment]
было бы отлично, если в компоненте изображений появилась настройка пресетов для аватарки - какую выводить в комментариях, какую выводить у автора в записи, какую в профиле пользователя и сохранять ли оригинал. Если оригинал сохраняется, то при клике в кабинете по аватарке выводить в лайтбоксе полную версию.

**Comment by EnotAlex** [comment]
Пользователи моего ресурса часто делают мне замечания по поводу отсутствия редактора аватар,  с помощью которого можно было бы выделять нужную область аватара и сохранять его для  миниаватара или главного аватара. 
К примеру размеры миниаватара на сайте квадратные, и естественно все горизонтальные или вертикальные фото будут сплющены в той или иной плоскости, что очень некрасиво смотрится и в целом сайту плюса не даёт. А с редактором, мы быстро выделяем нужную квадратную область на фото оригинала и сохраняем. 
Предлагаю добавить такую примочку на подобии этой
http://ruseller.com/lessons.php?rub_id=32&id=315
