### ISSUE TITLE
Ошибка в привязке профилей пользователей к типу контента

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#581]
**Используемая версия InstantCMS**: 2.8

**Версия PHP**:  5.6.29-0+deb8u1

**Как воспроизвести проблему**:

* Есть тип контента Компании
* Добавляем в этом типе контента связь с профилями пользователя "Сотрудники"
* 1 ошибка: На странице компании нет возможности добавить сотрудника (предлагаю реализовать ее с подтверждением указанного пользователя о его принадлежности к компании)
* 2 ошибка: Пользователь при редактировании своего профиля не может указать компанию, при нажатии на кнопку Добавить место работы выскакивает ошибка "An error occured"

![screenshot_1](https://user-images.githubusercontent.com/17408903/28759179-847033a2-75cc-11e7-93a7-5a8e039ab9c6.png)

Механизм привязки связей с пользователями нужен более гибкий - как с возможностью полного запрета пользователям привязываться к записям типов контента, так и с возможностью подтверждения в случае отметки кем-либо этого пользователя в какой-либо записи.

**Comment by fuzegit** [comment]
1. Вы постоянно путаете реальную ошибку с отсутствием функционала.
2. У меня нет такой проблемы. Нужно как-то развернуто описать.

Права для привязки регулируются соответствующим правилом доступа в списке правил компонента профили пользователей.

**Comment by iAndroS** [comment]
> Вы постоянно путаете реальную ошибку с отсутствием функционала.

В данном случае, я так понимаю, это отсутствие функционала, не ошибка? Зачем тогда такая возможность анонсирована, если она не функционирует? Или это у меня у одного так не функционирует, что невозможно привязаться пользователя к записи?

> У меня нет такой проблемы. Нужно как-то развернуто описать.

Да куда уж более развернуто? Пробую еще раз... Создал тип контента "Компании", в нем добавил связь с пользователями "Сотрудники". Идея такая, что "Сотрудники" могут выступать на сайте в роли консультантов и поддержки.
Упираюсь в следующее - нет возможности привязать со страницы сотрудников пользователя. Ок, будем считать это так задумано. Иду в профиль, свой админский. Пытаюсь "устроиться на работу" к вышеобозначенному типу контента и вижу указанную выше ошибку "An error occured".

В то же время, упираясь в вышеобозначенную логику, не могу найти ей практического применения без доработок. В любом случае, связь контента с пользователями должна быть подтверждена обоюдно (то есть, если привязываем юзера со страницы записи, то юзер подтверждает свое согласие, и обратно - если юзер решил привязаться к чьему-то контенту, то автор должен подтвердить это во избежание злоупотреблений).

**Comment by fuzegit** [comment]
> Иду в профиль, свой админский. Пытаюсь "устроиться на работу" к вышеобозначенному типу контента и вижу указанную выше ошибку "An error occured".

Я когда спросил, как повторить, очевидно имел в виду, что я попробовал и у меня на чистой установке всё работает как положено.

> Upd: удалил связь с пользователями в типе контента, но поле привязки в профилях пользователей осталось без возможности удаления из админки.

При удалении связи поле удаляется автоматически. Почему у вас не так, я не могу знать.

> Зачем тогда такая возможность анонсирована, если она не функционирует

Всё, что описано в новости о релизе InstantCMS 2.8.0 - всё функционирует так, как описано.
