### ISSUE TITLE
Дефолтный аватар со своим пресетом

### ISSUE THREAD

**Issue by mk198** [instantsoft/icms2#582]
**Используемая версия InstantCMS**: 2.8.0

**Версия PHP**:  5.4

**Как воспроизвести проблему**:

Заходим в компоненты -> Профили пользователей
Для поля аватар выбираем свой созданный пресет.
На выходе имеем либо пусто, либо предупреждение формата: Notice: Undefined index: <системное_имя_пресета> in /var/www/.../svadebnyivals.ru/system/libs/html.helper.php on line 202

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

Проблема в том, что в файле /system/libs/html.helper.php руками прописаны пути к дефолтным аватарам:
`if (empty($avatars)){
		$avatars = array(
            'normal' => 'default/avatar.jpg',
            'small' => 'default/avatar_small.jpg',
            'micro' => 'default/avatar_micro.png'
        );
    }`
И, если использовать, функцию html_avatar_image() с указанием своего пресета, то получаем такаю небольшую неприятность.
Для своего проекта без проблем исправить это прямо в функции, но для коробки предложил бы как-нибудь на лету генерировать дефолное изображение аватара, или для компонента "Загрузка изображений" сделать, чтобы при создании пресета создавались заглушки указанного размера.

**Comment by fuzegit** [comment]
Решено в шаблоне modern. Дефолтные аватары буквенные.
