### ISSUE TITLE
Вывести плагинацию в отдельный файл шаблона

### ISSUE THREAD

**Issue by pumpuic** [instantsoft/icms2#588]
Всем привет.
Хотелось бы иметь отдельный шаблон для плагинации, сейчас она формируется в /system/libs/template.helper.php и после обновления системы есть шанс потерять свою вёрстку.

**Comment by my-instantcms** [comment]
Есть файл (клон template.helper.php) \templates\compact\assets\helper.php
Если такой файл существует, система подключает helper.php а не template.helper.php
