### ISSUE TITLE
Настройки почты - smtp ложит сайт

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#592]
**Используемая версия InstantCMS**: 2.8
**Версия php**: 5.6.29-0+deb8u1

На странице настроек сайта, в разделе почта, вводим настройки smtp-отправки почты, smtp-авторизация, порт 465, шифрование TLS, сохраняем. Пытаемся отправить тестовое письмо с админки - ничего не происходит. Все другие страницы сайта минут на 5 уходят в даун и выдают 504 ошибку.

PS: проверял на нескольких сайтах на iCMS 2.8.0

**Comment by fuzegit** [comment]
Настраивайте правильно почту/сервер. В движке нет проблем.
