### ISSUE TITLE
Предложения для табличного шаблона вывода контента

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#593]
Предлагаю реализовать возможность вывода таблиц контента с возможностью сортировки по заголовкам и возможность выбора отображаемых полей (столбцов) пользователями. 
Если не совсем понятно предложение, могу более подробно описать в картинках, поискать примеры.

**Comment by pocus-1** [comment]
Предложение понятно и, в некоторых случаях может быть полезно.
Но сортируемые таблицы, это скорее для специфичных шаблонов или компонентов.
Сомнительно, что такое нужно в движок.

**Comment by iAndroS** [comment]
@pocus-1 ну опционально очень даже бы пригодился такой шаблон
