### ISSUE TITLE
Ошибка вывода поля родительского контента в виджете

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#597]
**Используемая версия InstantCMS**: 2.8.0

Виджет список контента при попытке вывести поле родительского контента в поле краткого описания выдает id родителя, а не его заголовок.

**Comment by fuzegit** [comment]
Это не ошибка. В виджете в поле описание ожидается, что будет выбрано... поле, содержащее описание. Как только будет возможность выводить в виджете списка любые поля, вы сможете сделать то, что вы хотите.

**Comment by Loadir** [comment]
Если срочно надо, [тут](https://github.com/instantsoft/icms2/pull/594) есть все нужные правки.

**Comment by iAndroS** [comment]
@Loadir спасибо вам, добрый человек!
