### ISSUE TITLE
Не правильно работает пагинация в группах

### ISSUE THREAD

**Issue by lakomet** [instantsoft/icms2#604]
**Используемая версия InstantCMS**: 2.8.0

**Версия PHP**: 5.6

**Как воспроизвести проблему**:

* первый шаг В настройках компонента "Группы", создаём и заполняем поле типа список
* второй шаг Отмечаем checkbox - "Показывать в фильтре"
* третий шаг Отмечаем checkbox - "Автоссылка"
* четвёртый шаг Создаём несколько групп, для появления пагинации
* пятый шаг Нажимаем на созданное поле-ссылку, попадаем на страницу сайт.ру/groups?системное_имя_поля=5 , т.е. получаем отфильтрованный по этому полю, список групп. Если перейти на любую страницу по пагинации, то попадаем на страницу сайт.ру/groups?page=2, т.е. на страницу без фильтра.

**Comment by mafru** [comment]
Случаем данной правкой ваша проблема не решается?
https://github.com/instantsoft/icms2/commit/24ea3abc4cb0ec65027f92082a8f6d777e3c78d4

**Comment by lakomet** [comment]
> Случаем данной правкой ваша проблема не решается?
Спасибо, помогло.
