### ISSUE TITLE
Недочёт при удалении профиля пользователями

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#606]
**Используемая версия InstantCMS**: 2.8.0

**Версия PHP**: 5.4.38

**Как воспроизвести проблему**:

* Регистрируешься на сайте
* Выполняешь какие либо действия ( добавляешь аватар и т.п.) которое отображается в ленте активности.
* С помощь кнопки **удалить профиль** - удаляешь профиль. Профиль пользователя скрывается в списке пользователей, но остаются видны все действия в ленте активности, как в виджете, так и на странице https://lovelovely.ru/activity. При нажатии на любую оставшуюся активность пользователя, любой пользователь попадает в удалённый профиль. И может в профиле сделать все доступные ему действия. Просто юзер задал вопрос, я удалил профиль почему меня видно в других местах?
Скриншоты проблемы:
![31-08-2017 10-06-34](https://user-images.githubusercontent.com/9349934/29913035-7bb89d02-8e3c-11e7-8475-dca9e74464e2.jpg)
![31-08-2017 09-58-28](https://user-images.githubusercontent.com/9349934/29912990-544748ae-8e3c-11e7-90b2-c65152293392.jpg)
![31-08-2017 09-59-28](https://user-images.githubusercontent.com/9349934/29912988-54438a70-8e3c-11e7-818e-a69793ea05ef.jpg)
![31-08-2017 10-02-13](https://user-images.githubusercontent.com/9349934/29912987-54434a42-8e3c-11e7-94a1-a9c58a24b092.jpg)
![31-08-2017 10-02-55](https://user-images.githubusercontent.com/9349934/29912989-54443fec-8e3c-11e7-915e-39a392167821.jpg)

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: не могу проверить

**Comment by fuzegit** [comment]
У меня дежавю. Вы же уже создавали подобный тикет и я на него отвечал.

**Comment by nomad48** [comment]
Я создал два тикета один за другим и один из них, Вы сразу закрыли. Но он по модальному окну. Раньше не создавал, так как не было функции удаления профилей юзеров.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/4cfb2ee5ad1ab91ed2b1075d2f8d30287e6f42dd
