### ISSUE TITLE
При формировании тайтла, если поле автоссылка заголовок формируется с кодом

### ISSUE THREAD

**Issue by ermakover** [instantsoft/icms2#608]
**Используемая версия InstantCMS: 2 

**Версия PHP**:  5.6

**Как воспроизвести проблему**:
Создать в любом типе контента поле "Список". 
Поставить чекбокс "Автоссылка". 
Затем внести созданное поле в настройках контента в "Шаблон генерации тайтлов страниц".
Посмотреть, что значение данного поля формируется и выводится вместе с кодом.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: На демо сайте мне не удалось даже добиться того, чтобы тайтл формировался заданными ключами {test} {category}
Пробовал в статьях и блогах.
![12a2e2113cc7b23f1373bd9f36026c03 jpg](https://user-images.githubusercontent.com/25240757/30128388-2d7b8320-934b-11e7-971e-02604f0926cd.jpg)

**Comment by fuzegit** [comment]
уже решено

**Comment by ermakover** [comment]
Как мне поправить?

**Comment by fuzegit** [comment]
дождаться обновления или полистать список коммитов, где в описании данная правка указана.
