### ISSUE TITLE
Тип поля "Город"

### ISSUE THREAD

**Issue by Alex-HAV** [instantsoft/icms2#61]
Тип поля город, как в профилях пользователей при добавлении контента а также для последующей сортировки. Хотелось бы что бы можно было просто выбрать страну или область без обязательного указания точного города

**Comment by strannic42** [comment]
С базой городов нужно очень серьёзно поработать, т.к. помимо фактических ошибок (к примеру, Крым со всеми городами и посёлками, и Севастополь до сих пор в базе почему-то украинские), есть ещё и пересортицы, и дубли. 
Не знаю, почему разработчики не воспользовались высланной имм частично исправленной базой.

**Comment by mafru** [comment]
А, где можно посмотреть исправленную базу?
Она для двух языков?

**Comment by softsolution** [comment]
Если кому нужно вот вносил правки в базу городов инстанта - правда это для старой ветки, но думаю в новой ветке структура похожая
https://gist.github.com/softsolution/0fe8bf099ebc1d38c36a
В базе городов инстанта есть Чечено-Ингушения - но сейчас это две республики - это тоже нужно поправить

**Comment by strannic42** [comment]
_mafru_, правки уважаемого _softsolution_ полнее моих. Я, на момент написания поста, видел InstantCMS около 20ти минут ))

**Comment by Maratakziaplus** [comment]
Функции редактирования и сортировки действительно не хватает. Хотелось бы иметь возможность подстраивать под себя. Кому то нужна только одна конкретная республика с ее городами, поэтому функция отключения неиспользуемых республик и городов тоже необходима.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/160d467ef2ceafbf0a3d0e38b5d58ba06c82c213
