### ISSUE TITLE
Пожелание - добавить возможность подключения скриптов в конец страницы

### ISSUE THREAD

**Issue by smartcontroltoday** [instantsoft/icms2#610]
Предлагаю добавить возможность подключения скриптов в конец страницы для ускорения загрузки. Некоторые тяжелые javascript файлы можно грузить перед `</body>`. 

Для этого нужно 
1. Добавить в cmsTemplate методы типа addFoot(..), foot(..)... (по аналогии с addHead, head...)
2. Добавить соответствующие свойства по аналогии с
```
    protected $head = array();
    	protected $head_main_css = array();
    	protected $head_css = array();
    	protected $head_main_js = array();
    	protected $head_js = array();
    	protected $head_js_no_merge = array();
    	protected $head_css_no_merge = array();

```     

Добавить в шаблоне перед </body> вызов метода
`    <?php $this->foot(); ?>`

Все системные скрипты можно так и грузить в блоке **head**, а сторонним компонентам дать возможность выносить скрипты в конец.

**Comment by maxicms** [comment]
Уже все давно реализовано. смотрите код.

**Comment by smartcontroltoday** [comment]
> Уже все давно реализовано. смотрите код.
Смотрю код - не вижу, чтобы было реализовано.

Смотрю:
1. Дефолтный шаблон - нет вывода скриптов перед `</body>` 
2. Файл template.php - последние правки два месяца назад и нет даже намека на скрипты в футере.

Если действительно есть - ткните, пожалуйста, пальцем.

**Comment by fuzegit** [comment]
/system/core/template.php
методы:
head
printCssTags
printJavascriptTags

разделять как то отдельно верх и низ не имеет никакого смыла. либо только верх, либо только низ. в своем шаблоне вы можете прекрасно это сделать. никакого отдельного разделения не будет.
