### ISSUE TITLE
При установке компонента с большим количеством папок выскакивает ошибка запроса

### ISSUE THREAD

**Issue by smartcontroltoday** [instantsoft/icms2#612]
Версия InstantCMS 2.8.1

При установке компонента с большим деревом папок выскакивает ошибка
` Data too long for column 'files' at row 1`

Запрос слишком длинный. 

-------

Добавлю сюда же, потому что тоже относится к полю files из таблицы cms_controllers.

При обновлении компонента поле не обновляется (как и addon_id, что не дает привязать старые компоненты к каталогу приложений). Я понимаю, что это сложно.. Но получается, что файлы пишутся только при установке, а все дальнейшие действия компонента при обновлении уже никак не логируются - он может добавить любые файлы и это при удалении не будет видно в дереве.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/0684518bf80ff1b7da4bbfe7a75931d3164f225f

если есть возможность, то можно проверить на текущей версии с гита.
