### ISSUE TITLE
element_id в php файле поля

### ISSUE THREAD

**Issue by GoodMade** [instantsoft/icms2#613]
Пожалуйста добавьте element_id для поля, чтобы можно было в файле поля узнать его id в таблице базы. Тем более что, системное имя поля можно изменить а id остаётся неизменным. Пригодно будет когда нужно привязать что-либо к полю.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/0684518bf80ff1b7da4bbfe7a75931d3164f225f
