### ISSUE TITLE
Каталог дополнений. Проверка версий.

### ISSUE THREAD

**Issue by pocus-1** [instantsoft/icms2#614]
**Используемая версия InstantCMS**: 2.8.1
Админка / Каталог дополнений / Установленные:
Если версия установленного компонента выше чем у компонента в каталоге, то у него вместо зелёной кнопки "Компонент установлен" выводится кнопка "Установить" или "Купить за хх Р".
Что не логично.

Живой пример - InstantMaps. 
Разработчик рассылал обновления (v 2.0.6), но забыл обновить каталог (v 2.0.4).

**Comment by fuzegit** [comment]
Очевидно проблема не в движке

**Comment by pocus-1** [comment]
Да, конечно. И вообще это не проблема.
Но такие забывчивый авторы дополнений будут встречаться и в будущем, а изменить условия сравнения версий не сложно. Хотя бы для того, чтобы у пользователей не возникало вопросов.
