### ISSUE TITLE
Очистка уведомлений

### ISSUE THREAD

**Issue by globator88** [instantsoft/icms2#615]
Не знаю было ли раньше открыта тема, я не нашел.
Не хватает кнопки для очистки уведомлений. Иногда их становится слишком много, а удалить по одному вручную не реально. http://joxi.ru/V2VKgG3Txlb4LA

**Comment by fuzegit** [comment]
Обновите свой шаблон. Кнопка очистки всех уведомлений появилась несколько релизов назад.
