### ISSUE TITLE
При удалении группы пользователь остаётся числиться в ней

### ISSUE THREAD

**Issue by ermakover** [instantsoft/icms2#622]
**Используемая версия InstantCMS**: 2.8.1

**Версия PHP**:  5.6

**Как воспроизвести проблему**:
Если пользователь состоял в группе и она была удалена, то во вкладке остаётся число групп, в которых он состоит вместе с удалённой. Допустим я состоял в трёх группах и одну удалили. Во вкладке в профиле остаётся цифра 3, а на деле я состою в двух группах.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: не знаю. Не могу на демо удалить группу.

**Comment by fuzegit** [comment]
Не подтверждается. Или иначе опишите последовательность действий или смотрите ваши установленные дополнения или правки.

**Comment by ermakover** [comment]
fuzegit, да, действительно на своём тестовом сайте сделал несколько групп, вступил, удалил, в профиле тоже удалилось их число, а вот на рабочем моём так не получается. Буду копать где причина. Извините.
