### ISSUE TITLE
Поле "Местоположение" - Крым привязан к Украине

### ISSUE THREAD

**Issue by ermakover** [instantsoft/icms2#623]
**Используемая версия InstantCMS**: 2.8.1

**Версия PHP**:  5.6

**Как воспроизвести проблему**:
Попробовать добавить любой город Крыма и мы увидим, что Крым в Украине. Это, конечно, щекотливый вопрос. Я хоть и житель России, но я против аннексии Крыма. Но пользователям как объяснить?

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: Там нет этого поля нигде

**Comment by nomad48** [comment]
@ermakover у меня так 
![29-09-2017 11-50-02](https://user-images.githubusercontent.com/9349934/31008345-7a206542-a50c-11e7-8eed-4072237615d7.jpg)
В компоненте география поменяйте и всё.

**Comment by ermakover** [comment]
nomad48, спасибо! Никак не привыкну, что есть компонент "География".
