### ISSUE TITLE
Массовое действие с комментариями

### ISSUE THREAD

**Issue by makartsoft** [instantsoft/icms2#625]
Предложение: массовые действия с комментариями, по аналогии с опубликованными материалами. 

Поясню: в контенте можно поставить галочки рядом с id каждого материала, а затем массово удалить. В комментариях этого не хватает, приходится удалять по одному (знак кирпич).

**Comment by iAndroS** [comment]
Можно сделать как в телеграм - при щелчке в поле сообщения оно выделяется, а дальше уже всплывает меню действий с комментариями

**Comment by makartsoft** [comment]
Решено в версии 2.9.0
