### ISSUE TITLE
Баг с редактированием постов в группах, где есть роли

### ISSUE THREAD

**Issue by my-instantcms** [instantsoft/icms2#627]
**Используемая версия InstantCMS**: 2.8.2

**Версия PHP**:  5.4

**Как воспроизвести проблему**:

Заходим в группу и создаем роль, например Тест
Попробуем редактировать пост группы и получаем ошибку в форме, но система не указывает в каком поле ошибка.
dump($errors); - показывает
```
Array
(
    [allow_groups_roles] => Указано недопустимое значение
) 
```

Как только удалить роль, проблема исчезает 

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
cmsFormField
