### ISSUE TITLE
Разавторизация пользователя при удалении

### ISSUE THREAD

**Issue by Yar-rus** [instantsoft/icms2#630]
**Используемая версия InstantCMS**: 2.8.2

При удалении пользователя через профиль админом, он остаётся авторизованным и ему доступны все действия на сайте.

**Comment by fuzegit** [comment]
Опишите последовательность действий.

**Comment by Yar-rus** [comment]
В данный момент такую проблему не наблюдаю. Она самоликвидировалась. Вопрос снимаю.
