### ISSUE TITLE
В Google Chrome не работает поле "Координаты на карте" 

### ISSUE THREAD

**Issue by Yar-rus** [instantsoft/icms2#632]
**Используемая версия InstantCMS**: 2.8.2

**Как воспроизвести проблему**: В браузере Google Chrome указать координаты в этом поле

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: Нет там этого поля.

В режиме редакции в модальном окне 404 вместо карты.  Версия Google Chrome 61.0.3163.100

**Comment by fuzegit** [comment]
В комплекте CMS нет такого поля.
