### ISSUE TITLE
Массовое быстрое редактирование записей

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#634]
Предлагаю добавить функционал массового быстрого редактирования записей. Конечно, не записей целиком, а только некоторых параметров:
1. Изменение основной категории
2. Изменение (или указание) дополнительных категорий
3. Добавление тегов
4. Указание даты публикации
5. Настройки публикации
6. Что-нибудь еще

Подобный функционал отлично реализован в WordPress - отмечаем галками все записи, которые нужно изменить, нажимаем "Изменить" и массово для всех выбранных записей меняем все параметры.

Спасибо.

**Comment by Lesnierf** [comment]
Правильная мысль

**Comment by iAndroS** [comment]
@asnenne  это для админки в списке контента вы предлагаете?
Где-то тут еще было от меня предложение быстрой правки отдельных полей записи с фронта без вхождения на страницу редактирования. Как реализовано в baza.drom.ru
Ваше бы предложение я переформулировал так (если правильно его понял) - в админке, в списке контента при выделении нескольких записей в меню действий чтоб появилась возможность массового обновления одного или несколькей полей на новые значения. Например, выделяем часть новостей, появляется стандартное меню действий и новый пункт "Обновить поля", при клике на нем появляется всплывающее окно с выбором полей для редактирования и указанием новых значений для этих полей. Как-то так, в-общем )
![screenshot_1](https://user-images.githubusercontent.com/17408903/32200322-053df55a-be0c-11e7-9012-9e868f159011.png)

**Comment by vlad7090** [comment]
да, полезная опция

**Comment by fuzegit** [comment]
Не уверен, что так будет удобно. Что должно быть в модалке при массовом изменении? Хотя бы примерное ui бы.

![Выделение_225](https://user-images.githubusercontent.com/13233234/72476632-bf5d3900-37fe-11ea-9a6e-bffc29b87029.png)

**Comment by ToxicSisters** [comment]
> Что должно быть в модалке при массовом изменении?

Теги бы еще туда. Очень напряжно заходить в каждую публикацию и пересохранять теги если вдруг нужно добавить новые.
Анонс статьи наверное лишний так как для каждой записи лучше чтобы он был свой.

**Comment by ToxicSisters** [comment]
И принадлежность к группам хорошо бы добавить если вдруг нужно массово прикрепить записи к другой группе.

**Comment by iAndroS** [comment]
> Не уверен, что так будет удобно. Что должно быть в модалке при массовом изменении? Хотя бы примерное ui бы.

Да вполне себе годное UI, просто между выбранными строками записей и показанной вами модалке можно промежуточную страницу сделать с выбором редактируемых полей, дабы сократить саму форму редактирования.

**Comment by lakomet** [comment]
> можно промежуточную страницу сделать с выбором редактируемых полей, дабы сократить саму форму редактирования.
Поддерживаю. Отмечаем чекбоксами записи, нажимаем редактировать, появляется окно, в котором выбираем поля, которые нужно изменить, нажимаем далее, появляется окно с выбранными полями. По сути, массово нужно менять одно-два поля, зачем всю портянку полей показывать? Если допустим массово хотим сменить категорию. Тут другой вопрос, если мы меняем теги, то будут добавлены новые или старые сотрутся, а новые запишутся или к старым добавятся новые? Думаю нужно сделать вместо кнопки "сохранить изменения", две кнопки - "добавить значения" и "обновить/перезаписать"

**Comment by fuzegit** [comment]
![Выделение_227](https://user-images.githubusercontent.com/13233234/72529653-c9268100-387e-11ea-9bda-9bac81dad61d.png)

Так устроит?

**Comment by asnenne** [comment]
Прекрасно!))

**Comment by fuzegit** [comment]
Соответственно в следующем шаге будет список полей. Все, что в них будет задано (даже если будет пусто), будет записано в выбранных записях.

**Comment by asnenne** [comment]
Ну да, то, что надо. Пустыми значениями можно очищать поля. А если чекбокс не включен, то поле не трогаем.

**Comment by lakomet** [comment]
> будет записано в выбранных записях.

Будет добавлено? Или старые записи перезапишутся новыми?

**Comment by fuzegit** [comment]
> Или старые записи перезапишутся новыми?

Заменятся.

**Comment by lakomet** [comment]
Если нужно добавить один тег для нескольких записей, то хотелось бы, чтоб была опция - "Заменить"/"Добавить"

**Comment by fuzegit** [comment]
> хотелось бы, чтоб была опция - "Заменить"/"Добавить"

Тогда к чекбоксам выше добавлять еще чекбокс "Добавить значения к существующим". По умолчанию будет выключен и будет заменяться.

**Comment by lakomet** [comment]
Отлично.

**Comment by fuzegit** [comment]
![Выделение_228](https://user-images.githubusercontent.com/13233234/72532416-6c2dc980-3884-11ea-9d50-1f9652c364e5.png)

Всё так? Всем заинтересованным нравится?

**Comment by lakomet** [comment]
> Всем заинтересованным нравится?

Куда уж лучше то? :+1:

**Comment by iAndroS** [comment]
Бомбезно и круто )

**Comment by ToxicSisters** [comment]
> Всё так? Всем заинтересованным нравится?

Все супер спасибо огромное!

**Comment by fuzegit** [comment]
Прошу протестировать функционал, скачав и размернув версию отсюда.

**Comment by fuzegit** [comment]
@asnenne @lakomet @ToxicSisters @iAndroS @vlad7090 @Lesnierf 

дайте фидбэк, всё ли так и работает, как хотелось?

**Comment by vlad7090** [comment]
Добрый день! Скачал, протестировал. Все круто, кроме одной недостающей опции - когда надо не просто внести новое значение, а последовательно обновить существующие. 

Т.е добавить бы еще один чекбокс во всплывающем окне https://prnt.sc/qspe0d - тогда позволит последовательно обновлять существующие записи.

Если возможно, в идеале, то еще один чекбокс "Заменить значение" с .... на .... - позволит массово изменить например ссылку или некие повторяющиеся значения во всех статьях.

**Comment by vlad7090** [comment]
На сколько еще сложно сделать быстрое редактирование у отображаемых полей https://prnt.sc/qspfmq как это сделано в разделе меню?

**Comment by asnenne** [comment]
Протестировал, всё, как и хотел. Спасибо!

**Comment by fuzegit** [comment]
> Все круто, кроме одной недостающей опции

О ней речи не было.

> На сколько еще сложно сделать быстрое редактирование у отображаемых полей

Наверное не сложно, но к этой задаче уже не относится.

> Протестировал, всё, как и хотел. Спасибо!

Пожалуйста)

**Comment by vlad7090** [comment]
> О ней речи не было.

Эх, жаль, т.к очень полезно было бы, как  и быстрое редактирование полей на скрине выше, возможно еще и с фронта, но это уже к админке не имеет отношения.

**Comment by ToxicSisters** [comment]
На первый взгляд все работает замечательно, спасибо. Учтены даже нюансы о которых многие и не подумали. Однако я бы сказала что само выделение записей не совем интуитивнопонятно. На первый взгляд вообще невозможно догадаться что их можно массово выделять и работать с ними. Поэтому предлагаю сделать с левой стороны галочки для наглядности.
![galki](https://user-images.githubusercontent.com/43343657/73225002-e4916600-4173-11ea-8182-9af3cce47924.png)

**Comment by iAndroS** [comment]
А изменение автора записи как-то можно внедрить сюда?
