### ISSUE TITLE
Авторизация через соцсети

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#64]
На многих сайтах это сильно облегчает задачу регистрации и тем самым способствует эффективному расширению сообщества. Основные соцсети - вк, твиттер, инстаграмм, фейсбук. Лучше если не через логинзу, а напрямую коннектится через апи соцсетей

**Comment by Val-Git** [comment]
Мне почему то видится следующий сценарий - пользователь заходит на сайт, регистрируется через одну из соц.сетей и уходит. Заходит через какое-то время и снова регистрируется через другую соц.сеть и так далее. Получается много "мертвых" записей в БД =(

**Comment by nomad48** [comment]
а чем uLOgin решение не нравится? Там всё учтено.

**Comment by vlad7090** [comment]
чтобы не было дублей, достаточно запрашивать мыло во время авторизации. если мыло в базе есть, то предлагать склеивать, отправляя на мыло уникальный урл для подтверждения владения мылом.

**Comment by vlad7090** [comment]
улогин не удобен тем, что меняют алгоритм или сам сервис не всегда работает корректно, в связи с чем не очень удобно

**Comment by nomad48** [comment]
да не, норм всё

**Comment by vlad7090** [comment]
опять же улогин, на сколько я знаю, нельзя привести к тому виду дизайна, который хочется сделать и надо использорвать стандартные варианты самого улогина

**Comment by vlad7090** [comment]
кстати, а где вы видели компонент улогина для 2-ки, который при этом бы спрашивал мыло при регистрации для идентификации пользователя?

**Comment by nomad48** [comment]
у меня стоит для 2-ки и все он запрашивает и постинг аватаров они поправили. Пожалуйста вот ссылка https://github.com/ulogin/ulogin-InstantCMS/tree/instantcms2

**Comment by Maratakziaplus** [comment]
У меня Ulogin выводит только никнейм и почту, вместо аватара пустышка. Сторонние разработки плохи тем, что они не всегда вовремя обновляются, некоторые просто отказываются поддерживать свои разработки. Тот же Ulogin не обновлялся с версии icms2.1. а у инстанта уже версия 2.4 и о какой нормальной работе Ulogin может идти речь. И это практически со всеми разработчиками такое происходит, выходит обновление движка и ты гоняешься месяцами за разработчиком компонента, просишь, умоляешь прислать обновление. Некоторые обновляют, а от некоторых ни ответа, ни привета. Поэтому, лучше всего авторизацию через соцсети иметь в коробке и не только авторизацию, но и все то, что я указал в посте №99

**Comment by nomad48** [comment]
@Maratakziaplus  да что Вы говорите, они прекрасно все обновляют и поддерживают, у меня Ulogin отрабатывает норм. Кстати по аватарам они как раз внесли изменения ,чтобы все норм было. Я им сам писал.

**Comment by Val-Git** [comment]
@Maratakziaplus ваше предложение звучит так: мне нужна авторизация через соц.сети, устанавливать сторонние дополнения не хочу, поэтому нужно внести такую авторизацию в коробку!

Мне, подобная фича в коробке не нужна! Но надо много чего другого - предлагаю разработчикам бросить все силы на реализацию моих хотелок?!

**Comment by nomad48** [comment]
@Maratakziaplus я ж Вам ссылку дал, https://github.com/ulogin/ulogin-InstantCMS/tree/instantcms2 там обновлённый компонент uLogin, можете у меня на сайте попробовать зарегатся через него. У меня корректно передаёт поля, город, дату рождения, аватар (большой или маленький) и другие опции если они мне нужны. Просто Вы наверно не настроили передачу этих полей у себя в личном кабинете uLOgin.
Вот посмотрите и включите что вам надо http://joxi.ru/NDrlw63CxZDYAP

**Comment by Maratakziaplus** [comment]
Спасибо большое, попробую.   Я там зарегил сайт, подтвердил, скачал плагин для icms2, установил на сайте и все.  Что то я в кабинете не нашел такие настройки как у вас. На скрине сверху код виджета, его тоже надо прописывать? Не могли бы описать последовательность ваших действии по установке и настройке? Спасибо.

**Comment by nomad48** [comment]
@Maratakziaplus зайдите на этот сайт http://ulogin.ru и там всё ясно, если нет есть же раздел помощь,  просто если не охота с вопросом разбираться, легче всего написать ничего не работает.
![28-01-2016 18-31-02](https://cloud.githubusercontent.com/assets/9349934/12648967/871a6766-c5ed-11e5-8eef-4bc3de06ce70.png)
![28-01-2016 18-31-25](https://cloud.githubusercontent.com/assets/9349934/12648966/871941e2-c5ed-11e5-8ed6-10c2c1a3c1dc.png)
![28-01-2016 18-31-42](https://cloud.githubusercontent.com/assets/9349934/12648968/871acd3c-c5ed-11e5-95a3-a914ab78eff1.png)
![28-01-2016 18-31-52](https://cloud.githubusercontent.com/assets/9349934/12648973/8d4f3d14-c5ed-11e5-8935-36388a144259.png)

**Comment by Maratakziaplus** [comment]
Val-Git, а что вы так нервничаете, я не только о себе думаю. Я просто внес свое предложение по улучшению удобства и простоты регистрации для пользователей. Больше не буду)

**Comment by Maratakziaplus** [comment]
nomad48 спасибо большое за подсказку, все ухожу отсюда, здесь мне чайнику делать нечего)

**Comment by nomad48** [comment]
@Maratakziaplus я сам чайник. Человек всё знать не может, но читать и изучать может и обязан.
В самом компоненте есть файл readme изучите его, там подробная инструкция, если что-то не получится, обращайтесь. 
[README.txt](https://github.com/instantsoft/icms2/files/108418/README.txt)

**Comment by Val-Git** [comment]
@Maratakziaplus я не нервничаю, я переживаю =)
Предложения вносить это хорошо, но подавать их нужно для общего блага, а не для личных мотивов) Так что вносите.

**Comment by Maratakziaplus** [comment]
@nomad48  Спасибо еще раз, наконец то разобрался с ulogin-ом)

**Comment by nomad48** [comment]
@Maratakziaplus вот и славно:)

**Comment by maxicms** [comment]
Уже кто пробывал поставить данное решение версии 2.0.2 по факту не заработало данные от соц сети получаем но регистрации вообще не происходит, настройки вроде все сделаны.

**Comment by nomad48** [comment]
@maxicms ПрИвет, у меня стоит на 2.4.1 стоит и все работает.

**Comment by maxicms** [comment]
в настройках виджета стоит с редиректом на корень сайта или на /ulogin ?

**Comment by nomad48** [comment]
@maxicms у меня стоит на корень сайта я так понял 
![09-03-2016 18-35-55](https://cloud.githubusercontent.com/assets/9349934/13640477/e7b7cffc-e625-11e5-8997-0473b0fa4147.png)

**Comment by maxicms** [comment]
все также, только ничего не происходит, :( жесть.

**Comment by nomad48** [comment]
@maxicms ты какой дистрибутив ставил? у них там их два

**Comment by maxicms** [comment]
ставил не тот что у них лежит в бранче а делал из тех файлов, в админке стоит 2.0.2

**Comment by pin-git** [comment]
ну создайте вы ветку на форуме , да укажите здесь ссылку на неё, совсем не в тему разговорчеГ

**Comment by maxicms** [comment]
и по какому признаку Вы определили что разговор не в тему? и для чего лезть на форум? есть конкретный тикет и мы тут извиняйте не цвет трусов обсуждаем. а реальную проблему, которая имеет место быть.

**Comment by pin-git** [comment]
ой, извините! нижнее бельё... телодвижения... точно! какая разница где писать, если это отдельно и конкретно. 
Unsubscribe

**Comment by nomad48** [comment]
@maxicms 
![09-03-2016 18-54-09](https://cloud.githubusercontent.com/assets/9349934/13641185/91c22d74-e628-11e5-92a0-35b0409b7bcd.png)
**_то есть в пакете, еще пакет есть_**
![09-03-2016 18-54-31](https://cloud.githubusercontent.com/assets/9349934/13641192/97498db4-e628-11e5-80d6-4284efc71dec.png)

**Comment by maxicms** [comment]
Этот тоже не рабочий отчасти нашел ошибку сейчас буду курить как ее исправить, да и закрою тут обсуждение а то PIN нервничает.

**Comment by nomad48** [comment]
@maxicms а почему у меня работает? а где ошибка, там где нотис выскакивает

**Comment by maxicms** [comment]
странный вопрос, просто суть ошибки в том что не происходит регистрация пользователя и в таблицу ulogin пишется 0, хотя ошибок нету.

**Comment by nomad48** [comment]
@maxicms у меня регаются и Kreator решение выдал на Форуме [http://www.instantcms.ru/forum/thread22356.html](url) по моему нотису 
`//--------------------
	public function getUloginUserNetworks ($user_id = 0) {
		$this->resetFilters();
		$this->filterEqual('user_id', $user_id);
		$q = $this->get('ulogin_user');
		if (is_array($q)) {
			foreach ($q as $q0) {
				$result[] = $q0['network'];
			}
		}
		return $result;
	}`

**Comment by maxicms** [comment]
Это решение нотисов которые перед выборкой сетей. у меня проблема в другом, а именно не создается новый пользователь вообще.

**Comment by Maratakziaplus** [comment]
Я руководствовался инструкцией **nomad48 ** и установил на 2.4.0, все без проблем работает. Вытягивает из соцсетей аватары, мейлы и сама регистрация проходит без проблем. А вообще конечно было бы хорошо иметь это в коробке, чтобы меньше мучиться при обновлениях. Но тут спецы говорят, что эта функция в коробке не нужна.

**Comment by maxicms** [comment]
Насчет в коробке тоже соглашусь, не стоит это туда пихать по ряду причин, у меня был отдельный случай, кто то напакостил в базе, сделал в базе пользователей ID float и 0 длинны, а так вроде все заработало.

**Comment by vlad7090** [comment]
а этот аддон проверяет по мылам и делает склейку если мылы совпадают?

**Comment by Maratakziaplus** [comment]
Нет не проверяет, мыла могут совпадать

**Comment by vlad7090** [comment]
> Нет не проверяет, мыла могут совпадать

Это неправильно, что под одним мылом может быть несколько профилей. Смысла от таого аддона нет, т.к в итоге один пользователь сам того не подозревая создаст несколько профилей и не будет понимать что происходит.

**Comment by nomad48** [comment]
Если одинаковые email профили склеиваются, я проверял. Есть виджет привязка аккаунтов, на нём попробуйте проверить.

**Comment by Maratakziaplus** [comment]
А у меня образовались два профиля с одинаковыми емейл, не могу понять почему не склеиваются.

**Comment by nomad48** [comment]
@Maratakziaplus  Я когда захожу под своим Яндекс, то мой профиль из uLogin-Яндекса, привязывается к основному профилю с email.

**Comment by Maratakziaplus** [comment]
Вот сижу и разбираюсь с виджетом привязки аккаунтов, думаю скоро разберусь)

**Comment by Maratakziaplus** [comment]
Разобрался. У меня оказывается одна и та же почта в яндексе зарегистрирована в двух зонах ru  и kz, на сайте через авторизацию регистрировался через ru, а с фейсбука тянет kz, поэтому и получились два аккаунта на одну почту)

**Comment by Maratakziaplus** [comment]
Оставил одну почту, вторую удалил. Теперь все склеилось и привязалось)

**Comment by nomad48** [comment]
Сегодня вышла версия uLogin 2.0.3 - кому надо устанавливайте, устранили все недочеты которые им указывали.

**Comment by Maratakziaplus** [comment]
А как обновиться, просто залить файлы или обычная установка через компоненты?

**Comment by nomad48** [comment]
@Maratakziaplus привет, я все лишнее удалил с их дистрибутива, установка обычная через админку.

**Comment by Maratakziaplus** [comment]
Привет, а что там лишнего)

**Comment by nomad48** [comment]
@Maratakziaplus вот [ссылка](https://yadi.sk/d/wa0BrxLcq6VHc) скачивай и ставь, можешь смержить перед установкой с 2.0.2

**Comment by Maratakziaplus** [comment]
Спасибо!
