### ISSUE TITLE
Лишние теги h1 в списке альбомов

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#640]
**Используемая версия InstantCMS**: 2.8.1

**Версия PHP**:  5.4.38

**Как воспроизвести проблему**: Зайти на страницу https://домен/albums и проверить через просмотр кода страницы

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

На странице один основной h1 + теги h1 от размещенных альбомов

**Comment by fuzegit** [comment]
В 2.8.2 этой проблемы нет.

**Comment by nomad48** [comment]
@fuzegit я понял, просто проверял на демо, а там 2.8.1 тоже, не посмотрел. Спасибо.
