### ISSUE TITLE
"Автоссылка" и вывод списка записей

### ISSUE THREAD

**Issue by murlysja** [instantsoft/icms2#641]
**Используемая версия InstantCMS**: 2.8.2

Если в разделе "Настройки" - "Сайт" - "Выводить на главной странице"  выбрать какой-либо тип контента, в котором есть кастомное поле с включенной опцией "Автоссылка", при нажатии на эту ссылку список записей выводится, но при этом отображается и все множество виджетов, привязанных к главной странице.

**Comment by fuzegit** [comment]
Не является ошибкой. В данном случае для главной нужно прописать отрицательные маски.
