### ISSUE TITLE
Проблема при создании виртуального поля

### ISSUE THREAD

**Issue by smartcontroltoday** [instantsoft/icms2#644]
Пытаюсь создать виртуальное поле (public $is_virtual = true;) и добавить его в тип контента.
При записи нового поля это свойство не передается и движок пытается добавить новую колонку в таблицу типа контента (cms_con_news) - неудачно, потому что свойство $sql не заполнено и запрос выходит некорретный. 

Смотрю метод добавления нового поля в файле [ctypes_fields_add.php](https://github.com/instantsoft/icms2/blob/master/system/controllers/admin/actions/ctypes_fields_add.php#L52) свойство не передается, а по умолчанию оно равно false. Если добавить его руками третьим параметром (просто для проверки) `$field_id = $content_model->addContentField($ctype['name'], $field, true);`, то поле добавится успешно. Но при удалении выскочит ошибка - будет попытка удалить колонку в таблице, а ее нет (и не должно быть же?).

Следующий шаг - просмотр записи с виртуальным полем. Виртуальное поле же не нужно заполнять? - но нужно, чтобы оно сразу отображалось. Ему не нужны значения, оно должно отображаться исходя из контекста (например, выводить URL текущей страницы). Поле виртуальное и сразу выскакивают ошибки на несуществующий индекс.. Потому что в таблице полей оно есть (cms_con_news_fields), а в таблице cms_con_news колонки нет и запрос его не возвращает.

**Comment by fuzegit** [comment]
Функционал виртуальных полей к сожалению не доделан. В вашем случае нужно всё же ставить свойство $sql с tinyint, пока иначе никак.
