### ISSUE TITLE
trim();

### ISSUE THREAD

**Issue by ValenokPC** [instantsoft/icms2#647]
**Используемая версия InstantCMS**: наверно все!

**Версия PHP**:  5,6

**Как воспроизвести проблему**:

При создании запроса в базу типа insert или update то значения полей обрабатываются функцией **trim()** которая очищает начало и конец строки от  ` \t\n\r\0\x0B`. Как быть если эти значения нужны! в началах или концах строк

**Comment by fuzegit** [comment]
> Как быть если эти значения нужны! в началах или концах строк

Делать запрос вручную через query()

trim убираться не будет.
