### ISSUE TITLE
Пинговалка в поисковые системы о новом материале

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#65]
На сколько знаю, в 2-ке еще ее не сделали, хотя очень сильно помогает в индексации сайта и ускорении этого процесса. Надеюсь в 2-ке также появится, что позволит сайтам продвигаться еще более эффективно. Только надо учесть, что если отложенная публикация, то пинговать только после публикации на сайте.

**Comment by mafru** [comment]
А зачем она нужна в коробке? Где данный функционал есть в коробке?
Раньше вроде в коробочной версии Dle был, но его из движка вынесли.
Думаю это должно быть сторонним компонентом, а пингование уже повесить на событие  добавления материала.
Только проблема обработки хуком материалов с отложенной публикацией. 
Может стоит подумать над добавлением события в файл cron_publication.php (первое что приходит на ум).

**Comment by fuzegit** [comment]
В коробке не будет
http://www.instantcms.ru/blogs/udarnyi-blog/komponent-ping-servisov-obnovlenija.html
