### ISSUE TITLE
Поле для счетчиков статистики в настройках сайта

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#654]
Предлагаю вынести в настройки сайта поле для счетчиков статистики сайта и прочих скриптов.
Сменил например шаблон, приходиться и для него виджет делать или в файлы лезть. А так было бы удобно - внес один раз и забыл о них.

**Comment by smartcontroltoday** [comment]
> Предлагаю вынести в настройки сайта поле для счетчиков статистики сайта и прочих скриптов.

Это скорее настройки не сайта, а конкретного шаблона. В настройки щаблона нужно добавить поля типа "Скрипты перед /body", "Стили css", может быть несколько текстовых полей для разных типов устройств (так удобнее) и потом весь этот код шаблон должен добавлять на страницы сайта. Это именно настройки шаблона должны быть.

**Comment by iAndroS** [comment]
@smartcontroltoday я тоже об этом думал, но в итоге пришел к выводу, что именно счетчики лучше в настройках сайта указывать. И да, в настройках шаблона тоже такие поля пригодились бы для других скриптов.

**Comment by nomad48** [comment]
@iAndroS берёте виджет html и вставляете туда любой скрипт (я проверял) на гугл счетчике всё работает, и вставляете на все страницы. Шаблон Вы меняете не каждый день, поэтому перед сменой шаблона скинул их вниз (в неиспользуемые) и закинули виджеты в новый шаблон.
