### ISSUE TITLE
Дополнительные категории

### ISSUE THREAD

**Issue by Yar-rus** [instantsoft/icms2#655]
Предложение, при создании записи, не давать возможность выбора дополнительных категорий, пока не будет выбрана основная.

**Comment by Yar-rus** [comment]
Причина чисто логическая, Сначала должно быть первое, затем второе. Без первого не должно быть второго.
Да, при сохранении система показывает ошибку, что не заполнено поле "Категория" и при выборе значения, такое-же значение (если он было выбрано ранее в "Дополнительных категориях") удаляется, но зачем такие действия пользователю. Ему можно строку в "Дополнительные категории" делать неактивным, пока он не выберет основную категорию.

**Comment by Val-Git** [comment]
Моё IMHO поле для ввода категорий должно быть одно. С типом введения вроде тегов или через запятую. Логика работы следующая: если пользователь ввел одну категорию - это главная, если ввел несколько, то первая - основная, а остальные дополнительные.
Такая модель не вносит лишней путаницы, упрощает ввод и не надо делать лишних проверок на заполненность основной категории перед вводом дополнительных))

**Comment by Yar-rus** [comment]
Выбор сразу из нескольких? Как, чекбоксами? А если категорий много? 
А вообще, выбор одноврЕменно всех необходимых категорий в одном месте (поле) очень правильная мысль. Чем меньше заморочек, тем лучше. 
А что касается главной категории, то, как я предполагаю, ее и нет вовсе... Они все одинаковые... Наверное.

**Comment by Val-Git** [comment]
> Выбор сразу из нескольких? Как, чекбоксами? А если категорий много?

Не понял ваших вопросов абсолютно. Есть поле ввода пользователь начинает вводить категорию, подтягиваются варианты. Он выбирает понравившийся, ставит запятую (или при выборе категория отображается в поле ввода в виде небольшой кнопки с крестиком удаления как в тегах). Или же выпадающий список с категориями и полем поиска, опять же как это сейчас есть в Chosen'е

> А что касается главной категории, то, как я предполагаю, ее и нет вовсе... Они все одинаковые... 

в ядре движка есть главная и есть дополнительные)) Хотя конечно лучше бы сразу было реализовано без таких разделений.

**Comment by Yar-rus** [comment]
> Выбор сразу из нескольких? Как, чекбоксами? А если категорий много?
Имел ввиду вывод всего списка категорий, а такой список легче выбирать чекбоксами. Видел где-то подобное... Но это портянка может получиться огромная. Если только в каком-нибудь раскрывающемся модуле...

> Есть поле ввода пользователь начинает вводить категорию, подтягиваются варианты. Он выбирает понравившийся, ставит запятую
А нельзя так делать. Пользователь может даже не догадываться, как его категория называется. Проще выбрать из предложенного и не заставлять его лишний раз мозги напрягать. А так ещё он пробежится по всем категориям и ещё что-нибудь выберет. Ну хорошо же! А про запятую так вообще ужас - ему ещё запятую вводить не хватало ))

Лично меня текущий способ выбора категории вполне устраивает, за исключением сказанного в первом сообщении..

**Comment by Lesnierf** [comment]
Поддерживаю, выбор всех нужных категорий в одной строчке это удобнее, понятнее, и форма займёт меньше места на экране. Ещё бы функционал сворачивания и разворачивания вложенных категорий в общем списке. (если категорий много, список длинный, искать нужные не удобно)

**Comment by Yar-rus** [comment]
Пожалуй, да, вариант выбора сразу нескольких категорий предпочтительнее.

**Comment by iAndroS** [comment]
@Yar-rus, зачем чекбоксы? Как сейчас реализован выбор дополнительных категорий, вполне удобная штука. В принципе, соглашусь с Val полностью - в одном поле добавлять и первая категория=основная категория!
