### ISSUE TITLE
Фильтр в связях

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#656]
**Используемая версия InstantCMS**: 2.8.2

Фильтр в связях ищет по всему типу контента по умолчанию, а не по выбранной родительской записи. 
Поясню на примере: Есть продавец, у которого есть куча товаров (дочерний тип контента). При переходе во вкладку связи, в фильтре не подставлен по умолчанию родительский контент, не каждый пользователь сообразит, что его нужно там выбрать, это во-первых. Во-вторых, сам выбор родителя в поле привязки не совсем юзабелен и интуитивно ясен, но это уже тема другого топика совсем.

**Comment by fuzegit** [comment]
> Фильтр в связях ищет по всему типу контента по умолчанию, а не по выбранной родительской записи.

Нет, это не так. Фильтр ищет только в связанном контенте.
