### ISSUE TITLE
Не корректная выборка в контенте.

### ISSUE THREAD

**Issue by maxicms** [instantsoft/icms2#657]
Суть проблемы заключается в том что если выбирать контент по правому соединению вспомогательной таблицы в которой запись может быть несколько раз, то при запросе материала мы получим только одну запись, так как у нас нет возможности в функции getContentItems отключить группировку по ключу. 

не совсем удобно.

**Comment by fuzegit** [comment]
> так как у нас нет возможности в функции getContentItems отключить группировку по ключу

группировки нет по умолчанию

**Comment by maxicms** [comment]
Не совсем правильно выразился :)  
суть в том что в запросе получаем например записи с id: 10, 11, 12, 10, 24

то на выходе когда мы формируем массив там идет $item[$key] то есть по факту на в выходном массиве будет только одна запись с id 10

**Comment by fuzegit** [comment]
ты планируешь в одном списке выводить несколько одинаковых записей?
