### ISSUE TITLE
В redactor не сохраняется заливка текста

### ISSUE THREAD

**Issue by andriy85if** [instantsoft/icms2#658]
**Используемая версия InstantCMS**: 2.8.2

**Версия PHP**:  7.1

 В redactor не сохраняется заливка текста.  

- устанавливаем заливку кнопкой "Заливка текста"
- сохраняем и видим, что заливка не отображается. 
- открывает запись для редактирования и видим, что и здесь заливки нет. 

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

**Comment by nomad48** [comment]
Кроме заливки текста не сохраняется "обычный и нумерованный" список
Хотя теги в тексте присутствуют.
устанавливаем обычный список кнопкой "Обычный список"
сохраняем и видим, что обычный список не отображается.
открывает запись для редактирования и видим, что и там список отсутствует.
![06-11-2017 17-00-01](https://user-images.githubusercontent.com/9349934/32445928-4e3488d0-c318-11e7-8b8c-bd87bde6d297.png)

**Comment by fuzegit** [comment]
Со списками проблем нет, смотрите свой css.

**Comment by nomad48** [comment]
@fuzegit свой это какой, шаблоны или Редактора?
