### ISSUE TITLE
Баг контента группы

### ISSUE THREAD

**Issue by Dobriy1982** [instantsoft/icms2#664]
**Используемая версия InstantCMS**: 2.8.2

**Версия PHP**:  5.4.45-0+deb7u9 

**На странице группы, не отображается добавленный в нее контент**:

* Создаю группу
* Создаю тип контента с настройками создания записей только в группах
* Создаю запись в этом типе контента, выбираю группу в форме создания записи
* Итог: запись создается, на странице списка записей, в заголовке записи появляется название группы, кликая по ней, открывается страница 404. На странице группы новая запись не появляется, так же как и не появляется вкладка "Контент"

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
Повторил за вами всё по пунктам. Проблему воспроизвести не удалось.
