### ISSUE TITLE
Баг меню группы во вкладке "Участники"

### ISSUE THREAD

**Issue by Dobriy1982** [instantsoft/icms2#667]
**Используемая версия InstantCMS**: 2.8.2

**Версия PHP**:  5.4.45-0+deb7u9

**Как воспроизвести проблему* *:

* захожу на страницу группы
* захожу во вкладку "Участники"
* Нажимаю на кнопку "Меню группы", в открывшемся меню есть два пункта: "Сделать администратором" и "Исключить", при нажатии на эти пункты, действие применяется к последнему пользователю в списке участников групп, нет никакой возможности выбрать пользователя к которому нужно применить действия этих пунктов. Совершенно не понятно логика этого функционала, проще говоря грубейшая ошибка разработчиков. Вообще такое ощущение что компонент "Группы" писали между делом на скорую руку. Движок, чистый, никаких редактирований кода не производилось.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА/НЕТ

**Comment by fuzegit** [comment]
> при нажатии на эти пункты, действие применяется к последнему пользователю в списке участников групп, нет никакой возможности выбрать пользователя к которому нужно применить действия этих пунктов. Совершенно не понятно логика этого функционала, проще говоря грубейшая ошибка разработчиков.

Не знаю, о чем вы пишите и какой "чистый движок" тестируете, но давайте писать объективно, вместо "писали между делом на скорую рук"

![_120](https://user-images.githubusercontent.com/13233234/32604740-c80d2808-c55f-11e7-94e2-5e00e5652a30.png)

Где и что вы нажимаете? Всё, что вы описали - не подтверждается.
