### ISSUE TITLE
Фильтр контента - Ошибка SQL запроса при выборе >1 поля связей

### ISSUE THREAD

**Issue by Lesnierf** [instantsoft/icms2#669]
Если в фильтре контента выбрать значения в более чем 1 поле Связей то в SQL запросе образуется дублирующая строка, что приводит к ошибке.

![image](https://user-images.githubusercontent.com/25480999/32726834-d5112e5a-c893-11e7-948c-6308651bc0b6.png)
![image](https://user-images.githubusercontent.com/25480999/32726900-13080cba-c894-11e7-83ae-ee9335bd362d.png)

**Comment by fuzegit** [comment]
На текущей версии с github вы проверяли проблему? Подозреваю, что она решена.

**Comment by Lesnierf** [comment]
Не проверял. Версия 2.8.2

**Comment by fuzegit** [comment]
Если есть возможность проверить на текущей версии отсюда, будем признательны.

**Comment by Lesnierf** [comment]
![image](https://user-images.githubusercontent.com/25480999/33208935-1b0d51d0-d12d-11e7-9a7d-544ba527cc53.png)
Установел версию из гита, ошибка осталась
