### ISSUE TITLE
Вызов файла шаблона из backend

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#679]
При вызове шаблона из backend, например:
`return cmsTemplate::getInstance()->render('****', array(
            'grid' => $grid
        ));`
Система ищет этот шаблон только (или обязательно) в папке шаблона default. Т.е. у меня шаблон называется не default И все файлы я использую из него. Следовательно чтобы тут все работало нужно обязательно залить файл шаблона в папку шаблона default

**Comment by fuzegit** [comment]
Система ищет в шаблоне, заданном для админки.
