### ISSUE TITLE
Предложение в ближайший релиз для RSS

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#680]
Яндекс ввел новую штуку "Турбо-страницы". Для их использования нужно как-то переоформить rss фид. Ссылка на документацию https://yandex.ru/support/webmaster/turbo/feed.html
Было бы круто видеть данную возможность в ближайшей обнове

**Comment by makartsoft** [comment]
В идеале чтобы был не дополнительный шаблон ленты RSS, а возможность к типу контента привязать еще один вариант вывода RSS. 
Т.е. важно чтобы у одного типа контента были разные ленты для Яндекс.Новости и для Турбо страниц
