### ISSUE TITLE
Виджет фильтр контента

### ISSUE THREAD

**Issue by danil050405** [instantsoft/icms2#683]
**Версия InstantCMS 2.8.2

**Версия PHP 5.4.45-0+deb7u9 

Здравствуйте! Не понятна работа виджета "Фильтр контента" с полями-свойствами (тип поля "Список", "Список: мультивыбор")
Если использовать фильтр непосредственно на на странице списка, который включается в настройках типа контента, то все работает как надо, однако, если же использовать для фильтрации контента виджет, то при установке в нем, в полях свойствах, нужные значения и нажатии на кнопку фильтровать, пользователю просто показываются все записи списка контента (и в случае если по заданным параметрам записей нет и в случае если они есть). Почему так?
Проверял на вашем демо сайте в типе контента "Объявления" - та же история

**Comment by iAndroS** [comment]
У меня вообще не работает виджет вне типа контента
