### ISSUE TITLE
PHP 7.0 - белый экран

### ISSUE THREAD

**Issue by danil050405** [instantsoft/icms2#684]
Здравствуйте. мой хостинг перешел на версию php 7.0. , после чего сайт встал, белый экран после авторизации, в режиме отладки тоже пусто. Хостеры что-то там поколдовали и появился комментарий ошибки (перевел на русский):

"Неустранимая ошибка: файл /var/www/dobri191/data/www/placenet.ru/system/controllers/nm_extends/frontend.php кодируется кодировщиком ionCube для PHP 5.3 и не может работать под PHP 7.0. Пожалуйста, попросите поставщика скрипта предоставить версию, закодированную с помощью кодировщика ionCube для PHP 5.6. в неизвестном на линии 0"

Подскажите как теперь быть?

**Comment by pocus-1** [comment]
> Подскажите как теперь быть?

Очевидно отключить расширение мессенжера и обратиться к разработчику
https://vk.com/neomessenger

**Comment by danil050405** [comment]
Действительно, даже не посмотрел что файл-то неомессенджера, а не системный)

**Comment by danil050405** [comment]
Хотя я рано начал радоваться, профиль пользователя тоже не работает, похоже это будет повсеместно...
