### ISSUE TITLE
Изменять автора в системном поле user

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#686]
Очень необходима надстройка для системного поля user, позволяющая задавать нового автора записи!
Высшим крутяком было бы, если автор записи или админ/модер мог указать нового автора материала, а тот должен подтвердить свое согласие его принять!
И уж совсем верх наглости с моей стороны предложить такое: чтобы автор мог указать соавтора (совладельца) записи. То есть, либо передать полностью запись в управление другого юзера, либо предложить стать соавтором.
К примеру, 2-3 ответственных сотрудника могли бы вести профиль своей компании на сайте, либо же можно было бы продать или передать безвозмездно кому-то право вести страницу какого-то важного контента.

**Comment by Val-Git** [comment]
Вы действительно считаете что такой функционал нужен в коробке?
Уточню вопрос: вы действительно считаете что такой функционал, кроме как вам, всем нужен в коробке?

**Comment by fuzegit** [comment]
Описываемый функционал не относится к полю.

**Comment by iAndroS** [comment]
> Менять владельца записи - да, об этом писали не раз.
Собственно, я это и имел ввиду, просто дальше уже нафантазировал. А принимать мои предложения или нет, решать, само собой, вам...

**Comment by iAndroS** [comment]
@fuzegit , а 

> Менять владельца записи - да, об этом писали не раз.

это будет в ближайшем релизе?

**Comment by murlysja** [comment]
> 
> 
> @fuzegit , а
> 
> > Менять владельца записи - да, об этом писали не раз.
> 
> это будет в ближайшем релизе?

Было бы неплохо внедрить.
