### ISSUE TITLE
Дать возможность отключать показ виджетов без удаления

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#69]
Было бы очень полезно просто давать отключать показ виджетов, при этом не удаляя виджет с позиции где он стоит, т.к порой просто на время надо отключить показ, а пото вернуть обратно.

Но если удалить его в "неиспользуемые виджеты", то если виджетов много, надо вспоминать куда его вновь вставить. Отключение показа позволит быстро урпавлять показом и скрытием виджета.

**Comment by mafru** [comment]
Я всегда в таком случае для виджета ставлю доступ «Администраторы». Когда понадобится доступ для всех, тогда изменяю права доступа.

**Comment by vlad7090** [comment]
я думал над этим, но не удобно с точки зрения визуальной и с точки зрения администрирования, т.к визуально не видно какие виджеты только для администратора, а какие нет. Тем самым можешь просто забыть или запутаться, если виджетов великое множество на разных страницах.

В случае с отключением показа будет визуально подсвечиваться, что виджет отключен.

**Comment by mafru** [comment]
А если одновременно с изменением прав доступа, в заголовок виджета добавлять слова (скрыт). В таком случае вы сразу будете видеть, какой виджет показывается, а какой скрыт.

**Comment by vlad7090** [comment]
в таком случае да, согласен, задача облегчается. но не удобнее ли всеже иметь возможность просто скрыть и тем самым вообще  не использовать ресурсы движка на показ данного виджета пусть даже админу.

**Comment by mafru** [comment]
Не думаю, что много ресурсов сэкономите не показывая виджет Администраторам.
Но если желаете никому не показывать виджет, то снимите все галочки на вкладке доступа настроек виджета. Тогда виджет не будет показываться и Администраторам.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/6e4c87fb2c2024a29c202bd1dbb7cb120653a32c
