### ISSUE TITLE
Редактирование контента на модерации пользователем

### ISSUE THREAD

**Issue by ermakover** [instantsoft/icms2#691]
**Используемая версия InstantCMS**: 2.8.2

**Версия PHP**:  5.6

Как пожелание - можно ли сделать, чтобы пользователь мог редактировать контент, находящийся на модерации?

На данный момент пользователь публикует контент, а он, например, не соответствует правилам сайта или подан с ошибками.  Я сам могу его отредактировать, а вот пользователь не может. И хорошо, если я знаю что редактировать. 

На примере моего сайта. Столкнулся с проблемой, когда стал платить людям за добавление контента. Им надо было добавить свою собаку, её фотоальбом с описанием и фотографии собаки с изменением заголовков фото. Почти все делают всё это с ошибками, неполным описанием. Хорошо бы если было можно возвращать контент на доработку или хотя бы редактировать контент на модерации.

**Comment by fuzegit** [comment]
Будет реализовано вот так http://www.instantcms.ru/forum/thread28334-1.html 
В версии здесь, уже доступно.

**Comment by ermakover** [comment]
О, круто, спасибо!
