### ISSUE TITLE
Загрузка картинки по ссылке

### ISSUE THREAD

**Issue by ValenokPC** [instantsoft/icms2#692]
**Используемая версия InstantCMS**: 2.8.2

**Версия PHP**:  7.1

**Как воспроизвести проблему**: 
В любом типе контента загрузить вот эту картинку по ссылке!
https://img-fotki.yandex.ru/get/893753/64060800.1030a/0_4cd540_5c3b7ecd_orig

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

Если ссылка вот такого типа `https://img-fotki.yandex.ru/get/893753/64060800.1030a/0_4cd540_5c3b7ecd_orig` то при загрузки файла по ссылке выйдет ошибка **Файл имеет неподходящий формат**

**Comment by nomad48** [comment]
@ValenokPC так и на PHP 5.4 потому что у файла нет расширения из списка допустимых расширений для изображений jpg, gif, png и т.д.

**Comment by ValenokPC** [comment]
Это то понятно, на мой взгляд лучше проверять на совпадение MIME-типов чем расширений! Т.к не у всех ссылок есть расширения!

**Comment by Val-Git** [comment]
1. Когда ссылка с расширением это прямая ссылка на файл.
2. Не разбирался как конкретно сейчас реализовано, но вероятно тип файла и определяется именно по MIME-типу, т.к расширению верить нельзя в любом случае.

**Comment by ValenokPC** [comment]
@Val-Git Сейчас проверка идет по расширению файла! https://github.com/instantsoft/icms2/blob/6528bf84135e3d4c0cc279b37f0545e2fb977e4d/system/core/uploader.php#L247-L287
