### ISSUE TITLE
Хлебные крошки и контент по-умолчанию

### ISSUE THREAD

**Issue by narochnyi** [instantsoft/icms2#695]
Если установить в настройках "Тип контента по-умолчанию" какой-нибудь тип контента и включить хлебные крошки, то в них, при открытии этого контента будет отображаться пункт на этот тип, а при переходе будет редиректить на главную.

Думаю логичнее будет убрать этот пункт у контента по-умолчанию, чтобы после "картинки домика" шла сразу категория, если есть!

**Используемая версия InstantCMS**: 2.8.2

**Версия PHP**:  5.5

**Comment by iton1** [comment]
Согласен, что нужно это исправить, приведу пример в скринах.

При таких настройках:
![default](https://user-images.githubusercontent.com/17750649/34668242-8acaab9e-f47d-11e7-8c59-b25507a8927d.png)

В хлебных крошках ссылка с редиректом на главную, она не нужна.
![default](https://user-images.githubusercontent.com/17750649/34668196-52f86b84-f47d-11e7-9ccd-0498f21d4c92.png)

Правильнее вот так
![default](https://user-images.githubusercontent.com/17750649/34668401-41223196-f47e-11e7-965a-18d0786a3aa5.png)

**Comment by narochnyi** [comment]
А пока, это исправляется внесением изменений в файл:
`"\templates\default\controllers\content\item_view.tpl.php"`

в 13 строке заменить:
`if ($ctype['options']['list_on']){`

на  
`if ($ctype['options']['list_on'] & cmsConfig::get('ctype_default') != $base_url){`
