### ISSUE TITLE
Вышла из строя админ-панель.

### ISSUE THREAD

**Issue by Shrain2** [instantsoft/icms2#696]
**Используемая версия InstantCMS**: Неизвестно

**Версия PHP**:  5.3

**Как воспроизвести проблему**: 

Зайти на URL админ-панели http://www.etpm.ru/admin/login.php

Ввести логин и пароль.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: НЕТ

После авторизации получаем ошибку, текст ошибки ниже. Это не баг, это скорее разовая ошибка, возможно даже вызванная какими-то неправильными действиями администратора. Но я вынужден написать об этом здесь, ПОСКОЛЬКУ других каналов техподдержки я не нашел. Дело в том, что мне передали сайт с уже неработоспособной админ-панелью, и мне дешевле будет поручить программисту перенести сайт на Битрикс, чем оплачивать ему поиски корня данной проблемы. Поэтому очень прошу помочь с решением. Заранее большое спасибо!

Текст ошибки:
-------------------------------------------------------------
Warning: session_start() [function.session-start]: open(/home/tmp/sess_b3b461ba78c848d91f4e41946b369592, O_RDWR) failed: No such file or directory (2) in /home/cableop2/public_html/admin/index.php on line 13

Warning: session_start() [function.session-start]: Cannot send session cache limiter - headers already sent (output started at /home/cableop2/public_html/admin/index.php:13) in /home/cableop2/public_html/admin/index.php on line 13

Warning: Cannot modify header information - headers already sent by (output started at /home/cableop2/public_html/admin/index.php:13) in /home/cableop2/public_html/core/cms.php on line 1780

Warning: Cannot modify header information - headers already sent by (output started at /home/cableop2/public_html/admin/index.php:13) in /home/cableop2/public_html/core/cms.php on line 1782

Warning: Unknown: open(/home/tmp/sess_b3b461ba78c848d91f4e41946b369592, O_RDWR) failed: No such file or directory (2) in Unknown on line 0

Warning: Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/home/tmp) in Unknown on line 0
-------------------------------------------------------------

**Comment by fuzegit** [comment]
1. У вас первая ветка, тикет вы написали для второй.
2. Другие каналы для того, чтобы задать вопрос - очевидно это официальный сайт CMS.
> и мне дешевле будет поручить программисту перенести сайт на Битрикс, чем оплачивать ему поиски корня данной проблемы. 

конечно, проще не думая написать, чтобы с вашим сайтом разобрались бесплатно, особенно с проблемой, никак не связанной с CMS. Потому что проблема в некорректно настроенном сервере, о чем пишут ваши же приведенные ошибки. Решение проблемы в том, чтобы обратиться в техподдержку хостинга с просьбой правильно настроить php, а именно директорию для сессий.
С вас 20000 рублей. Дешевле, чем перейти на Битрикс, как просили.
