### ISSUE TITLE
InstantCMS не работает, техподержка в помощи грубо отказывает

### ISSUE THREAD

**Issue by InstantCMSsuxx** [instantsoft/icms2#697]
Поскольку в предыдущей ветке мне нагрубили, и ветку тут же трусливо закрыли, во избежание ответа, придется начать новую. История переписки старой ветки ниже. Всем, кому интересно качество работы InstantCMS, рекомендую изучить. А в целом, конечно, не люблю флудить, но все время вынуждают. Итак....

> Другие каналы для того, чтобы задать вопрос - очевидно это официальный сайт CMS.

На официальном сайте CMS я не нашел каналов связи кроме форума. Чтобы задать вопрос на форуме, нужно сначала повысить карму или что-то вроде того, точно не помню. Но смысл видимо в том, что прежде чем задать свой вопрос, я должен сначала обильно пофлудить в других темах. И сделано это в целях борьбы со спамом. Я всегда считал, что в борьбе с спамом помогает модератор, а не флуд, но видимо я что-то не понимаю.

> конечно, проще не думая написать, чтобы с вашим сайтом разобрались бесплатно

Во-первых, конечно, проще грубить людям, особенно по интернету, чем самому подумать. Где в моем посте написано, что я прошу бесплатно чинить сайт? Покажите.
Во-вторых, у меня есть сведения, что совсем недавно CMS работала. То есть изначально все было настроено правильно. А затем, без всякой видимой причины, без изменения настроек сайта и хостинга, работать она перестала. Поэтому я и пытаюсь найти специалистов, чтобы они не только исправили проблему, но и нашли причину её возникновения. Или подразумевается, что это нормально, когда админ-панель вдруг перестает работать, и каждый раз нужно просто платить 20 000 руб.?

И, кстати, по поводу...

> С вас 20000 рублей

А почему не 100 000? Есть какое-то обоснование под этой цифрой? К примеру тех. поддержка Битрикс стоит 2500 рублей в час (программисты уровня Senior Developers если что), итого за эту сумму я могу заказать 8 часов техподдержки Битрикса. И что, вы хотите сказать, что на настройку хостинга под вашу CMS требуется 8 часов? Или этим у вас будет заниматься программист уровня выше Senior? Или может быть весь ваш проект построен на том, что сама CMS бесплатная, и с трудом работающая, но по драконовским тарифам вы её допилите на месте? Типа мы вам подарим автомобиль, платите только за обслуживание. Но забыли сказать, что автомобиль - это прогнившая шоха, а обслуживание стоит как за Мерседес.
Нет уж, спасибо, но я лучше найму своего программиста, чтобы он перенес сайт либо на Битрикс, либо на  Джумлу, по выбору клиента. Первое немного дороже на стадии внедрения, зато куда дешевле в обслуживании, и несравнимо надежнее (по крайней мере случаев отказа админ-панели за последние лет 10 я не видел). Второе не многим хуже (а скорее всего вообще ничем) вашего "решения", зато куда дешевле.
Не трудитесь отвечать, уведомления с этого аккаунта я поставлю на автоматическое удаление. Общаться с вами мне не о чем.

**Первая ветка переписки:**
Используемая версия InstantCMS: Неизвестно

Версия PHP: 5.3

Как воспроизвести проблему:

Зайти на URL админ-панели http://www.***.ru/admin/login.php

Ввести логин и пароль.

Воспроизводится ли проблема на демо http://demo.instantcms.ru/: НЕТ

После авторизации получаем ошибку, текст ошибки ниже. Это не баг, это скорее разовая ошибка, возможно даже вызванная какими-то неправильными действиями администратора. Но я вынужден написать об этом здесь, ПОСКОЛЬКУ других каналов техподдержки я не нашел. Дело в том, что мне передали сайт с уже неработоспособной админ-панелью, и мне дешевле будет поручить программисту перенести сайт на Битрикс, чем оплачивать ему поиски корня данной проблемы. Поэтому очень прошу помочь с решением. Заранее большое спасибо!

Текст ошибки:
Warning: session_start() [function.session-start]: open(/home/tmp/sess_b3b461ba78c848d91f4e41946b369592, O_RDWR) failed: No such file or directory (2) in /home/cableop2/public_html/admin/index.php on line 13

Warning: session_start() [function.session-start]: Cannot send session cache limiter - headers already sent (output started at /home/cableop2/public_html/admin/index.php:13) in /home/cableop2/public_html/admin/index.php on line 13

Warning: Cannot modify header information - headers already sent by (output started at /home/cableop2/public_html/admin/index.php:13) in /home/cableop2/public_html/core/cms.php on line 1780

Warning: Cannot modify header information - headers already sent by (output started at /home/cableop2/public_html/admin/index.php:13) in /home/cableop2/public_html/core/cms.php on line 1782

Warning: Unknown: open(/home/tmp/sess_b3b461ba78c848d91f4e41946b369592, O_RDWR) failed: No such file or directory (2) in Unknown on line 0

Warning: Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/home/tmp) in Unknown on line 0

У вас первая ветка, тикет вы написали для второй.
Другие каналы для того, чтобы задать вопрос - очевидно это официальный сайт CMS.
и мне дешевле будет поручить программисту перенести сайт на Битрикс, чем оплачивать ему поиски корня данной проблемы.

конечно, проще не думая написать, чтобы с вашим сайтом разобрались бесплатно, особенно с проблемой, никак не связанной с CMS. Потому что проблема в некорректно настроенном сервере, о чем пишут ваши же приведенные ошибки. Решение проблемы в том, чтобы обратиться в техподдержку хостинга с просьбой правильно настроить php, а именно директорию для сессий.
С вас 20000 рублей. Дешевле, чем перейти на Битрикс, как просили.

**Comment by fuzegit** [comment]
Уважаемый InstantCMSsuxx (отличный никнейм кстати).

Во-первых, вам никто не грубил. Во-вторых, я вам написал корректно, что здесь не место решать проблемы своего сайта, это не форум и не место **подобного** общения. В-третьих, проблемы, кому вам проще заплатить, ну явно к нам не относятся, если вам проще перевести сайт на Битрикс, в чем проблема? Иначе к чему вы эту информацию написали здесь. В-четвертых. На официальном сайте есть раздел фрилансеров, выбрав из которых, вы за скромную сумму решили бы свою проблему. В-пятых, можно было найти примерную с вашей проблемой тему на форуме и написать в ней свой вопрос.

> ветку тут же трусливо закрыли

Т.е. вы это расценили как "трусливо", вместо того, чтобы понять, что вы не правы. Ок.

> Где в моем посте написано, что я прошу бесплатно чинить сайт? Покажите.

Где написано, что вы ищите исполнителя? И даже если бы вы это написали, то повторяю, здесь не место поиска исполнителей, если вы не в курсе.

> А почему не 100 000? Есть какое-то обоснование под этой цифрой? К примеру тех. поддержка Битрикс стоит 2500 рублей в час (программисты уровня Senior Developers если что), итого за эту сумму я могу заказать 8 часов техподдержки Битрикса. И что, вы хотите сказать, что на настройку хостинга под вашу CMS требуется 8 часов? Или этим у вас будет заниматься программист уровня выше Senior?

Наверное, потому, что я парировал на ваши слова "мне дешевле будет поручить программисту перенести сайт на Битрикс, чем оплачивать ему поиски корня данной проблемы", а не выставлял вам реальный счет.

Самое интересное, что я дал вам ответ на ваш вопрос и написал в чем проблема и как ее решать. В ответ, вы обложили CMS (которая не при чем в вашей проблеме) и иже с ней, не понравился вам ответ. Так  кто хамит в итоге?
