### ISSUE TITLE
Добавить хук content_form

### ISSUE THREAD

**Issue by narochnyi** [instantsoft/icms2#699]
Необходимо добавить хук:
list($form, $item)  = cmsEventsManager::hook("content_form", array($form, $item));
Чтобы можно было выводить данные во всех формах контента!

Сейчас есть только для определенного контента
list($form, $item)  = cmsEventsManager::hook("content_{$ctype['name']}_form", array($form, $item));

**Comment by fuzegit** [comment]
такой хук есть
https://github.com/instantsoft/icms2/blob/master/system/controllers/content/frontend.php#L801

**Comment by narochnyi** [comment]
Прошу прощения за не внимательность!
