### ISSUE TITLE
Добавление записей типов контента в закладки

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#70]
Очень удобно пользоваться разделом дополнений, т.к в нем есть закладки, также как и у официального форума движка. Позволяет быстро найти нужную запись.
 Надеюсь в следующем релизе будет также в дефолте, тем более что в дополнениях уже есть предложение реализации.

**Comment by Maratakziaplus** [comment]
Поддерживаю, очень необходимая функция
