### ISSUE TITLE
Настройка длины текстового поля

### ISSUE THREAD

**Issue by ermakover** [instantsoft/icms2#701]
**Используемая версия InstantCMS**: 2.8.2

**Версия PHP**:  5.6

Прошу о возможности указывать в настройках текстового поля и поля HTML контента минимальную и максимальную длину поля в символах с указанием сколько ещё нужно написать для того, чтобы контент можно было сохранить.

А то вот стал людям платить за записи в блогах. Они одно предложение напишут, мне либо удалять, либо платить, потому что пока нет возможности возвращения на модерацию.

**Comment by iAndroS** [comment]
Да, также столкнулся с такой задачей, но только вот проблема - там же считаются символы исходного кода (в html). Наверное, не получится реализовать адекватный подсчет символов. Разработчикам, конечно, виднее, но в принципе, это правильная мысль. Хотя бы даже минимальное количество символов с учетом html символов можно было бы задать, и то польза какая-то была бы.
