### ISSUE TITLE
Дополнительные пользовательские проверки при (перед) установке дополнений

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#704]
В установщике дополнений можно до установки проверить наличие дополнений или версии движка.
Не помешал бы hook для пользовательской проверки.

Например мне уже несколько раз нужно было сделать проверки и при отсутствии не продолжать установку:
- Проверял наличие того или иного шаблона
- Если ли необходимый тип контента
- Имеется ли нужное поле.

Проверки эти нужны были. Так как при отсутствии чего либо сайт падает.

**Comment by Val-Git** [comment]
Если вы хотите проверить наличие шаблона, какого либо типа контента или поле не говорит ли это о том, что ваше дополнение сделано как-то не универсально? Я предполагаю что дополнение должно одинаково работать на любом шаблоне и любом типе контента. Набор стандартных полей легко определяется по версии движка, а дополнительные поля должны быть внутри дополнения или на крайний случай можно определить по наличию или отсутствию файла этого поля. Но, повторюсь, дополнение считаю должно быть универсальным! Ему фиолетово какой стоит шаблон у пользователя или какие типы контента у него в системе

**Comment by fuzegit** [comment]
http://docs.instantcms.ru/dev/packages#%D0%B1%D0%BB%D0%BE%D0%BA-depends

**Comment by krylos** [comment]
> что ваше дополнение сделано как-то не универсально
Исключения все таки бывают. И не обязательно с моими компонентами.
Для примера установочные пакеты для тем InThemer
- Нужно сообщить пользователю что InPlayer не установлен
- При отсутствии нужного типа контента имеющегося в теме сайт падает
Таких примеров можно дать полно и с другими компонентами. Поэтому не нужно перебирать все возможные случаи а дать перед установкой например выполниться файлу start.php (его нет это я щас придумал) в котором можно вручную сделать проверки и при необходимости остановить установку или продолжить. Если же файл install.php который выполняется после закачки файлов. Логично что можно сделать аналогичный и для выполнения перед установкой и закачкой.

> depends
читал я это. по этому вопросу там ничего не написано. если он принимает значения template, ctype_name и fields - то вопрос может быть исчерпан.

**Comment by fuzegit** [comment]
Так в установщике дополнения в install.php делайте нужные вам проверки и не устанавливайте дополнение, возвратив false или же текст ошибки, который и будет показан пользователю.

**Comment by krylos** [comment]
> Так в установщике дополнения в install.php делайте

Думал он выполняется в конце, после закачки файлов и исполнения install.sql
тогда вопрос закрыт.
