### ISSUE TITLE
SEO для записей

### ISSUE THREAD

**Issue by iton1** [instantsoft/icms2#707]
Используемая версия InstantCMS 2.9.0

Есть генератор seo тегов для записи, **но не предусмотрена функция замена тегов на всех записях определенного компонента автоматический ну или нажатие на кнопку замены тегов**.

Сейчас получается так, чтобы заменить теги генератором в существующих записях, нужно зайти в каждую запись и пересохраниться, это проблематично если записей много или со временем у поисковиков изменятся правила формирования тегов и придется их переписывать(опять заходить в каждую запись и пересохранять).

![default](https://user-images.githubusercontent.com/17750649/34669391-74a8fad2-f482-11e7-87f9-00506f6095dc.png)

**Comment by iAndroS** [comment]
Уже неоднократно поднималась тема о необходимости массового update записей в типах контента. Иногда пересохранять записи нужно и для других задач, не только с целью мета-теги перезаписать?, но и любые другие. Это или компонент отдельный должен быть, или в ядре реализовано.
