### ISSUE TITLE
updateFiltered

### ISSUE THREAD

**Issue by pin-git** [instantsoft/icms2#708]
**Используемая версия InstantCMS**: 2.9.0

**Версия PHP**: 5.5.38, 5.6.31

**Версия MySQL**: 5.5, 5.6, 5.7

**Как воспроизвести проблему**:

в `model.php` используем `$this->updateFiltered()`, в начале и середине таблицы отрабатывает, последнюю запись не изменяет, но при этом отдаёт `true`.

`/system\core\model.php => 524 => cmsModel->updateFiltered()
UPDATE cms_test i SET 'is_current' = 1 WHERE (i.user_id = '1') AND (i.item_id = '3')`

**Comment by fuzegit** [comment]
Я не понял суть проблемы. Границы таблиц в базе данных относительны. Поясните или сформулируйте иначе. updateFiltered изменяет то, что вы её укажите. В приведённом запросе 'is_current' должно быть в обратных аппострофах, а не в кавычках.

**Comment by pin-git** [comment]
апострофы нормальные, исправил в связи с форматированием текста на данном ресурсе.

вышло "с больной головы на здоровую", разобрался, причина ошибки невнимательность

**Comment by fuzegit** [comment]
> разобрался, причина ошибки невнимательность

Бывает и такое) Тогда закрываю тикет.
