### ISSUE TITLE
Разный Title для разных страниц контента

### ISSUE THREAD

**Issue by narochnyi** [instantsoft/icms2#709]
Привет! 

Думаю что будет полезным, в плане SEO, сделать добавление в Title номера текущей страницы.

Потому что сейчас у таких страниц как:

> /articles?page=2
> /articles?page=3
> ...
> /articles?page=№

Заголовки одинаковые, а по сути, это разные страницы!

**Comment by iton1** [comment]
А зачем в title добавлять номера страниц? что это нам даст

**Comment by narochnyi** [comment]
Потому что, получается у нас много разных страниц, с одним и тем же заголовком, а в SEO это не комильфо!

**Comment by iton1** [comment]
Ну это как вариант добавить в title номер страницы, еще есть атрибут rel="canonical" который используют для страниц листинга - это скорей всего правильнее вариант.

https://yandex.ru/support/webmaster/controlling-robot/html.html#canonical
https://support.google.com/webmasters/answer/139066?hl=ru

Как правило в поиске продвигают  страницу /articles , а на страницах листинга(пример: /articles?page=2 и т.д.) прописывают атрибут rel="canonical" , это можно проверить в выдаче поисковых систем.

**Comment by SergeyRN** [comment]
Правильно добавлять номера страниц, Вы указали ссылки на страницы из Гугла и Яндекса. Там указано как правильно применять rel="canonical".

Он применяется когда ОДНА И ТА ЖЕ страница открывается по разным адресам, а с помощью  rel="canonical" можно указать какой  именно УРЛ каноничный (правильный)...
