### ISSUE TITLE
Работа хука user_delete в компонента images. Правильно?

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#714]
По какой то логика (уверен она есть) папки upload пользователей создаются в подпапках 000, 001, 002, 003 и т.д.

В указанном в заголовке хуке при удалении пользователя удаляется папка ...../upload/u1, где 1 - id пользователя. А такой папки нет, так как папка пользователя находится в подпапке 000

Или я не разобрался в логике или хук работает не правильно, т.к. должна удаляться папка ..../upload/000/u1 так как именно в ней папка пользователя а не в просто upload.

**Comment by nomad48** [comment]
Могу добавить к этому, что при удалении профиля, фотоальбомы и фото пользователя не скрываются и через них можно спокойно попасть в профиль к удалённому юзеру.
Пример: профиль у далён: 
![13-01-2018 20-29-10](https://user-images.githubusercontent.com/9349934/34908419-8c20f8e6-f8a0-11e7-8cda-8a66f01d8cf3.jpg)
Фотоальбомы и фото на месте:
![13-01-2018 20-29-22](https://user-images.githubusercontent.com/9349934/34908428-9af920d2-f8a0-11e7-91c6-cb08497d386d.jpg)

Пример: https://lovelovely.ru/albums/49-zhenka.html
