### ISSUE TITLE
Редирект с www в .htaccess

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#715]
Добавить в сборку (опционально закомментированные) строки для редиректа сайта с www на без.
Большинству сайтов это нужно, приходится дописывать.

Там же есть редирект на https, почему бы и этому не быть ...

**Comment by Alex-HAV** [comment]
Потому что везде используются разные методы, дописать же не проблема
https://www.reg.ru/support/hosting-i-servery/sajty-i-domeny/kak-dobavit-redirekt/kak-nastroit-pereadresatsiyu-na-domen-bez-www
