### ISSUE TITLE
Администратор не может опубликовать материал, находящийся в черновике другого пользователя

### ISSUE THREAD

**Issue by rubesslov** [instantsoft/icms2#719]
**Используемая версия InstantCMS**: 2.9.0

**Версия PHP**:  5.4.16

**Как воспроизвести проблему**:

1. от имени пользователя создать материал и добавить в черновики
2. Перезайти от имени администратора (впрочем, периодически и у того же пользователя прав не хватает, закономерность не отловил)
3. Кнопки "Опубликовать" - нет (вернее она есть, но в боковом меню, тем не менее - она не работает)

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

Этот текст можно стереть, если вы сообщаете не о баге, а пишите пожелание/предложение.

**Comment by rubesslov** [comment]
Я это наблюдаю в функционале фотоальбомов (они у меня самые частоиспользуемые)

**Comment by fuzegit** [comment]
Из черновиков администратор и не должен иметь прав публиковать. Не стоит путать черновики и модерацию.
