### ISSUE TITLE
Ссылка в уведомлении о доработке контента - ведёт на главную

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#720]
**Используемая версия InstantCMS**: 2.9.0

**Версия PHP**: 5.4.38

**Как воспроизвести проблему**: Ссылка в уведомлении о доработке контента - ведёт на главную, а не на возвращённый материал. 

* первый шаг: Юзер добавляет материал и отправляет на модерацию, 
* второй шаг: админ или модератор проверяет и возвращает материал для доработки. 
* третий шаг: юзер получает сообщение о возврате материала
* четвертый шаг: открывает уведомление на сайте
* пятый шаг: нажимает на ссылку на свой материал, она ведет на главную, а не на его материал.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

![19-01-2018 12-18-10](https://user-images.githubusercontent.com/9349934/35143756-83877c92-fd13-11e7-9381-84318379660d.jpg)

**Comment by nomad48** [comment]
Уточнение по комиту, ссылка на материал подтягивается от той страницы, на которой открыто уведомление.

**Comment by fuzegit** [comment]
На текущей версии отсюда проблема решена, проверьте

**Comment by nomad48** [comment]
я если честно, не могу найти какие правки внести из комита...

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/230e81f871e5f9bd83fa8586a4acb56e73d3fa87#diff-37606cfe33fb6a7b0e019835ba77b34dR51

**Comment by nomad48** [comment]
@fuzegit да, спасибо, сейчас нормально!
