### ISSUE TITLE
"Новые комментарии" добавить возможность выбора типа контента

### ISSUE THREAD

**Issue by Jestik** [instantsoft/icms2#725]
Виджет "Новые комментарии", предлагаю добавить возможность выбора типа контента из которого показывать комментарии, в идеале еще и категории.

Например для показа последних обсуждений по теме материала в конце страницы.

**Comment by iAndroS** [comment]
Поддерживаю! Если у меня разносторонний сайт, как-то нехорошо в разделе о беременности показывать комментарии из раздела сайта о способах построения нейронных сетей в космонавтике )
