### ISSUE TITLE
Шаблон генерации META-описаний к записям - не работает строковое поле

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#728]
**Используемая версия InstantCMS**: 2.9

Предустановленный тип контента новости.
Вставляю в настройках типа контента в поле "Шаблон генерации META-описаний" значение строкового поля {teaser}, галочка "Автоматическая генерация META-описаний" установлена.

В результате генерируется в дескрипшне записи дескрипшн из блока "SEO по умолчанию"

Считаю, что строковое поле анонса новости идеально бы подходило под такую задачу, как формирование дескрипшна записи ввиду своей небольшой длины и отсутствия лишних тегов.

**Comment by mafru** [comment]
Скорее всего в настройках контента у вас отключен вывод поля в записях, поэтому он не участвует в генерации seo. Включите вывод в записи и сделайте его доступным для просмотра только для группы Администраторов и все будет работать.

**Comment by asnenne** [comment]
Правильнее было бы игнорировать в СЕО-настройках настройки доступа для чтения. Сейчас путаница. Есть поля, которые заполняются только для СЕО, зачем их видеть админу при просмотре записи.
