### ISSUE TITLE
Не работает "Сайт доступен только авторизованным пользователям"

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#729]
**Используемая версия InstantCMS**: 2.9

Сайт выключен на техобслуживание. Хотел предоставить доступ только админам и модерам, пока других пользователей нет. Выставил галочку "Сайт доступен только авторизованным пользователям", но данная функция не работает - пускает только админа

**Comment by fuzegit** [comment]
http://www.instantcms.ru/novosti/release290.html

> Доступ к отключенному сайту можно ограничивать по группе пользователя (раньше только для администраторов);
