### ISSUE TITLE
Подписка на новые материалы типов контента на e-mail

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#73]
Для информационных сайтов очень полезное дополнение. Можно встретить на воржпресс, битрикс и прочих системах, т.к позволяет значительно расширить аудиторию и ее охват, а также увеличить лояльность аудитории.
Также было бы полезно под каждым виджетом подписки выводить количество подписчиков.

В письме раз в день или раз в 3 дня отправлять анонсы самых читаемых за это время материалов, либо опционально в настройках компонента указывать - отправлять выбранные администратором анонсы, или отправлять из набора.

**Comment by globator88** [comment]
Еще можно сделать для пользователей подписка по определенном параметром. На пример для объявлений, при добавлении автомобиля по выбранном заранее пользователем критериям приходить оповещение на email.
Хотя бы сделать отдельным компонентом, так как в коробку вряд ли это можно добавить.

**Comment by vlad7090** [comment]
> да, было бы полезно как отельный компонент

**Comment by EnotAlex** [comment]
к примеру, пользователь фильтрует объявления, а тут ему пишет что таких объявлений нет и предлагается нажать на кнопку "Подписаться", для того чтобы если вдруг появятся подобные объявления  (подходящие под данный фильтр), то ему придёт уведомление на email.
Когда он нажимает на кнопку "Подписаться" в специальную таблицу типо cms_board_search_x летят параметры сортировки.
В сам момент добавления объявление можно сверять эти объявление с параметрами из таблицы cms_board_search_x и при успехе отправлять уведомление на мыло.
в общем как-то так ..
