### ISSUE TITLE
SEO по-умолчанию (ошибка в title)

### ISSUE THREAD

**Issue by iton1** [instantsoft/icms2#731]
InstantCMS v2.9.0 

Все повторил на  демо http://demo.instantcms.ru/ и ошибка появилась

**В корневой категории типа контента в браузере в title выводится переменная из категории "SEO по-умолчанию", а не слова.**

1) Если на сайте выключены или нет наборов 

![default](https://user-images.githubusercontent.com/17750649/35353965-d3e7faf0-0159-11e8-909c-806c90f72b60.png)

2) В типе контента в "SEO по-умолчанию" в "Тайтл страницы" прописываем переменную {title}

![default](https://user-images.githubusercontent.com/17750649/35354026-fa173e5c-0159-11e8-9cad-45afd88b55db.png)

3) В корневой категории в title выводится {title} — InstantCMS 2 демо сайт , урл http://demo.instantcms.ru/articles

![default](https://user-images.githubusercontent.com/17750649/35354153-49b4ee50-015a-11e8-82a3-b732d93eed17.png)

p.s. в категориях к примеру http://demo.instantcms.ru/articles/marketing с title все в порядке.

**Comment by fuzegit** [comment]
В этих параметрах нельзя указывать переменные
