### ISSUE TITLE
Проблема с виджетами при замене URL типа контента

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#732]
**Используемая версия InstantCMS**: 2.9.0

1. Создаем тип контента TYPE
2. Привязываем к нему виджет КАТЕГОРИИ
3. Переопределяем название типа контента по этой инструкции http://docs.instantcms.ru/manual/settings/rewriting
4. Виджет категорий перестает отображаться. Полагаю, любой виджет, привязанный к данному типу контента перестает отображаться, только которые ко всем страницам сайта работают

**Comment by fuzegit** [comment]
В чём ошибка? После переопределения названия страницы очевидно нужно изменить.

**Comment by iAndroS** [comment]
Какой страницы? Речь идет о типе контента ведь. Если вы имеете в виду переставить виджет, то я безуспешно это делал.

**Comment by fuzegit** [comment]
Вы в разделе виджеты и страницы были в админке? 
http://docs.instantcms.ru/manual/widgets/pages

**Comment by iAndroS** [comment]
О, по маске url не сообразил что-то перенастроить виджет, благодарю! 
То есть, страница виджетов компонента по сути в базе пишется реальный url компонента, к которому привязываются виджеты, выходит так? И все же это неочевидно, видя необходимые казалось предустановленные страницы виджетов )))
