### ISSUE TITLE
Сделать чекбокс в настройках "Сайт работает на https"

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#733]
**Используемая версия InstantCMS**: 2.9

Проблема давняя. Если решил настраивать сайт на работу по SSL, то приходиться ручками править htaccess и лезть в конфиг-файл, чтобы сменить протокол ручками, затем генерировать карту сайта.
Было бы на порядок удобнее, если в настройках сайта была такая галочка в наличии, позволяющая избегать лишних телодвижений, о наличии которых неопытный пользователь может и не догадываться.

**Comment by fuzegit** [comment]
Ничего не нужно делать, всё распознаётся автоматически. Вы не предлагайте решения (весьма сомнительные), а описывайте проблему.

**Comment by iAndroS** [comment]
Ни разу автоматически не распознался url карты сайта. Переходишь по адреса https://site/sitemap.xml и видишь в нем ссылки на карты типов контента с префиксами http://

**Comment by fuzegit** [comment]
Вот я и спрашиваю, опишите, где протокол некорректен.

**Comment by fuzegit** [comment]
Ну раз пояснять вы не хотите, вынужден закрыть тикет.
