### ISSUE TITLE
Проблема с отправкой email

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#734]
**Используемая версия InstantCMS**: 2.9

**Версия PHP**:  5.6.30-0+deb8u1

**Как воспроизвести проблему**:

* в настройках компонента "Авторизация и регистрация" ставим галочку "Требовать подтверждения e-mail при регистрации"
* Пытаемся регаться с email, письмо не приходит
* Ждем сколь угодно долго - письма нет
* Удаляем аккаунт, ждем опять сколько угодно времени - писем нет
* Регаем новый акк с тем же email и другим именем (для наглядности теста)
* Моментально приходит письмо, которое должно было отправиться предыдущему пользователю! (проверял вышеописанные шаги 2 раза, сработали одинаково!)
* Также не приходят письма-уведомления о новых сообщениях в ЛС (на 2.8.2 на другом сайте приходят моментально)

Тестовые письма с раздела настроек сайта приходят сразу. На этом же сервере 2 сайта на разных конфигурациях php но на версии 2.8.2 движка отрабатывают как часики все почтовые уведомления.

**Comment by nomad48** [comment]
Замечаю задержку с доставкой сообщений и уведомлений на email до нескольких минут. Использую SMPT Яндекс, SSL. Проверял на тестовых юзерах, Уведомление на сайте приходит моментально, а уведомление на email приходит с задержкой. Ранее приходило моментально.

**Comment by fuzegit** [comment]
В случае с задержкой отправки:

![_211](https://user-images.githubusercontent.com/13233234/35432285-a0916550-0290-11e8-9405-f828e3ec23d3.png)

![_212](https://user-images.githubusercontent.com/13233234/35432286-a0afc8ce-0290-11e8-9da5-c2d8edf50654.png)

Либо настраивайте правильно почту. Никаких проблем с механизмом почты нет.

**Comment by nomad48** [comment]
@fuzegit так что надо, отключить или включить наоборот?

**Comment by fuzegit** [comment]
Если нужна очередь, включить, иначе - выключить. При выключенной опции письма будут отсылаться сразу, даже если их нужно отослать очень много (например при подписках).

**Comment by nomad48** [comment]
@fuzegit я понял спасибо.

**Comment by iAndroS** [comment]
@fuzegit у меня именно как у вас на скриншотах настройки (((
При этом понимаю, что разом все письма отправлять не есть гуд - можно и в спамеры попасть...
Почта же позже пришла пачкой почему-то!..
Почему на других сайтах на 2.8.2 при тех же условиях и настройках почта работает сразу? Как-то можно продиагностировать причину сего странного поведения?

**Comment by fuzegit** [comment]
Читайте описание в новостях к обновлениям. И решайте проблемы на форуме, а не здесь.

**Comment by iAndroS** [comment]
На всякий случай добавлю сюда ссылку на форум http://www.instantcms.ru/forum/thread28964-1.html
