### ISSUE TITLE
БАГ: неправильно генерируется автоссылка для поля Список: мультивыбор

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#735]
**Используемая версия InstantCMS**: 2.9.0

**Версия PHP**:  5.6

**Как воспроизвести проблему**:

На примере типа контента Страницы.

1. Создаем поле Список: мультивыбор (системное имя, например, field) со значениями:
     пылесос
     телевизор
     бутерброд
2. Разрешаем показ этого поля в фильтре, стоит галочка "Мультивыбор чекбоксами".
3. Включаем опцию "Автоссылка".
4. Добавляем запись, выбираем любые значения из этого списка. 

Значения преобразовываются в ссылки, которые ведут на 404 страницу. Они имеют такой вид:
http://example.com/pages?field=1
http://example.com/pages?field=2
http://example.com/pages?field=3

Не знаю, как должны выглядеть эти ссылки, подозреваю, что как-то так:
http://example.com/pages?field=пылесос
http://example.com/pages?field=телевизор
http://example.com/pages?field=бутерброд

Но те, которые генерируются, ведут в никуда.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: НЕТ, потому что функция "Автоссылка" в этом типе поля на демо отключена.

**Comment by fuzegit** [comment]
Вы для типа контента "Страницы" включите опцию "Просмотр списка на сайте включен".
Ссылки указанные вами в начале - верные. Всё работает корректно.

**Comment by asnenne** [comment]
> для типа контента "Страницы" включите опцию "Просмотр списка

Блин, точно. Простите, затупил. Всё работает корректно.
