### ISSUE TITLE
Инструкция - как сломать сайт на iCMS 2.9

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#736]
**Используемая версия InstantCMS**: 2.9

1. Удалите группу пользователей Администраторы
2. Профит!

Вывод: нужно запретить удаление групп пользователей, как это сделано у системных типов контента.

**Comment by fuzegit** [comment]
> Вывод: нужно запретить удаление групп пользователей, как это сделано у системных типов контента.

Неверный вывод. Правильный вывод, убирать у всех пользователей удалённую группу.
