### ISSUE TITLE
Новый интерфейс панели администрирования

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#738]
От версии к версии часть недочетов уходит, но в целом они остаются - управлять сайтом с мобильных устройств практически невозможно :( думаю именно в связи с этим большая часть CMS имеют вид, в котором основные инструменты управления находятся слева, а сам контент и настройки справа, т.к это наиболее удобный вариант как на ПК (хотя админка на ПК у инстанта полностью адекватно себя ведет и интуитивно понятная), но всеже некий подобный вид http://fusetheme.com/assets/images/homepage/angular/dashboard.png стал неким стандартом и адаптировать его гораздо проще.

**Comment by iAndroS** [comment]
У меня с мобильника в вертикальном положении не видно админ-меню совсем, а в горизонтальном - не видно пункта меню "Пользователи" )
