### ISSUE TITLE
Обтекание изображений текстом

### ISSUE THREAD

**Issue by gLokS** [instantsoft/icms2#74]
Уважаемые разработчики, сделайте, пожалуйста, чтобы в типах контента, таких как: новости, статьи, блоги, изображения обтекались текстом по умолчанию. Я имею ввиду стандартный загрузчик изображений, а не при помощи сторонних редакторов. Ну и еще было бы замечательно, чтобы при нажатии на эти изображения они открывались бы в оригинальном размере во всплывающем окне (плагин ColorBox по-моему называется).

**Comment by fuzegit** [comment]
http://demo.instantcms.ru/news/9-rossijane-stali-pervymi-na-chempionate-mira.html

все обтекается

**Comment by gLokS** [comment]
Извиняюсь,в новостях и блогах действительно есть обтекание. А вот в  статьях у менявот так: http://i76.fastpic.ru/big/2016/0110/2f/31ef73a6559545557879a3e8540ced2f.png

**Comment by SadKit** [comment]
Поддерживаю! 
В статьях и и при создании нового типа контента со структурой схожей со статьями текст просто идет справа или слева, согласно выравниванию, но НЕ ОБТЕКАЕТизображение.

На примере http://demo.instantcms.ru/news/9-rossijane-stali-pervymi-na-chempionate-mira.html
текст слишком короткий, чтобы заметить, что он не станет обтекать картинку снизу.

Тем не мение в новостях обтекание работает нормально.

**Comment by SadKit** [comment]
Что касается загрузчика изображений, было бы замечательно, если бы в настройках пресетов была возможность задать абсолютную величину изображение, чтобы масштабирование было не по одной стороне, а по конкретному размеру.

**Comment by gLokS** [comment]
Нет, в новостях и блогах обтекается, в статьях нет. Можете на демо посмотреть новость "Количество преступлений в России сокращается", все обтекается

**Comment by SadKit** [comment]
> Нет, в новостях и блогах обтекается, в статьях нет. Можете на демо посмотреть новость "Количество преступлений в России сокращается", все обтекается

Я про тоже, а в статьяи и новых типах контента с полем "Изрбображение" нет.

**Comment by SadKit** [comment]
Интересное наблюдение в данной проблеме. Я добавил еще одно поле, и получилось так, что основное поле текста оказалось ниже картинки и... начало ее обтекать.
Вывод: как бы это правильно сказать, выравнивание основывается на положении поля. Если поле находится сбоку от картинки, то весь тект в поле выравнивается относительно картинки, и не обтекает ее. Но если поле будет "ниже" картинки при отображении, то оно ее обтекает. Как это исправить,я не знаю.

**Comment by Maratakziaplus** [comment]
Еще лучше иметь кнопку в админке в типах контента право выбора обтекаемости текста, например: сделать текст обтекаемым "да", "нет"

**Comment by mafru** [comment]
> Вывод: как бы это правильно сказать, выравнивание основывается на положении поля. Если поле находится сбоку от картинки, то весь тект в поле выравнивается относительно картинки, и не обтекает ее.

Выравнивание, а если быть точнее отображение содержания блочного элемента основано на свойстве css - overflow. Для всех полей указанное свойство равно - hidden.
Однако для поля, являющегося соседним по отношению к полю изображение, overflow равно visible
.content_item .ft_image + .field {
    overflow: visible;
}
Вот отсюда и появляется соответствующее поведение полей.

**Comment by iAndroS** [comment]
А у меня не обтекается нигде - картинка сверху, текст идет ниже. Шаблон сторонний. Думаю, это не проблема iCMS, а конкретно стилей шаблона.
