### ISSUE TITLE
Другие поля в свойствах. Добавить свое поле.

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#745]
В свойствах можно добавить следующие поля: list, list_multiple, string, color, number, checkbox
Добавить возможность добавления и других полей системных, в том числе и тех которые установлены от сторонних разработчиков.

**Comment by Loadir** [comment]
Лучше обычным полям добавить зависимость от категорий контента.

**Comment by krylos** [comment]
Думал про это.
А теперь представьте список полей если у вас 10 категорий и в каждой 10 подкатегорий и в каждой разные свойства.
Какой будет список полей? Как эти поля корректно отображать в фильтре, который подстраивается из свойств конкретной категории.

**Comment by Loadir** [comment]
> Какой будет список полей?
Такой же как и сейчас список свойств. Добавить в грид списка полей фильтр по категориям или т.п.

> Как эти поля корректно отображать в фильтре
Если поле доступно в категории, его выводить и в фильтре на странице этой категории. Так же как сейчас работают свойства.
