### ISSUE TITLE
Расширить числовое поле

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#748]
По умолчанию, числовое поле создается как float что позволяет сохранять как целые так и дробные числа. Так вот где проблемы при сохранении чисел, для примера представим что это поле для "цены" записи:

Сохраняем число: 49999 - сохраняется нормально
Сохраняем число: 49999.01 - выдает ошибку "Слишком длинное значение (макс. длина: 7)"

Может в числовом поле лучше не пол-ву знаков проверять а по самому числу: Между этими числами  разница в одну сотую, а сохранить никак. Понимаю и даже знаю как это обойти, но может все таки исправить системно? Строковые поля считать по кол-ву знаков, числовые по числу.

**Comment by fuzegit** [comment]
![_228](https://user-images.githubusercontent.com/13233234/36445839-7cb3f01c-1690-11e8-8907-6e40d77173fb.png)
