### ISSUE TITLE
Не отображаются виджеты в контенте по-умолчанию

### ISSUE THREAD

**Issue by narochnyi** [instantsoft/icms2#751]
InstantCMS: 2.9.0

Привет.
Если в системе указать по умолчанию любой тип контента, например Articles, и в админке, в разделе "Виджеты и страницы", в левом меню, выбрать папку "Контент", а в ней "Статьи: Все страницы" и поставить на данную позицию виджет, он не будет отображаться на странице просмотра записи, потому что в URL не будет "articles"

**Comment by iAndroS** [comment]
А если создать пользовательскую страницу виджетов с маской /*.html?

**Comment by narochnyi** [comment]
Тогда она будет действовать для всех типов контента, а надо чтобы для Статей. Внимательнее!
