### ISSUE TITLE
При удалении фото средствами редактора, сам файл изображения теперь НЕ удаляется с сервера

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#752]
**Используемая версия InstantCMS**: 2.9.0

**Версия PHP**:  5.4.38
**Как воспроизвести проблему**: Попробовать удалить фото средствами редактора, сам файл изображения почему-то не удаляется с сервера;

В релизе 2.8.0 была добавлена хорошая функция, в данный момент на 2.9.0 она не работает.
пошагово: Имеем картинку в теле статьи
![10-02-2018 11-13-01](https://user-images.githubusercontent.com/9349934/36060188-8979189c-0e55-11e8-8438-f7134226a7df.jpg)
![10-02-2018 11-13-26](https://user-images.githubusercontent.com/9349934/36060189-899a4e22-0e55-11e8-892e-175523cc274a.jpg)
![10-02-2018 11-14-34](https://user-images.githubusercontent.com/9349934/36060190-89b9f7a4-0e55-11e8-8bd4-9ec7ad967224.jpg)
![10-02-2018 11-14-55](https://user-images.githubusercontent.com/9349934/36060191-89da1606-0e55-11e8-8757-4c2add698198.jpg)
![10-02-2018 11-15-44](https://user-images.githubusercontent.com/9349934/36060192-89fa74a0-0e55-11e8-94c2-b2a90b06aab8.jpg)
![10-02-2018 11-16-24](https://user-images.githubusercontent.com/9349934/36060193-8a19ccb0-0e55-11e8-84bb-5a27b7d174fa.jpg)
![10-02-2018 11-18-20](https://user-images.githubusercontent.com/9349934/36060194-8a3d2e3a-0e55-11e8-9299-7b3b5491d13b.jpg)
Проверял на всех типах контента. По крайней мере на 2.8.0 функция работала точно, потому что проверял именно эту функцию и всё удалялось.
Также не удаляются файлы изображений с расширением .csv у меня мапса нет, но картинки есть - например логотип Инстаграм.
**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: не смог проверить

**Comment by fuzegit** [comment]
Кэш соединения FTP обновите и кэш браузера после удаления.
Файлы прекрасно удаляются.

**Comment by nomad48** [comment]
@fuzegit 
"Кэш соединения FTP обновите и кэш браузера после удаления.
Файлы прекрасно удаляются." - я всё делал, файлы удаляются в теле статьи, но остаются на сервере. Кэш браузера чистил, а про кэш FTP первый раз слышу.

**Comment by fuzegit** [comment]
В стоковом редакторе "Redactor" файлы удаляются и с сервера, я проверил.

**Comment by nomad48** [comment]
@fuzegit у меня все файлы как в 2.9.0 я мержил.

**Comment by fuzegit** [comment]
Так я не против, что у вас по какой то причине не удаляется. Я не могу повторить у себя, всё удаляется. Чтобы исправить ошибку, если она есть, мне её нужно воспроизвести, иначе никак.

**Comment by nomad48** [comment]
@fuzegit я тестировал, выловил такую ошибку: когда удаляешь картинку из тела статьи, то в консоли
![13-02-2018 16-11-08](https://user-images.githubusercontent.com/9349934/36151549-b5a069b8-10d8-11e8-9c45-52dd54a39e6e.png)
![13-02-2018 16-14-04](https://user-images.githubusercontent.com/9349934/36151605-e8d81c54-10d8-11e8-8103-b8fa5b79568c.png)

**Comment by fuzegit** [comment]
Судя по первому скрину на урл удаления фото у вас 404.
404 возникает в файле /system/controllers/files/frontend.php в public function actionDelete(){

**Comment by fuzegit** [comment]
Ну я же вам написал, что повторить у себя я не могу, как я могу гадать, как исправить то, что у меня работает.

**Comment by nomad48** [comment]
@fuzegit куда копать не подскажите? с чего хоть начать искать?

**Comment by fuzegit** [comment]
> 404 возникает в файле /system/controllers/files/frontend.php в public function actionDelete(){

**Comment by nomad48** [comment]
@fuzegit добрый вечер, мне @Val-Git помог разобраться с проблемой. Скажите пожалуйста, а это так задумано, что картинки размещённые в контенте до релиза 2.8.0 не удаляются с сервера, а после релиза 2.8.0 удаляются. Или же предполагается что и старые картинки должны (хотя бы в теории) удаляться. Сегодня проверял и это выяснил. Спасибо.

**Comment by fuzegit** [comment]
> Скажите пожалуйста, а это так задумано, что картинки размещённые в контенте до релиза 2.8.0 не удаляются с сервера

да. потому что в новом релизе они фиксируются в базе.

**Comment by nomad48** [comment]
@fuzegit спасибо за быстрый ответ. Я понял.
