### ISSUE TITLE
Добавить упорядочивание категорий по алфавиту

### ISSUE THREAD

**Issue by dimbons** [instantsoft/icms2#753]
В АДМИНКЕ, в разделе КОНТЕНТ, в окошке ПОРЯДОК сделать кнопочку "По возрастанию" или "По алфавиту" или "А-Я". Было бы очень удобно при добавлении новой категории, отсортировать ее сразу по алфавиту, а не тащить ее через кучу папок. Очень упростит жизнь тем у кого много категорий.

**Comment by fuzegit** [comment]
это на текущей реализации невозможно
