### ISSUE TITLE
Недоработка: Модерация и лента активности

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#756]
**Используемая версия InstantCMS**: 2.9

Если материал прошел через модератора, то не публикуется в ленте активности - публикуются лишь материалы, которые разрешено публиковать на сайте без модерации.

**Comment by fuzegit** [comment]
В компоненте лента активности включите соответствующую опцию. Вы бы сначала на форуме поспрашивали что ли...

**Comment by iAndroS** [comment]
Вы думаете, я не знаю об этой элементарщине? Сколько вы уже "закрыли" таким образом запросов от пользователей, или это только на мои такая нестандартная реакция? Отбиваете все желание постить сюда, а ведь проблема действительно имеет место быть! 
Почему, если я модерацию выключаю, посты уходят в ленту активности, а если включаю, то не уходят?
Ок, усложним задачу, возможно, дело в том, что сначала модератор вернул материал на доработку, а потом уже после повторной отправки на модерацию пропустил пост. Почему его в ленте нет?

**Comment by fuzegit** [comment]
@iAndroS не придумывайте лишнего насчет реакции. Вы как описали, **по написанному я точь в точь проверил**. Всё публикуется, о чём посмел вам сообщить.

> возможно, дело в том, что сначала модератор вернул материал на доработку, а потом уже после повторной отправки на модерацию пропустил пост. Почему его в ленте нет?

Т.е. вы считаете, что последовательность ваших действий, приводящих возможно к такой ошибке, **я должен предугадать**?

Отредактируйте первое сообщение, пожалуйста, и опишите **всю последовательность действий, приводящих к ошибке**. 

Даже при добавлении здесь тикета я сделал шаблонный текст, но по-видимому написан он просто так, чтобы стереть.
![_227](https://user-images.githubusercontent.com/13233234/36443306-6b89b760-1689-11e8-9769-5abfd7808593.png)

**Comment by fuzegit** [comment]
Исправлено
