### ISSUE TITLE
Работа Uploader

### ISSUE THREAD

**Issue by antonmakasin** [instantsoft/icms2#76]
Заметил, что при загрузке файла через Uploader название загруженного файла остается исходным.
Раньше кодировалось.
Обнаружил отсутствующую строку:
$dest_file = substr(md5( $user->id . $user->files_count . microtime(true) ), 0, 8) . '.' . $dest_ext;

Вопрос разработчикам: в связи с чем данное изменение? Старая реализация имела какие-то изъяны?
Вопрос актуален, например, при загрузке файлов на кириллице - в названии иероглифы.

**Comment by fuzegit** [comment]
> Заметил, что при загрузке файла через Uploader название загруженного файла остается исходным.

да, при нативной загрузке через форму (не через ajax)

> Вопрос актуален, например, при загрузке файлов на кириллице - в названии иероглифы.

в названии файла или где? вообще движок название транслитирует. Пример покажите.
