### ISSUE TITLE
Сообщение о незаполненности поля к нему не привязано.

### ISSUE THREAD

**Issue by Yar-rus** [instantsoft/icms2#761]
**Используемая версия InstantCMS**: 2.9.0

**Версия PHP**:  УКАЖИТЕ ВЕРСИЮ

**Как воспроизвести проблему**:

* Создать запись
* Оставить незаполненным обязательное поле
* Сохранить

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

При сохранении записи у обязательного поля, если оно не заполнено, появляется модуль  с сообщением "Пожалуйста, заполните это поле". Ранее этот модуль жестко был привязан к полю. Сейчас же он остается в том месте экрана, где появился изначально, несмотря на прокрутку.

**Comment by fuzegit** [comment]
Поясните подробнее пожалуйста.

**Comment by Yar-rus** [comment]
* Создать/редактировать запись
* Оставить незаполненным обязательное поле (стираю заголовок, например)
* Сохранить. У данной пустой строки появиться сообщение "Пожалуйста, заполните это поле".
* Колесиком мышки прокручиваем - содержимое сдвигается, но поле остается на месте. Получается привязанным не к полю, а к тому месту, где появилось первый раз 

При использовании боковой прокрутки поле совсем исчезает.

**Comment by fuzegit** [comment]
Так это стандартное браузерное html5 предупреждение.
