### ISSUE TITLE
При изменении url групп, вкладка в профиле пользователя НЕ редиректит на новый адрес.

### ISSUE THREAD

**Issue by Margauza** [instantsoft/icms2#762]
**Используемая версия InstantCMS**: 2.9.0 и 2.9.1 та что сейчас на гите

**Версия PHP**:  5.4 и 7.0

**Как воспроизвести проблему**:

* первый шаг: войдя в АДМИНКА - КОМПОНЕНТЫ изменив урл компонента ГРУППЫ сохранить.
* второй шаг: Пойти в профиль пользователя, перейти по вкладке группы и убедиться что не происходит редиректа на новый урл. То есть в адресе все еще groups вместо того который мы установили в списке групп. Сами группы и всякие там наборы, перенаправляются без проблем. Хорошо бы исправить и вкладку в профиле чтобы люди не путались.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: невозможно проверить

Прилагаю скриншот для ясности (3 в одном). 
![clubs0](https://user-images.githubusercontent.com/18312974/36859859-641d1d18-1d88-11e8-8c17-4fda5b94dc10.JPG)

**Comment by fuzegit** [comment]
Это урл вкладки. Не имеет никакого отношения к урл компонента. Изменить урл вкладки можно в таблице cms_users_tabs. Ваше пожелание можно перефразировать, как "дать возможность менять урл вкладок профиля".

**Comment by Margauza** [comment]
Не нашла как удалить этот тикет, так что отредактировала. Можно ли его перевести в открытые? Спасибо.
