### ISSUE TITLE
Пустая переменная $errors

### ISSUE THREAD

**Issue by ValenokPC** [instantsoft/icms2#764]
Не могу понять если выше идет проверка, то зачем передавать в hook пустую переменную?

https://github.com/instantsoft/icms2/blob/70b102d5622e07bfbb33c506f11adea8b24b7f58/system/controllers/content/actions/item_add.php#L220

**Comment by fuzegit** [comment]
Стоит подумать, зачем так это сделано. А лучше задавать вопросы повышения квалификации на форуме.
