### ISSUE TITLE
Последний вход пользователя (запись даты в профиле)

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#765]
Ранее уже поднималась тема по поводу того что неверно записывается дата последнего входа пользователя и выяснилось с подачи fuse следующее: если пользователь входит по сессии то дата входа не обновляется, таким образом на сайте часто встречается ситуация что пользователь часто входит по сессии и дата входа не обновляется, но по факту получается так что пользователь в течении дня входит на сайт 5-10 раз с интервалом в 2-3 часа и всегда "вход проходит по сессии" то есть дата последнего входа в профиле не обновляется. Здесь вопрос не в том у кого сколько хранятся сессии на сервере а именно по этой дате. Хочется видеть реальную дату, когда пользователь стал онлайн. Человек на сайте находится не долго.
Что видим по факту: пользователя на сайте нет, последний вход был 1-2 дня назад, но даже если юзер появился онлайн и пропал, дата вода все равно "давно". 
Может логичнее обновлять эту дату в момент "добавления" записи в число пользователей онлайн?

**Comment by nomad48** [comment]
У меня после обновления до 2.10 и этого тиккета в компоненте inDating пользователи онлайн, пока не разлогинятся нажав на кнопку **ВЫХОД**, а если человек вышел с сайта просто закрыв вкладку или окно браузера, то статус **онлайн** везде где используется inDating остаётся постоянно. @fuzegit подскажите пожалуйста, что в 2.10 отвечает теперь за данную функцию, я смотрел [здесь](https://github.com/instantsoft/icms2/commit/7467641b6605c2fc03de1384df5e6f949c948387), но там очень много правок.
