### ISSUE TITLE
Письмо о новом личном сообщении на сайте

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#766]
Добавить информацию от кого пришло сообщение, на примере как это сделано на оф.сайте icms.

p.s. иногда важно знать от кого пришло сообщение и переходить на сайт, если знаешь от кого письмо и нужно ли срочно его прочитать.

**Comment by Val-Git** [comment]
И текст самого сообщения желательно.

**Comment by Loadir** [comment]
> И текст самого сообщения желательно.
В плане безопасности, это не есть гуд. Так как к почте могут иметь доступ третьи лица (например жена))) )

**Comment by Val-Git** [comment]
Если третьи лица имеют доступ к почте - они имеют доступ к аккаунту!
В различных соц.сетях на почту падает текст сообщения - и это очень удобно! Как минимум жена не жаловалась)))
