### ISSUE TITLE
Проблема с выстраиванием картинок в .widget_tabbed

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#767]
**Используемая версия InstantCMS**: 2.9.0

**Версия PHP**:  5.4.38

**Как воспроизвести проблему**: В виджете с несколькими вкладками, поставить новые фотографии - второй, или третьей вкладкой.

* первый шаг - ставим виджет **новые фото** второй вкладкой или третьей вкладкой.
![14-03-2018 11-09-28](https://user-images.githubusercontent.com/9349934/37390395-f6e531ea-2778-11e8-98b3-c4bba1871cfa.png)
* второй шаг - сохраняем и идём на сайт.
![14-03-2018 11-12-15](https://user-images.githubusercontent.com/9349934/37390401-fbf46d04-2778-11e8-9e30-1b6bcf291fab.png)
* третий шаг - заходим во вкладку новые фотографии - они рассыпаются, и не выстраиваются в плитку, при нажатии F12 они выстраиваются как надо, но при обновлении страницы, проблема возвращается.
![14-03-2018 11-13-34](https://user-images.githubusercontent.com/9349934/37390435-193271ae-2779-11e8-8b60-b7aef09f6263.png)

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

Хотел у себя на сайте поставить картинки, второй вкладкой, столкнулся с такой проблемой. Чистка кэш не помогает.

**Comment by pocus-1** [comment]
Похожая проблема и со слайдерами. В общем везде, где стили зависят от ширины контейнера и высчитываются через JS в момент загрузки. У табов при загрузке ширины нет, нет и стилей у содержимого.

**Comment by fuzegit** [comment]
Решено в шаблоне modern.
