### ISSUE TITLE
Баг отображения поля "Список: мультивыбор" в фильтре

### ISSUE THREAD

**Issue by Dspecopt** [instantsoft/icms2#768]
**Используемая версия InstantCMS**: 2.9

**Версия PHP**:  5.3

Возникает проблема с полем "Список: мультивыбор" у которого снята галочка с "Мультивыбор чекбоксами". Если это поле будет выводится в фильтрах на странице дважды (допустим на странице со списком объявлении: первый фильтр - между списком категории и контентом, второй - виджет с фильтром), то это поле будет некорректно отображаться и функционировать. 
1 шаг: создаем поле Список: мультивыбор без отображения чекбоксами
![opera _2018-03-16_175146](https://user-images.githubusercontent.com/37438737/37527416-0cb1754e-2943-11e8-8369-20ba73036e4e.png)

2 шаг: Размещаем (допустим на всех страницах с объявлениями) виджет "фильтр"

3 шаг: переходим на страницу с объявлениями
![1 instantcms](https://user-images.githubusercontent.com/37438737/37527058-1c719c58-2942-11e8-8c4c-ede4655ada92.jpg)

--------------------------------------
Предлагаю сделать отображение поля без "Мультивыбор чекбоксами" не только в полях типов контента, но ещё и в свойствах.
![opera _2018-03-16_180045](https://user-images.githubusercontent.com/37438737/37527936-4f4cc132-2944-11e8-9a02-c81e4f99a57e.png)

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА
[](url)

**Comment by elipss** [comment]
Если включен дефолтный фильтр, то в виджете будет так поле отображаться.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/issues/895
