### ISSUE TITLE
Ошибка в файле install\index.php

### ISSUE THREAD

**Issue by WolfAloneManAlone** [instantsoft/icms2#774]
**Используемая версияInstantCMS**:  2.9.0

**Версия PHP**:  PHP 7.2.0

**Как воспроизвести проблему**:  Warning: session_start(): Failed to read session data: memcache (path: tcp://127.0.0.1:11211) in install\index.php on line 3

**Comment by fuzegit** [comment]
Ошибка у вас на сервере, о чем вы же и сообщили.
> Failed to read session data: memcache (path: tcp://127.0.0.1:11211)

**Comment by WolfAloneManAlone** [comment]
я совсем новичок в этой сфере 
Помогите пожалуйста

**Comment by fuzegit** [comment]
У нас есть форум http://www.instantcms.ru/forum там можно задавать вопросы по **своим** проблемам.
У вас сессии включены на memcache, который по видимому отключен или не установлен. Обращайтесь к хостеру с этим вопросом.

**Comment by WolfAloneManAlone** [comment]
Спасибо
