### ISSUE TITLE
Error 404 при применении фильтра в поиске по тегам

### ISSUE THREAD

**Issue by Val-Git** [instantsoft/icms2#78]
Ошибку заметил в каталоге дополнений, затем проверил на 2.4.0 стандартном шаблоне.

Для каталога дополнений (http://addons.instantcms.ru/tags/search?q=%D0%BF%D0%BE%D1%80%D1%82%D0%B0%D0%BB)
1. Жмем в виджете тегов на тег "портал" (самый заметный, но можно выбрать любой другой).
2. На странице результатов поиска (ссылка приведена выше) нажимаем "Показать фильтр".
3. В поле фильтра указываем "Компонент" и нажимаем кнопку "Фильтровать".
4. Выводится "404 Страница не найдена" вместо результатов фильтрования.

На 2.4.0
1. Выбираем тег "пример" в виджете тегов (также можно любой другой тег).
2. На странице результатов поиска жмем "Показать фильтр"
3. Выбираем например "Тип статьи" - "Авторская".
4. Пимпа "Фильтровать" и "404 Страница не найдена"

**Comment by nomad48** [comment]
Эту ошибку я еще на 2.2.1 заметил, но думал ее в следующем релизе поправят, но сейчас у меня 2.3.0 и уже есть наверно 2.4.1, а она тянется http://joxi.ru/JMAjvQaHo4QVAe
