### ISSUE TITLE
Теги, улучшить логику

### ISSUE THREAD

**Issue by Jestik** [instantsoft/icms2#780]
2.9.0
Использую 2 типа контента: новости, статьи

Виджет теги, вывожу списком. сортировка по популярным, вывод только тегов из статей
В итоге в виджете показывается возле тега цифра 3 - т.е. количество всех материалов с данным тегом, что не очень логично т.к. выбрано показывать только из типа контента "Статьи"

При клике на тег, открывается страница с результатами поиска, но выбрана вкладка "новости", опять же не логично, нажимал то я на тег в разделе статей и хотел увидеть все статьи с данным тегом

**Comment by fuzegit** [comment]
> В итоге в виджете показывается возле тега цифра 3 - т.е. количество всех материалов с данным тегом

это не будет исправлено

> но выбрана вкладка "новости", опять же не логично, нажимал то я на тег в разделе статей и хотел увидеть все статьи с данным тегом

исправлено
