### ISSUE TITLE
Удаленные в корзину материалы видны в поиске.

### ISSUE THREAD

**Issue by HiAndy** [instantsoft/icms2#783]
**Используемая версия InstantCMS**: 2.9.0

**Версия PHP**:  Любая версия

**Как воспроизвести проблему**: Удалить материал в корзину и попробовать найти его поиском.

В InstantCMS появилась возможность удалять контент в корзину, а поиск работает без учета этого нововведения. В результате удаленный в корзину контент виден в результатах поиска и переход по ссылке из поиска приводит к отсутствующей странице с ошибкой 404.
Предлагаю добавить в файле \system\controllers\content\hooks\fulltext_search.php в фильтры поле is_deleted:
```
$filters[$ctype['name']] = array(
                array(
                    'condition' => '=',
                    'value'     => 1,
                    'field'     => 'is_pub'
                ),
                array(
                    'condition' => '=',
                    'value'     => 1,
                    'field'     => 'is_approved'
                ),
                array(
                    'condition' => 'IS',
                    'value'     => NULL,
                    'field'     => 'is_parent_hidden'
                ),
                array(
                    'condition' => 'IS',
                    'value'     => NULL,
                    'field'     => 'is_deleted'
                )
);
```

**Comment by fuzegit** [comment]
уже решено, будет в очередном коммите
