### ISSUE TITLE
Ссылка в уведомлении о личном сообщении на email

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#785]
При новом личном сообщении на сайте на email отправляется текст и в этом тексте указано лишь название сайта и информация о том что есть личное сообщение. При этом активные ссылки на сайт отсутствуют. Желательно иметь хоть одну активную ссылку на сайт чтоб пользователь мог из письма перейти на сайт. А не угадывать по email или названию сайта куда ему нужно перейти.

**Comment by fuzegit** [comment]
Уже писали об этом, при чём вы же.

https://github.com/instantsoft/icms2/issues/766
https://github.com/instantsoft/icms2/blob/master/system/languages/ru/letters/messages_new.txt

**Comment by Val-Git** [comment]
И я должен был отписываться ранее, что удобно будет (для пользователя) добавить сам текст сообщения в письме. Потому как "вам поступило сообщение..." малоинформативно.
