### ISSUE TITLE
Разные схемы для расположения виджетов

### ISSUE THREAD

**Issue by webomax** [instantsoft/icms2#786]
Разрабатываю доску объявлений, верстка сильно отличается от структуры дефолтной темы, поэтому создавался свой макет. Но при этом хотелось бы создать и виджеты, которые можно располагать. Но схема расположения в системе одна. Было бы не плохо использовать несколько схем для разных страниц. Например при переключении страниц в левой части, в правую бы подгружалась нужная схема, заранее где-то в админке сопоставленная с той или иной страницей. Скорее всего на этой же странице виджета.

**Comment by Alex-HAV** [comment]
Так можно реализовать все нужные позиции прописав для них условия в виде "если здесь есть виджет то вот такой код, если пусто то такой". если а потом уже расставлять куда нужно в админке

**Comment by zau4man** [comment]
Совершенно верно. Создайте позиций в схеме с избытком. 
А при выводе позиций в main.tpl.php шаблона оберните их проверкой на наличие виджетов  в позиции. 

`<?php if ($this->hasWidgetsOn('banner1')) { ?>
                <div class="banner">
                    <?php $this->widgets('banner1', false, 'wrapper_banner'); ?>
                </div>
            <?php } ?>`

Если виджетов нет - позиция выведена не будет, место занимать не будет.
