### ISSUE TITLE
php7.2 ругается на тип данных в /system/core/template.php

### ISSUE THREAD

**Issue by Risgit** [instantsoft/icms2#788]
**Используемая версия InstantCMS**: 2.9.0

**Версия PHP**:  7.2.4

**Как воспроизвести проблему**: Установить новую версию php и перейти в админку

После обновления php до 7.2.4 стало писать то тут то там:
Warning: sizeof(): Parameter must be an array or an object that implements Countable in /home/neos/web/*******.ru/public_html/system/core/template.php on line 1196

Лечится изменением 
protected $controllers_queue;
на 
protected $controllers_queue = [];

**Comment by fuzegit** [comment]
уже давно исправлено, см. код

**Comment by Risgit** [comment]
Спасибо, в следующий раз буду внимательнее.
Тогда в версии 2.10 , если юзер не авторизован, ругается на строки 
`$item['is_new'] = (strtotime($item['date_pub']) > strtotime($user->date_log));`
в файлах \system\controllers\activity\model.php и \system\controllers\content\frontend.php
Предлагаю сделать как-то так:
`$item['is_new'] = !empty($user) ? (strtotime($item['date_pub']) > strtotime($user->date_log)) : null;`

**Comment by fuzegit** [comment]
Лучше вот так /system/core/user.php тогда уж
```php
        //
        // если авторизован, заполняем объект данными из базы
        //
        if ($this->id){
            $this->loadAuthUser($this->id);
        } else {

            // для неавторизованных ставим дату посещения
            $_date_log = self::getCookie('guest_date_log', 'integer');

            if (self::isSessionSet('user:date_log')){
                $date_log = self::sessionGet('user:date_log');
            }

            if (!self::isSessionSet('user:date_log') || !$_date_log || ((time()-self::USER_ONLINE_INTERVAL) >= $_date_log)){

                $date_log = time();

                self::setCookie('guest_date_log', $date_log, 31536000);

                self::sessionSet('user:date_log', $date_log);

            }

            $this->date_log = date('Y-m-d H:i:s', $date_log);

        }
```

**Comment by Risgit** [comment]
> Лучше вот так /system/core/user.php тогда уж
А так и вообще круто будет!
