### ISSUE TITLE
Баг в сроке публикации

### ISSUE THREAD

**Issue by globator88** [instantsoft/icms2#789]
Не нашел информацию про этот баг. Возможна проблема уже решено. Так как я использую версию 2.8.2
Если выбрать срок публикации "дни" а потом пересохранить запись, то срок публикации записи удаляется и запись публикуется без срока. Заметил это когда получил сообщение от пользователей. Так как максимум срок публикации на сайте 30 дней. Но там были записи пол года давности.

**Comment by fuzegit** [comment]
Опишите более подробно, как повторить проблему. Или, что будет лучше всего, скачайте версию отсюда и проверьте на ней, если это не затруднит.
Пока что я выставил в правах "дни" создал/пересохранил запись - всё работает как положено.

**Comment by globator88** [comment]
После пересохранение, редактируйте запись через профиль администратора и посмотрите на срок публикации. Там пусто?
Постараюсь вечером установить и проверить на чистом instant.

**Comment by fuzegit** [comment]
> Там пусто?

нет, поле "Дата окончания публикации" и само значение на месте.

В общем надо подробности, как мне по шагам повторить проблему, если она есть.

**Comment by globator88** [comment]
https://drive.google.com/file/d/1ZRvCYXW6Lw0K9PLlq6ERtdzBBI1YTOqB/view
