### ISSUE TITLE
Исчезают Свойства в "Виджет фильтр" после фильтрации

### ISSUE THREAD

**Issue by elipss** [instantsoft/icms2#790]
**Используемая версия InstantCMS**: < 2.9.0 
**Версия PHP**:  5.3-7.0

**Как воспроизвести проблему**:

* Открыть страницу "Типа контента" где расположен "Виджет фильтр"
* Нажать кнопку "Фильтровать"
* Поля Типов контента остаются, **Свойства исчезают**
* Чтобы снова фильтровать "Записи" c другими галками "Свойств" нужно заходить в ту же категорию, подкатегорию Типа контента.  
* Все это странно и **не похоже на Фичу** . 
* Спасибо за внимание. 

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: **ДА** !

**Comment by fuzegit** [comment]
Уже давно решено

**Comment by elipss** [comment]
Подскажите пожалуйста где это решено и будет ли в обновлении ?

**Comment by fuzegit** [comment]
Здесь решено и разумеется в обновление это включено.
