### ISSUE TITLE
Проблема с полем дата в виджете "Фильтр контента"

### ISSUE THREAD

**Issue by webomax** [instantsoft/icms2#795]
**Используемая версия InstantCMS**: 2.9.0

**Версия PHP**:  7.1

**Как воспроизвести проблему**:

* В типе контента отметить отображение фильтра в списке
* На страницу со списком этого контента поместить виджет фильтра

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

Баг заключает в том, что если на странице присутствует 2 фильтра, один над списком контента, а другой в виджете, в поле дата публикации (от и до) при клике в них не отображает выпадающий календарик. А в фильтре над списком контента работает.

**Comment by fuzegit** [comment]
Есть ли примеры надобности, когда реально буду выводить и фильтр (который отключается) и виджет? Предполагается, что должно использоваться что-то одно.

**Comment by webomax** [comment]
Реальных примеров нет. Это было просто замечание. Кто-то так же может подумать что это баг
