### ISSUE TITLE
Просмотр списка отключен, связи и хлебные крошки

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#799]
**Используемая версия InstantCMS**: 2.9.0

Добрый день.

Проблема вот в чем. 

Есть два типа контента - Компании (родитель) и Товары (дочки). В Товарах отключаем просмотр списка на сайте. Т.е., нам не нужно выводить всё в куче. Но нужно оставить просмотр списка товаров во вкладке фирмы. С этим всё в порядке - так и есть. Но при переходе на товар в хлебных крошках содержится ссылка на список всех товаров. А так как мы отключили просмотр списка на сайте, то ссылка эта ведет на страницу с ошибкой 404. 

**Главная -> ~~Каталог товаров~~ -> Пылесос Samsung**

Правильнее было бы в этом случае выводить не битую ссылку, а, например, ссылку на Товары родительской Компании, т.е., при просмотре дочки в хлебных крошках выводить ссылку на список дочек конкретного родителя. 

Но возникает вопрос, что делать, если родителей несколько? В этом случае нужно каким-то образом выводить ссылку на список дочек того родителя, с которого произошел переход на страницу дочки. А если переход произошел из поиска или с другой какой-то страницы, которая не является родителем для этой дочки (например, из виджета с любой страницы), то не выводить вообще ничего, т.е. 

**Главная -> Пылесос Samsung**

Всё лучше, чем битые ссылки.

Спасибо.

**Comment by fuzegit** [comment]
> В этом случае нужно каким-то образом выводить ссылку на список дочек того родителя, с которого произошел переход на страницу дочки.

только добавлять get параметр для такой ссылки, blabla.html?parent=company но я не уверен, что это так нужно.

**Comment by fuzegit** [comment]
Максимум, что я могу по этому поводу сделать, это убрать ссылки на списки в хлебных крошках.

**Comment by asnenne** [comment]
Понимаете, я не могу знать всех нюансов и тонкостей. Я не разработчик и даже не программист. Как нужно - это не мне решать. Я нашел ошибку и о ней сообщил. Привел варианты, как было бы с моей точки зрения лучше. Сейчас выводится битая ссылка, вот и всё. Моя задача - найти и сообщить. Что делать дальше я не знаю. Просто не умею. Что такое get параметр - для меня это темный лес. Убрать ссылки на списки в хлебных крошках - если другого ничего нельзя сделать, то так будет лучше, чем битые ссылки. Но в этом случае и хлебные крошки не нужны. Зачем они, если ведут на главную? Проще тогда их вообще отключить.

**Comment by fuzegit** [comment]
> Я не разработчик и даже не программист. Что делать дальше я не знаю. Просто не умею.

Так я и не пишу, что нужно программировать от вас)

> Что такое get параметр - для меня это темный лес. 

В конце ссылки на запись добавится site.ru/blabla.html**?parent=company**, что вполне вероятно будет забраковано сеошниками. А иначе никак не определить к какому родителю принадлежит запись.

Поэтому на текущий момент я просто убрал битые ссылки.

**Comment by asnenne** [comment]
> site.ru/blabla.html ?parent=company

Компании - **spr**
Товары - **cat**

Страница компании - site.ru/**spr**/blabla.html
Страница списка товаров этой компании - site.ru/**spr**/blabla/view-**cat** - если переходим с этой станицы на товар, то эта ссылка и выводится в хлебных крошках.

> будет забраковано сеошниками

Это почему же? Потому что станет лучше, чем с битыми ссылками?))

> просто убрал битые ссылки

Это не выход. Потому что теряется смысл хлебных крошек.

**Comment by fuzegit** [comment]
страница товара будет как
  site.ru/cat/blabla.html?parent=spr

**Comment by asnenne** [comment]
> страница товара будет как

А вот это уже хуже)) Сразу не понял, о чем речь. Да, так плохо для сео - 100500 дублей.

**Comment by fuzegit** [comment]
> А вот это уже хуже))

Воот. Об этом я и веду речь. Но без доп параметра никак не отследить в каком контексте открывается ссылка.
