### ISSUE TITLE
Работа с изображениями.

### ISSUE THREAD

**Issue by SadKit-zz** [instantsoft/icms2#80]
При насполнении сайта информацией столкнулся с определенной проблемой, в разных типах контента необходимо использовать одни и те же картинки, обложки, изображения статусов и т.д. При текущем положении каждый раз приходится загружать изображение заново, и это так или иначе занимает дисковое пространство. как вариант, можно использовать адрес уже загруженного изображения, если он известнен, однако, в случае если версткой будет заниматься не искушенный пользователь, он конечно же не будет разыскивать адреса картинок.
Как временный вариант в реджиме редактирования повесил сайдбар с кодами наиболее часто используемых элементов, но это тоже не правильно. 
Было бы хорошо, если бы в настройках можно было указать папку на сервере, в которую либо предварительно по FTP либо загрузчиком поместить требуемый графический контент, а при использовании его на сайте был бы выбор, загрузить с локального компа или использовать файлы из папки на сервере.

Заранее спасибо

**Comment by mafru** [comment]
Можете привести пример, где вы такое видели? По-моему это уже лишнее.

**Comment by SadKit** [comment]
Видел что именно? Использование графического контента не с локальной машины а с сервера? во многих CMS, MaxSite, к примеру из фриварных. Adobe Day CQ (не помню как он сейчас называется) из коммерческих.
Почему лишнее, На сайте только одного типа контента будет порядка 400 страниц, на них используется 5 одинаковых изображений в разной вариации, + одинаковые изображения используются в разных типах контента на одну тему которых тоже не мало. При этом, если участь, что на каждую картинку создается несколько пресетов получается как минимум не рациональное использование дискового пространства, и увеличение траффика, т.к. не спасет локальный кэш. Одинаковые картинки (кто в идеале могут быть закэшированы) бузут загружаться вновь и вновь, т.к. по факту являются разными фалами для разных статей.

**Comment by mafru** [comment]
На сайте только одного типа контента будет порядка 400 страниц, на них используется 5 одинаковых изображений в разной вариации, 
Думаю в таком случае, легче внести изменение в файл шаблона типа контента.

**Comment by SadKit** [comment]
Во все шаблоны всех типов контента и переделывать это после каждого обновления?
Да, можно, можно даже свою CMS написать... или использовать другую :(
Вопрос лишь в том, что не все могут легко и просто внести изменения в шаблоны. Ибо если это делать из спортивного интереса дабы продемонстрировать свое конг-фу, или чтобы потом это продать - быть может и да. Но когда нет возможности либо по времени, либо по знаниям, либо... нужное подчеркнуть или дописать, то выбор падет на ту CMS которая это предлагает.
И опять же если бы была возможность с легкостью разобраться в чужим коде, да еще и модифицировать его на свое усмотрение, врядли бы стали писать разработчикам...

**Comment by SadKit** [comment]
> Указанные изображения загружаются через поле изображения или редактор?
И так и так. В редакторе просто копипасчу код, хоть какой-то выход. А в полях "размножаю" ;) одно и тоже.

**Comment by mafru** [comment]
> Во все шаблоны всех типов контента и переделывать это после каждого обновления?

К вашим правкам в шаблоне делаете комментарии и при обновлении все ваши правки вы сразу будете видеть в шаблоне. Не вижу проблемы.

**Comment by SadKit** [comment]
А как с полями быть??? ;) Скажем так. да, часто используемых картинок можно добавить в шаблон, я еще проще сделал, в режиме редактирования на сайдбар их повесил и вставляю адрес руками. Согласен, колхоз, но хоть что-то
А вот использование одного и того же файла в поле "изображение" для разных типов контента я как-то не представляю как на уровне шаблона решить. придумывать новое поле "Изображение 2"  в котором будет фигурировать ссылка на файл. Но тогда пресеты для разных расзмеров будут отсутствовать :/

**Comment by mafru** [comment]
Если честно, я вообще слабо представляю, что вы конкретно хотите получить на выходе? Может покажите примеры своих страниц, где используется одни и те-же изображения. 
Можно хотя-бы скринами, тогда может что-то смогу и посоветовать.

**Comment by SadKit** [comment]
Можно и отправить ;) куда?

**Comment by pin-git** [comment]
Использование уже закаченных на сервер изображений вещь хорошая. Да и оптимизаторы настаивают не повторяться. Если говорить про файл-менеджер, то напрашивается огромное количество ньюансов включая безопасность, да и не удобно. Возможно лучшим вариантом будет индексирование, сверка по загрузке и предложение использовать файл на сервере.

**Comment by SadKit** [comment]
Ну это разработчикам виднее внутренние хитросплетения, как это будет, индексация, доступ в папку, промеждуточный модуль... Я просто смотрю с точки зрения пользователя, наверное ;)

**Comment by vlad7090** [comment]
да, файменеджер удобно было бы для выбора уже залитых картинок на фтп

**Comment by SadKit** [comment]
Как на мой взгляд это было бы удобно более чем в трех аспектах:
1) Оптимизация дискового пространства сервера и файлового массива.
2) Эргономика рабочего места для привлеченных редакторов
3) Существенное облегчение работы редактора(ов) при работе с нескольких компьютеров (необходимые файлы могут быть загружены предварительно и могут быть использовании в случае их отсутствие на используемом рабочем месте)
4) Возможность оптимизации процессов в случае командной удаленной работы, лицо ответственное за графику загружает контент для дальнейшего использования редакторами.

как-то так ;)

**Comment by iAndroS** [comment]
А как вам решение такое: у каждого пользователя в редакторе при вставке картинки выводится ссылка "Выбрать из ранее загруженных", где ему показываются его ранее загруженные картинки и можно еще предоставить выбор из общих фотоальбомов?

**Comment by vlad7090** [comment]
да, именно это и было бы удобно

**Comment by SadKit** [comment]
Выбрать из ранее загруженных - уже удобно. 
Если рассматривать возможность выбора из фотоальбомов, то  тоже хорошо, быть может даже удобнее. Задать одному альбому статус "системный", чтобы он не отражался в списке остальных альбомов и хранить там графику, которая используется на сайте. Этот "системный" альбом будет доступен в редакторе, как вариант.

**Comment by fuzegit** [comment]
Для некоторых редакторов HTML данный функционал появился. В целом, функционал некого файлового менеджера делать не планируется. Во всяком случае в обозримом будущем.
