### ISSUE TITLE
Добавить переключатель языка

### ISSUE THREAD

**Issue by Margauza** [instantsoft/icms2#801]
Здравствуйте,
добавьте пожалуйста в движок переключатель языка с симпатичными флажочками. Неудобно, языки есть а переключателя нету. Спасибо.

**Comment by fuzegit** [comment]
В CMS нет мультиязычности контента, надобности в переключателе тоже нет.

**Comment by Margauza** [comment]
> В CMS нет мультиязычности контента, надобности в переключателе тоже нет.

Соцсетям это не мешает. Есть мультиязычность интерфейса, порой этого достаточно. 

А если нужен разный контент, можно разбить пользователей на языковые группы (группы пользователей), создать свои типы контента для каждой (все равно все эти поля дублируются в базе, даже если есть мультиязычность в движке) и давать им доступ к тому контенту, который соответствует их языку. А в некоторых случаях и связи могут сгодиться для некоторых разновидностей мультиязычности. 

PS: Печально что вы закрываете тикеты по инерции  даже не подумав хорошенько. Но хозяин барин, нет так нет.

**Comment by fuzegit** [comment]
> Печально что вы закрываете тикеты по инерции

это не так

> Соцсетям это не мешает. Есть мультиязычность интерфейса, порой этого достаточно.

в соцсетях как минимум меняется язык меню, названия полей и т.п. У нас этого нет. А вот если добавить переключатель, возникнут лишние вопросы, как раз на эту тему.
