### ISSUE TITLE
2.10 с гита: не подгружается редактор LIVE

### ISSUE THREAD

**Issue by Margauza** [instantsoft/icms2#803]
**Используемая версия InstantCMS**: 2.10 c git

**Версия PHP**:  5.5

**Как воспроизвести проблему**:

Ошибка 1:  не подгружается редактор LIVE

* В типе контента создать поле текст HTML с редактором LIVE
* Перейти в редактирование или создание нового материала.
* Убедиться что редактор не подгружается.

Скриншоты прилагаю.
1
![live1](https://user-images.githubusercontent.com/18312974/39303677-bcb8e8b4-495f-11e8-957b-e2468f03229c.jpg)
2
![live2](https://user-images.githubusercontent.com/18312974/39303688-c97398a6-495f-11e8-8574-b9bd9c5829ce.jpg)

Ошибка 2: В редакторе redactor изображения не открываются в новой вкладке. Галочка естественно установлена но редактор не запоминает.

![redactor](https://user-images.githubusercontent.com/18312974/39303693-d16ecac6-495f-11e8-9def-c82c6b7c25c2.jpg)

**Comment by fuzegit** [comment]
> В редакторе redactor изображения не открываются в новой вкладке. Галочка естественно установлена но редактор не запоминает.

этот чекбокс для ссылки изображения, которая у вас не указана

**Comment by Margauza** [comment]
> этот чекбокс для ссылки изображения, которая у вас не указана

Но ведь раз изображение уже загружено разве ссылка не должна подставляться сама? Изображение загружено визуально подогнано-уменьшено но оригинал ведь этот же.

**Comment by fuzegit** [comment]
> Но ведь раз изображение уже загружено разве ссылка не должна подставляться сама?

вы путаете мягкое с тёплым. всё работает правильно.
проблему с редактором live исправим.

**Comment by r2git** [comment]
> разве ссылка не должна подставляться сама?
Не должна. Если вы хотите, чтобы картинка была ссылкой на другую картинку - нужно ввести ее вручную.

**Comment by fuzegit** [comment]
Проблема с live решена

**Comment by Margauza** [comment]
Вы правы насчет редактора. Когда я поменяла лайв на редактор, народ стал жаловаться что ссылка не подставляется а я решила что имеют ввиду редактор редактор.
