### ISSUE TITLE
2.10: не нашел опций подписок или их нет или не будет

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#804]
1) На странице просмотра записи нет кнопок подписаться, увидел только в списке. Логично предположить что пользователь читая статью должен иметь возможность подписаться на новые не переходя в список с этой же страницы.
2) В настройках типа контента (или еще где) не нашел в каком типе контента выводить эту кнопку подписаться, отображается везде

**Comment by fuzegit** [comment]
1. Подписаться можно на списки чего-либо. Кнопка подписки в записи - не логична. Подписка в записи есть в связях, в соответствующей вкладке.
2. Так и должно быть, см. тз

**Comment by lakomet** [comment]
> на что будет подписываться юзер при нажатии на кнопку в записи?
Я и написал, что логичнее сделать виджетом, с четырьмя кнопками - "Подписаться на ВСЕ новости", "Подписаться на новости -> спорт", "Подписаться на новости от Васи" и "Подписаться на новости -> спорт от Васи"
Я не настаиваю, просто высказал мнение.

**Comment by fuzegit** [comment]
Сделал виджет

**Comment by lakomet** [comment]
> Сделал виджет

Спасибо.

**Comment by lakomet** [comment]
А в виджете "Фильтр контента", кнопки "Подписаться", не будет?

**Comment by fuzegit** [comment]
> А в виджете "Фильтр контента", кнопки "Подписаться", не будет?

нет
