### ISSUE TITLE
Не обновляется количество подписавшихся.

### ISSUE THREAD

**Issue by lakomet** [instantsoft/icms2#805]
**Используемая версия InstantCMS**: УКАЖИТЕ ВЕРСИЮ текущая с гита

* первый шаг Нажимаем "Подписаться"
* второй шаг Не перезагружая страницы, нажимаем "Отписаться"
* третий шаг цифра подписчиков не уменьшиться, пока не перезагрузишь страницу, при этом, если нажать на кнопку с цифрой "количество подписчиков", то вылетает модальное окно с ошибкой

**Comment by fuzegit** [comment]
починил, спасибо
