### ISSUE TITLE
Редакторы и типограф (снова по 2.10)

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#806]
**Используемая версия InstantCMS**: 2.10 git

**Версия PHP**:  5.6.33

**Как воспроизвести проблему**: Добавить пост, например в блогах. Форматирование -> Код -> в коде вставить какой нибудь код с Iframe, при нажатии на enter код превращается в Iframe. Либо при вставке многострочного кода сбивается разметка строк, появляются какие то отступы. После нажатия редактировать, в блоке код все переводы строк выглядят как <br> и все вытягивается в одну строку. Дальше даже сохранять страшно) Все тоже самое только без переводов строк. Пожалуйста в обновлении давайте решим с отображением контента. Заполнение контента пользователями - это важный момент при ведении сайта. На оф сайте же оч хорошо этот блок работает, даже пронумерован. В компонентах inthemer даже синтакс. подстветка в блоках имеется , а в движке так вот.

Еще важный момент касающийся редакторов:

Стиль отображения контента внутри окна при добавлении записей "тянется" из стилей редактора. По умолчанию он схож со стилями дефолтного шаблона, но если использовать другой шаблон либо изменить шаблон default то при добавлении контента стили в окне при добавлении уже не те что будут после публикации записи. Если можно то пусть стили редактора для окна добавления
записи берутся из шаблона а не редактора. На то он ведь и визуальный редактор wysiwyg - как видим так и будет. А на деле даже заголовки совсем другие опубликуются нежели те что в редакторе. Не говоря уже о блоках "цитата", "код" и тд.

Для примера, даже в оф.каталоге дополнений при добавлении или редактировании записи заголовок h2 в редакторе вообще шрифт белого цвета. А при публикации норм.

В общем если можно то стили шаблона пусть будут приоритетными в окне добавления записи перед стилями редактора.

Спасибо.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: Тест на версии с гита

**Comment by fuzegit** [comment]
Это проблема редактора redactor. В маркитапе всё нормально. 
Честно говоря, странно от вас это читать.
> На оф сайте же оч хорошо этот блок работает, даже пронумерован.

так на офсайте не wysiwyg редактор и код там форматируется на сервере, как впрочем и здесь в маркитапе.

> Стиль отображения контента внутри окна при добавлении записей "тянется" из стилей редактора. По умолчанию он схож со стилями дефолтного шаблона, но если использовать другой шаблон либо изменить шаблон default то при добавлении контента стили в окне при добавлении уже не те что будут после публикации записи.

вы шутите?
