### ISSUE TITLE
Подписка на приватный тип контента

### ISSUE THREAD

**Issue by lakomet** [instantsoft/icms2#807]
**Используемая версия InstantCMS**: 2.10 с гита

**Как воспроизвести проблему**:

* первый шаг В настройках доступа типа контента, допустим "статьи", запрещаем просмотр чужих записей
* второй шаг Переходим в статьи, и у нас не исчезла кнопка подписаться.
* третий шаг возможно это так и задумано, но мне кажется не логичным подписываться на контент, который не сможешь увидеть, ведь перейдя из уведомления получаем 403 ошибку.

**Comment by fuzegit** [comment]
В таком типе контента просто отключите подписки.

**Comment by lakomet** [comment]
Но это не выход, ведь я могу группе "Пользователи 1", запретить просмотр чужих записей, а группе "Пользователи 2" разрешить просмотр всех записей. Соответственно первым подписка не нужна, а вторым нужна((
