### ISSUE TITLE
Возможность добавлять изображения категориям

### ISSUE THREAD

**Issue by pumpuic** [instantsoft/icms2#809]
Уважаемые разработчики, рассмотрите пожалуйста предложение добавить изображения категориям, это достаточно важный момент, даже для элементарной доски объявлений где надо вывести категории плиткой, изображений нет.

Самые обычные примеры, где приходится придумывать костыли:
https://www.freelancer.com/job/
https://www.upwork.com/

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/issues/192
