### ISSUE TITLE
2.10 git (финал) Глюки в редакторе live при добавлении материала

### ISSUE THREAD

**Issue by Margauza** [instantsoft/icms2#810]
**Используемая версия InstantCMS**: 2.10 git (финал)

**Версия PHP**:  5.5

Суть проблемы описать крайне затруднительно поэтому наскриншотила.

**Как воспроизвести проблему**:

* В типе контента сделать одно или лучше два поля с редактором лайв. Проставить галочки обработка типографом, ссылки через редиректы и тд.
* Используя браузер мозилла 52.6.0 (проблемы наблюдались и в других браузерах но версии точно назвать не могу) Создать материал, 
а. Загрузить изображение. Зайдя в редактирование изображения задать ему обтекание отступы и тд расположив изображение слева.
б. Добавить абзац текста и так как текст получится добавить только над изображением, подтянуть его чтобы оно обтекалось текстом.
в.Нажав клавишу энтер попробовать добавить пустую строку для добавления еще одного абзаца. 
В этот момент можете обнаружить что пустая строка визуально не создалась а черточка обозначающая начало введения текста оказалась совершенно в другом месте а не там где ей следовало быть. 
Переключитесь в режим кода и увидите что пустая строка все таки создалась но в визуальном режиме ее не видно.
* третий шаг.... решить проблему :)
Другие проблемы возникают иногда см скриншоты. Текст вставленный клавишами иногда не виден в режиме кода. При при повторном редактировании изображения релативные ссылки слетают и заменяются на полные, а ссылка на большее изображение слетает совсем (при каких условиях это происходит я к сожалению так и не смогла понять чтобы подробнее описать. 

**1. загружаем фотку**
![1](https://user-images.githubusercontent.com/18312974/39409616-e346c40c-4bf2-11e8-8eb3-a02e0e0538bd.jpg)
**2. добавляем текст. клавишей энтер создаем место для вставки еще текста и черточка улетает за пределы.**
![4_](https://user-images.githubusercontent.com/18312974/39409639-48641f88-4bf3-11e8-822e-47edf29a5bf2.jpg)
**3. переключаемся в режим кода и видим лишние строки но в визуальном режиме их не видно а черточка ушла за изображение**
![3](https://user-images.githubusercontent.com/18312974/39409648-8954dee2-4bf3-11e8-978c-5cc6fcd77f87.jpg)
**4. Если вставлять текст клавишами то иногда в режиме код его вообще не  видно**
![5](https://user-images.githubusercontent.com/18312974/39409656-ba121d42-4bf3-11e8-9d89-e13a592ed252.jpg)

**Comment by fuzegit** [comment]
Это сторонний редактор, мы не правим его исходный код.

**Comment by Margauza** [comment]
Печально.

**Comment by fuzegit** [comment]
http://www.innovastudio.com/live-editor.aspx
