### ISSUE TITLE
Комментарии открываются по минуте после обновления до 2.10.0

### ISSUE THREAD

**Issue by Risgit** [instantsoft/icms2#813]
**Используемая версия InstantCMS**: 2.10.0

**Версия PHP**:  7.2.0

**Как воспроизвести проблему**: Попытаться вывести где-нибудь на странице список комментариев.

* первый шаг Обновляем сайт с миллионом комментариев до версии 2.10.0
* второй шаг  Ждем минуту пока откроется страница.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: НЕТ, там нет миллиона комментариев.

Отображение онлайн пользователей, это прекрасно, но сайт после обновления совершенно перестает шевелиться. 
`/system\controllers\comments\model.php => 296 => modelComments->getComments()
SELECT i.*, r.score as `is_rated`, u.nickname as `user_nickname`, u.is_deleted as `user_is_deleted`, u.avatar as `user_avatar`, IF(online.date_created IS NOT NULL AND TIMESTAMPDIFF(SECOND, online.date_created, NOW()) <= 180, 1, 0) as `is_online`
FROM cms_comments i
LEFT JOIN cms_users as u ON u.id = i.user_id
LEFT JOIN cms_sessions_online as online ON online.user_id = u.id
LEFT JOIN cms_comments_rating as r ON r.comment_id = i.id AND r.user_id='86'
WHERE (i.is_deleted IS NULL) AND (i.is_approved = '1')
ORDER BY i.date_pub desc
LIMIT 10
Время выполнения 39.34046 секунд`

Пробовал переносить комментарии на свежеустановленный сайт (только данные из cms_comments, вся структура и остальные таблицы дефолтные), результат ненамного лучше.
`/system\controllers\comments\model.php => 296 => modelComments->getComments()
SELECT i.*, r.score as `is_rated`, u.nickname as `user_nickname`, u.is_deleted as `user_is_deleted`, u.avatar as `user_avatar`, IF(online.date_created IS NOT NULL AND TIMESTAMPDIFF(SECOND, online.date_created, NOW()) <= 180, 1, 0) as `is_online`
FROM cms_comments i
LEFT JOIN cms_users as u ON u.id = i.user_id
LEFT JOIN cms_sessions_online as online ON online.user_id = u.id
LEFT JOIN cms_comments_rating as r ON r.comment_id = i.id AND r.user_id='1'
WHERE (i.is_deleted IS NULL) AND (i.is_approved = '1')
ORDER BY i.date_pub desc
LIMIT 10
Время выполнения 29.33635 секунд`
В таблице sessions_online одна строка!

Так что мне придется либо отказываться от отображения онлайн пользователей (редактировать system/controllers/comments/model), либо что-то придумывать.

**Comment by fuzegit** [comment]
Присоединение таблицы онлайн пользователей никак от слова совсем не может вызвать такие тормоза. Вероятно у вас проблема с индексами или иная частная проблема. Смотрите EXPLAIN запроса, либо обращайтесь в личку с предоставлением доступа к пациенту.

**Comment by fuzegit** [comment]
Да, лучше напишите мне на почту или в личку на офсайте, я посмотрю в чем причина. Мне уже самому интересно, столько вы бьётесь с этой проблемой :-)
