### ISSUE TITLE
Показывать список диалогов вместо последнего диалога

### ISSUE THREAD

**Issue by Dspecopt** [instantsoft/icms2#816]
**Используемая версия InstantCMS**: 2.10

**Версия PHP**:  5.5

**Как воспроизвести проблему**:

* первый шаг
открыть сайт с мобильного устройства

* второй шаг
Зайти в личные сообщения

После открытия личных сообщений вместо вывода списка диалогов с пользователями (http://dl4.joxi.net/drive/2018/05/07/0030/0042/2002986/86/b3481fc583.png), сразу же выводится последний диалог: http://dl3.joxi.net/drive/2018/05/07/0030/0042/2002986/86/dd9a9ac58c.png

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

**Comment by fuzegit** [comment]
В чём баг?

**Comment by krylos** [comment]
Он наверное имел ввиду что на мобильных если открывает по ссылке "Личные сообщения" то логично видеть список диалогов а не последний диалог, а при нажатии "Написать сообщение" то диалог. Но это скорее не баг а пожелание.
