### ISSUE TITLE
Вывод категории/категорий в самой записи

### ISSUE THREAD

**Issue by pumpuic** [instantsoft/icms2#822]
Было бы удобно видеть в самой записи категорию/категории к которым принадлежит запись.
Сейчас можно вывести только айди категории.

**Comment by pumpuic** [comment]
http://www.instantcms.ru/forum/thread29681-1.html#289651

**Comment by ermakover** [comment]
Да, согласен. И хорошо бы сделать это полем, как было решено у DWD http://www.instantcms.ru/blogs/kladovka-kodera/pole-seo-tekst-dlja-icms-2-obnovlenie-1-4-0.html

**Comment by fuzegit** [comment]
Где выводить категории (место на странице)?
Как они должны выводиться?
Опции вывода категорий?

Делать вывод категорий полем не вариант, люди будут путаться, т.к. управление категориями делается в настройках типа контента. Т.е. либо вообще всё с категориями переносить в поле, либо я не знаю как сделать лучше.
Накидывайте варианты, обсуждайте. Для эффективности обсуждения можно перенестись на оффорум, если хотите.

**Comment by pumpuic** [comment]
1. В подвале, т.е. в show_bar, например, дальше каждый пусть дизайнит по своему усмотрению.
2. Самый простой вывод в виде названия и ссылки, т.е. <a href="/categoryone" title="categoryone">categoryone</a>, <a href="/categorytwo" title="categorytwo">categorytwo</a>, и так до победного.
3. Выводить/не выводить в записи, выводить/не выводить в списке, выводить все категории к которым привязана запись/выводить только одну, например первую.

**Comment by asnenne** [comment]
> Где выводить категории (место на странице)?
Там, где выводятся теги, только выше тегов.
Как они должны выводиться?
> Как теги, только иконка категорий.

Опции в записи:
- только основная категория
- все категории
- не показывать

Аналогично в списке.

**Comment by multiusercms** [comment]
Да просто выводить полем и каждый настроит так как ему надо. Так в друпале сделано и никто не путается.
> люди будут путаться, т.к. управление категориями делается в настройках типа контента. Т.е. либо вообще всё с категориями переносить в поле, либо я не знаю как сделать лучше.

Не зная движок, страницу создания самих категорий тоже не сходу найдешь. На странице создания категории можно написать подсказку чтобы после, перешли в тип контента и создали (вывели созданные) категории. 
Инстант сложный движок для сложных сайтов, так что те кто его использует, с такой мелочью точно справятся, но зато гибкости и маневренности больше появится.

**Comment by fuzegit** [comment]
Решено полем
https://github.com/instantsoft/icms2/blob/master/system/fields/category.php
