### ISSUE TITLE
дефолтные аватары буквами

### ISSUE THREAD

**Issue by Yar-rus** [instantsoft/icms2#823]
**Используемая версия InstantCMS**: 2.10.0

Просьба сделать возможность настройки вывод дефолтного аватара буквами в админке. До 2.9.0 это можно было настраивать правкой в системном файле /system/libs/template.helper.php. С 10-й версии это работает частично.

Тема на форуме: http://www.instantcms.ru/forum/thread29616-1.html

**Comment by nomad48** [comment]
Подтверждаю, тоже самое у меня после обновления на 2.10. @fuzegit подскажите пожалуйста, что поправить?

**Comment by fuzegit** [comment]
В новом шаблоне modern всё будет нормально.
