### ISSUE TITLE
Улучшить отображение меню пользователя в мобильной версии

### ISSUE THREAD

**Issue by ermakover** [instantsoft/icms2#826]
На данный момент на мои сайты заходят 60-80% со смартфонов. На другие, я думаю, тоже. 
В виджете меню пользователя в мобильном отображаются три пункта - логин пользователя, его аватар и маленький, незаметный треугольник, который и является МЕНЮ ПОЛЬЗОВАТЕЛЯ.
У меня все пользователи жмут на логин-аватар и переходят на свою страницу. Не все догадываются ткнуть в маленькую фитюльку справа, поэтому я получал кучу гневных писем, что меню работает криво - выскакивает и пропадает.
Вот у себя сделал примерно вот так https://soba4nik.ru/
Будуд признателен, если вы найдёте более мудрое решение этой проблемы.

**Comment by nomad48** [comment]
> Будуд признателен, если вы найдёте более мудрое решение этой проблемы.

поставьте Responsive Multi Level Menu - будет ещё лучше.
