### ISSUE TITLE
Проблемы с модерацией

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#827]
**Используемая версия InstantCMS**: 2.09-2.10

1. Пользователи добавили 2 комментария к одной записи.
2. В персональном меню появилась кнопка "Модерация (2)". Нажимаем на нее.
3. Переходим в раздел модерации, видим 2 комментария. Открываем запись, к которой добавлены комментарии.
4. Подтверждаем оба комментария.
5. В персональном меню остается кнопка "Модерация (1)". При переходе по ней пусто.

Точно такая же картина, если перейти сразу на страницу материала и там промодерировать комментарий, минуя страницу moderation.

Таким образом, для модерации каждого комментария нужно переходить к нему из раздела модерации. Иначе будет висеть ошибка с неправильным числом непромодерированных комментариев.

![dsd](https://user-images.githubusercontent.com/16401582/39985360-18d14a28-5767-11e8-9ce0-f36fe26773fa.png)
![dsdf](https://user-images.githubusercontent.com/16401582/39985375-20c99168-5767-11e8-802f-1abd63bf9324.png)

Спасибо.

**Comment by fuzegit** [comment]
Что-то я не могу повторить проблему. Разными пользователями добавлялись комментариия или это не имеет значения?

**Comment by asnenne** [comment]
Не имеет значения. Еще раз по шагам.

К одной записи добавлены два комментария. Переходим на страницу модерации, оттуда на любой из комментариев. А на странице записи подтверждаем все комментарии сразу. Т.е., мы же не слепые, всё видим. Подтверждаем все комментарии на этой записи. На странице модерации всё пропадает, но кнопка остается с числом комментариев для модерации, которые мы уже подтвердили.

Если каждый комментарий промодерировать, перейдя на каждый персонально со страницы модерации, то всё нормально. Но если перейти только на один комментарий, а там промодерировать все остальные, которые есть, то тогда вот такая проблема. Могу записать видео.

**Comment by asnenne** [comment]
Пробовал повторить, не получилось ничего)) Может какой-то временный глюк был, не знаю. Сейчас вроде всё ровно. Но зато обнаружилась другая проблема)) Открою новую тему.
