### ISSUE TITLE
Оптимальный редактор 

### ISSUE THREAD

**Issue by elipss** [instantsoft/icms2#829]
**Используемая версия InstantCMS**: 2.9 >

**Версия PHP**:  7 >

Для instantcms существует несколько редакторов, но в каждом есть свои плюсы и минусы. 
Для оптимального редактора необходимо:
Назначение прав пользователям из панели администратора:  какие плагины будут доступны в редакторе для Новых, Пользователей, Модераторов, Администраторов (itiny)
Увеличение изображения при клике
Ограничение размера загружаемых картинок
Сохранение набранных данных при переходе на предыдущую страницу, обновлении страницы или когда что-то пошло не так. 

![1](https://user-images.githubusercontent.com/38455496/40179307-b1571336-59ec-11e8-8b5f-aaa536b3f3ce.png)

Выбор формата текста
Чистка формата текста
Вставка ссылок
Вставка изображений (redactor)
![default](https://user-images.githubusercontent.com/38455496/40179570-57578fb8-59ed-11e8-806f-0f92f4709c90.png)

Вставка видео
Вставка таблицы
Цвет текста
Размер шрифта
Спойлеры в спойлере (markitup)
![default](https://user-images.githubusercontent.com/38455496/40179991-64d40602-59ee-11e8-98bf-7ec8ef2f4165.png)
Разделение на страницы
Предварительный просмотр
Смайлы (qip)
![qip](https://user-images.githubusercontent.com/38455496/40179577-5b28f064-59ed-11e8-8207-b7b39d4981ff.png)

**Comment by elipss** [comment]
В redactor добавить спойлер и смайлы ?

**Comment by fuzegit** [comment]
> В redactor добавить спойлер и смайлы ?

добавим
