### ISSUE TITLE
Свой дизайн писем

### ISSUE THREAD

**Issue by webomax** [instantsoft/icms2#832]
Не нашел как сделать свой дизайн для системных писем. Подскажите, есть шаблон письма, как его встроить в движок?

**Comment by webomax** [comment]
Был бы Хук, было бы проще. А так только в системных файлах колупаться не охото.

**Comment by fuzegit** [comment]
шаблоны писем хранятся тут https://github.com/instantsoft/icms2/tree/master/system/languages/ru/letters

**Comment by webomax** [comment]
Вы не поняли, там хранятся содержимое писем. А как их оборачивать в дизайн, добавляя шапку и подвал в каждом файле, свою верстку писем....?! Ну это очень не оптимально.А потом что в каждом таком файле правки вносить что ли?!

**Comment by fuzegit** [comment]
Движок берет шаблоны писем именно из этих файлов. Там и делаете нужную вам вёрстку. Иного не предусмотрено в принципе.

**Comment by webomax** [comment]
Вы издеваетесь что ли? Нахрена прописывать 20 раз одну и туже верстку в каждом таком файле, а потом при изменении чего либо править все эти 20 файлов?! Не очевидно что ли что я предлагаю обернуть все эти шаблоны в один общий. Вот как например мне быть если я хочу задизайнить все системные письма? Все файлы править? Зачем? Был бы хук, я бы в своем компоненте оборачивал бы в свою верстку письма. Я предлагаю функционал, а просто решил спросить очевидную вещь, то о чем Вы написали в первом комментарии...

**Comment by krylos** [comment]
Андрей дело говорит. К тому же верстку писем "сложновато" делать в txt файлах писем. Хотя бы потому что в этих файлах учитываются все переводы строк на новую. Логично оставить эти файлы для писем как есть и добавить возможность, например hook, для отправки своего дизайна письмо с вставкой содержимого письма из txt файла в свой шаблон письма.

**Comment by fuzegit** [comment]
> Я предлагаю функционал, а не просто решил спросить очевидную вещь, то о чем Вы написали в первом комментарии

> Подскажите, есть шаблон письма, как его встроить в движок?

Где вы что предложили?

> Не очевидно что ли что я предлагаю обернуть все эти шаблоны в один общий. 

Нет

> Нахрена прописывать 20 раз одну и туже верстку в каждом таком файле, а потом при изменении чего либо править все эти 20 файлов

Вы спросили, я ответил, как сделать.

> Был бы хук, я бы в своем компоненте оборачивал бы в свою верстку письма.

Хук есть

> Андрей дело говорит.

Так кто спорит то? Так и нужно писать, мол предлагаю то то и то то, а не "нахрена". Сформулируйте нормально пожелание, открою тикет обратно.

>  Хотя бы потому что в этих файлах учитываются все переводы строк на новую.

Не учитываются, если при отправке указать соответствующий флаг.

> например hook

Хук есть в компоненте messages в соответствующем методе. При этом, если в своём компоненте вы отправляете сами, то вообще ни что не мешает делать письма как угодно.

**Comment by webomax** [comment]
Сорри за резкость.

`
        $before_send = cmsEventsManager::hook('before_send_email', array(
            'send_email' => true,
            'success'    => false,
            'to'         => $to,
            'letter'     => $letter
        ));
        if(!$before_send['send_email']){
            return $before_send['success'];
        }`

Это единственный хук, который вообще не учитывает что я присылаю через него.
А так как Вы сделали еще системную очередь, то при ее обработке и этого хука нету

**Comment by webomax** [comment]
Так а может проще не выкручиваться в своих компонентах, а создать в движке шаблон письма, типа каркаса. Ну пусть это будет email.tpl.php. А внутри дизайн письма и к примеру вставка {content}, в которую и будет подставляться содержимое из файлов "system/languages/ru/letters/..."

**Comment by webomax** [comment]
Изначально я не правильно поставил вопрос. Надеюсь на понимание)

**Comment by webomax** [comment]
Передайте в созданный хук еще информацию о пользователе. Хочу в подвале письма вывести ссылку на редактирования профиля. Типо что-то вроде отписаться. Достаточно id пользователя, ну или на крайний случай адрес почты, по ней ID узнать потом не проблема.
