### ISSUE TITLE
2.10 - ошибки RSS после обновления

### ISSUE THREAD

**Issue by iAndroS** [instantsoft/icms2#833]
После обновления с 2.9 на 2.10 RSS-лента отдается с ошибками. Ридеры ругаются на спецсимволы html (тире, кавычки и прочее в html-коде).
Тема на форуме http://www.instantcms.ru/forum/thread29726-1.html

**Comment by ShushkovEV** [comment]
Не знаю в чем дело но ошибки полностью не исчезли на разных хостингах разный результат. Один и тот же сайт на одном хостинге RSS не работает, на другом работает https://instantcms.ru/forum/thread29726-3.html#294387
