### ISSUE TITLE
Продление срока публикации и уведомление об окончании срока публикации

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#835]
**Используемая версия InstantCMS**: 2.X

Настройки типа контента:
- Управление сроком публикации - ДА
- Что делать после окончания срока публикации - СКРЫТЬ

Настройки доступа типа контента:
- Выбор срока окончания публикации - ДНИ
- Максимальный срок публикации, дней - ЧИСЛО

Для удобства использования предлагаю добавить следующий функционал:

- В настройках доступа добавить поле "За сколько дней уведомлять автора об окончании срока публикации". Если пусто - не уведомлять, если указано число дней - уведомлять (уведомлением и на почту).

- Если срок публикации еще не закончился, то пользователь не имеет возможности ее продлить - поле с количеством дней скрыто. Предлагаю снять это ограничение, чтобы срок публикации можно было не тогда, когда он уже вышел, а тогда, когда удобно. И в этом случае предыдущий срок должен прибавляться к новому. Т.е., публикуется запись на 10 дней. Прошло 4 дня, пользователь решил продлить еще на 17 дней. Редактирует запись, выбирает 17, и теперь срок публикации завершится через 23 дня.

Сейчас же мы имеем такую картину: во-первых, пользователь должен сам считать, когда у него выходит срок публикации (если нет уведомлений), но никто ничего считать не будет, а уведомление напомнило бы ему о необходимости продления, а во вторых, нет возможности продлить срок не тогда, когда он вышел, а тогда, когда это удобно, ведь бывают ситуации, когда сделать что-то по тем или иным причинам не получается сейчас, но вполне могло получиться вчера.

Спасибо.

**Comment by asnenne** [comment]
Что интересно, в более ранних версиях (проверял в 2.6) можно было продлевать срок публикации в любое время. В 2.10 только в последний день или когда уже запись снята с публикации. Временно решил удалением $is_expired 
из строки https://github.com/instantsoft/icms2/blob/e73b0f7775a7a85b55b5fe0a2c98c111519f26ef/system/controllers/content/frontend.php#L789
`if (($action=='add' && $is_pub_end_days) || ($action=='edit' && $is_expired && $is_pub_ext && $is_pub_end_days)){`

Получилось `if (($action=='add' && $is_pub_end_days) || ($action=='edit' && $is_pub_ext && $is_pub_end_days)){`

Но не уверен, что это правильно. Видимо, я вырезал какую-то проверку просроченных записей. Возможно, это для чего-то было нужно.

**Comment by globator88** [comment]
Можно еще добавить: когда выбран "Удалить в корзину" при окончании срока публикации уведомлять пользователя что "Ваша запись перемешена в корзину, если не восстановите, будет удалено окончательно после 30 дней" или что то в этом духе.

**Comment by Portalrk** [comment]
**Поддерживаю в InstantCMS: 2.X 
Для удобства использования добавить следующий функционал:**
В настройках доступа добавить поле "За сколько дней уведомлять автора об окончании срока публикации". Если пусто - не уведомлять, если указано число дней - уведомлять (уведомлением и на почту). 
---
Очень нужная функция! 
Облегчит для пользователя отслеживание своего объявления и для сайта хорошо.
Чтобы такое сделать чтоб разработчики услышали и добавили эту функцию в настройки icms2
