### ISSUE TITLE
Не работает компонент Редиректы в сторонних компонентах 

### ISSUE THREAD

**Issue by elipss** [instantsoft/icms2#836]
**Используемая версия InstantCMS**: 2,10,1

**Как воспроизвести проблему**:

*  кликнуть по ссылке
* появится ошибка 404 

Спасибо.

**Comment by fuzegit** [comment]
![_323](https://user-images.githubusercontent.com/13233234/40356194-0c5edd22-5dc1-11e8-9cb4-bd3009b2bce8.png)

**Comment by elipss** [comment]
Без галочки Редирект работает.  Спасибо . Подскажите,пожалуйста, позже с "Проверять HTTP referer" будет работать ?

**Comment by fuzegit** [comment]
> Подскажите,пожалуйста, позже с "Проверять HTTP referer" будет работать ?

это вопрос к вашему браузеру, он не передаёт рефер. по умолчанию этот чекбокс отключим.
