### ISSUE TITLE
Компонент "География" проблема при загрузке 2-х с половиной миллионов городов

### ISSUE THREAD

**Issue by racheev** [instantsoft/icms2#837]
**Используемая версия InstantCMS**: 2.10

**Версия PHP**:  5.6

**Как воспроизвести проблему**:  загрузить  2 с половиной миллиона городов

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: НЕТ

**Comment by racheev** [comment]
А не требует решения, это вы уже исправили проблему?
А то при выборе города ругается на нехватку памяти. 
Походу он пытается загрузить все сразу, и регионы и города и страны

**Comment by elipss** [comment]
Может не хватает оперативной памяти на хостинге ?

**Comment by racheev** [comment]
Да в том-то и дело что хватает. Бесконечно память можно увеличивать, но это не выход.
