### ISSUE TITLE
Ограничение размера загружаемых изображений + интеграция с облачными сервисами

### ISSUE THREAD

**Issue by elipss** [instantsoft/icms2#838]
Пожелание/предложение:
Для экономии места на хостинге можно сделать ограничение размера загружаемых изображений в мб. 
![default](https://user-images.githubusercontent.com/38455496/40361945-b3c5f14c-5dd3-11e8-8155-70935ceb3e7b.png)
Так же интеграцию с облачными сервисами , обсуждалось [здесь](https://github.com/instantsoft/icms2/issues/329) 

Cпасибо.

**Comment by fuzegit** [comment]
Максимальный размер файлов задаётся в настройках PHP.

**Comment by elipss** [comment]
а настройку из /templates/default/js/fileuploader.js можно в панель вынести ?
