### ISSUE TITLE
Двойная инициализация публикаций в ленте активности

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#839]
**Используемая версия InstantCMS**: 2.10

**Версия PHP**:  5.4.38

**Как воспроизвести проблему**: Разместить новость, сразу отредактировать и сохранить

* первый шаг - размещаем новость (любой контент)
* второй шаг - после размещения редактируем
* третий шаг - сохраняем

В Ленте активности два события

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: не могу проверить

Сделал правки из этой [темы](http://www.instantcms.ru/forum/thread29732-2.html) - контент не задваивается, задваиваются события в ленте актвиности.

![23-05-2018 10-11-30](https://user-images.githubusercontent.com/9349934/40408913-d308e80e-5e71-11e8-8b13-23c945d66b94.png)
![23-05-2018 10-12-20](https://user-images.githubusercontent.com/9349934/40408919-d820587c-5e71-11e8-98b5-b91031ed6171.png)

**Comment by fuzegit** [comment]
решено уже давно

**Comment by nomad48** [comment]
@fuzegit я добавил файлы которые Вы указали - этот /system/core/model.php и этот /system/controllers/content/model.php, надо еще что-то добавлять я не пойму? У меня реально как я показал.

**Comment by fuzegit** [comment]
На текущей версии с гита я проблему не могу повторить. В ленте ничего не задваивается.

**Comment by fuzegit** [comment]
@nomad48 чтобы что-то вам посоветовать, мне нужно самому повторить проблему. Но я не могу это сделать, на текущей версии с гита указанной проблемы нет уже.

**Comment by nomad48** [comment]
Уважаемый @fuzegit проверьте пожалуйста еще раз. На демо проблема есть, у себя на сайте смог повторить с одним из альбомов. На форуме тоже есть [тема](http://www.instantcms.ru/forum/thread29798-1.html)
![28-05-2018 15-36-31](https://user-images.githubusercontent.com/9349934/40615055-e4ad910c-628d-11e8-81ba-a25997b91bd5.png)

![28-05-2018 15-17-41](https://user-images.githubusercontent.com/9349934/40615058-e8e346c2-628d-11e8-80cc-26d34c59fa10.png)

**Comment by fuzegit** [comment]
@nomad48 ну я же вам писал, что в версии здесь проблема исправлена. На демо версия 2.10. Если вы хотите проверить, решилась ли проблема, проверять нужно на текущей версии с гита. Как мне это вам еще объяснить, я не знаю.
На текущей версии я НЕ могу воспроизвести проблему.
