### ISSUE TITLE
Подгрузка большего количества записей раздела/виджета на аяксе

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#84]
Предлагаю опционально сделать возможность не только использовать стандартную пагнинацию, но и подгрузку большего количества записей на той же странице списка записей, но по клику по кнопке "Загрузить еще".

Аналогично можно и для виджетов дать возможность показывать большее количество записей на той же странице. 
Такая фишка очень удобна для контентных сайтов и на многих проектах на вордпрессе федеральных она используется.

**Comment by iAndroS** [comment]
Вроде в блогах было готовое решение

**Comment by fuzegit** [comment]
https://instantcms.ru/blogs/lunyi-blog/ajax-podgruzka-kontenta-dlja-dvoiki.html
