### ISSUE TITLE
Тип поля: набор изображений

### ISSUE THREAD

**Issue by ArtSolist** [instantsoft/icms2#841]
Здравствуйте. Хотелось бы иметь возможность в типе поля "набор изображений" в списке выводить только первое изображение. Список контента намного привлекательней выглядит с изображениями, но если выводить поле "Набор изображений" в списке то выглядит это не очень. Можно конечно прикрутить к типу контента два поля, "Изображение" и "Набор изображений"... но это лишнее поле (записи в таблице) и лишние изображения на сервере, без которых можно было обойтись.

**Comment by Yar-rus** [comment]
А ещё плюс - в записи все фото подряд просматриваются. Очень жирный плюс.
Дело в том, что то, о чёт тут пишите, вполне работает. Может это только мне так повезло... Настроек я вроде никаких не делал... Попробуйте основному полю с фото задать тип "Набор изображений".

**Comment by ArtSolist** [comment]
Yar-rus, спасибо. Проверил, это действительно работает) Только у поля системное имя должно быть обязательно "photo", а я при создании поля обозвал его "images".  Откуда мне было знать что это реализовано, только определенное системное имя нужно было дать.
