### ISSUE TITLE
Не отображаются наборы в недефолтных типах контента

### ISSUE THREAD

**Issue by elipss** [instantsoft/icms2#843]
**Используемая версия InstantCMS**: 2.10.1

Доброе время суток. Не отображаются наборы в недефолтных типах контента. Спасибо.

**Comment by elipss** [comment]
Вы проверяли ? В объявлениях отображается сразу.

**Comment by fuzegit** [comment]
> Вы проверяли ?

да

**Comment by elipss** [comment]
Когда скачивается один и тот же архив, ставится cms не могут быть разные результаты по отображению наборов в  **недефолтных** типах контента .

**Comment by fuzegit** [comment]
Нет в CMS недефолтных типов контента. Но при всём при этом я создал новый тип контента и создал в нём пару наборов. Всё отображается прекрасно.

**Comment by elipss** [comment]
Для отображения нужно от двух наборов...
