### ISSUE TITLE
Не работает подсчёт количества просмотров

### ISSUE THREAD

**Issue by Yar-rus** [instantsoft/icms2#845]
**Используемая версия InstantCMS**: 2.10.0

Не производится подсчёт просмотров записи в типах контента. Счётчики остановились. 

Воспроизводится ли проблема на демо http://demo.instantcms.ru/: ДА
На демосайте к статьям включаю  "Считать количество просмотров", глаз появляется, но количеств просмотров ноль, несмотря на просмотры с разных  ip.

**Comment by fuzegit** [comment]
> На демосайте к статьям включаю "Считать количество просмотров", глаз появляется, но количеств просмотров ноль, несмотря на просмотры с разных ip.

Проверять нужно не под администратором или автором записей. Всё работает.

**Comment by fuzegit** [comment]
Я выше дал ответ на ваш вопрос. Еще раз: если автор записи или администратор смотрит, то просмотры НЕ считаются.
