### ISSUE TITLE
Редирект со страницы логина если уже авторизирован

### ISSUE THREAD

**Issue by webomax** [instantsoft/icms2#846]
Если я уже авторизирован, то предлагаю при переходе по такой ссылке(ниже) редиректить сразу на страницу что указана в параметре back, зачем просить пользователя вводить снова логин и пароль.

https://demo.instantcms.ru/auth/login?back=/users/1/edit/notices

**Comment by fuzegit** [comment]
Сейчас именно так и происходит
https://github.com/instantsoft/icms2/blob/master/system/controllers/auth/actions/login.php#L52

**Comment by webomax** [comment]
Вы прислали сноску на код, но в коде видно что это происходит после сабмита, то есть ввода логина и пароля. Так если человек уже авторизирован на сайте и переходит по этой ссылке, зачем его просить снова ввести логин и пароль?

![2018-05-30_16-32-38](https://user-images.githubusercontent.com/11249756/40723358-73672ad0-6427-11e8-85fe-eeca45a4776e.png)

Смотрите, даже в сообщении говорится о том что необходима авторизация, но если посмотреть в шапку мы увидим что я авторизован уже. Логично сразу редиректить меня без показы формы авторизации

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/blob/master/system/controllers/auth/actions/login.php#L6

Это актуально только для администраторов, что было сделано осознано. Пожалуйста, старайтесь сначала вникнуть, как всё работает.

**Comment by webomax** [comment]
Про админа я понял, но причем тут редирект для пользователя на ГЛАВНУЮ? Я же пишу о параметре back, который не учитывается.

**Вот этот переход, если пользователь аторизирован:**
https://demo.instantcms.ru/auth/login?back=/users/1/edit/notices
**Должен перекинуть его сюда:**
https://demo.instantcms.ru/users/1/edit/notices
**А не на главную**

Вот о чем мой посыл. То ли я так хреново объясняю, то ли хер его знает что еще...

**Comment by fuzegit** [comment]
> То ли я так хреново объясняю

Есть такая вероятность)

> редирект для пользователя на ГЛАВНУЮ

если бы сразу об этом написали, вопрос был бы понятен. сделаем.
