### ISSUE TITLE
Профили удалённые самими юзерами, показываются в друзьях.

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#848]
**Используемая версия InstantCMS**: 2.10.1

**Версия PHP**:  5.4.38

**Как воспроизвести проблему**:

* первый шаг - добавиться в друзья
* второй шаг - потом удалить свой профиль не полностью, а через кнопку "УДАЛИТЬ ПРОФИЛЬ" в настройках профиля.
* третий шаг - удалённый юзер отображается в друзьях.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

![31-05-2018 16-56-19](https://user-images.githubusercontent.com/9349934/40786396-9e6701c0-64f3-11e8-89d7-0aa0489d4d96.png)
![31-05-2018 16-54-50](https://user-images.githubusercontent.com/9349934/40786336-7ba71c88-64f3-11e8-88a3-c7a7b63d4353.png)
![31-05-2018 16-55-07](https://user-images.githubusercontent.com/9349934/40786337-7bf04ade-64f3-11e8-9010-96c2fb2bbda3.png)

Если пользователь скрывается из списка юзеров при удалении профиля через кнопку, то из друзей тоже должен скрываться.

**Comment by fuzegit** [comment]
> то из друзей тоже должен скрываться

не должен. яркий пример тому vk.
