### ISSUE TITLE
Пользовательское соглашение при регистрации

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#85]
В связи с законом о перс.данных, некоторые проекты нуждаются в такой фишке. По сути в настройках регистрации если заполнить поле "Пользовательское соглашение", то во фронте при регистрации выводить это поле и чекбокс для подтверждения согласия.

**Comment by Maratakziaplus** [comment]
Согласен

**Comment by globator88** [comment]
В принципе нужная вещь. Но пока можно на странице регистрации написать что "Регистрируясь вы соглашаетесь..." и дать ссылку на правила сайта.

**Comment by nomad48** [comment]
Я так сделал пока:
`<?php if (!$this->controller->options['is_reg_enabled']){ ?>

    <p><?php echo $this->controller->options['reg_reason']; ?></p>
    <?php return; ?>

<?php } ?>

<?php
    $this->renderForm($form, $user, array(
        'action' => href_to('auth', 'register'),
        'method' => 'post',
        'append_html' => $captcha_html,
        'submit' => array(
            'title' => LANG_CONTINUE
        )
    ), $errors);
?>

<p>Нажимая кнопку «Продолжить», Вы принимаете условия <a href="/pages/polzovatelskoe-soglashenie.html" target="_blank">Пользовательского соглашения </a> </p>

<script>

    function toggleGroups(){

        if ($('select#group_id').length == 0){ return false; }

        var group_id = $('select#group_id').val();

        $('.groups-limit').hide();

        $('.group-' + group_id).show();

        $('fieldset').each(function(){

           if ($('.field:visible', $(this)).length==0) {
               $(this).hide();
           }

           if ($('.group-' + group_id, $(this)).length>0) {
               $(this).show();
           }

        });

    }

    $(document).ready(function(){

        if ($('select#group_id').length == 0){ return false; }

        $('select#group_id').change(function(){ toggleGroups(); });

    });

    toggleGroups();

</script>`

**Comment by my-instantcms** [comment]
http://www.instantcms.ru/forum/thread23178.html#221384

**Comment by nomad48** [comment]
@my-instantcms о хорошее решение, попробую. Спасибо.

**Comment by EnotAlex** [comment]
поддерживаю, но это должно быть в коробке, потом просто замучаетесь изменять каждую приблуду после обновления.

**Comment by fuzegit** [comment]
#1253
