### ISSUE TITLE
Заголовок записи в модальном окне

### ISSUE THREAD

**Issue by webomax** [instantsoft/icms2#853]
Если Вывести существующую запись в модальном окне, прописав ссылку на эту запись указав класс ajax-modal, то заголовок присутствует и в окне и в самой записи.

1) Есть необходимость скрыть заголовок при выводе записи в модалке.
2) Как можно указать размер модалки при выводе в ней записи?

**Comment by fuzegit** [comment]
Вопросы стоит задавать на форуме http://www.instantcms.ru/forum

**Comment by webomax** [comment]
Так же возможно баг. Если добавить этот класс родительскому в главном меню, то в модалке начнут открываться все подменю

**Comment by fuzegit** [comment]
> Так же возможно баг. Если добавить этот класс родительскому в главном меню, то в модалке начнут открываться все подменю

а вот о багах нужно писать уже здесь. исправим этот https://github.com/instantsoft/icms2/blob/master/templates/default/js/modal.js#L7 недочёт
