### ISSUE TITLE
Возможность отменить кликабельность родительского пункта меню(Главного меню)

### ISSUE THREAD

**Issue by webomax** [instantsoft/icms2#854]
Есть такая структура меню:

-Помощь
--Пункт1
--Пункт2
--Пункт3

Необходимо отменить кликабельность пункту (-Помощь). Сейчас это ни как ни сделать.

**Comment by fuzegit** [comment]
Значит решетка, других вариантов нет

**Comment by webomax** [comment]
Решетка сработала, но правильное ли это решение?! Наверно javascript:void(0); это был бы лучшим вариантом и к якорю прокрутки бы не было.

**Comment by fuzegit** [comment]
Стоп. Так вообще ничего не указывайте и всё. Только тут https://github.com/instantsoft/icms2/blob/master/system/controllers/admin/forms/form_menu_item.php#L49 уберите array('required'),

**Comment by webomax** [comment]
Убрал, пересохранил. А он в пункт подставляет / (на главную)

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/blob/master/system/controllers/menu/model.php#L167

заменить на

if ($item['url'] && $parse_hooks){

**Comment by webomax** [comment]
Это победа) Спасибо! Вы же включите это в обновление?!

**Comment by fuzegit** [comment]
да
