### ISSUE TITLE
Не очищаются все уведомления в модальном окне

### ISSUE THREAD

**Issue by webomax** [instantsoft/icms2#859]
К сожалению как не пробовал на демке не смог себе добавить еще одно уведомление. Но замечено у себя под админом что при клике на кнопку очистить ни чего не происходит.

![2018-06-05_17-05-31](https://user-images.githubusercontent.com/11249756/40981602-feeb8ee6-68e3-11e8-9110-7e253d4a85b4.png)

Добавьте в демке уведомлений через базу и посмотрите пожалуйста.

**Comment by fuzegit** [comment]
Уже в версии на гите исправлено

**Comment by webomax** [comment]
Что-то пробежался по коммитам, не нашел. Укажите на строчку кода. Спасибо

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/793521632a924d3f72bc51df992ce435442de802#diff-bbe21c17890ffd398fd810bc2951bef8R384
