### ISSUE TITLE
Возможность вкладывать один тип контента в другой

### ISSUE THREAD

**Issue by rkonsta** [instantsoft/icms2#86]
Создаем например типы контента ”компании" и "сообщение блога компаний" указывает что в типе ”компании" можно размещать тип ”сообщение блога компании". После этого пользователь добавляет страничку компании в каталог и в дальнейшем, может добавлять, например, сообщения блога компании как ссылки на отдельный вложенный тип контента. Также добавление ”продукты компании" как возможный вариант.

**Comment by SadKit** [comment]
Эм... а использовать группы для "консолидации" контента? В них как раз сходятся воедино все типы контекста.

**Comment by rdimrs** [comment]
очень жду эту функцию, такая функция была заявлена в видео на 13.30 минуте https://www.youtube.com/watch?v=pVT5QCqy9g0

**Comment by iAndroS** [comment]
SadKit, а не покажите пример грамотно структурированных и организованных групп на двойке? Что-то как ни пытался, ничего толкового не выходит.

**Comment by SadKit** [comment]
Ну на грамотно структурированные не замахнусь. Но для некоторых материалов, которые подразумевают по нескольку экземпляров разных типов контента, но объедененных по смыслу (в моем случае, это определенный тайтл Аниме, который имеет несколько сезонов, ответвлений и т.д а соответственно описание всех релизов, альбомы с релизами, новости и статьи на этому же тайтлу) Группа становится сосредоточением этих материалов, поскольку в ней перечисляется и отображается весь связанный контент. Далеко не панацея, но хоть есть определенная точка контакта. Хотя конечно было бы намного лучше, если бы было бы поле или виджет для каждого типа контента, который бы, базируясь на этой связи, отображал что-то вроде "материалы на эту же тему"

**Comment by rkonsta** [comment]
С гуппами так не получиться. Там нет не категорий не дополнительных типов полей для заполнения и обычному пользователю сложно будет объяснить что и как делать.

**Comment by iAndroS** [comment]
@SadKit 
можно ссылочку на посмотреть, в личку хотя бы. Хочу реализовать группы на городском портале, но никак не могу разобраться, чтоб толково выглядело все это добро. Одно только добавление контента в группы реализовано немного через не руки: выпадающие списки и т.д.
Юзерам просто не понять, они привыкли к контактам и кашкам, когда есть группа и в ней просто пустое поле для текста - просто и эффективно.

**Comment by rdimrs** [comment]
Группы это не то совсем. Посмотрите видео несколькими сообщениями выше, вот так должно быть.

**Comment by iAndroS** [comment]
@rdimrs данный функционал был в первой бете, но потом R2 по каким-то своим соображениям отказался от него и убрал: видимо, нашел кучу багов, отлов которых отложить до лучших времен, я не знаю...

**Comment by WebManG** [comment]
Очень важный и нужный функционал, позволяющий создавать сложные сайты с минимумом программирования. Я голосую за его реализацию в ближайших релизах.

**Comment by Alex-HAV** [comment]
Присоеденияюсь к WebManG!

**Comment by rookees** [comment]
Функционал необходим как воздух.  готов 10к инвестировать в этот функционал.

**Comment by iAndroS** [comment]
Не запланировано ли данное улучшение в ближайших релизах?

**Comment by Vampireos** [comment]
Присоединяюсь) за простую реализацию блога

**Comment by iAndroS** [comment]
Тоже готов инвестировать в данный функционал!

**Comment by iAndroS** [comment]
Люди готовы инвестировать, а предложение опять в долгосрочной перспективе. Может, там реализация очень сложная? Или в чем может быть проблема? Не зря ведь R2 отказался в свое время от связей типов контента.
Мне даже грешным делом подумалось, что специально отказались, иначе 90% компонентов потом будут не нужны :)

**Comment by fuzegit** [comment]
@iAndroS, **все** предложения о инвестициях остаются на словах. Подчеркиваю, **все**. Кто и куда готовы инвестировать мне неведомо.

> Мне даже грешным делом подумалось, что специально отказались, иначе 90% компонентов потом будут не нужны :)

Все сговорились. Да. Чтобы пользователям хуже жилось и обобрать их до нитки.

**Comment by rookees** [comment]
Так а в чем тогда проблема ?   Просто вопрос стоит или делать самим и потом придумывать костыль  для решения из коробки??

**Comment by fuzegit** [comment]
@rookees, нет проблемы. Вы тут мило между собой общаетесь :)

**Comment by iAndroS** [comment]
@fuzegit, как-то несерьезно. Вы хотя бы можете объяснить, почему это в долгосрочной перспективе, какие сложности/костыли мешают реализации? Почему R2 отказался от реализации этого функционала, хотя изначально он был? 
Не верите в инвесторов? Так объявите сбор, как когда-то на проверку безопасности единички (обозначьте сумму/сроки мы сами сбор организуем), или же выпустите платным компонентом. 
Многие будут только рады такому универсальному конструктору. Вот у меня несколько идей сайтов, под которые инстант вроде как идеально подходит, но ТОЛЬКО если бы в нем были связи типов контента!
Конечно, там будет еще куча пожеланий/предложений, это стопудово, но даже минимума пока нет, и это печалит.

**Comment by WebManG** [comment]
И я хочу мило пообщаться :-)
А если серьёзно, Игорь, то связи типов контента - очень востребованный функционал. Даже не так. Связи - это бомба! Это ещё ещё одно огромное преимущество перед конкурентами. Во многом именно из-за них я ждал Двойку. Вариант, который показал R2 в первой демке, очень удачен. Я не смогу его внедрить в Двойку так же хорошо, как вы это планировали. Зато готов участвовать и финансово, и при тестировании-оптимизации.
Для вас важен вопрос заработка, мы это понимаем. Озвучте сумму - соберём.

**Comment by fuzegit** [comment]
@iAndroS. Попытайтесь меня услышать, если это возможно конечно. В долгосрочной перспективе потому что на данный момент лично у меня нет желания тратить время на это, а движок, напомню, open source. Означает это то, что разработчики вправе сами выбирать приоритет разработки и что внедрять в релизах, т.к. не связаны ни перед кем финансовыми обязательствами.
> Почему R2 отказался от реализации этого функционала, хотя изначально он был? 

я не могу знать.

> Не верите в инвесторов? Так объявите сбор

Не верю. Все, кому что-то было надо - брали и писали конкретно, конкретному разработчику. Обсуждали и получали решение. Никакой сбор мы, как разработчики, объявлять не будем, а инициатором сбора проверки безопасности было сообщество, мы лишь предложили исполнителя.
Есть конкретное предложение - логично связаться напрямую и обсудить вопрос. А пока всё вилами по воде. И формулировка "как-то несерьезно" явно относится не к нам.
Кроме того, я вообще не вникал, что имеется в виду под связями. По моему мнению, в InstantVideo2 есть связи между типом контента "Каналы" и типом контента "Видео". Такого рода связь внедрить универсально не проблема.

@WebManG, дак я не против, что это востребованный функционал. И не писал нигде, что это не нужно.

-----
http://www.instantcms.ru/freelancers
Синий блок справа под фильтром.

**Comment by Alex-HAV** [comment]
Игорь, а если у кого то заказать, а потом предоставить бесплатно для внедрения в коробку? Такой вариант реален?

**Comment by fuzegit** [comment]
Реальны все варианты. Но обсуждать нужно предметно. Я не против сделать связи, но возмутительные сообщения и странные намёки, как было сегодня от @iAndroS, мне категорически не нравится.

**Comment by WebManG** [comment]
> По моему мнению, в InstantVideo2 есть связи между типом контента "Каналы" и типом контента "Видео".
Да, похоже. Аналогичного типа связь и между группами и постами. Но это всё не универсальные решения, заточенные только под эти ситуации. Вы же стремитесь сделать универсальный, расширяемый движок. Во многом у вас это получилось. Из крупного остались только связи типов.
> Такого рода связь внедрить универсально не проблема.
Кому как. :-) Тем более, что для последующего встраивания в движок, способ реализации должен быть согласован с основными разработчиками.
Может быть R2 ответит про причины отказа от этого в релизе и подскажет подходящий алгоритм? Тогда и ТЗ для стороннего разработчика будет  более понятно, и получившееся решение в коробку добавите без проблем.

**Comment by Loadir** [comment]
Здорово побеседовали. Десятым буду в списке participants ))). Тоже есть заинтересованность в этом.

**Comment by fuzegit** [comment]
> Аналогичного типа связь и между группами и постами. Но это всё не универсальные решения, заточенные только под эти ситуации.

Связи между группами и типами универсальны, т.е. это штатная полноценная поддержка.

> Может быть R2 ответит про причины отказа от этого в релизе и подскажет подходящий алгоритм

Причины вероятно были в излишнем усложнении и, что вероятно самое главное, в  том, что его постоянно подгоняли на тот момент - "когда релиз". Это имхо основная проблема всех существующих "неокончательных" работ в движке.

Связи в моём понимании не должны зависеть от функционала привязки к группам. Поэтому использовать столбцы parent_* нельзя. Они скорее всего и останутся за группами.

В связи со всем этим, нужно внятное описание функционала связей, чтобы потом не переделывать. Без фанатизма.

Как я вижу - я описал выше (это в целом схоже с тем, что показывал r2 в видео). Как видите связи вы - мне пока что непонятно.

**Comment by iAndroS** [comment]
@fuzegit, вероятно, вы неправильно меня поняли. Обидеть точно никого не хотел, прошу прощения, если ненароком все же это случилось. Для меня было непонимание, почему такая востребованная и важная функция, внедренная изначально, была отменена и внедрение ее отложено в долгосрочную перспективу! 
Как видите, вопрос поднят не зря - тема масштабируется, диалог пошел. Волнует она не одного меня.
Поверьте, я искренее болею за инстант и глубоко признателен вам и R2 за столь прекрасную CMS. Никогда в своих сообщениях я не пытался обидеть вас или R2 - это обычные рабочие диалоги между людьми, не принимайте близко к сердцу.
Я предложил неплохой вариант, косвенно вы его приняли. Для решения вопроса предлагаю решение: мы коллективно пишем ТЗ с вашим участием, далее вы озвучиваете сумму и ориентировочные сроки за приоритетность разработки, мы ее собираем и переводим вам.
Почему мы не заказываем такие решения на стороне? По нескольким причинам:
1. Никто не знает движок лучше вас, а значит, о глубокой интеграции в движок скорее всего речи быть не может
2. Хотим, чтоб это было в ядре и без костылей
3. Нужно именно универсальное решение, потому как при персональной работе будут отклонения в каждом индивидуальном случае. При написании и тестировании разработки в работе будут выявлены узкие места в универсальности, которые будут в итоге приведены к более-менее нормальному виду.
Наверняка не все причины указал. Буду признателен за подробный ответ.

**Comment by fuzegit** [comment]
@iAndroS в сообщении выше я дал же ссылку, где написано, что можно внедрить почти любую нужную движку доработку. За деньги. Принимать решение вам. Никого не принуждаю, я лишь даю возможность, чтобы все были довольны.

> http://www.instantcms.ru/freelancers
> Синий блок справа под фильтром.

Это не означает, что за все доработки нужно платить. Этот вариант для тех, кому не терпится.

Пишите, составляйте, присылайте. email по ссылке.

**Comment by iAndroS** [comment]
Ок, спасибо!

**Comment by WebManG** [comment]
В очередной раз пересмотрел видео от r2 [https://youtu.be/pVT5QCqy9g0?t=723] (ссылка на момент описания связей). Как по мне, то это минимальный вариант реализации связей, если совсем без фанатизма. :-)

Для бОльшей универсальности, на мой взгляд, можно добавить ещё некоторые опции.
Например, опции/шаблоны вывода подчинённого типа контента на странице записи родительского. Для примера возьмём пресловутый каталог фирм с товарами. Так вот, оформление вывода товаров фирмы на странице этой фирмы может отличаться от оформления вывода списка товаров всего сайта (например, фотографии с названием в первом случае, таблица с подробностями во втором).

Ещё будет полезна опциональная возможность раскладывать по типам подчинённые записи на родительской странице, каждый в свою вкладку, в случае, когда привязано несколько подчинённых типов. Например, для того же каталога фирм будет удобно разложить на разные вкладки список товаров, отзывы, список магазинов/офисов, ещё что-то. Соответственно нужна возможность сортировки связанных типов в таблице "Связи" в родительском типе. А для блогоподобных задач нагляднее будет вывод всех подчинённых типов материалов в одной ленте подряд с сортировкой по дате и кнопками-фильтрами наборов (всё, посты, альбомы, видео и т.д.)

Нечто подобное обсуждали в теме [http://www.instantcms.ru/forum/thread19578-6.html](Вложенные типы контента в двойке), сообщение 82. Кстати, там же есть опрос, в котором 43 человека сказали про актуальность данного функционала. Loadырь даже сделал работающие примеры. Но как-то не сложилось довести это всё до полноценной реализации.

Я не знаю, как на Инстанте принято собирать деньги на подобное и сколько это будет стоить. За добавление подобного функционала могу сразу перевести куда надо 20 wmz. Если сумма будет большая или желающих скинуться не хватит, добавлю ещё.

**Comment by fuzegit** [comment]
Смысл в том, что сделать как в категориях (множественный выбор и вывод в одном списке) всех подряд вложенных типов контента чуть более чем нереально. Таблицы разные, запросы будут адовые.

**Comment by WebManG** [comment]
Хорошо, согласен по поводу вывода нескольких вложенных типов контента в одном общем списке. Но в отдельные вкладки выводить вполне можно (товары, отзывы и т.п.). И сделать так, чтобы каждая вкладка имела свой адрес.
И оформление табов этих вкладок или вообще всей области вложенного контента можно вынести в отдельный шаблон. Чтобы можно было оформлять переключатели типа вложенного контента под свой проект: или табами, или кнопками как в наборах, или просто ссылками.

**Comment by iAndroS** [comment]
Как-то так:
![11](https://cloud.githubusercontent.com/assets/17408903/19414425/419cf964-937f-11e6-882e-554e7211e020.png)

**Comment by rookees** [comment]
Тут вопрос про сквозную фильтрацию по полям ещё нужно продумать

**Comment by WebManG** [comment]
> про сквозную фильтрацию по полям ещё нужно продумать

Что именно Вы имеете ввиду?

**Comment by rookees** [comment]
> Что именно Вы имеете ввиду?

Я имею ввиду сквозные поля,  по которым я буду фильтровать. 

Как пример  Марка Авто - Модель - Модификация - года выпуска - объем двигателя и т.д    И к этому всему есть контент: Отзывы, блоги, форумы и т.д

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/bbb90846f3baaa2eaa9bc284afaf9a80d28b21aa
