### ISSUE TITLE
Ошибка отображения даты выполнения задачи в планировщике

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#860]
**Используемая версия InstantCMS**: 2.10

В 2.10 с появлением подписок в планировщике появилось новое задание - удаление просроченных неподтвержденные подписки гостей.

Подписки не использую, поэтому не могу сказать, работает ли вообще эта задача правильно. Но точно могу сказать, что в планировщике не правильно отображается время последнего запуска. Даже если запусти вручную, дата и время не меняются.

![2018-06-06_122058](https://user-images.githubusercontent.com/16401582/41029381-32868cce-6984-11e8-96f0-58e05a67d0fc.jpg)

**Comment by fuzegit** [comment]
Дата меняется, время не меняется, т.к. включена опция в задании "Строгое следование периоду"

**Comment by asnenne** [comment]
Ну, хорошо, что всё хорошо)) Но я все равно не понимаю, как это работает)) Хорошо.

**Comment by asnenne** [comment]
Спасибо.
