### ISSUE TITLE
Прошу добавить в хук $dataset

### ISSUE THREAD

**Issue by webomax** [instantsoft/icms2#863]
system\controllers\content\frontend.php

Прошу добавить в хуке текущий датасет.

list($ctype, $this->model**, $dataset**) = cmsEventsManager::hook("content_{$ctype['name']}_list_filter", array($ctype, $this->model**, $dataset**));

Так как не смог его получить в самом обработчике хука. Возможно и есть другое решение...

**Comment by webomax** [comment]
Ну подскажите тогда как хоть текущий датасет получить в хуке???

**Comment by fuzegit** [comment]
http://www.instantcms.ru/forum
