### ISSUE TITLE
Прошу добавить отступы в модальном окне при выводе записи

### ISSUE THREAD

**Issue by webomax** [instantsoft/icms2#867]
Если вывести запись в модальном окне с помощью ссылки и класса ajax-modal, то в окне будут явно отсутствовать отступы.

**Comment by webomax** [comment]
Почему не требует решения то?

**Comment by fuzegit** [comment]
Потому что отступы вы должны делать там, какой контент вы показываете в модальном окне. Вывод фотографий, например, не требует отступов.

**Comment by webomax** [comment]
Там а как я сделаю эти отступы, это запись компонента "Контент"...
Сделаю отступ, так он и при просмотре записи будет присутствовать. 
А мне нужно только в окне.

**Comment by fuzegit** [comment]
Я вам ответ дал.

> А мне нужно

Если требуется помощь в каком-либо вопросе, пожалуйста, воспользуйтесь форумом.

**Comment by webomax** [comment]
Походу дело не во мне. Вы упираетесь настырно.

Вот я ставлю на ссылку в меню например вывод в модальном окне содержимое какой либо новости. Я будучи не разбирающийся в коде почему должен наблюдать кривое окно???

Я должен искать решение и изобретать велосипеды?

То есть есть системный способ вывести содержимое записи в попа окне. а кривость этого должен решать кто??? Не Вы????

**Comment by webomax** [comment]
![2018-06-12_13-13-56](https://user-images.githubusercontent.com/11249756/41284620-8136ad82-6e42-11e8-8d80-852a2f23212b.png)

Это по Вашему нормально?

**Comment by webomax** [comment]
Такое ощущение что Вы даже и не пытаетесь вникнуть в проблему. Посылаете постоянно куда-то...

**Comment by fuzegit** [comment]
> Вы упираетесь настырно

Я отвечаю на ваш вопрос. Вы ответ не слышите и в очередной раз хамите. 

> почему должен наблюдать кривое окно

Не наблюдайте, а решайте **свою** задачу, не можете решить, спросите на форуме. В движке не предусмотрен вывод записи в модальном окне. Принцип работы модального окна в части отступов я описал выше.

> даже и не пытаетесь вникнуть в проблему

Со стороны CMS проблемы нет. Как это еще вам донести, чтобы вы вникнули в мой ответ, я не знаю.

> Посылаете постоянно куда-то

Процитируйте, куда я "постоянно вас посылаю".

**Comment by fuzegit** [comment]
> Давайте я Вам заплачу. Мне что денег жалко что ли. На форуме я сколько буду ждать ответа.

Патологическое хамство или просто природная наглость?

> Вы разработчик, Вам сложно дать совет?

Я вам дал ответ и отреагировал на ваше issue. Совета вы не спрашивали. И здесь не место для советов, для этого у нас есть форум, нравится вам такой расклад или нет.

Ваша проблема решается двумя css правилами

.nyroModalLink h1 {
    margin: 15px;
}
.nyroModalLink .content_item {
    margin: 15px;
}
