### ISSUE TITLE
Поддержка WebP

### ISSUE THREAD

**Issue by makartsoft** [instantsoft/icms2#871]
Добрый день. WebP сегодня поддерживается всеми современными браузерами и многими графическими редакторами. На многих движках его поддержка уже включена.
Предлагается включить поддержку WebP в InstantCMS. Спасибо

**Comment by Val-Git** [comment]
Ничего не имею против WebP, но про поддержку всеми современными браузерами это вы загнули! Кроме хрома (+ возможно браузеров на его основе) и мобильных андроид браузеров больше ничто не поддерживает пока.
Но, соглашусь, ключевое слово "пока"))

**Comment by fuzegit** [comment]
Я уже сделал, там правки в 2х строчках

**Comment by makartsoft** [comment]
Добрый день. Спасибо за внимание к этому предложению. Но к сожалению, простое добавление webp в system/controllers/images/frontend.php не позволяет грузить такие файлы.

Пробовал у себя (php 6 и 7, поддержка webp на хостинге включена) и на демо сайте. Пишет, что "Файл имеет неподходящий формат"

**Comment by fuzegit** [comment]
У меня всё работает. Работа осуществляется функциями imagewebp и imagecreatefromwebp, имена которых формируются динамически.

**Comment by fuzegit** [comment]
Для теста я взял изображение из поиска гугла http://whatjackhasmade.co.uk/wp-content/uploads/2017/06/compressed.webp

И загрузил его на аватар

![_025](https://user-images.githubusercontent.com/13233234/42732582-cdde09ec-882c-11e8-9876-f9b48afeb1eb.png)

**Comment by makartsoft** [comment]
Странно. Сейчас вновь проверил - не работает. На демосайте https://demo.instantcms.ru/ тоже не работает.

Т.е. открываю профиль https://demo.instantcms.ru/users/2, нажимаю редактировать профиль, удаляю существующий аватар и загружаю тестовое изображение, которое вы привели в пример http://whatjackhasmade.co.uk/wp-content/uploads/2017/06/compressed.webp. Выдает ошибку "Файл имеет неподходящий формат".

Тип контента "Новости" - аналогично на демосайте.

![default](https://user-images.githubusercontent.com/21121917/42735349-ec78f9c4-885a-11e8-910e-e7379c0a3fec.png)

Тоже самое на реальном хостинге и на чистой установке OpenServer.

Для чистоты эксперимента попробовал на чистой установке WordPress с этим изображением и своим в Webp - работает.

![wp 1](https://user-images.githubusercontent.com/21121917/42735351-f10e6532-885a-11e8-9995-2698578485fe.png)

**Comment by fuzegit** [comment]
Я разобрался.
Всё в общем-то работает, проблема в том, что функция finfo_file, которая валидирует файл по его заголовкам (это наиболее надёжный способ), отдаёт mime тип как "application/octet-stream" вместо положенного "image/vnd.wap.wbmp".
Вероятней всего, более старые версии php и функция finfo_file просто не понимает этот тип файла.

Решение тут нет как такового, кроме как установить версию PHP поновее. Если хотите чтобы заработало в ущерб безопасности, то в файле /system/core/uploader.php после строчки 

    private function isMimeTypeAllowed($file_path) {

добавить

    return true;

Но я бы так делать не стал.

**Comment by makartsoft** [comment]
Fuze, спасибо, вы правы. Стояла версия php7.0. На версии 7.2 заработало без проблем.

**Comment by facepoint** [comment]
> А автоконвертацию в момент загрузки в webp реально прикрутить? И выводить, соответственно, оба варианта в шаблоне для разных браузеров в зависимости от поддержки формата...

Да, это очень актуально на сегодняшний день! Гугл очень положительно к этому относится. А тем более сегодня, когда скорости загрузки на мобильных отдается особое предпочтение. В битрикс видимо есть реализация https://vc.ru/services/279880-kak-uskorit-zagruzku-sayta-s-webp и во многих других движках, которые при этом по всем параметрам уступают инстанту:) Apple также стал поддерживать этот формат. А если отдавать в двух форматах, то 100% будет работать у всех! По сути такая поддержка нужна в трех полях: изображение, список изображений, фотогалерея.

**Comment by fuzegit** [comment]
Всё давно есть.

![Выделение_005](https://user-images.githubusercontent.com/13233234/147341850-d1d1fcaf-7c15-4681-a4c0-d4b8b879502d.jpg)
