### ISSUE TITLE
Ссылка от кого в письме о личном сообщении не работает

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#883]
**Используемая версия InstantCMS*: 2.10.1 с Гита

**Версия PHP**:  5.4.38

**Как воспроизвести проблему**: Отправить юзеру оффлайн личное сообщение.

* первый шаг - пишем письмо юзеру оффланй
* второй шаг - юзер получает письмо и не может понять от кого оно
![01-07-2018 23-45-38](https://user-images.githubusercontent.com/9349934/42138681-e6b6cdf8-7d89-11e8-80de-d86013d4db17.png)

* третий шаг... всё

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: не могу проверить

**Comment by fuzegit** [comment]
![_325](https://user-images.githubusercontent.com/13233234/42138756-23154cc4-7d8b-11e8-8962-0d208a65bbbb.png)

**Comment by nomad48** [comment]
ну не знаю, у меня так

**Comment by fuzegit** [comment]
> ну не знаю, у меня так

вы видите, что даже шаблон письма разнится? У вас он не стоковый, вы его правили.

**Comment by nomad48** [comment]
позвольте спросить, чем мой шаблон отличается от вашего? Тем что получен в яндекс-почте?

**Comment by fuzegit** [comment]
> Тем что получен в яндекс-почте?

сарказм ваш неуместен. вы описали возможную проблему, я её проверил на текущей версии. скриншот, что проблемы нет, я прикрепил.

> чем мой шаблон отличается от вашего

найдите одно отличие, которое дало мне полагать, что вы свой шаблон правили. При этом, есть подозрение, что у вас далеко не версия с гита и как минимум еще один файл не совпадает ни с версией 2.10.0, ни с версией отсюда.

**Comment by nomad48** [comment]
> У вас сообщение отсылается не от этого шаблона.
а от какого?

> Сравните уже свой скрин и мой.
сравнил, ткните носом меня, я действительно не вижу разницы
