### ISSUE TITLE
Разработка и Установка типа поля в определенный компонент (для разработчиков)

### ISSUE THREAD

**Issue by krylos** [instantsoft/icms2#888]
Добавить возможность в системном устройстве поля указать в каком компоненте оно будет выводиться.
Разработчики: смогут в коде указать в каком компоненте поле будет доступно администратору сайта для вывода.
Пользователи (админы сайта) будет видеть это поле в нужном компоненте.
Например, если поле делается только лишь для профиля пользователя то оно все равно видно в типах контента. Поле может использоваться и в других компонентах.

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/blob/master/system/core/formfield.php#L122

https://github.com/instantsoft/icms2/blob/faed34ffb373fa970a2d92582af3b2297d74a984/system/core/form.php#L632
