### ISSUE TITLE
Поле "Список:Мультивыбор" + Виджет = ошибка

### ISSUE THREAD

**Issue by iton1** [instantsoft/icms2#893]
**Используемая версия InstantCMS**: InstantCMS v2.10.1
**Как воспроизвести проблему**:

Создаем поле "Список: мультивыбор" в типе контента

![default](http://dl4.joxi.net/drive/2018/07/17/0013/2721/871073/73/6df4982360.jpg)

Заполняем "Предустановленные значения"

![default](http://dl3.joxi.net/drive/2018/07/17/0013/2721/871073/73/6eaf031c4d.jpg)

Создаем виджет и в нем выбираем созданное поле "Список: мультивыбор"

![default](http://dl3.joxi.net/drive/2018/07/17/0013/2721/871073/73/8c7ad891cb.jpg)

В виджете на странице в поле вместо заполненной информации выводятся цифры

![default](http://dl3.joxi.net/drive/2018/07/17/0013/2721/871073/73/a9e3a8f263.jpg)

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

Хотелось бы это исправить.

**Comment by fuzegit** [comment]
#594
