### ISSUE TITLE
Виджеты - Список контента

### ISSUE THREAD

**Issue by iton1** [instantsoft/icms2#894]
Хотелось бы увеличить количество полей которое можно вывести в виджете в списке контента, в типе контента создается много полей, а вот вывести их нет возможности в списке контента.

![default](http://dl4.joxi.net/drive/2018/07/17/0013/2721/871073/73/ca84bfcf34.jpg)

**Comment by maxisoft-git** [comment]
О каких полях идет речь? вы сделали скрин для настройки опции, а не вывода полей. сам вывод полей делается в вашем шаблоне.

**Comment by iton1** [comment]
Пример, есть тип контента "Объявления" в котором созданы поля

![default](http://dl3.joxi.net/drive/2018/07/18/0013/2721/871073/73/e13eb10d4c.jpg)

Мне необходимо на страницах вывести виджет с контентом, добавляю на страницы "виджет" - "Список контента"

![default](http://dl3.joxi.net/drive/2018/07/18/0013/2721/871073/73/f93885e256.jpg)

Получился такой виджет на страницах

![default](http://dl4.joxi.net/drive/2018/07/18/0013/2721/871073/73/b68d2d401f.jpg)

Но у меня еще есть поля "Телефон", "Цена", "Цвет" которые я тоже хочу вывести в виджете, но у меня нет возможности это сделать, вот была бы возможность выводить больше полей!

![default](http://dl4.joxi.net/drive/2018/07/18/0013/2721/871073/73/6c78560e2c.jpg)

**Comment by maxisoft-git** [comment]
:) все у вас есть сделайте себе нужный шаблон для данного виджета и выводите.

**Comment by Loadir** [comment]
Со строковыми полями это возможно, а с остальными? например с полем типа "Список" надо получать значения $fields, а это в шаблоне делать не "комильфо".
