### ISSUE TITLE
Отключение черновиков

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#897]
**Используемая версия InstantCMS**: 2х

С модерацией появились черновики. Это круто! Но как их отключить? Простые пользователи из двух кнопок "Отправить на модерацию" и "Сохранить в черновики" почему-то выбирают второй вариант. В итоге запись не опубликована и о ней никто не знает. 

Нужна возможность опционально отказаться от черновиков вообще. 

Пробовал скрыть стилями кнопку. Хорошо, скрыл. Но тут опять проблема. Если пользователь отправляет на модерацию, а кнопка "Опубликовать" [не работает](https://github.com/instantsoft/icms2/issues/896), то у нас получается скрытой кнопка "Сохранить", потому что ей зачем-то присваивается класс to_draft, а в меню действий - save_draft. Этот же класс у кнопок Сохранить в черновики.

Вот такие дела.

Спасибо.

**Comment by Yar-rus** [comment]
Всё же черновики нужны. Но должно быть всё понятно и логично. 

1. Кнопки я переименовал в "Опубликовать" и  "Сохранить в черновики (пока не публиковать)". Длинно, но более понятно.  Я это сделал, после того, как понял, что некоторые пользователи, действительно, не понимают. Одна женщина создала запись и нажала "Сохранить в черновики".  Затем заходила в течении нескольких дней и видно было, что она искренне не понимает, почему ее объявление не видно в списке. Ну не поймут иногда люди банальные, на наш взгляд, вещи, что поделаешь. Вот такие записи я никак не могу опубликовать до сих пор, именно по причине не работающей кнопки для админа, хотя они заполнены на сто процентов.

2. Столкнулся с тем, что люди, иногда заполняют огромное количество полей, но доходя до фото, которое обязательно, не могут его предоставить в данный момент. Им бы сохранить в черновики, что они и пытаются сделать, а вот тут и проблема - поле-то обязательное. В итоге человек злой, запись не сохраняется. 
Просьба дать возможность сохранить в черновики, невзирая на обязательность полей. Пусть даже, если заполнено хоть одно поле из ста.

Отсюда еще одно предложение - уведомление о недозаполненой записи . Вручную модератором или автоматом по графику.

**Comment by asnenne** [comment]
Кому-то нужны, а кому-то нет. Должно быть опционально. Сейчас, получается, они навязаны, хотя мне, например, они не нужны. Есть пункт "Публиковать на сайте - да/нет". Он вполне заменяет черновики. И всё понятно. Единственное, что тогда обязательность полей сделать только в том случае, если выбрано Публиковать на сайте ДА. А если НЕТ, тогда не проверять обязательные поля. И не было бы путаницы у простых людей, которые, по-сути, вообще ни при чем.

**Comment by lakomet** [comment]
Поддерживаю то, что проверку полей на заполненность, при сохранении в черновики, нужно убрать. А кнопку "Сохранить в черновики", обрезать до "В черновики", чтоб слово "сохранить", не сбивало людей с толку.

**Comment by narochnyi** [comment]
Поддерживаю! +то что добавить в черновик можно без заполнения обязательных полей

**Comment by elipss** [comment]
https://instantcms.ru/forum/thread29944-1.html#304464
