### ISSUE TITLE
Удаление профиля пользователем

### ISSUE THREAD

**Issue by Dimson-Git** [instantsoft/icms2#90]
Очень важная функция соц сети - удаление своего профиля пользователем, почему-то до сих пор не реализована

**Comment by vlad7090** [comment]
но по закону о хранении данных о пользователе, всеже необходимо оставлять профиль в БД для администратора.

**Comment by Dimasterson** [comment]
С этим не спорю, пусть остается, но функционально это должно присутствовать. При просмотре удаленного пользователя должно выводится, что пользователь удален, а в базе пусть лежит. И чтобы при желании можно было восстановиться.

**Comment by nomad48** [comment]
Согласен, мне пишут частенько, как удалить профиль?

**Comment by Dimasterson** [comment]
Вот и мне бывают пишут, пока только физически из админки, в этом и вся печаль. Еще хотелось бы блэк лист, куда пользователи будут заносить недругов :)

**Comment by shuma375** [comment]
Всем пишут. Реально очень важная функция. Делал возможность удалять акк хуком, но что то не то получилось
