### ISSUE TITLE
Предлагаю оптимизировать lang_slug

### ISSUE THREAD

**Issue by sipaj** [instantsoft/icms2#903]
Добавить очистку от нуль байта (вполне возможно где-то до этого такая очистка выполняется - не искал).
Заменить цикл  **foreach** на функцию **strtr**
Выигрыш по скорости в нижеследующей версии функции - около 23%.
```php
function lang_slug($string){

    $string    = strip_tags(trim($string));
    $string = str_replace(chr(0), '', $string); // <- ДОБАВИТЬ
    $string    = mb_strtolower($string, 'utf-8');
    $string    = str_replace(' ', '-', $string);

    $slug = preg_replace ('/[^a-zа-яёйїієґ0-9\-\/]/u', '-', $string);
    $slug = preg_replace('/([-]+)/i', '-', $slug);
    $slug = trim($slug, '-');

    $ru_en = array(
                    'а'=>'a','б'=>'b','в'=>'v','г'=>'g','д'=>'d',
                    'е'=>'e','ё'=>'yo','ж'=>'zh','з'=>'z',
                    'и'=>'i','й'=>'i','к'=>'k','л'=>'l','м'=>'m',
                    'н'=>'n','о'=>'o','п'=>'p','р'=>'r','с'=>'s',
                    'т'=>'t','у'=>'u','ф'=>'f','х'=>'h','ц'=>'c',
                    'ч'=>'ch','ш'=>'sh','щ'=>'sch','ъ'=>'','ы'=>'y',
                    'ь'=>'','э'=>'e','ю'=>'yu','я'=>'ja', 'і'=>'i', 'ї'=>'yi',
					'є'=>'ye', 'ґ'=>'g'
                    );
// Убираем цикл
//    foreach($ru_en as $ru=>$en){
//        $slug = str_replace($ru, $en, $slug);
//    }

     // Заменить цикл foreach на такой вариант.
     $slug = strtr($slug, $ru_en); 

    if (!$slug){ $slug = 'untitled'; }
    if (is_numeric($slug)){ $slug .= strtolower(date('F')); }

    return $slug;

}
```
Ещё +3..4% в варианте со статической переменной.
```php
function lang_slug($string){

   static  $ru_en = array(
                    'а'=>'a','б'=>'b','в'=>'v','г'=>'g','д'=>'d',
                    'е'=>'e','ё'=>'yo','ж'=>'zh','з'=>'z',
                    'и'=>'i','й'=>'i','к'=>'k','л'=>'l','м'=>'m',
                    'н'=>'n','о'=>'o','п'=>'p','р'=>'r','с'=>'s',
                    'т'=>'t','у'=>'u','ф'=>'f','х'=>'h','ц'=>'c',
                    'ч'=>'ch','ш'=>'sh','щ'=>'sch','ъ'=>'','ы'=>'y',
                    'ь'=>'','э'=>'e','ю'=>'yu','я'=>'ja', 'і'=>'i', 'ї'=>'yi',
					'є'=>'ye', 'ґ'=>'g'
                    );

    $string    = strip_tags(trim($string));
    $string = str_replace(chr(0), '', $string); // <- ДОБАВИТЬ
    $string    = mb_strtolower($string, 'utf-8');
    $string    = str_replace(' ', '-', $string);

    $slug = preg_replace ('/[^a-zа-яёйїієґ0-9\-\/]/u', '-', $string);
    $slug = preg_replace('/([-]+)/i', '-', $slug);
    $slug = trim($slug, '-');

     // Заменить цикл foreach на такой вариант.
     $slug = strtr($slug, $ru_en); 

    if (!$slug){ $slug = 'untitled'; }
    if (is_numeric($slug)){ $slug .= strtolower(date('F')); }

    return $slug;

}
```

**Comment by fuzegit** [comment]
> Добавить очистку от нуль байта

не требуется

> Заменить цикл foreach на функцию strtr Выигрыш по скорости в нижеследующей версии функции - около 23%.

Сомнительная замена как по мне. А выигрыш скорости вообще взят из головы в данном случае. Вы, кстати, тестировали этот вариант? Меня, например, смущает описание в примере  
> Обратите внимание на приоритет замен ("h" не используется, так как существуют более длинные совпадения) и как замененный текст больше не участвует в поиске.

на странице описания функции.

> Ещё +3..4% в варианте со статической переменной.

А это вообще с отсутствующим смыслом применения статических переменных. В этом участке кода статическая переменная не нужна, а ставить её якобы для увеличения производительности мягко говоря не нужно. Самое малое, что это сделает, так это запутает программиста, который этот код увидит впервые.

Спасибо за интерес к оптимизации движка, но подобные предложения будут отклоняться.

**Comment by sipaj** [comment]
Код на статистику конечно же гонял на работающем сервере.
10 тысяч циклов.
Тестовая строка:  'Ёжики кучно швыряют землицей - dosada!'

Время выполнения (худший результат выбрал): 

- Время выполнения: 0.20282 сек. (оригинальная функция)
- Время выполнения: 0.16303 сек. (замена цикла foreach на strtr)
- Время выполнения: 0.15156 сек. (замена цикла foreach на strtr + статическая переменная на таблице замены символов)
