### ISSUE TITLE
Категории и местоположение

### ISSUE THREAD

**Issue by asnenne** [instantsoft/icms2#907]
**Используемая версия InstantCMS**: 2

**Как сейчас:**

На сайте контент добавляется в различные города. Например, объявления. Каждая запись имеет привязку к какому-то городу (города в качестве примера). Посетитель заходит на сайт, фильтрует записи для своего города. Переходит в интересующее его объявление. На странице записей выведен список категорий для быстрого перехода. Но получается не совсем быстрого. Если посетитель перейдет по ссылке категории, то попадет на нее, но список будет не из нужного города, а все подряд. 

**Как предлагаю:**

Для полей рядом с галочкой "Показывать в фильтре" добавить еще одну галочку - использовать в ссылках. Создаем поле, например, город. И теперь все ссылки на странице, которая привязана, допустим, к Воронежу, ведут на списки, отфильтрованные по Воронежу. Все ссылки - это я имею ввиду ссылки категорий, хлебные крошки (опционально) и т.д. И до тех пор, пока человек не выберет другой город или не сбросит фильтр.

Спасибо.

**Comment by allkonekt** [comment]
asnenne, что бы пользователь понимал с чем это связано, нужно выводить "**уведомление**" выше записей на заметном фоне,, о том что используется фильтр, и кнопку - сбросить.

**Comment by asnenne** [comment]
allkonekt, откуда у Вас такие бредовые идеи? Всё еж давно сделано и работает. И так как НАДО, а не так, как Вы это видите. А видите Вы не то, что нужно.
