### ISSUE TITLE
Косяк с "Система комментариев Мнения" на страницах фото в фотоальбомах . 

### ISSUE THREAD

**Issue by elipss** [instantsoft/icms2#909]
Комментарии Мнения отображаются в фотоальбомах, на странице фотографий отображаются дефолтные комментарии .

**Comment by elipss** [comment]
Компонент для джумлы или вордпрес ?

**Comment by fuzegit** [comment]
> Компонент для джумлы или вордпрес ?

Ваш сарказм не попал в цель. О проблемах со сторонними компонентами необходимо писать их авторам.
