### ISSUE TITLE
Добавление хука - автозагрузчик классов.

### ISSUE THREAD

**Issue by maxisoft-git** [instantsoft/icms2#913]
При разработке расширении, часто используется composer для установки классов и требуемых пакетов, нет возможности без правки системы корректно подключать автозагрузчик composer.

возможно стоит сделать вызов хука после  spl_autoload_register('autoLoadCoreClass');

тогда можно было через него осуществлять автозагрузку классов и пакетов.

**Comment by fuzegit** [comment]
> сделать вызов хука после spl_autoload_register('autoLoadCoreClass');

добавлять туда вызов хука не вариант.
