### ISSUE TITLE
Возможность закреплять какую-то статью (контент) наверху (на первой позиции)

### ISSUE THREAD

**Issue by DorimenUkraine** [instantsoft/icms2#92]
Как Администрация проекта и сообщество смотрит на то, чтобы добавить к опциям публикации статьи возможность закреплять какую-то статью (контент) наверху (на первой позиции) на указанное количество времени?

**Comment by vlad7090** [comment]
было бы полезно. например если новость какая-то важная

**Comment by vlad7090** [comment]
Хотя вероятно это можно сделать с помощью полей или свойств и дальнейшей выборки через запрос в виджете. Было бы отлично, если бы в документации было изложено как это можно сделать.

**Comment by fuzegit** [comment]
Решается при помощи механизма наборов.
