### ISSUE TITLE
SEO для категорий + Шаблон генерации

### ISSUE THREAD

**Issue by iton1** [instantsoft/icms2#921]
Добавить возможность указывать переменные для категорий и генерировать Title, keywords, description , как для записей. 

Это очень удобно, чем прописывать все руками.

p.s. Сейчас у категорий можно прописать теги через "SEO по-умолчанию", но об ошибке я писал тут   
 https://github.com/instantsoft/icms2/issues/731 но тогда ответили, что не предусмотрены переменные.

**Comment by asnenne** [comment]
> Добавить возможность указывать переменные для категорий и генерировать Title, keywords, description , как для записей.

Смотрите в каталоге дополнений (компонент inseo), такой функционал уже есть и стоит копейки.

**Comment by allkonekt** [comment]
Также есть просьба добавить возможность "изменять" тег H1 в категориях (не записях, а именно категориях).

На текущий момент, в версии 2.10.1, тег H1 зависит напрямую от названия категории, и его нельзя изменить штатными методами для отображения.

Если категории новостей "Политика", то и заголовок тега H1 в теле страницы идентичен названию категории "Политика".
И нет возможности его изменить, что бы было например: "Новости политики и власти".
Повторюсь... Речь не о "записях" контента, а о "категориях".. Будет очень хорошо, добавить штатное поле "Заголовок страницы категории", выше существующего поля "Описание категории".

**Comment by iton1** [comment]
> 
> 
> > Добавить возможность указывать переменные для категорий и генерировать Title, keywords, description , как для записей.
> 
> Смотрите в каталоге дополнений (компонент inseo), такой функционал уже есть и стоит копейки.

На каждый сайт ставить дополнение не всегда удобно, а тут функционал уже работает и реализован почти на 100%, только немного доделать и в коробке! может в следующем релизе реализуют


> Также есть просьба добавить возможность "изменять" тег H1 в категориях (не записях, а именно категориях).

А это обещают реализовать в следующем обновление, перед новым годом.
