### ISSUE TITLE
Сохранить в черновики

### ISSUE THREAD

**Issue by lakomet** [instantsoft/icms2#928]
**Используемая версия InstantCMS**: 2.10.1
Моё предложение такое, в том случае, когда админ редактирует записи пользователей, заменить кнопку "Сохранить в черновики", на "Отправить на доработку". Первое - зачем админу, сохранять чужую запись в черновики? Второе - админ может начать редактировать какую нибудь мелочь в записи пользователя, но поняв, что правок будет много, как её отправить на доработку, если её уже одобрил один из модераторов? Ну и такая ситуация: 
при редактировании записи пользователя, случайно нажал "Сохранить в черновики", а восстановить из черновиков, может только автор, что в принципе логично, но я то нажал случайно, а автор записи, может не появляться на сайте долгое время, когда он появится на сайте, то он и не догадается, куда пропала его запись. Как её востановить из черновиков?

**Comment by ToxicSisters** [comment]
Видимо загвоздка в том что при публикации материала, он прикрепляется бы к админу а не автору материала. Была бы возможность у админа переключаться между профилями, такх проблем бы не возникало.
