### ISSUE TITLE
Загрузка файла

### ISSUE THREAD

**Issue by ValenokPC** [instantsoft/icms2#930]
При загрузки файла переименовывать загружаемый файл при сохранении в папку в более меньшее название или к примеру генерировать название файла автоматически . Такая же беда и с картинками
т.к пользователи не стесняются и загружают файлы с названием в 500+ символов.

**Comment by fuzegit** [comment]
А проблема то в чем?

**Comment by ValenokPC** [comment]
Не совсем удобно + есть еще одна проблема с файлами. Когда создании пост, то при загрузки файла в базе не записывается **target_id** всегда NULL. Только после редактирование поста перезагрузить файл повторно то поле заполнится!
