### ISSUE TITLE
При просмотре записи или набора контента в виджете меню не выделяются активные категории 

### ISSUE THREAD

**Issue by BorisRBJ** [instantsoft/icms2#932]
В коде виджета "меню" отсутствует соответствующий функционал.
Но он присутствует в коде виджета "категории".
**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА
![99999999999](https://user-images.githubusercontent.com/14174951/47261036-751aca00-d48c-11e8-94f8-4a213cf5ac45.jpg)

**Comment by fuzegit** [comment]
> Но он присутствует в коде виджета "категории".

там совершенно другой принцип определения активного меню. В системных меню активность определяется по URL.
