### ISSUE TITLE
Доступ на чтение комментариев из закрытых типов контента

### ISSUE THREAD

**Issue by Val-Git** [instantsoft/icms2#937]
**Используемая версия InstantCMS**: 2.10.1

**Как воспроизвести проблему**:

* из под Гостя переходим по ссылке https://demo.instantcms.ru/comments
* в списке комментариев внизу 2 коммента из статьи "Общественный анализ зарубежного опыта"
* кликаем по заголовку статьи -> переходим сюда: https://demo.instantcms.ru/articles/11-obschestvennyi-analiz-zarubezhnogo-opyta.html#comment_5
* 403 Доступ запрещён. Группам, к которым вы принадлежите, запрещён доступ к этой странице

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

В идеале, думаю, комментарии из закрытых записей не должны выводиться пользователю нигде. Или же - вариант минимум - убрать ссылки на закрытые записи из заголовков в комментах (шаг 3 описания выше)

**Comment by fuzegit** [comment]
> В идеале, думаю, комментарии из закрытых записей не должны выводиться пользователю нигде. Или же - вариант минимум - убрать ссылки на закрытые записи из заголовков в комментах (шаг 3 описания выше)

Дело в том, что в данном случае доступ закрывается на все записи страниц articles через "Виджеты и страницы".

**Comment by Val-Git** [comment]
Да, это я понимаю)) И тут все логично. 
Я имел ввиду, что комментарии из закрытых разделов (в нашем случае все страницы articles) могут видеть пользователи не имеющие доступа к этому разделу.

**Comment by fuzegit** [comment]
В 2.12.0 реализована возможность указывать какие комментарии будут выводиться в списке/виджете.
