### ISSUE TITLE
Ограниечение в наборах по группам

### ISSUE THREAD

**Issue by WebRio** [instantsoft/icms2#941]
**Используемая версия InstantCMS**: 2.10.1

**Версия PHP**:  7,1

**Как воспроизвести проблему**:

* первый шаг
В типе контента создать набор
* второй шаг
Выставить права для групп, показывать группам - администраторы, а не показывать группам всем в исключение администраторов
* третий шаг....
Посетить данный набор как не авторизованный гость, постелить сайта. И видим картину, что ограничение по группам которым запретили показывать набор, чудесным обзором отображается это как-то не логично.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: Не знаю

**Comment by fuzegit** [comment]
Всё работает корректно

![Выделение_038](https://user-images.githubusercontent.com/13233234/97411006-c6c67c80-1910-11eb-821c-43bccb77be13.jpg)

![Выделение_039](https://user-images.githubusercontent.com/13233234/97411013-c75f1300-1910-11eb-99c8-e3b85ad48989.jpg)
