### ISSUE TITLE
Доработка фильтра по полю "местоположение"

### ISSUE THREAD

**Issue by allkonekt** [instantsoft/icms2#945]
Просьба добавить возможность в фильтре для поля city (местоположение/город)выбирать одно из значений:

Только страна и/или страна - область и/или  страна - область - город.
(В идеале дать пользователям "администраторам" возможность самостоятельно создавать вложенные категории "поселки/районы"... Эх!!! 

Сейчас можно использовать фильтр по полю city, только выбрав последовательно все 3 значения.

Если создавать дополнительно два поля (страна + область), для их отображения в фильтре, то теряется универсальность использования поля "местоположение", в таком случае в фильтре вместо одного фильтра - отображается три, и они не связаны (в одном можно выбрать страну "Россия", в другом область "Киев" (грубый пример), и исходя из того что эти данные выбраны некорректно, объявления не отобразятся. Нужно лишь для поля "city" - предоставить возможность выбирать любое значение (не последнее "город").

**Comment by fuzegit** [comment]
> Только страна и/или страна - область и/или страна - область - город.

- Сделайте в фильтре видимым только поле город. 
- Сделайте отдельными полями (связав их согласно документации https://docs.instantcms.ru/manual/ctypes/fields/types#местоположение) https://www.youtube.com/watch?v=UAvayMWfpwo

Других вариантов нет и не получится.
