### ISSUE TITLE
Notices на странице несуществующего тега

### ISSUE THREAD

**Issue by san-sanych-k** [instantsoft/icms2#948]
При переходе по ссылке несуществующего тега выводится куча notice типа:

Notice: Undefined variable: seo_title in .,.
Notice: Undefined variable: seo_keys in ...
Notice: Undefined variable: seo_desc in ...
Notice: Undefined variable: seo_title in ...
Notice: Undefined variable: seo_h1 in ...

**Используемая версия InstantCMS**: 
2.10.1

**Версия PHP**:  
5.6.32

**Как воспроизвести проблему**: 
Перейти к поиску несуществующего тега, например: https://demo.instantcms.ru/tags/search?q=несуществующийтег

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**:
Скорее всего да, но на демо отключена отладка

**Comment by fuzegit** [comment]
Давно исправлено здесь
