### ISSUE TITLE
Выбор пресета изображения в виджете

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#95]
В настройках виджета есть возможность выбирать какое поле выводится для вывода изображения, но нет возможности выбрать пресет, т.к всеже выводить большую картинку в виджете смысла нет, а вот выбрать из пресетов было бы самое то, что позволяло бы оптимизировать скрорость работы сайта за счет выбора именно тех размеров пресетов, которые настроены в админке.

**Comment by mafru** [comment]
> В настройках виджета
О настройках какого именно виджета идет речь?
