### ISSUE TITLE
Недостаток в переменной group группы на сайте

### ISSUE THREAD

**Issue by san-sanych-k** [instantsoft/icms2#950]
**Используемая версия InstantCMS**: 
2.10.1

**Версия PHP**:  
5.6.32

**Как воспроизвести проблему**:
В файле /controllers/groups/actions/group.php 
перед строкой
list($group, $group['fields']) = cmsEventsManager::hook('group_before_view', array($group, $group['fields']));
глянуть значение переменной $group, в ней в $group['fields'] содержится пару сотен лишних вложений одних и тех же текущих полей.

**Comment by fuzegit** [comment]
С точки зрения красоты и отладки, да, не красиво. С точки зрения самого кода и ооп - всё нормально.
Переделаю красивее.
