### ISSUE TITLE
Дабавить hook user_before_registered

### ISSUE THREAD

**Issue by san-sanych-k** [instantsoft/icms2#958]
**Используемая версия InstantCMS**: 2.10.1

**Версия PHP**:  5.6.32

Есть hook который срабатывает после успешной регистрации пользователя на сайте: user_registered

Часто требуется hook например с названием user_before_registered

Запускать его в случае успешной валидации формы в файле register.php сразу после строк:

`if (!$errors){`

Как то так:

```
if (!$errors){

            	$user = cmsEventsManager::hook('user_before_registered', $user);

                //
                // Блокируем пользователя, если включена верификация e-mail
                //
```

**Comment by fuzegit** [comment]
есть хук registration_validation как раз для этих целей
