### ISSUE TITLE
GROUP BY в методе getCount()

### ISSUE THREAD

**Issue by softsolution** [instantsoft/icms2#96]
День добрый, уважаемые разработчики.
Столкнулся с проблемой.
Мне нужно сгруппировать результаты перед перед подсчетом записей, пользуюсь методами ядра getCount() для подсчета результатов и get() для вывода записей. Но оказалось, что group BY поддерживается только в get(), а в getCount() - поддержки нет и данные, которые они выдают отличаются. Подскажите является ли это ошибкой, не хотелось бы отдельно запрос писать только для подсчета записей. Спасибо

**Comment by Val-Git** [comment]
Тоже сталкивался с этой проблемой! Понял, что в реализации `getCount()` GROUP BY не поддерживается((, как минимум пока что.

**Comment by softsolution** [comment]
Я просто не могу понять это сознательно сделано или недоработка.

**Comment by Val-Git** [comment]
А попробуйте протестировать. Потому что я когда наткнулся на этот "косяк" - посмотрел, немного расстроился и переделал алгоритм по другому (некогда было разбираться).

Добавьте в файл ..\system\core\model.php в функцию `getCount($table_name, $by_field='id')` строку 
`if ($this->group_by){ $sql .= "GROUP BY {$this->group_by}\n"; }`
после where, у меня это 1178 строка.

И посмотрите как будет отрабатывать?))

**Comment by softsolution** [comment]
да, дело не в этом. функцию я переписал уже. если это недоработка, то нужно в основной дистрибутив эти правки добавить.

**Comment by Val-Git** [comment]
если они помогут, то добавят))) Просто перед пулл-реквестом надо протестировать...
