### ISSUE TITLE
В SiteMap сделать возможность размещения не только контента, но и каталогов, и каталоги+наборы

### ISSUE THREAD

**Issue by ermakover** [instantsoft/icms2#966]
Просьба в SiteMap сделать возможность размещения не только контента, но и каталогов, и каталоги+наборы.
Поисковики, в частности Google мне пишет постоянно - на вашем сайте есть популярные страницы, которых нет в карте сайта. И эти популярные страницы, как раз категории и наборы+категории.

**Comment by fuzegit** [comment]
уже есть
