### ISSUE TITLE
Не формируется robots.txt при включенном типе контента по умолчанию

### ISSUE THREAD

**Issue by geminisf** [instantsoft/icms2#968]
**Используемая версия InstantCMS**: 2.11.0

**Версия PHP**:  7.2

**Как воспроизвести проблему**:

* Выбрать в админке тип контента по умолчанию, например, посты.
* Перенести содержимое файла robots.txt в админку и удалить его. 
* Перейти по ссылке https://мой_сайт/robots.txt и получить страницу 404.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: Демо сайт еще не обновлен до версии 2.11.0

**Comment by iton1** [comment]
У меня тоже не создается файл robots.txt после обновления на 2.11.0. 

Yandex - директивы host больше нет, она упразднена, нет смысла ее добавлять в файл robots.txt.

https://webmaster.yandex.ru/blog/301-y-redirekt-polnostyu-zamenil-direktivu-host

Google - в гугле нет такой директивы host
