### ISSUE TITLE
Выбор автора записи контента администратором

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#97]
В 1 ветке инстантвидео была такая фишка, которая удобна для того, чтобы можно было публиковать контент под разным авторством. Во многих проектах такая опция очень полезна.
Было бы отлично, если бы во второй ветке также эта опция была.

**Comment by Maratakziaplus** [comment]
Такое видел в мапсе, очень удобная штука. Например публикуешь контент и потом передаешь права другому пользователю и он становится автором этого контента.

**Comment by Dimson-Git** [comment]
Поддерживаю, тоже жду эту фишку

**Comment by makartsoft** [comment]
Тоже поддерживаю. Часто бывает, не под тем автором делается запись, чтобы не удалять, приходится лезть в БД и править на нужного.
