### ISSUE TITLE
Сворачиваемые блоки в форме создания/редактирования записи - ошибка отображения

### ISSUE THREAD

**Issue by Kerncraft1** [instantsoft/icms2#975]
**Используемая версия InstantCMS**: 2.11.0

**Версия PHP**:  7.2

**Как воспроизвести проблему**:

* В настройках типа контента в пункте "Сворачиваемые блоки в форме создания/редактирования записи" выбрать к примеру пункт "Комментарии" или "Публикация". В предыдущих версиях эта настройка делала выбранные опции "свернутыми" и их можно было открыть и отредактировать, если есть соответствующие права. 
Сейчас же блоки просто скрываются стилями display: none, что не соответствует заголовку "Сворачиваемые блоки".
`<fieldset id="fset_is_comment" class="is_collapsed is_collapse" style="display: none;">`
Шаблон установлен дефолтный.

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: НЕТ

**Comment by fuzegit** [comment]
Не могу повторить, всё работает как положено.
![_109](https://user-images.githubusercontent.com/13233234/51026286-35511380-159f-11e9-9792-ca5251b2f87a.png)

Дайте больше информации о проблеме, либо повторите на демо.

**Comment by Kerncraft1** [comment]
> Дайте больше информации о проблеме, либо повторите на демо.

Вот и я удивляюсь, что на демо работает.
Скрин - http://prntscr.com/m5r6y8
У данных блоков почему-то свойство display none. Если в настройках типа контента галочку снять, то блоки как и положено выводятся раскрытыми.

**Comment by fuzegit** [comment]
Может проблема в каких то других скриптах вашего сайта?
