### ISSUE TITLE
Добавление материалов в избранное в коробке

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms2#98]
Полезно для контентных сайтов, т.к когда много материалов на сайте, то полезно иметь функцию добавление в избранное, т.к потом сложно найти нужные прочитанные материалы, или те материалы, которые планируешь прочитать.
В 1 ветке был такой хак, что было очень удобно
В каталоге дополнений также вижу что есть такая опция http://addons.instantcms.ru/ что также очень удобно. При чем можно выводить ссылку "Добавить в избранное" для гостей, но при клике выдавать сообщение с формой авторизации, что надо зарегистрироваться, чтобы добавить в избранное

**Comment by Maratakziaplus** [comment]
Поддерживаю

**Comment by Dimasterson** [comment]
Очень нужный функционал +

**Comment by globator88** [comment]
Один из хороших решений http://www.instantcms.ru/blogs/bitblog/izbranoe-v-2-0.html
Хотел бы что то вроде этого. Хотя бы разделение по типом контента.
