### ISSUE TITLE
Добавить для SEO в тайтл номера страниц

### ISSUE THREAD

**Issue by SergeyRN** [instantsoft/icms2#980]
Сейчас в категории, если перейти на 2-ю, 3-ю (и т.д.) страницу, в панелях вебмастера получаются дубли страниц, из-за того что у них одинаковый тайтл.

Поэтому сейчас для исключения таких дублей, такие страницы закрывают от индексации в роботсе так:
`Disallow: /*?page=*`

Однако это не правильно (тем более в 2.11 была проделана работа над тайтлами в категориях)
Правильно сделать на таких страницах разные тайтлы, путем добавления номера страниц.
 
Просьба добавить в тайтл категорий, при пагенации, номера страниц.
Решение здесь:
https://instantcms.ru/forum/thread30898-8.html#302933

Вроде бы работает везде...

**Comment by iton1** [comment]
Не правильно добавлять нумерацию в title в категории, самый правильный способ использовать атрибут rel="canonical" .

https://github.com/instantsoft/icms2/issues/709

**Comment by SergeyRN** [comment]
Рекомендую прочитать для чего и как используется атрибут rel="canonical" в саппорте Гугла и блога Яндекса.
https://support.google.com/webmasters/answer/139066?hl=ru
https://webmaster.yandex.ru/blog/10371

**Он используется совершенно для других вещей, а именно когда ОДНА И ТА ЖЕ страница открывается с нескольких адресов.**

Кроме того даже если и пытаться таким способом ( rel="canonical") регулировать этот вопрос тогда надо будет создавать сложный инструмент для страниц. В котором можно бы было указывать лишь для одной страницы категории канонический адрес, а остальные должны оставаться не каноническими.

Иначе все страницы и ?page=1 и ?page=2 будут иметь атрибут rel="canonical", в результате Какая из них будет считаться каноничной поисковиком?
