### ISSUE TITLE
Недочёт на стене пользователя

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2#981]
**Используемая версия InstantCMS**: 2.10.1

**Версия PHP**:  5.6.37

**Как воспроизвести проблему**: При ответе на статус пользователя на стене, при полном удалении пользователя с сайта оставившего ответ, остается счетчик его ответа в статусе, хотя на самой стене всё удаляется.

* первый шаг - Пользователь регистрируется на сайте
* второй шаг - Оставляет на комментарий на статус у любого пользователя
* третий шаг - Удаляем полностью пользователя добавившего комментарий к статусу пользователя
* четвертый шаг - со стены всё удаляется, но остается счетчик количества ответов в статусе
В базе, таблица **cms_users_statuses**, столбец **replies_count**

![20-01-2019 11-34-49](https://user-images.githubusercontent.com/9349934/51436975-e8a8bf00-1ca7-11e9-88e2-c54289b4e45a.png)
![20-01-2019 11-35-39](https://user-images.githubusercontent.com/9349934/51436976-e9415580-1ca7-11e9-9113-549bf96dce91.png)

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

![20-01-2019 11-45-20](https://user-images.githubusercontent.com/9349934/51437049-4d184e00-1ca9-11e9-9045-96eef7a1f308.png)
![20-01-2019 11-45-39](https://user-images.githubusercontent.com/9349934/51437050-4d184e00-1ca9-11e9-9390-fad9f39e05e6.png)

**Comment by nomad48** [comment]
Я обновился до 2.12.1, те ответы, что на стене остались принудительно надо из базы удалить?

**Comment by fuzegit** [comment]
Счетчик нужно обнулять вручную для старых записей. С новыми проблем нет.

**Comment by nomad48** [comment]
Спасибо
