### ISSUE TITLE
Подключение widgets.js при отображении компонента на главной

### ISSUE THREAD

**Issue by webomax** [instantsoft/icms2#982]
https://github.com/instantsoft/icms2/blob/bfa7e4764719282361689a4ecb02f59eddf0657f/system/core/core.php#L813

Для себя создал компонент (лендинг), который открывается на главной (реализовано через хуки frontpage, fronptpage_types и опции "Выводить на главной странице"), так же создал для себя пустой макет (empty.tpl.php)

```
<!DOCTYPE html>
<html>
<head>
    <title><?php $this->title(); ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
	<link rel="icon" type="image/vnd.microsoft.icon" href="/favicon.ico">
    <!--[if lt IE 9]>
        <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
    <![endif]-->
    <?php $this->head(); ?>
</head>
	<body><?php $this->body(); ?></body>
</html>
```

Если пользователь админ, в шапку подключается widgets.js, хотя в моем случае он не нужен. Как мне предотвратить добавление этого скрипта не касаясь системных файлов CMS?

**Comment by fuzegit** [comment]
Никак не отключить. Чем он вам мешает, тем более он показывается только администратору.
