### ISSUE TITLE
Видимость поля - Для каких списков показывать

### ISSUE THREAD

**Issue by iton1** [instantsoft/icms2#986]
**Используемая версия InstantCMS**: InstantCMS 2.11.0

**Версия PHP**:  5.6

**Как воспроизвести проблему**:

Заходим в тип контента "Доска объявлений" у него установлен "Стиль списка по умолчанию" - **default_list_table(Таблица)** ,  заходим в настройки поля к примеру "Фотография" в "Видимость поля" ставим галочку к примеру "В профиле"

![default](https://user-images.githubusercontent.com/17750649/51807069-3e2a3080-2293-11e9-97b5-7a3c5648f51a.png)

Фотографии как показывались в категории, так и показываются

![default](https://user-images.githubusercontent.com/17750649/51807083-6dd93880-2293-11e9-9c8e-7fdf33380823.png)

У себя на сайте ставил галочки "В корзине" так фото показывалось в "В связях, в списке" и т.д.

Поэкспериментировал, если зайти в настройки "Тип контента: Объявления" и в "Стиль списка по умолчанию" выбрать "default_list (Обычный)" то фотографии пропадают, как и задано в "Видимость поля".

![default](https://user-images.githubusercontent.com/17750649/51807141-315a0c80-2294-11e9-9754-0b9d519bc320.png)

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

Этот текст можно стереть, если вы сообщаете не о баге, а пишите пожелание/предложение.

**Comment by fuzegit** [comment]
Проблема только с шаблоном "Таблица". Решено в новом шаблоне.
