### ISSUE TITLE
Что должно быть по умолчанию, в коробке

### ISSUE THREAD

**Issue by Maratakziaplus** [instantsoft/icms2#99]
1. Поле город в типах контента и профиле пользователя
2. Расширенный поиск (по дате, с картинками, ценами и т.д.)
3. Кнопка "Добавить в избранное" и вкладка в профиле, на сайте инстанта пользователь **Val** предлагал решение этого вопроса, может его встроите в инстант, если код вас устраивает.
4. Поднятие и оформление рамкой вип объявлении на определенный срок, после окончания этого срока автоматически снимается с объявления статус ВИП
5. Архив объявлении в профиле пользователя с возможностью восстановления за определенную плату
6. Адаптированное видео с ютуб, в данное время видео не адаптировано под моб.устройства
7. Поле яндех карта в типах контента с возможностью поиска по адресу 
8. Авторизация через соцсети, у Ulogin есть наработки под инстант, может с ними договоритесь
9. Отзывы пользователей в типах контента, ну примерно так, как реализовано в мапсе

Почему говорю, что это все необходимо иметь в коробке. Без этих функции не обходится практически ни один современный сайт. Минус сторонних разработок в том, что не все и не всегда поддерживают свои разработки, при очередном обновлении движка начинают возникать большие проблемы, приходится удалять какие то компоненты так и не дождавшись обновления.

**Comment by vlad7090** [comment]
лучше всеже не в коробке, т.к кому то может это и не надо, но как доп.опции от официального разработчика, которые можно поставить допами

**Comment by lokanaft** [comment]
Вы перепутали багтрекер со своим тз

**Comment by Maratakziaplus** [comment]
Да согласен, нужно именно от разработчика движка. Честно говоря, я очень устал гоняться за разработчиками различных компонентов и из за этого много всяких компонентов по удалял из своего сайта.

**Comment by Maratakziaplus** [comment]
**lokanaft ** Это не важно, главное чтоб дошло до разработчиков) здесь я впервые

**Comment by fuzegit** [comment]
Maratakziaplus, для обсуждения субъективных мнений есть форум. 
>  главное чтоб дошло до разработчиков

главное, чтобы вы поняли ответы
