### ISSUE TITLE
Некорректная работа поля число

### ISSUE THREAD

**Issue by zau4man** [instantsoft/icms2#990]
**Используемая версия InstantCMS**: 2.11.0

**Как воспроизвести проблему**:

Настроить поле следующим образом

![image-2019-02-02-16-02-26](https://user-images.githubusercontent.com/13526431/52164674-d0f52000-2716-11e9-8c9a-b69bdaa86584.png)

И попытаться сохранить в поле 1000000 (миллион). При просмотре на сайте число так и будет выведено 1000000.

Если же сохранить в поле 1000000.20 то выведется 1,000,000.2 руб., т.е. будет использоваться разделитель, но будет неправильное количество знаков после запятой.

Также бы хотелось в качестве разделителя использовать пробел. В текущей реализации опций сохранить пробел не получиться.

**Comment by fuzegit** [comment]
#991
