### ISSUE TITLE
Расширить влиятния виджета в шаблоне

### ISSUE THREAD

**Issue by WebRio** [instantsoft/icms2#992]
Добавить возможность создавать места для виджетов глобально, а не только в фале main.tpl.php. В данный момент имеются недостатки, к примеру нет возможности разместить виждет после самой статьи перед комментариями.

Для наглядного объяснения скажем, нужно создать место для виджета на странице статьи, открываем файл default_item.tpl.php и прописываем там код виджета.

**Comment by lokanaft** [comment]
Что мешает сделать это сейчас?

`            cmsCore::getInstance()->runWidgets();
            $this->widgets('header', false, 'wrapper_plain');`

**Comment by WebRio** [comment]
> 
> 
> Что мешает сделать это сейчас?
> 
> ` cmsCore::getInstance()->runWidgets(); $this->widgets('header', false, 'wrapper_plain');
Низкий поклон вам, я php не особо силен, но с вашим примером все виджеты дублируются.

**Comment by WebRio** [comment]
> 
> 
> Что мешает сделать это сейчас?
> 
> ` cmsCore::getInstance()->runWidgets(); $this->widgets('header', false, 'wrapper_plain');`

В вашем пример виджеты дублируются.

А если так то все нормально.
```
                cmsCore::getInstance()->runWidgets();
                $this->widgets('left-bottomf', false, 'wrapper_plain');
                unset($this->widgets);
```
