### ISSUE TITLE
Изменяемый размер заголовка контента

### ISSUE THREAD

**Issue by geminisf** [instantsoft/icms2#996]
Доброго дня! Хочу внести предложение - увеличить длину заголовка до 250 знаков. Или сделать заголовок контента изменяемым, Чтобы владелец сайта сам мог выставить максимальную длину. Пусть даже с предупреждением большими красными буквами о том, что это вредно.

**Comment by elipss** [comment]
В разных Типах контента может быть нужна разная длина заголовка, поэтому лучше изменяемая длина.

**Comment by vitaliyremi** [comment]
Поддерживаю!

**Comment by fuzegit** [comment]
![Выделение_017](https://user-images.githubusercontent.com/13233234/95680656-e9a02380-0be3-11eb-8d29-d2e9b7d84a6c.jpg)

Или мы позже внедрили, и не заметили этот тикет, или вы не заметили опцию. Так или иначе, возможность сейчас есть.
